### ISSUE TITLE
Bindable error on quit exit from editor

### ISSUE THREAD

**Issue by peppy** [ppy/osu#10418]
Seems like somehow `OnResuming` is being called more than once (or `OnSuspending` was never called?)

```
[runtime] 2020-10-08 08:51:58 [error]: System.InvalidOperationException: This bindable is already bound to the requested bindable (osu.Game.Rulesets.Mods.Mod[]).
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Bindables.Bindable`1.BindTo(Bindable`1 them)
[runtime] 2020-10-08 08:51:58 [error]: at osu.Game.Screens.Select.SongSelect.OnResuming(IScreen last) in /Users/dean/Projects/osu/osu.Game/Screens/Select/SongSelect.cs:line 567
[runtime] 2020-10-08 08:51:58 [error]: at osu.Game.Screens.Select.PlaySongSelect.OnResuming(IScreen last) in /Users/dean/Projects/osu/osu.Game/Screens/Select/PlaySongSelect.cs:line 51
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Screens.ScreenStack.resumeFrom(IScreen source)
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Screens.ScreenExtensions.MakeCurrent(IScreen screen)
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Threading.Scheduler.Update()
[runtime] 2020-10-08 08:51:58 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

**Comment by bdach** [comment]
How is this reproduced? I've tried a few things and can't seem to hit anything of the sort.

**Comment by peppy** [comment]
It was completely random unfortunately. Haven't had it happen again since.

**Comment by Joehuu** [comment]
Can reproduce:
- Go to song select
- Press edit on any beatmap (osu! ruleset)
- Move any hit object
- Press alt-f4 two times

![G3WpO9A7sF](https://user-images.githubusercontent.com/35318437/97260208-b5c71f80-17d9-11eb-8fce-3c0d762d8d8d.gif)
