### ISSUE TITLE
wont even launch

### ISSUE THREAD

**Issue by brendanfraserjust** [ppy/osu#10726]
**Describe the crash:** 
game wont start
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/MyPPYBA.png
**osu!lazer version:** 
2020.1031.0
**Logs:**
Unhandled exception. osuTK.Graphics.GraphicsContextException: Invalid window
   at osuTK.Platform.SDL2.Sdl2GraphicsContext..ctor(GraphicsMode mode, IWindowInfo win, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at osuTK.Platform.SDL2.Sdl2Factory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at osuTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at osuTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded)
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device)
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode)
   at osu.Framework.Platform.GameWindow..ctor(Int32 width, Int32 height)
   at osu.Framework.Platform.DesktopGameWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 55
Aborted
**Computer Specifications:** 
CPU: AMD Ryzen 2700x
GPU: AMD Radeon 5700XT
RAM: 16GB 3200MHz
OS: Gentoo Linux (kernel version 5.4.72)

**Comment by stamby** [comment]
Perhaps your OS of choice has something to do with it.

**Comment by bdach** [comment]
I can assure you that the game does launch on my linux setup. Is this x11 or wayland?

Overall there's not much information to go on in this report. You could try the `--sdl` switch to bypass osutk but I'm not expecting much seeing that SDL2 seems to be entirely failing to create a window. Maybe something will be visible in `dmesg` - but at this point who knows, we're not likely going to be able to provide a resolution here and you'll probably have to try and diagnose your gentoo setup to get to a working state.

**Comment by brendanfraserjust** [comment]
alright i think i figured out why it doenst work. 
i added the opengl useflag to my /etc/portage/make.conf file in order to recompile packages(that support it) with opengl support(which libsdl2 was one of them), then i tried running it again and i got a different error this time:
`No usable version of libssl was found
Aborted`
for this install i used libressl rather than openssl, other than optimizations this is the only thing i really did differently from my previous gentoo install that this game did work on.
>Is this x11 or wayland?
i use the x server
>Maybe something will be visible in dmesg
[ 7996.740640] osu![10950]: segfault at 0 ip 0000000000000000 sp 00007ffdb4409768 error 14 in osu![400000+15000]
[ 7996.740645] Code: Bad RIP value.

**Comment by bdach** [comment]
`libressl` is not supported by the .NET Core runtime - see #7994 and dotnet/runtime#24869. Closing as partially resolved / partially duplicate.
