### ISSUE TITLE
Crash on saving new beatmapset that is identical to an existing one

### ISSUE THREAD

**Issue by nbvdkamp** [ppy/osu#10734]
**Describe the crash:** 
If you open the editor from the main menu (to create a new beatmap), save the beatmap without doing anything and do this again an exception is thrown because the BeatmapSetInfo hashes are identical, violating a database uniqueness constraint.

**osu!lazer version:** 
Latest master.

**Logs:**
```
Exception has occurred: CLR/Microsoft.EntityFrameworkCore.DbUpdateException
An exception of type 'Microsoft.EntityFrameworkCore.DbUpdateException' occurred in osu.Game.dll but was not handled in user code: 'An error occurred while updating the entries. See the inner exception for details.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.Hash'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```
[runtime.log](https://github.com/ppy/osu/files/5505542/runtime.log)

**Comment by peppy** [comment]
I attempted to fix this locally but doesn't seem like the best idea. Can actually be fixed once the differ implementation in the editor supports more than just hitobjects (so we can be sure whether a change has happened from the default state, including metadata).

**Comment by peppy** [comment]
I believe this has been resolved with realm and editor flow changes.
