### ISSUE TITLE
Game crash after entering spectator mode

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10777]
**Describe the crash:** 
i tried to spectate someone and then the game suddenly started to hang and crash.
this doesn't seem to repro all the time and im not sure how to do it.

**osu!lazer version:** 
2020.1109.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5518314/logs.zip)

**Computer Specifications:** 
OS: windows 10
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8 GB

**Comment by bdach** [comment]
Well, this will be it:

```
2020-11-10 15:25:56 [error]: An unhandled error has occurred.
2020-11-10 15:25:56 [error]: System.InvalidCastException: Unable to cast object of type 'osu.Game.Rulesets.Taiko.Replays.TaikoReplayFrame' to type 'osu.Game.Rulesets.Osu.Replays.OsuReplayFrame'.
2020-11-10 15:25:56 [error]: at osu.Game.Rulesets.Replays.FramedReplayInputHandler`1.get_NextFrame()
2020-11-10 15:25:56 [error]: at osu.Game.Rulesets.Replays.FramedReplayInputHandler`1.SetFrameFromTime(Double time)
2020-11-10 15:25:56 [error]: at osu.Game.Rulesets.UI.FrameStabilityContainer.updateReplay(Double& proposedTime)
```

The more important question is what caused the frames from the wrong ruleset to arrive in the first place...
