### ISSUE TITLE
Dragging sliderend onto bottom timeline crashes game

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10938]
Have been able to reproduce a couple of times on [this beatmap](https://osu.ppy.sh/beatmapsets/1220612)  at 01:03:014 - but still uncertain what triggers it. Sometimes an [unhandled error](https://i.imgur.com/6OMxE5m.png) is thrown instead 

**video:** https://youtu.be/f_b7vhDL12E
**osu!lazer version:** 2020.1121.0

**Logs:**
[runtime.log (while dragging)](https://github.com/ppy/osu/files/5578539/runtime.3.log)
[runtime.log (original error)](https://github.com/ppy/osu/files/5578540/runtime.4.log)

**Comment by bdach** [comment]
There is no trace of a crash in the attached logs. Are you sure you uploaded ones from just after a crash and haven't ran the game again after?

**Comment by Pennek** [comment]
shit, i may have done that. let me try to reproduce

**Comment by Pennek** [comment]
[this](https://github.com/ppy/osu/files/5578496/runtime.log) should be it

**Comment by bdach** [comment]
Yeah, that one's got a stack trace.

```
2020-11-21 22:08:01 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2020-11-21 22:08:01 [error]: at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.SliderSelectionBlueprint.updatePath()
2020-11-21 22:08:01 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2020-11-21 22:08:01 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2020-11-21 22:08:01 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2020-11-21 22:08:01 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2020-11-21 22:08:01 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2020-11-21 22:08:01 [error]: at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.Components.PathControlPointPiece.OnDrag(DragEvent e)
2020-11-21 22:08:01 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2020-11-21 22:08:01 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
```

**Comment by Pennek** [comment]
The above issue may be another issue entirely, since I was dragging and rewinding. Rewatching the video I noticed that wasn't done originally. I tried replicating it and got another crash. Here's the [runtime.log](https://github.com/ppy/osu/files/5578519/runtime.log)

**Comment by bdach** [comment]
I have attempted a few times and am unable to reproduce.

**Comment by nbvdkamp** [comment]
I was able to reproduce it by rightclicking while dragging the sliderend over the timeline, scrolling the timeline. I got a slightly different stack trace:
```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in osu.Game.Rulesets.Osu.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at osu.Game.Rulesets.Osu.Objects.Drawables.Connections.FollowPointConnection.refreshPoints() in E:\dev\osuFork\osu\osu.Game.Rulesets.Osu\Objects\Drawables\Connections\FollowPointConnection.cs:line 51
   at osu.Game.Rulesets.Osu.Objects.Drawables.Connections.FollowPointConnection.onEntryInvalidated() in E:\dev\osuFork\osu\osu.Game.Rulesets.Osu\Objects\Drawables\Connections\FollowPointConnection.cs:line 45
   at osu.Game.Rulesets.Osu.Objects.Drawables.Connections.FollowPointLifetimeEntry.refreshLifetimes() in E:\dev\osuFork\osu\osu.Game.Rulesets.Osu\Objects\Drawables\Connections\FollowPointLifetimeEntry.cs:line 95
   at osu.Game.Rulesets.Osu.Objects.Drawables.Connections.FollowPointLifetimeEntry.onDefaultsApplied(HitObject obj) in E:\dev\osuFork\osu\osu.Game.Rulesets.Osu\Objects\Drawables\Connections\FollowPointLifetimeEntry.cs:line 72
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, BeatmapDifficulty difficulty, CancellationToken cancellationToken) in E:\dev\osuFork\osu\osu.Game\Rulesets\Objects\HitObject.cs:line 130
   at osu.Game.Screens.Edit.EditorBeatmap.processHitObject(HitObject hitObject) in E:\dev\osuFork\osu\osu.Game\Screens\Edit\EditorBeatmap.cs:line 253
   at osu.Game.Screens.Edit.EditorBeatmap.UpdateState() in E:\dev\osuFork\osu\osu.Game\Screens\Edit\EditorBeatmap.cs:line 229
   at osu.Game.Screens.Edit.EditorBeatmap.Update() in E:\dev\osuFork\osu\osu.Game\Screens\Edit\EditorBeatmap.cs:line 217
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   ...
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
```
Seems to match the last log but I'm not sure if it's actually what is happening in the video
