### ISSUE TITLE
Hidden mod crashes with KeyNotFoundException

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11015]
**Describe the crash:** 
the game suddenly crashed after going into the spectator mode (ingame).

**osu!lazer version:** 
2020.1128.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5616758/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5616759/updater.log)
[database.log](https://github.com/ppy/osu/files/5616760/database.log)
[network.log](https://github.com/ppy/osu/files/5616761/network.log)
[performance.log](https://github.com/ppy/osu/files/5616762/performance.log)

**Comment by bdach** [comment]
Specific to hidden - will most likely happen every time when starting spectate on someone who's in the middle of a hidden map...

```
2020-11-30 14:52:03 [error]: An unhandled error has occurred.
2020-11-30 14:52:03 [error]: System.Collections.Generic.KeyNotFoundException: The given key 'osu.Game.Rulesets.Osu.Objects.SliderTailCircle' was not present in the dictionary.
2020-11-30 14:52:03 [error]: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2020-11-30 14:52:03 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.getFadeOutParametersFromSliderHead(OsuHitObject h)
2020-11-30 14:52:03 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.applyState(DrawableHitObject drawable, Boolean increaseVisibility)
2020-11-30 14:52:03 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.ApplyIncreasedVisibilityState(DrawableHitObject hitObject, ArmedState state)
```

Probably should soft-fail and just not apply the fade.

**Comment by peppy** [comment]
This can also be reproduced by pausing (using the new key binding) while watching a hidden play.

**Comment by bdach** [comment]
Can [also happen in tests, apparently...](https://ci.appveyor.com/project/peppy/osu/builds/36594371)

Half-inclined to just add a reference from the nested DHOs (slider tail/repeat circle) to the main slider itself, through which the slider head should be always retrievable without fail. Not sure how huge of a transgression it would be - it doesn't *feel* like a good step, but definitely an easy one...
