### ISSUE TITLE
Crash when install

### ISSUE THREAD

**Issue by dragondemon111311** [ppy/osu#11100]
i install osu!lazer and it crash
here is my log:
2020-12-05 11:51:21 [verbose]: ----------------------------------------------------------
2020-12-05 11:51:21 [verbose]: runtime Log for ShadowPC (LogLevel: Verbose)
2020-12-05 11:51:21 [verbose]: osu 2020.1204.0.0
2020-12-05 11:51:21 [verbose]: Running on Microsoft Windows NT 6.1.7601 Service Pack 1, 2 cores
2020-12-05 11:51:21 [verbose]: ----------------------------------------------------------
2020-12-05 11:51:21 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2020-12-05 11:51:21 [error]: An unhandled error has occurred.
2020-12-05 11:51:21 [error]: System.DllNotFoundException: Unable to load DLL 'SHCore.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
2020-12-05 11:51:21 [error]: at osu.Framework.Platform.Windows.WindowsWindow.SetProcessDpiAwareness(ProcessDpiAwareness awareness)
2020-12-05 11:51:21 [error]: at osu.Framework.Platform.Windows.WindowsWindow..ctor()
2020-12-05 11:51:21 [error]: at osu.Framework.Platform.Windows.WindowsGameHost.CreateWindow()
2020-12-05 11:51:21 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
2020-12-05 11:51:21 [error]: at osu.Desktop.Program.Main(String[] args)

PLZ HELP

**Comment by bdach** [comment]
From the above log excerpt I presume this is Windows 7 SP1, which presumably doesn't have DPI scaling APIs.

Transferring to framework for proper handling.
