### ISSUE TITLE
osu! has stopped working

### ISSUE THREAD

**Issue by NellaR1** [ppy/osu#11151]
Recently installed osu!lazer, but it won't start, every time I try to run it it just crashes instantly, here's what the windows error says:

**Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osu!.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5f1757ad
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24384
  Fault Module Timestamp:	5c6e248c
  Exception Code:	e0434352
  Exception Offset:	000000000000be0d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	8202
  Additional Information 1:	abf9
  Additional Information 2:	abf9a7321a7308e212607a703332821d
  Additional Information 3:	c21e
  Additional Information 4:	c21e61f2cc2a703d9a660ffe5d9c5463**

And these are the logs:

**2020-12-11 19:15:25 [verbose]: ----------------------------------------------------------
2020-12-11 19:15:25 [verbose]: runtime Log for crespo (LogLevel: Verbose)
2020-12-11 19:15:25 [verbose]: osu 2020.1204.0.0
2020-12-11 19:15:25 [verbose]: Running on Microsoft Windows NT 6.1.7601 Service Pack 1, 4 cores
2020-12-11 19:15:25 [verbose]: ----------------------------------------------------------
2020-12-11 19:15:25 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2020-12-11 19:15:52 [error]: An unhandled error has occurred.
2020-12-11 19:15:52 [error]: System.DllNotFoundException: Unable to load DLL 'SHCore.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
2020-12-11 19:15:52 [error]: at osu.Framework.Platform.Windows.WindowsWindow.SetProcessDpiAwareness(ProcessDpiAwareness awareness)
2020-12-11 19:15:52 [error]: at osu.Framework.Platform.Windows.WindowsWindow..ctor()
2020-12-11 19:15:52 [error]: at osu.Framework.Platform.Windows.WindowsGameHost.CreateWindow()
2020-12-11 19:15:52 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
2020-12-11 19:15:52 [error]: at osu.Desktop.Program.Main(String[] args)**
[runtime.log](https://github.com/ppy/osu/files/5680002/runtime.log)

I'm on Windows 7 x64, any help would be appreciated, thanks.

**Comment by peppy** [comment]
Please wait for the next release. It will be fixed.
