### ISSUE TITLE
Background beatmap imports can stop normal game flows from working as expected

### ISSUE THREAD

**Issue by osuShiro** [ppy/osu#11198]
**Describe the bug:** 

While having beatmaps importing from stable, the game will hold on a background when accessing the editor via the main menu. Trying to edit a beatmap through the beatmap listing (F3 > edit) works without problems.

The game continues rendering normally while on the background. I can still open options with control+o, but other keys are unresponsive (escape in particular). Trying to exit the game with the window's cross returns to main menu while showing the "are you sure?" dialog.

Reproduction steps:
- begin importing beatmaps through the options in the main menu
- wait until maps are being imported
- try to access the editor via the main menu

**osu!lazer version:** 
2020.1212.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5714630/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5714631/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5714632/updater.log)
[database.log](https://github.com/ppy/osu/files/5714633/database.log)
[debug.log](https://github.com/ppy/osu/files/5714634/debug.log)
[network.log](https://github.com/ppy/osu/files/5714635/network.log)

**Comment by peppy** [comment]
So there's two issues here:

One is that the import process is single-threaded, with no priority given to the editor (to import your new beatmap) over the stable beatmap import. This means the editor is going to be waiting for that import to completely finish before it can display

The second is that due to this loading taking so long, you were able to quit back to the main menu and start a second editor loading, triggering an actual exception (as seen in your logs):

```
2020-12-18 08:29:26 [error]: System.InvalidOperationException: Cannot perform operations on a LeasedBindable that has been Returned.
2020-12-18 08:29:26 [error]: at osu.Framework.Bindables.LeasedBindable`1.checkValid()
2020-12-18 08:29:26 [error]: at osu.Framework.Bindables.LeasedBindable`1.set_Value(T value)
2020-12-18 08:29:26 [error]: at osu.Game.Screens.Edit.Editor.load(OsuColour colours, GameHost host, OsuConfigManager config)
2020-12-18 08:29:26 [error]: --- End of stack trace from previous location where exception was thrown ---
2020-12-18 08:29:26 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2020-12-18 08:29:26 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2020-12-18 08:29:26 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2020-12-18 08:29:26 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
```

This one definitely needs to be looked into.
