### ISSUE TITLE
Failed to join multiplayer room error

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11294]
**Describe the crash:** 
i just tried to join a multiplayer room and then this error appeared. im not able to reproduce this again.

**osu!lazer version:** 
2020.1225.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5740314/database.log)
[network.log](https://github.com/ppy/osu/files/5740315/network.log)
[performance.log](https://github.com/ppy/osu/files/5740316/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5740317/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5740318/updater.log)

**Comment by bdach** [comment]
From the log:

```
2020-12-24 17:52:22 [error]: System.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
2020-12-24 17:52:22 [error]: ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2020-12-24 17:52:22 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2020-12-24 17:52:22 [error]: at osu.Game.Online.RealtimeMultiplayer.StatefulMultiplayerClient.JoinRoom(Room room)
```

This is one of the areas we already know we need to follow up on (general thread safety of handling events from server).
