### ISSUE TITLE
Multiplayer crash after losing connection inside the lobby and rejoining

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11292]
**Describe the crash:** 
i completed a map in multiplayer, returned to the lobby and waited for a new map and after waiting for a few seconds i suddenly lost the connection. i tried to reconnect but it didnt work so i tried it again until i could join the lobby again and then the game crashed. 

**osu!lazer version:** 
2020.1225.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5740196/database.log)
[network.log](https://github.com/ppy/osu/files/5740197/network.log)
[performance.log](https://github.com/ppy/osu/files/5740198/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5740199/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5740200/updater.log)

**Comment by bdach** [comment]
Relevant stack trace part:

```
2020-12-24 16:58:58 [error]: System.InvalidOperationException: Sequence contains no matching element
2020-12-24 16:58:58 [error]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2020-12-24 16:58:58 [error]: at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
2020-12-24 16:58:58 [error]: at osu.Game.Screens.Multi.RealtimeMultiplayer.Match.RealtimeReadyButton.OnRoomChanged()
```

The ready button is expecting the logged-in user to be in the room, but the server has probably dropped them already at this point. Most likely there is nothing better to do than the boot the user out to the lounge, but obviously it shouldn't be fatal.
