### ISSUE TITLE
Multiplayer potential crash after exiting a lobby and returning to lounge

### ISSUE THREAD

**Issue by peppy** [ppy/osu#11309]
```
2020-12-25 15:48:34 [error]: Failed to update room: test.
2020-12-25 15:48:34 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2020-12-25 15:48:34 [error]: at osu.Game.Online.Multiplayer.PlaylistItem.MapObjects(BeatmapManager beatmaps, RulesetStore rulesets)
2020-12-25 15:48:34 [error]: at osu.Game.Screens.Multi.Components.RoomManager.update(Room local, Room remote)
2020-12-25 15:48:34 [error]: at osu.Game.Screens.Multi.Components.RoomManager.onRoomsReceived(List`1 received)
```

**Comment by Joehuu** [comment]
If you didn't see discord for the reproduction: https://discord.com/channels/188630481301012481/188630652340404224/792076183343726593. Still happens.

**Comment by peppy** [comment]
The only potential null I can see here is the first line (`apiBeatmap`). Not sure how this can happen though, missing (or empty) data in the API response?

**Comment by smoogipoo** [comment]
One that I've seen in a quick investigation has ruleset_id=5. Ruleset search filtering is done locally, so it's probably enough to quietly ignore such errors.

**Comment by peppy** [comment]
@smoogipoo are you able to take a look at this one? i'm not 100% sure on the best way to "quietly ignore" these errors, and you're more familar with this code.

**Comment by peppy** [comment]
Can no longer reproduce a hard crash as described here (it shows up as an error message but will not crash the game). Closing for now.
