### ISSUE TITLE
Endless playing state (multiplayer)

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#11329]
**Describe the bug:** 
After finishing a beatmap and returning to beatmap selection my panel shows "playing", so ill restart the game but seems to not let me join to that room
**Screenshots or videos showing encountered issue:** 
![osu_2020-12-26_19-44-35](https://user-images.githubusercontent.com/50848502/103161640-d2201200-47b2-11eb-8977-637d99acff94.jpg)

**osu!lazer version:** 
2020.1225.0
**Logs:**
when it happened
[logs.zip](https://github.com/ppy/osu/files/5743949/logs.zip)
after it happened
[logsafter.zip](https://github.com/ppy/osu/files/5743950/logsafter.zip)

**Comment by bdach** [comment]
From first log:

```
2020-12-27 00:25:43 [error]: Score submission failed!
2020-12-27 00:25:43 [error]: Microsoft.AspNetCore.SignalR.HubException: An unexpected error occurred invoking 'ChangeState' on the server. NotJoinedRoomException: This user has not yet joined a multiplayer room.
2020-12-27 00:25:43 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2020-12-27 00:25:43 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2020-12-27 00:25:43 [error]: at osu.Game.Screens.Multi.RealtimeMultiplayer.RealtimePlayer.SubmitScore(Score score)
```

From second log:

```
2020-12-27 00:29:13 [error]: System.AggregateException: One or more errors occurred. (An unexpected error occurred invoking 'JoinRoom' on the server. InvalidStateException: Already joined to this room.)
2020-12-27 00:29:13 [error]: ---> Microsoft.AspNetCore.SignalR.HubException: An unexpected error occurred invoking 'JoinRoom' on the server. InvalidStateException: Already joined to this room.
2020-12-27 00:29:13 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2020-12-27 00:29:13 [error]: at System.Threading.Tasks.ForceAsyncAwaiter`1.GetResult()
2020-12-27 00:29:13 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2020-12-27 00:29:13 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
```

Not sure what happened there, but it must have been server side... Possibly dropped/reordered messages?

**Comment by peppy** [comment]
99% sure this has been fixed via server-side state fixes. Closing for now.
