### ISSUE TITLE
Can't run tournament client

### ISSUE THREAD

**Issue by TheEZIC** [ppy/osu#11377]
Can't run tournament client on lattest release and commit. I tried to run it using the `--tournament` argument, but nothing happened. I also tried to build it using this command in my IDE termenal: `dotnet run -p osu.Desktop -c Release -tournament`. This launched a default client.

https://user-images.githubusercontent.com/35061249/103385356-0c6b1580-4b0b-11eb-9b11-1c90989c1ace.mp4

Osu!lazer version:  2020.1229.0

Logs when I tried to launch through termenal:
[network.log](https://github.com/ppy/osu/files/5755935/network.log)
[performance.log](https://github.com/ppy/osu/files/5755936/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5755937/runtime.log)
[database.log](https://github.com/ppy/osu/files/5755938/database.log)

My PC specificartion:
Processor: AMD Ryzen 5 1600
Graphics card: MSI 1050ti 4gb
RAM: 8GBx2 2400hz

**Comment by frenzibyte** [comment]
I've only told you to fill out the issue template for helping you further, and by that, I just mean doing the following:
![2020-12-31 01 38 08](https://user-images.githubusercontent.com/22781491/103384857-02481780-4b09-11eb-8449-7324bf21c2b6.gif)

And then filling out each section as written (describe crash, attach screenshots or video, attach logs, attach computer specs)

**Comment by TheEZIC** [comment]
`dotnet run -p osu.Desktop -c Release -- --tournament`
I've tried it before. This caused the crash

Logs:
[network.log](https://github.com/ppy/osu/files/5755956/network.log)
[performance.log](https://github.com/ppy/osu/files/5755957/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5755955/runtime.log)

Video:
https://user-images.githubusercontent.com/35061249/103385494-c2cefa80-4b0b-11eb-855a-8edc022b2e58.mp4

**Comment by TheEZIC** [comment]
If necessary, I can attach logs and videos when I launch from a desktop shortcut

**Comment by frenzibyte** [comment]
No need to, the logs you've attached are enough, I can see the issue now, relevant part here:
```
2020-12-30 22:57:21 [error]: An unhandled error has occurred.
2020-12-30 22:57:21 [error]: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Drawing.Point' because the type requires a JSON string value to deserialize correctly.
2020-12-30 22:57:21 [error]: To fix this error either change the JSON to a JSON string value or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
2020-12-30 22:57:21 [error]: Path 'Matches[0].Position.X', line 21, position 12.
2020-12-30 22:57:21 [error]: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2020-12-30 22:57:21 [error]: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2020-12-30 22:57:21 [error]: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2020-12-30 22:57:21 [error]: at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
```

guessing something regressed with the JSON decoding

**Comment by TheEZIC** [comment]
Ok, delete bracket.json helped solve the problem. Thanks

**Comment by peppy** [comment]
We are going to fix this properly. I'm not sure why this was closed, please don't close issues by deleting files. That's not a valid solution and it doesn't help with visibility (which is why this wasn't fixed yet).

Tracking in https://github.com/ppy/osu/issues/11443

**Comment by TheEZIC** [comment]
Do I need to reopen or recreate it?

**Comment by bdach** [comment]
No. The issue has been fixed already in `master`. The fix will be out next release.
