### ISSUE TITLE
"download failed" error

### ISSUE THREAD

**Issue by LudovikoX** [ppy/osu#11484]
I tried downloading osu!lazer, i already have osu! installed and i keep getting this error saying the download has failed.

  
![Capture](https://user-images.githubusercontent.com/77456803/104627430-01fd5f80-5665-11eb-8d7c-eca5c32f4e60.PNG)

version 2021.109.0

[SquirrelSetup.log](https://github.com/ppy/osu/files/5816062/SquirrelSetup.log)

I'm using windows 10, 64 bit.

**Comment by bdach** [comment]
Relevant error:

```
2021-01-14 12:27:22> IEnableLogger: Failed to invoke post-install: System.UnauthorizedAccessException: Access to the path 'C:\Users\Student\Start Menu\Programs\ppy Pty Ltd' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
```

You seem to be running the installer with insufficient privileges. Please try running with admin privileges and seeing if it fixes (although this probably indicates some deeper-level brokenness of your system, as I'm not sure why you should be prohibited from writing to your own user start menu catalogue).
