### ISSUE TITLE
Leaving playlist lounge while it's busy joining a room crashes game

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#11570]
```
[runtime] 2021-01-22 13:58:03 [error]: System.InvalidOperationException: This bindable has already been Returned.
[runtime] 2021-01-22 13:58:03 [error]: at osu.Framework.Bindables.LeasedBindable`1.Return()
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Screens.OnlinePlay.OngoingOperationTracker.endOperation() in /Users/salman/Desktop/osu/osu.Game/Screens/OnlinePlay/OngoingOperationTracker.cs:line 55
[runtime] 2021-01-22 13:58:03 [error]: at osu.Framework.Threading.Scheduler.Add(Action task, Boolean forceScheduled)
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Screens.OnlinePlay.OngoingOperationTracker.<BeginOperation>b__5_0() in /Users/salman/Desktop/osu/osu.Game/Screens/OnlinePlay/OngoingOperationTracker.cs:line 47
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Screens.OnlinePlay.Lounge.LoungeSubScreen.<>c__DisplayClass34_0.<joinRequested>b__1(String _) in /Users/salman/Desktop/osu/osu.Game/Screens/OnlinePlay/Lounge/LoungeSubScreen.cs:line 183
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Screens.OnlinePlay.Components.RoomManager.<>c__DisplayClass28_0.<JoinRoom>b__1(Exception exception) in /Users/salman/Desktop/osu/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs:line 102
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Online.API.APIRequest.TriggerFailure(Exception e) in /Users/salman/Desktop/osu/osu.Game/Online/API/APIRequest.cs:line 141
[runtime] 2021-01-22 13:58:03 [error]: at osu.Game.Online.API.APIRequest.<>c__DisplayClass24_0.<Fail>b__0() in /Users/salman/Desktop/osu/osu.Game/Online/API/APIRequest.cs:line 174
```

https://user-images.githubusercontent.com/22781491/105500962-aa9a6780-5cd4-11eb-918f-2de2a4a3e881.mov

**Comment by peppy** [comment]
https://github.com/ppy/osu/issues/11543
