### ISSUE TITLE
Crash when starting a multiplayer match with mods

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#11810]
```
Unhandled exception. osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the InternalChildren of a Loading Drawable while not on the load thread. Consider using Schedule to schedule the mutation operation.
   at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member)
   at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
   at osu.Game.Screens.Play.HUD.ModDisplay.<.ctor>b__9_0(ValueChangedEvent`1 mods) in /home/smgi/Repos/osu/osu.Game/Screens/Play/HUD/ModDisplay.cs:line 78
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Game.Screens.OnlinePlay.Multiplayer.MultiplayerMatchSubScreen.UpdateMods() in /home/smgi/Repos/osu/osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs:line 296
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
```
Not entirely sure how this happened - I started play with no mods, then set required_mods (just DT) and started another play. Seems like this regressed from the recent mod changes.

**Comment by peppy** [comment]
Is that the end of the call stack? Curious where that's getting called from, thread-wise.

**Comment by smoogipoo** [comment]
Updated the issue description.

**Comment by smoogipoo** [comment]
Not sure at this point whether this is a regression of my changes though - still investigating.
