### ISSUE TITLE
Scaling slider in editor while snapping causes unhandled exception

### ISSUE THREAD

**Issue by InfinityGhost** [ppy/osu#11831]
**Describe the crash:** 
Attempting to scale a slider that is also snapping to another object results in an unhandled exception. 

```
Unhandled exception. System.ArgumentException: Position must be finite, but is (NaN, NaN).
   at osu.Framework.Graphics.Drawable.set_Position(Vector2 value)
   at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.Components.PathControlPointPiece.updateMarkerDisplay() in /repos/osu/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs:line 194
   at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.Components.PathControlPointPiece.OnHoverLost(HoverLostEvent e) in /repos/osu/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs:line 125
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at osu.Framework.Input.InputManager.updateHoverEvents(InputState state)
   at osu.Framework.Input.InputManager.HandleMousePositionChange(MousePositionChangeEvent e)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.MousePositionAbsoluteInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass101_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /repos/osu/osu.Desktop/Program.cs:line 55
   ```

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/39218853/108473969-b7bb5f80-725c-11eb-8d8a-d593c93198ad.mp4

**osu!lazer version:** 
a6d163619a21b251fbba7cf05ece587fde06a607 Local Release

**Logs:**

[database.log](https://github.com/ppy/osu/files/6008419/database.log)
[network.log](https://github.com/ppy/osu/files/6008420/network.log)
[performance.log](https://github.com/ppy/osu/files/6008421/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6008422/runtime.log)

**Computer Specifications:** 
Intel i7 4790 @ 4.00GHz
NVIDIA GTX 1070
Running NixOS w/ GNOME 3 X11

**Comment by peppy** [comment]
I can't seem to reproduce this, so it may be specific to the beatmap or the slider nodes you have within. Are you able to provide the beatmap (or an empty beatmap with just enough hitobjects to reproduce the crash)?

**Comment by InfinityGhost** [comment]
> I can't seem to reproduce this, so it may be specific to the beatmap or the slider nodes you have within. Are you able to provide the beatmap (or an empty beatmap with just enough hitobjects to reproduce the crash)?

Will have to go back and see if I can reproduce this on latest, I don't even remember which beatmap this occured.

**Comment by InfinityGhost** [comment]
No longer can reproduce this as of ab49e84d170cf7376ca25e6f239306ccf840475a.
