### ISSUE TITLE
Wrong error message shown to silenced/restricted/banned users when trying to send chat messages

### ISSUE THREAD

**Issue by Modsnotworking** [ppy/osu#11902]
**Describe the bug:** Replace 'Posting Message Failed/error' than a notification(if Banned/Silenced/restricted),'You/User's name have been banned/restricted/silenced for 5/10 minutes, etc' or (if you are sending messages too quickly then), refer to the linked pull request by peppy #11903 

**Screenshots or videos showing encountered issue:** 
![osu_2021-02-25_19-18-38](https://user-images.githubusercontent.com/70589304/109162942-c941c180-779e-11eb-816d-9297946dcae0.jpg)

**osu!lazer version:** **2021.220.0**
**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6043373/logs.zip)

**Comment by frenzibyte** [comment]
```
2021-02-25 13:48:15 [error]: Posting message failed.
2021-02-25 13:48:15 [error]: osu.Game.Online.API.APIException: You cannot send messages while silenced, restricted or banned.
2021-02-25 13:48:15 [error]: ---> System.Net.WebException: Forbidden
2021-02-25 13:48:15 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2021-02-25 13:48:15 [error]: at osu.Framework.IO.Network.WebRequest.beginResponse(CancellationToken cancellationToken)
2021-02-25 13:48:15 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken)
```

For you, reason why: `osu.Game.Online.API.APIException: You cannot send messages while silenced, restricted or banned.`

Should probably be shown as an error message by `system` in the chats.

**Comment by Modsnotworking** [comment]
@frenzibyte so does this mean that I have been silenced, restricted or BANNED, but I didn't even got any notification that I have been silenced, restricted or banned?

**Comment by bdach** [comment]
[Check your profile.](https://osu.ppy.sh/users/17880531) You have a 5 minute silence on record.

The only thing that's a problem of the game in this issue is the error message.

**Comment by Modsnotworking** [comment]
@bdach so should I close this issue now?

**Comment by bdach** [comment]
No. The error message should be fixed on our side.

**Comment by Modsnotworking** [comment]
@bdach Ok I'll let this issue be open
