### ISSUE TITLE
Editor crashes if PlaylistOverlay was previously opened (at least once)

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11968]
**Describe the bug:** As title. Steps to reproduce:
- Open the `PlaylistOverlay`
- Close it and go to the editor
- The editor will throw an error (see the end of the post)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/110186874-dd2c9980-7e16-11eb-9da3-b0c03a4929f2.mp4

**osu!lazer version:** `2021.302.0`

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6094162/runtime.log)

Here's the error:
```
2021-03-05 23:55:42 [verbose]: Screen changed → Editor
2021-03-05 23:55:42 [error]: An unhandled error has occurred.
2021-03-05 23:55:42 [error]: osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the Transforms of a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Transforms.Transformable.AddTransform(Transform transform, Nullable`1 customTransformID)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis](TThis t, Transform transform)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.TransformableExtensions.FadeColour[T,TEasing](T drawable, ColourInfo newColour, Double duration, TEasing& easing)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.TransformableExtensions.FadeColour[T](T drawable, ColourInfo newColour, Double duration, Easing easing)
2021-03-05 23:55:42 [error]: at osu.Game.Graphics.UserInterface.OsuAnimatedButton.<>c__DisplayClass10_0.<load>b__0(ValueChangedEvent`1 enabled)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2021-03-05 23:55:42 [error]: at osu.Game.Collections.CollectionFilterDropdown.CollectionDropdownMenuItem.collectionChanged()
2021-03-05 23:55:42 [error]: at osu.Game.Collections.CollectionFilterDropdown.CollectionDropdownMenuItem.<LoadComplete>b__17_1(ValueChangedEvent`1 _)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2021-03-05 23:55:42 [error]: at osu.Framework.Bindables.LeasedBindable`1.set_Value(T value)
2021-03-05 23:55:42 [error]: at osu.Game.Screens.Edit.Editor.load(OsuColour colours, GameHost host, OsuConfigManager config)
2021-03-05 23:55:42 [error]: --- End of stack trace from previous location ---
2021-03-05 23:55:42 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2021-03-05 23:55:42 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_0`1.<LoadComponentsAsync>b__1()
2021-03-05 23:55:42 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2021-03-05 23:55:42 [error]: --- End of stack trace from previous location ---
2021-03-05 23:55:42 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-03-05 23:55:42 [error]: --- End of stack trace from previous location ---
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2021-03-05 23:55:42 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-03-05 23:55:42 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-05 23:55:42 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-03-05 23:55:42 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-03-05 23:55:42 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
```

**Comment by frenzibyte** [comment]
This isn't exactly happening because of the playlist overlay, IIRC the same exception with the same stack trace will be thrown if you switch to editor from song select's footer beatmap options.

This is happening because of `Editor` changing the value of the beatmap bindable while in load thread:
https://github.com/ppy/osu/blob/b24174911908fb6c7a640d1ac56689cd3d4bb8d7/osu.Game/Screens/Edit/Editor.cs#L106-L122
which causes certain components (`CollectionDropdownMenuItem`'s `OsuAnimatedButton` in this case) to attempt mutating their transforms list, and that's not allowed when not in update thread.

A good fix would likely be to move `Editor`'s loading logic into `LoadComplete` such that the beatmap can be safely changed.
