### ISSUE TITLE
Osu!lazer : Cant sign in

### ISSUE THREAD

**Issue by Eluminae** [ppy/osu#11972]
Hello there,

I can't signin for no reason. I got no error message ingame but here the logs

```
==> network.log <==
2021-03-06 18:05:07 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2021-03-06 18:05:07 [verbose]: ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
2021-03-06 18:05:07 [verbose]: at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
2021-03-06 18:05:07 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: --- End of inner exception stack trace ---
2021-03-06 18:05:07 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-03-06 18:05:07 [verbose]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken).
2021-03-06 18:05:07 [verbose]: Login failed!
```

```
$ neofetch
                __.;=====;.__                   stacy@terminator
            _.=+==++=++=+=+===;.                ----------------
             -=+++=+===+=+=+++++=_              OS: Void Linux x86_64
        .     -=:``     `--==+=++==.            Host: MS-7850 1.0
       _vi,    `            --+=++++:           Kernel: 5.10.19_1
      .uvnvi.       _._       -==+==+.          Uptime: 8 hours, 43 mins
     .vvnvnI`    .;==|==;.     :|=||=|.         Packages: 1675 (xbps-query)
+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm.   Shell: bash 5.1.4
 -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE   Resolution: 1440x900
  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'   WM: sway
   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!     Terminal: alacritty
     -1vvnvv.     `~+++`        ++|+++          CPU: Intel i5-4690K (4) @ 3.900GHz
      +vnvnnv,                 `-|===           GPU: AMD ATI Radeon HD 7970/8970 / R9 280X
       +vnvnvns.           .      :=-           Memory: 3946MiB / 15937MiB
        -Invnvvnsi..___..=sv=.     `
          +Invnvnvnnnnnnnnvvnn;.
            ~|Invnvnvvnvvvnnv}+`
               -~|{*l}*|~
```

**Comment by jai-x** [comment]
I believe this is specifically a problem with Void Linux using LibreSSL. In comparison to most Linux distributions using OpenSSL, Void Linux chooses to use LibreSSL. While LibreSSL purports to be API compatible it often poses problems and is officially not supported by the `dotnet` runtime. See https://github.com/dotnet/runtime/issues/24869

There is good news however, Void Linux is switching back to using OpenSSL soon: https://voidlinux.org/news/2021/02/OpenSSL.html
Please wait for this change to take place from the Void Linux maintainers and then update your system.

**Comment by frenzibyte** [comment]
Then I believe this can be closed as not an issue on our end, yeah?

**Comment by Eluminae** [comment]
Oh ! I was not aware of this switch to openssl. The last news say that the full rebuild to openssl is underway.

There is lot of chance that this is related to my issue. I'll just wait some days to play osu then 

I'll re-open if the issue is not solved after the migration. Ty a lot for pointing this news !
