### ISSUE TITLE
Storyboarded outros don't play out

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#11982]
**Describe the bug:** 

As can be observed on maps like [Queen - Don't Stop Me Now](https://osu.ppy.sh/beatmapsets/5381#osu/26567), [Feryquitous - (S).0ngs//---::compilation.[TQR-f3]](https://osu.ppy.sh/beatmapsets/1124097#osu/2348896) or [Inspector K - Disconnected Hardkore (CanBlaster Remix)](https://osu.ppy.sh/beatmapsets/832364#osu/1743837). Not sure how intended this is, but they should definitely be shown and be skippable like stable.

This was reported at #9373, but that was closed due to grouping different issues together, and hasn't been separately reported since.

**Screenshots or videos showing encountered issue:** 

Not needed

**osu!lazer version:** 
latest: 2021.302.0

**Logs:**

N/A

**Comment by peppy** [comment]
We don't really have the flow in place to handle outro time at all. Might take a bit of effort to get the skip logic hooked up, but straightforward otherwise.

**Comment by Cublibre** [comment]
@marlinabowring and I have started working on this, though we're not sure how to show the score after the outro ends/is skipped. 
Right now we're checking if there's still time left in the storyboard in `Player.updateCompletionState` as shown below, but we don't know where to go from there. How can we listen for an exit/skip request or check if the outro has ended after the map has completed?

```cs
// Player.cs
private void updateCompletionState(ValueChangedEvent<bool> completionState)
{
    // ...
    prepareScoreForDisplayTask ??= Task.Run( ... );

    if (storyboardEndTime > currentTime) return;
    // ...
}
```

**Comment by peppy** [comment]
That's not something I can easily answer without actually implementing this myself. You're going to need to add new logic to handle this case, since you're requiring the skip display for a second non-adjacent time segment.

**Comment by marlinabowring** [comment]
We're working on making the tests for our implementation. We are able to create a dummy beatmap and create StoryboardSprites but are confused on how to add a start/end time for them. We want them to appear after the last hit object so that there is an outro. Any advice?

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu/blob/a5b3ac7ef8101c867bec8c1188ec4595ccb1c919/osu.Game.Tests/Visual/Gameplay/TestSceneLeadIn.cs#L51-L57

**Comment by Cublibre** [comment]
We have written an initial implementation and unit tests, but our unit tests are inconsistently failing. When running all of them at once, we get `Cannot invoke BeginPlaying when already playing` at `osu.Game.Online.Spectator.SpectatorStreamingClient`. This doesn't occur when running the tests individually per session, or one by one in the GUI. Any ideas on avoiding this?

[Unit tests -- TestSceneStoryboardWithOutro.cs](https://github.com/marlinabowring/osu/blob/9c6226a5621416df08d2e464f924f8082d303143/osu.Game.Tests/Visual/Gameplay/TestSceneStoryboardWithOutro.cs)

<details>
<summary>Stack trace</summary>

```
TearDown : System.AggregateException : One or more errors occurred. (Cannot invoke BeginPlaying when already playing)
  ----> System.InvalidOperationException : Cannot invoke BeginPlaying when already playing
--TearDown
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at osu.Framework.Testing.TestScene.checkForErrors()
   at osu.Framework.Testing.TestScene.RunTests()
--InvalidOperationException
   at osu.Game.Online.Spectator.SpectatorStreamingClient.BeginPlaying(GameplayBeatmap beatmap, Score score) in C:\Users\cublibre\Source\eecs481\osu\osu.Game\Online\Spectator\SpectatorStreamingClient.cs:line 161
   at osu.Game.Rulesets.UI.ReplayRecorder`1.LoadComplete() in C:\Users\cublibre\Source\eecs481\osu\osu.Game\Rulesets\UI\ReplayRecorder.cs:line 52
   at osu.Framework.Graphics.Drawable.loadComplete()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Game.Rulesets.UI.FrameStabilityContainer.UpdateSubTree() in C:\Users\cublibre\Source\eecs481\osu\osu.Game\Rulesets\UI\FrameStabilityContainer.cs:line 99
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass103_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Framework.Testing.TestScene.<>c__DisplayClass12_0.<SetupGameHost>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
-----
```
</details>

**Comment by frenzibyte** [comment]
Checking out the branch with the commit that has this unit test in, it looks to pass running all of them at once:
![CleanShot 2021-04-15 at 08 18 33@2x](https://user-images.githubusercontent.com/22781491/114817711-30551d00-9dc3-11eb-99cb-161ae819c112.png)

**Comment by Cublibre** [comment]
That's strange.. does it pass every time for you? Sometimes all of them would pass but it seems like most of the time that weird error happens.

**Comment by smoogipoo** [comment]
Can ignore the test failure you mentioned.
