### ISSUE TITLE
Null reference on changelog display

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12000]
```
2021-03-11 15:44:18 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-03-11 15:44:18 [error]: at osu.Game.Overlays.ChangelogOverlay.<>c__DisplayClass11_0.<ShowBuild>b__0()
2021-03-11 15:44:18 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-03-11 15:44:18 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-03-11 15:44:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

**Comment by Modsnotworking** [comment]
How do you delete downloaded replays(when you click on someone's score and press 'Download Replay' in osu!lazer? or are those downloaded replays automatically deleted after you view them?

PS. I am sorry for leaving this question here

**Comment by peppy** [comment]
There will eventually be a way to purge these, but for now you will hav to delete *all* replays from the maintenance area of settings if you really want to get rid of them.

**Comment by Joehuu** [comment]
Or delete one at a time using right click.

**Comment by peppy** [comment]
what why the FUCK are you replying here
