### ISSUE TITLE
Editor crashes when trying to select nodes overlapped by other objects

### ISSUE THREAD

**Issue by Momoccchi** [ppy/osu#12089]
When I right click on a node that is over another object it selects the object below instead of the node and causes the game to crash. I have been able to consistently recreate this crash, but as far as I know it's only an issue when both objects are sliders. 

Videos: 
https://streamable.com/l0ntzz -in a map where I had to deal with this issue a lot. 
https://streamable.com/36ccdz -recreating the issue in a simple pattern. 

This is on osu!lazer 2021.312.0

[runtime.log](https://github.com/ppy/osu/files/6173676/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6173677/updater.log)
[database.log](https://github.com/ppy/osu/files/6173678/database.log)
[performance.log](https://github.com/ppy/osu/files/6173679/performance.log)

Computer Specifications: 
AMD Ryzen 5 3600
AMD RX 5700XT Sapphire Nitro 
16 GB Ram
I forgot what motherboard I have but it's a good one.

**Comment by bdach** [comment]
The logs are missing the exception trace, but I can reproduce and it looks scary:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Graphics.Drawable.ToSpaceOfOtherDrawable(RectangleF input, IDrawable other)
   at osu.Framework.Graphics.Drawable.get_BoundingBox()
   at osu.Framework.Graphics.Containers.CompositeDrawable.get_BoundingBox()
   at osu.Framework.Graphics.Drawable.computeRequiredParentSizeToFit()
   at osu.Framework.Graphics.Drawable.get_RequiredParentSizeToFit()
   at osu.Framework.Graphics.Containers.CompositeDrawable.computeAutoSize()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateAutoSize()
   at osu.Framework.Graphics.Containers.CompositeDrawable.updateChildrenSizeDependencies()
   at osu.Framework.Graphics.Containers.CompositeDrawable.get_Size()
   at osu.Framework.Graphics.Drawable.get_DrawSize()
   at osu.Framework.Graphics.Drawable.get_DrawRectangle()
   at osu.Framework.Graphics.Drawable.Contains(Vector2 screenSpacePos)
   at osu.Framework.Graphics.Containers.CompositeDrawable.Contains(Vector2 screenSpacePos)
   at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.Components.PathControlPointPiece.ReceivePositionalInputAt(Vector2 screenSpacePos) in /home/dachb/Dokumenty/opensource/osu/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs:line 115
```
