### ISSUE TITLE
Bugs regarding new Tablet Support

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#12099]
**Describe the bug:** 
1.) Unplugging the detected Tablet will show the autoreport message and crash the Game afterwards
Happens when Tablet is disabled aswell
Unplugging and Replugging other Tablets while they are not the detected one is fine

2.) Plugging in a Tablet while osu! is running wont detect the Tablet

3.) As with OpenTabletDriver, having the default Drivers installed will make the Devices not work
Step2 of this [video](https://www.youtube.com/watch?v=35-Jz6_TZOc) fixes that issue

4.) The Tabletname scales with the Tabletsize
Small Tablet == Big Font (eg Huion H430P)
Large Tablet == Small Font (eg Huion H610 V2 Pro)

**osu!lazer version:** 
2021.320.0

**Logs:**
Logs when unplugging Tablet:
[performance.log](https://github.com/ppy/osu/files/6175275/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175276/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6175277/updater.log)
[database.log](https://github.com/ppy/osu/files/6175278/database.log)
[network.log](https://github.com/ppy/osu/files/6175279/network.log)

**Comment by bdach** [comment]
Please don't clump up issues like this. One issue per one item in the future, please.

1. This is an actual issue.

```
2021-03-20 10:10:10 [error]: osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the Transforms of a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
2021-03-20 10:10:10 [error]: at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member)
2021-03-20 10:10:10 [error]: at osu.Framework.Graphics.Transforms.Transformable.AddTransform(Transform transform, Nullable`1 customTransformID)
2021-03-20 10:10:10 [error]: at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis](TThis t, Transform transform)
2021-03-20 10:10:10 [error]: at osu.Framework.Graphics.Drawable.Hide()
2021-03-20 10:10:10 [error]: at osu.Game.Overlays.Settings.Sections.Input.TabletSettings.<LoadComplete>b__22_7(ValueChangedEvent`1 val)
2021-03-20 10:10:10 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2021-03-20 10:10:10 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
```

2. Cannot reproduce.
3. This is best taken to OTD themselves.
4. I don't understand what you mean. Why would the text scale with the tablet size?

**Comment by bdach** [comment]
The [`TabletInfo` bindable](https://github.com/ppy/osu-framework/blob/b103b43453b3975e4ae28b383659f502883610b7/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L29-L31) is not safe for adding transforms in callback. Would appreciate opinions whether to add schedules locally (in `TabletSettings` and `TabletAreaSelection`), or to fix it framework-side by making it an update-thread-safe bindable.

**Comment by ackhack** [comment]
2.) 
[performance.log](https://github.com/ppy/osu/files/6175666/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175667/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6175668/updater.log)
[database.log](https://github.com/ppy/osu/files/6175669/database.log)
[network.log](https://github.com/ppy/osu/files/6175670/network.log)
when connencting a Tablet while osu! is running i get these erros

3.) Will create Issue at their Repo

4.)Thats what i mean with the Text scales.
![image](https://user-images.githubusercontent.com/43985368/111871304-7caa6a00-8989-11eb-8e1b-517fc61dd2da.png)
![image](https://user-images.githubusercontent.com/43985368/111871353-ba0ef780-8989-11eb-82bc-478d63721a4b.png)

**Comment by bdach** [comment]
Point 2. has been fixed along with 1.
