### ISSUE TITLE
Crash in editor when making changes to hitobjects

### ISSUE THREAD

**Issue by peppy** [ppy/osu#12179]
May be related to autoplay generation or some other weirdness.

https://user-images.githubusercontent.com/191335/112435722-76046400-8d88-11eb-94ac-3daca293bdc1.mp4

```

[runtime] 2021-03-25 06:30:55 [error]: An unhandled error has occurred.
[runtime] 2021-03-25 06:30:55 [error]: System.InvalidOperationException: A DrawableSliderHead was hit before it became hittable!
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Osu.UI.StartTimeOrderedHitPolicy.HandleHit(DrawableHitObject hitObject) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/UI/StartTimeOrderedHitPolicy.cs:line 53
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Osu.UI.OsuPlayfield.onNewResult(DrawableHitObject judgedObject, JudgementResult result) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs:line 142
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.UI.Playfield.<.ctor>b__27_2(DrawableHitObject d, JudgementResult r) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/Playfield.cs:line 103
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.onNewResult(DrawableHitObject d, JudgementResult r) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 213
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.onNewResult(DrawableHitObject drawableHitObject, JudgementResult result) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 384
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.ApplyResult(Action`1 application) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 768
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Osu.Objects.Drawables.DrawableHitCircle.CheckForResult(Boolean userTriggered, Double timeOffset) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs:line 134
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateResult(Boolean userTriggered) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 785
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Osu.Objects.Drawables.DrawableHitCircle.<load>b__20_4() in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs:line 65
[runtime] 2021-03-25 06:30:55 [error]: at osu.Game.Rulesets.Osu.Objects.Drawables.DrawableHitCircle.HitReceptor.OnPressed(OsuAction action) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs:line 225

```

**Comment by peppy** [comment]
I'm sure this is still an issue, but I can't readily reproduce it. If anyone runs into this in the future a more solid reproduction case would be appreciated.
