### ISSUE TITLE
osu!lazer first time download, can't login

### ISSUE THREAD

**Issue by Kaedae** [ppy/osu#12209]
**Describe the bug:** It's my first time downloading osu!lazer. When I tried logging in onto my account for some reason it doesn't login. Before I made this post, I first read all the posts with the same problem as I have, I tried all of their suggestion on what to do when they can't login (for example: disabling IPv6 on network settings) and none of them worked for me. So I made this post regarding to my problem.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/81525922/112817688-4c637980-90b5-11eb-834f-7a485669efe5.png)

**osu!lazer version:** 2021.323.0 

**Logs:** 
[network.log](https://github.com/ppy/osu/files/6220729/network.log)
[database.log](https://github.com/ppy/osu/files/6220731/database.log)

**Comment by peppy** [comment]
This looks like a potential cloudflare level issue (https://www.cloudflarestatus.com/incidents/44p4slgcfhmz). Can you confirm you're in AU?

**Comment by Kaedae** [comment]
I can say that I'm not from AU. I am from SEA, Philippines.

**Comment by peppy** [comment]
It's likely still related. Please try again in a few hours.

**Comment by Kaedae** [comment]
I'll update after trying. Thank you.

**Comment by Kaedae** [comment]
> I'll update after trying. Thank you.

I checked the Cloud Flare Status and now it says "This incident has been resolved." Just tried to login again and still getting the same problem.

![image](https://user-images.githubusercontent.com/81525922/112843961-c572c900-90d5-11eb-8ef4-d40dea547886.png)

**Here are the latest logs btw**
[network.log](https://github.com/ppy/osu/files/6222039/network.log)
[database.log](https://github.com/ppy/osu/files/6222040/database.log)

**Comment by frenzibyte** [comment]
```
2021-03-29 13:28:25 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: An error occurred while sending the request.
2021-03-29 13:28:25 [verbose]: ---> System.IO.IOException: The read operation failed, see inner exception.
2021-03-29 13:28:25 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
2021-03-29 13:28:25 [verbose]: ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-03-29 13:28:25 [verbose]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken).
2021-03-29 13:28:25 [verbose]: Login failed!
```

that still looks like a SSL/TLS handshake failure, maybe give it a bit before retrying? seems only 24 minutes passed since they fixed it

**Comment by Kaedae** [comment]
> ```
> 2021-03-29 13:28:25 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: An error occurred while sending the request.
> 2021-03-29 13:28:25 [verbose]: ---> System.IO.IOException: The read operation failed, see inner exception.
> 2021-03-29 13:28:25 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
> 2021-03-29 13:28:25 [verbose]: ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
> 2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
> 2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
> 2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
> 2021-03-29 13:28:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.FillAsync(Boolean async)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: --- End of inner exception stack trace ---
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
> 2021-03-29 13:28:25 [verbose]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken).
> 2021-03-29 13:28:25 [verbose]: Login failed!
> ```
> 
> that still looks like a SSL/TLS handshake failure, maybe give it a bit before retrying? seems only 24 minutes passed since they fixed it.

Oh sure, I'll be waiting for maybe 10 hours or a day. Thank you

**Comment by peppy** [comment]
To confirm can you access the osu! site fine in a web browser?

**Comment by Kaedae** [comment]
> To confirm can you access the osu! site fine in a web browser?

Yes, I can access the site normally and fine.

**Comment by peppy** [comment]
@Kaedae are you still encountering this same issue?

**Comment by Kaedae** [comment]
Yup. I try logging in day by day still the same. Came back to original osu! now, just gonna wait for the lazer to become stable. Thanks for helping

**Comment by peppy** [comment]
Keep in mind that this issue is not magically going to go away. It's likely something specific to your PC configuration that is going to need to be solved.

**Comment by etekweb** [comment]
I was having a similar issue, and it let me log in again once I switched the DNS server on my computer to Cloudflare's public DNS server (1.1.1.1 and 1.0.0.1) instead of my router's DNS server (which in theory also points to 1.1.1.1, but idk).

Might be helpful in case others are having issues logging in or accessing web features in osu!lazer.

**Comment by ItsIgnacioPortal** [comment]
I'm having this same exact issue, but in version osu lazer version 2022.1123.0.0
[network.log](https://github.com/ppy/osu/files/10120748/network.log)
[performance.log](https://github.com/ppy/osu/files/10120750/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10120751/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10120752/updater.log)
[database.log](https://github.com/ppy/osu/files/10120753/database.log)
[input.log](https://github.com/ppy/osu/files/10120754/input.log)

Windows information (output of `systeminfo`): [systeminfo.txt](https://github.com/ppy/osu/files/10120770/systeminfo.txt)
I have disabled IPv6 on my gateway network interface, and I'm using 1.1.1.1 and 1.0.0.1 as my dns servers.
This is a wireshark pcap file of the traffic when this error pops up: [osu-lazer-no-internet.zip](https://github.com/ppy/osu/files/10120872/osu-lazer-no-internet.zip)

@peppy any clue? could you share your `systeminfo`?

**Comment by peppy** [comment]
Your system-wide SSL is broken somehow.

Providing a wireshark capture is likely not sufficient to figure this out because it sounds like there's something on your system mangling ssl traffic. I think you're going to have to investigate this one further yourself.

**Comment by ItsIgnacioPortal** [comment]
Using this filter removes all of the noise (ip.dst==172.67.14.100 || ip.src==172.67.14.100 || ip.dst==104.22.74.180 || ip.src==104.22.74.180 || ip.dst==104.22.75.180 || ip.src==104.22.75.180 || ip.src==1.1.1.1 || ip.dst==1.1.1.1 || ip.src==1.0.0.1 || ip.dst==1.0.0.1)

- DNS resolves correctly
- The TCP three-way-handshake completes successfully
- TLS completes the Client Hello and Server Hello dance just fine
- However, it seems to mess up when it actually has to transmit the Application Data

This is very odd to me, as I don't have any issue like this with any other program besides Osu!Lazer.

Could you run this command and share the output with me?: `dotnet --list-runtimes` Perhaps installing a different .NET runtime version will help, but I want to know what _does_ work

**Comment by peppy** [comment]
The runtime is bundled with the install. It has to be something at a windows, driver or hardware level.

**Comment by ItsIgnacioPortal** [comment]
> It has to be something at a windows, driver or hardware level.

This has to be an issue in Osu!Lazer or one of its dependencies. How come every other piece of software I've tried can easily communicate with osu.ppy.sh?

Check this out: https://stackoverflow.com/questions/63223539/ssl-error-the-message-received-was-unexpected-or-badly-formatted-for-a-net-ap

When Osu!Lazer tries to talk to osu.ppy.sh, it uses the `TLS_AES_256_GCM_SHA384 (0x1302)` cipher-suite, but when firefox communicates with osu.ppy.sh it uses the `TLS_AES_128_GCM_SHA256 (0x1301)` cipher-suite. **@peppy Perhaps removing support for `TLS_AES_256_GCM_SHA384 (0x1302)` would force Osu!Lazer to use `TLS_AES_128_GCM_SHA256 (0x1301)`, and that would fix the SSL issues?**

**Comment by ThePooN** [comment]
> I can visit https://osu.ppy.sh/home from Firefox just fine.

can you reach https://osu.ppy.sh/home from IE/Edge? IE uses Windows' SSL implementation, so does Edge (I hope).

Also, is this a genuine version of Windows or did you install using an altered ISO, or altered Windows in other ways?

**Comment by ItsIgnacioPortal** [comment]
> can you reach https://osu.ppy.sh/home from IE/Edge? IE uses Windows' SSL implementation, so does Edge (I hope).

Yes, it loads fine in Internet Explorer and in Microsoft Edge.

> Also, is this a genuine version of Windows or did you install using an altered ISO, or altered Windows in other ways?

Yes, I have a geniune version of Windows. All of my OS info is in [the `systeminfo.txt` I shared](https://github.com/ppy/osu/files/10120770/systeminfo.txt), I only redacted some info to avoid doxxing my family.

**Comment by Trung0246** [comment]
Going to bump this thread since apparently for some reason cloudflare stuff prevent me from logging in on lazer

```
2023-05-07 06:31:11 [verbose]: ----------------------------------------------------------
2023-05-07 06:31:11 [verbose]: network Log for trung (LogLevel: Verbose)
2023-05-07 06:31:11 [verbose]: Running osu 2023.419.0.0 on .NET 6.0.15
2023-05-07 06:31:11 [verbose]: Environment: Windows (Microsoft Windows NT 10.0.22621.0), 8 cores
2023-05-07 06:31:11 [verbose]: ----------------------------------------------------------
2023-05-07 06:31:11 [verbose]: Request to https://lazer.ppy.sh/oauth/token failed with System.Net.WebException: Forbidden.
2023-05-07 06:31:11 [verbose]: Response was: <!DOCTYPE html>
2023-05-07 06:31:11 [verbose]: <html lang="en-US">
2023-05-07 06:31:11 [verbose]: <head>
2023-05-07 06:31:11 [verbose]: <title>Just a moment...</title>
2023-05-07 06:31:11 [verbose]: <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
2023-05-07 06:31:11 [verbose]: <meta http-equiv="X-UA-Compatible" content="IE=Edge">
2023-05-07 06:31:11 [verbose]: <meta name="robots" content="noindex,nofollow">
2023-05-07 06:31:11 [verbose]: <meta name="viewport" content="width=device-width,initial-scale=1">
2023-05-07 06:31:11 [verbose]: <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
2023-05-07 06:31:11 [verbose]: 
2023-05-07 06:31:11 [verbose]: 
2023-05-07 06:31:11 [verbose]: </head>
2023-05-07 06:31:11 [verbose]: <body class="no-js">
2023-05-07 06:31:11 [verbose]: <div class="main-wrapper" role="main">
2023-05-07 06:31:11 [verbose]: <div class="main-content">
2023-05-07 06:31:11 [verbose]: <noscript>
2023-05-07 06:31:11 [verbose]: <div id="challenge-error-title">
2023-05-07 06:31:11 [verbose]: <div class="h2">
2023-05-07 06:31:11 [verbose]: <span class="icon-wrapper">
2023-05-07 06:31:11 [verbose]: <div class="heading-icon warning-icon"></div>
2023-05-07 06:31:11 [verbose]: </span>
2023-05-07 06:31:11 [verbose]: <span id="challenge-error-text">
2023-05-07 06:31:11 [verbose]: Enable JavaScript and cookies to continue
2023-05-07 06:31:11 [verbose]: </span>
2023-05-07 06:31:11 [verbose]: </div>
2023-05-07 06:31:11 [verbose]: </div>
2023-05-07 06:31:11 [verbose]: </noscript>
2023-05-07 06:31:11 [verbose]: <div id="trk_jschal_js" style="display:none;background-i
2023-05-07 06:31:11 [verbose]: (Response was trimmed)
2023-05-07 06:31:11 [verbose]: Login failed for username Trung0246 (Forbidden)!
2023-05-07 06:31:14 [verbose]: Request to https://lazer.ppy.sh/oauth/token failed with System.Net.WebException: Forbidden.
2023-05-07 06:31:14 [verbose]: Response was: <!DOCTYPE html>
2023-05-07 06:31:14 [verbose]: <html lang="en-US">
2023-05-07 06:31:14 [verbose]: <head>
2023-05-07 06:31:14 [verbose]: <title>Just a moment...</title>
2023-05-07 06:31:14 [verbose]: <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
2023-05-07 06:31:14 [verbose]: <meta http-equiv="X-UA-Compatible" content="IE=Edge">
2023-05-07 06:31:14 [verbose]: <meta name="robots" content="noindex,nofollow">
2023-05-07 06:31:14 [verbose]: <meta name="viewport" content="width=device-width,initial-scale=1">
2023-05-07 06:31:14 [verbose]: <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
2023-05-07 06:31:14 [verbose]: 
2023-05-07 06:31:14 [verbose]: 
2023-05-07 06:31:14 [verbose]: </head>
2023-05-07 06:31:14 [verbose]: <body class="no-js">
2023-05-07 06:31:14 [verbose]: <div class="main-wrapper" role="main">
2023-05-07 06:31:14 [verbose]: <div class="main-content">
2023-05-07 06:31:14 [verbose]: <noscript>
2023-05-07 06:31:14 [verbose]: <div id="challenge-error-title">
2023-05-07 06:31:14 [verbose]: <div class="h2">
2023-05-07 06:31:14 [verbose]: <span class="icon-wrapper">
2023-05-07 06:31:14 [verbose]: <div class="heading-icon warning-icon"></div>
2023-05-07 06:31:14 [verbose]: </span>
2023-05-07 06:31:14 [verbose]: <span id="challenge-error-text">
2023-05-07 06:31:14 [verbose]: Enable JavaScript and cookies to continue
2023-05-07 06:31:14 [verbose]: </span>
2023-05-07 06:31:14 [verbose]: </div>
2023-05-07 06:31:14 [verbose]: </div>
2023-05-07 06:31:14 [verbose]: </noscript>
2023-05-07 06:31:14 [verbose]: <div id="trk_jschal_js" style="display:none;background-i
2023-05-07 06:31:14 [verbose]: (Response was trimmed)
2023-05-07 06:31:14 [verbose]: Login failed for username Trung0246 (Forbidden)!
```

Is cloudflare overzealous with my ip?

**Comment by peppy** [comment]
Can you try visiting https://lazer.ppy.sh and make sure that works for you?

**Comment by Trung0246** [comment]
![image](https://user-images.githubusercontent.com/11626920/236741728-c5923b68-d7fc-4eef-a8ee-8cafe78c7abf.png)
Hm looks like it works as expected. Maybe it's really cloudflare thing.

**Comment by peppy** [comment]
It's quite weird that it doesn't trigger from a browser but does from lazer. We have cloudflare on the most relaxed setting so this shouldn't really be a thing.

Could it be that you have a VPN applied to one of the two cases?

**Comment by Trung0246** [comment]
No VPN enabled for both case either.

**Comment by ThePooN** [comment]
@Trung0246 Hey, I'm an infrastructure engineer for osu!.

If you can still reproduce, please [email me](mailto:thepoon@osufr.live) your network log file and both IPv4 an IPv6 addresses (can be obtained using https://whatismyipaddress.com/) so I can look into this further.

Thanks

**Comment by peppy** [comment]
On further investigation, the lowest setting we can choose ("Essentially off") is not off. Unless we pay cloudflare mega enterprise bucks they are always going to block the most potent IPs. Which means this user's PC or network is probably compromised.

**Comment by ThePooN** [comment]
I have looked into @Truang0246's situation further and I can confirm with 100% certainty @peppy's probable diagnosis (bad IP/network score).

**Comment by ItsIgnacioPortal** [comment]
https://community.cloudflare.com/t/community-tip-best-practices-for-captcha-challenges/56301
