### ISSUE TITLE
Local scores with customized "Barrel Roll" mod throw invalid cast exceptions

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12454]
If you played and beat a beatmap with the BR mod customized (in my case: 4.00 roll speed, Direction CounterClockwise), the local scores that you have made before cannot be fetched at all and an error message pops up (every time you go to the Local tab of a beatmap), saying "An unhandled error has occurred.".

Even if you close the client and reload the game, the bug still persists.

![osu_2021-04-16_15-17-50](https://user-images.githubusercontent.com/77842743/115073880-f0775e00-9ec6-11eb-8654-6fbfcec25f6e.jpg)
^^^
Here is what has happened (after restarting the game as well).

**Comment by frenzibyte** [comment]
Logs?

**Comment by ZedME** [comment]
[performance.log](https://github.com/ppy/osu/files/6327473/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6327474/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6327475/updater.log)
[database.log](https://github.com/ppy/osu/files/6327476/database.log)
[network.log](https://github.com/ppy/osu/files/6327477/network.log)

**Comment by frenzibyte** [comment]
Relevant logs:
```
2021-04-16 19:21:50 [error]: An unhandled error has occurred.
2021-04-16 19:21:50 [error]: System.InvalidCastException: Invalid cast from 'System.Int64' to 'osu.Framework.Graphics.RotationDirection'.
2021-04-16 19:21:50 [error]: at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
2021-04-16 19:21:50 [error]: at System.Int64.System.IConvertible.ToType(Type type, IFormatProvider provider)
2021-04-16 19:21:50 [error]: at osu.Framework.Bindables.Bindable`1.Parse(Object input)
2021-04-16 19:21:50 [error]: at osu.Game.Rulesets.Mods.Mod.CopyAdjustedSetting(IBindable target, Object source)
2021-04-16 19:21:50 [error]: at osu.Game.Online.API.APIMod.ToMod(Ruleset ruleset)
2021-04-16 19:21:50 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
2021-04-16 19:21:50 [error]: at osu.Game.Scoring.ScoreManager.TotalScoreBindable.updateScore(Int32 beatmapMaxCombo, Double accuracy)
2021-04-16 19:21:50 [error]: at osu.Game.Scoring.ScoreManager.TotalScoreBindable.onScoringModeChanged(ValueChangedEvent`1 mode)
2021-04-16 19:21:50 [error]: at osu.Game.Scoring.ScoreManager.GetBindableTotalScore(ScoreInfo score)
2021-04-16 19:21:50 [error]: at osu.Game.Online.Leaderboards.LeaderboardScore.load(IAPIProvider api, OsuColour colour, ScoreManager scoreManager)
```

Will give it a quick investigation.
