### ISSUE TITLE
SSL connection not established due to reset by peer

### ISSUE THREAD

**Issue by YuhItsVon** [ppy/osu#12479]
I have multiple problems. I looked through Reddit and osu forums, yet I couldn't find anything. Can you help me with these problems?

Problem #1
<img width="214" alt="Screen Shot 2021-04-17 at 5 45 17 PM (1)" src="https://user-images.githubusercontent.com/82780775/115160974-dc129d00-a04f-11eb-89f8-d64fcce13750.png">

I don't know how to fix this. Here are my logs below.
[Logs.zip](https://github.com/ppy/osu/files/6332215/Logs.zip)

Problem #2
Whenever I try to import (skins, beatmaps, etc) from stable, this message keeps showing up. It also doesn't work.
<img width="403" alt="Screen Shot 2021-04-18 at 2 09 10 PM" src="https://user-images.githubusercontent.com/82780775/115160989-ed5ba980-a04f-11eb-8fd9-bcfd49cf7a2b.png">

Problem #3
Screen Shot 2021-04-17 at 5.49.07 PM.png
Every time I finish a level, this keeps popping up. I don't know how to fix this.
<img width="398" alt="Screen Shot 2021-04-18 at 2 09 14 PM" src="https://user-images.githubusercontent.com/82780775/115161000-f3ea2100-a04f-11eb-9ec2-f8bea406054b.png">

More Information:

I use a MacBook: Big Sur (Not Catalina or below) the version of Osu! Lazer is 
<img width="217" alt="Screen Shot 2021-04-18 at 2 09 22 PM" src="https://user-images.githubusercontent.com/82780775/115161005-f9e00200-a04f-11eb-88fb-15cf99e68ee0.png">

I hope you guys can help me fix this :D Thanks!

**Comment by frenzibyte** [comment]
I don't see your logs?

**Comment by YuhItsVon** [comment]
> I don't see your logs?

Whoops, my bad.
[Logs.zip](https://github.com/ppy/osu/files/6332214/Logs.zip)

**Comment by frenzibyte** [comment]
For problem 1, it's a "connection reset by peer" error while osu!lazer is trying to log in:
```
2021-04-18 00:44:24 [error]: An unobserved error has occurred.
2021-04-18 00:44:24 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The SSL connection could not be established, see inner exception.)
2021-04-18 00:44:24 [error]: ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2021-04-18 00:44:24 [error]: ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
2021-04-18 00:44:24 [error]: ---> System.Net.Sockets.SocketException (54): Connection reset by peer
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-04-18 00:44:24 [error]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.FileWebRequest.Complete(Exception e)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.PerformAsync(CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: An unobserved error has occurred. (inner)
2021-04-18 00:44:24 [error]: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2021-04-18 00:44:24 [error]: ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
2021-04-18 00:44:24 [error]: ---> System.Net.Sockets.SocketException (54): Connection reset by peer
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-04-18 00:44:24 [error]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.FileWebRequest.Complete(Exception e)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: at osu.Framework.IO.Network.WebRequest.PerformAsync(CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: An unobserved error has occurred. (inner) (inner)
2021-04-18 00:44:24 [error]: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
2021-04-18 00:44:24 [error]: ---> System.Net.Sockets.SocketException (54): Connection reset by peer
2021-04-18 00:44:24 [error]: --- End of inner exception stack trace ---
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
2021-04-18 00:44:24 [error]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-04-18 00:44:24 [error]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2021-04-18 00:44:24 [error]: An unobserved error has occurred. (inner) (inner) (inner)
2021-04-18 00:44:24 [error]: System.Net.Sockets.SocketException (54): Connection reset by peer
```

Can you confirm whether you encounter this all the time, that's weird.

As for problem 2, you would have to symlink your osu!stable folder to the path `~/.osu` for osu!lazer to read and import from it, until https://github.com/ppy/osu/issues/3763 is resolved.

As for problem 3, you seem to have restarted the game prior to attaching the logs, the latest thing I see in your logs is staying in the main menu screen, without going to song select and actually play a beatmap, but it's high likely the same as in "problem 1".

**Comment by YuhItsVon** [comment]
Can you confirm whether you encounter this all the time? and whether navigating through the osu! website works just fine?

Everytime I log into osu!lazer, this appears every time. The website works fine (osu.ppy.sh)

**Comment by peppy** [comment]
Do you have some kind of firewall / antivirus / internet security / router blocking stuff?

**Comment by YuhItsVon** [comment]
I do have the free version of Malware. I do not have anything else.

**Comment by peppy** [comment]
Did you find a solution to your issue?

**Comment by YuhItsVon** [comment]
> Did you find a solution to your issue?

Problem 1 disappeared in an update.

However, Problem 2 was not fixed. I don't quite know what to do.

**Comment by frenzibyte** [comment]
You mean "Problem 3"? "Every time I finish a level, this keeps popping up."

**Comment by YuhItsVon** [comment]
> You mean "Problem 3"? "Every time I finish a level, this keeps popping up."

yes

**Comment by bizzk3t** [comment]
I came across a similar issue on Ubuntu, I resolved this issue by restarting my computer.

Possible cause: Before playing osu, I updated my computer and it changed some network packages, specifically, dns-utils and bind9-host.
