### ISSUE TITLE
Newer versions of osu require SDL development package to run

### ISSUE THREAD

**Issue by vesterlay** [ppy/osu#12523]
Executing the newest version of osu results in this error: 
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at osu.Framework.Platform.SDL2DesktopWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 54

```
Which basically requires _Simple DirectMedia Layer development files_ `libsdl2-dev` to be installed. Is that an intended behavior? 

My OS is Linux Deepin 20.2

**Comment by peppy** [comment]
may be related to https://github.com/ppy/SDL2-CS/issues/42

**Comment by Fuseteam** [comment]
i think it is, i encountered the same on ubuntu 18.04

**Comment by peppy** [comment]
We've resolved this upstream and it should be fixed in the next release.
