### ISSUE TITLE
Clicking on names in chat sometimes will make osu freeze and stop responding

### ISSUE THREAD

**Issue by Flanster** [ppy/osu#1290]
Some say clicking on just BanchoBot does this, but I found it happens at a random point with any name.
I attached VS debugger to get the following error:
~~~
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Invalid value (NaN) provided for component translation.Y.
  Source=osu.Framework
  StackTrace:
       at osu.Framework.Graphics.DrawInfo.checkComponentValid(Single component, String name)
       at osu.Framework.Graphics.DrawInfo.ApplyTransform(Vector2 translation, Vector2 scale, Single rotation, Vector2 shear, Vector2 origin)
       at osu.Framework.Graphics.Drawable.computeDrawInfo()
       at osu.Framework.Graphics.Drawable.get_DrawInfo()
       at osu.Framework.Graphics.Drawable.ComputeScreenSpaceDrawQuad()
       at osu.Framework.Graphics.Drawable.get_ScreenSpaceDrawQuad()
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(Int32 treeIndex, RectangleF bounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(Int32 treeIndex, Int32& j, CompositeDrawable parentComposite, List`1 target, RectangleF maskingBounds)
       at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(Int32 treeIndex, RectangleF bounds)
       at osu.Framework.Platform.GameHost.UpdateFrame()
       at osu.Framework.Threading.GameThread.ProcessFrame()
       at osu.Framework.Threading.GameThread.runWork()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at osu.Framework.Threading.Scheduler.Update()
       at osu.Framework.Threading.GameThread.ProcessFrame()
       at osu.Framework.Platform.GameHost.<Run>b__89_1(Object <sender>, FrameEventArgs <e>)
       at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
       at OpenTK.GameWindow.RaiseUpdateFrame(Double elapsed, Double& timestamp)
       at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e)
       at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
       at osu.Framework.Platform.GameHost.Run(Game game)
       at osu.Desktop.Program.Main(String[] args)
  InnerException: 
~~~

**Comment by DaPrimeAtce** [comment]
I've noticed this issue too, you're not alone.

**Comment by Shawdooow** [comment]
99% sure this is caused by the graph showing rank if a player is newer than 90 days or doesn't have any plays (banchobot)

**Comment by peppy** [comment]
Is anyone able to reproduce this?

**Comment by Shawdooow** [comment]
I can, clicking on banchobot causes it 100% of the time
