### ISSUE TITLE
Game crashing when repeatedly loading score with invalid mod

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12934]
**Describe the bug:** 

There is an unhanded exception when loading scores in the song selection carousel.
In my case, it's trying to load a score with the random mod (https://github.com/ppy/osu/pull/12568), which doesn't exist in 2021.523.0

Excerpt from log:

```
2021-05-24 12:44:54 [error]: An unhandled error has occurred.
2021-05-24 12:44:54 [error]: System.InvalidOperationException: There is no mod in the ruleset (osu) matching the acronym RD.
2021-05-24 12:44:54 [error]: at osu.Game.Online.API.APIMod.ToMod(Ruleset ruleset)
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreInfo.<>c__DisplayClass45_0.<get_Mods>b__0(APIMod m)
2021-05-24 12:44:54 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreInfo.get_Mods()
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreManager.TotalScoreBindable.updateScore(Int32 beatmapMaxCombo, Double accuracy)
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreManager.TotalScoreBindable.onScoringModeChanged(ValueChangedEvent`1 mode)
2021-05-24 12:44:54 [error]: at osu.Framework.Bindables.Bindable`1.BindValueChanged(Action`1 onChange, Boolean runOnceImmediately)
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreManager.TotalScoreBindable..ctor(ScoreInfo score, Func`1 difficulties)
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreManager.GetBindableTotalScore(ScoreInfo score)
2021-05-24 12:44:54 [error]: at osu.Game.Scoring.ScoreManager.GetBindableTotalScoreString(ScoreInfo score)
2021-05-24 12:44:54 [error]: at osu.Game.Online.Leaderboards.LeaderboardScore.load(IAPIProvider api, OsuColour colour, ScoreManager scoreManager)
```

**osu!lazer version:** 2021.523.0

**Logs:** (Ignore the ruleset failed to load errors)

[performance.log](https://github.com/ppy/osu/files/6532388/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6532389/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6532390/updater.log)
[network.log](https://github.com/ppy/osu/files/6532391/network.log)

**Comment by peppy** [comment]
What is your expectation?

Just delete the score or work around it.
