### ISSUE TITLE
Score import fails on every map

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#13320]
**Describe the bug:** 
Score import fails and replay is unavailable on almost every map.
I have no idea about this because I thought it was okay a few mins ago on pure lazer build but only happened on a build with local framework, now it is happening on pure build, too
It's working fine on AppImage and was working fine yesterday.

**osu!lazer version:** 
Local build, commit daff4a1a003f46da3538c3c066a57c38db203a1b

**Logs:**

```
2021-06-03 14:56:16 [verbose]: Screen changed → PlayerLoader
2021-06-03 14:56:19 [verbose]: Screen changed → SoloPlayer
2021-06-03 14:57:42 [error]: Score import failed!
2021-06-03 14:57:42 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2021-06-03 14:57:42 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2021-06-03 14:57:42 [error]: at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
2021-06-03 14:57:42 [error]: at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
2021-06-03 14:57:42 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.get_replayStringContent() in /mnt/general/osu/lazergit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 95
2021-06-03 14:57:42 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.createReplayData() in /mnt/general/osu/lazergit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 66
2021-06-03 14:57:42 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.Encode(Stream stream) in /mnt/general/osu/lazergit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 54
2021-06-03 14:57:42 [error]: at osu.Game.Screens.Play.Player.ImportScore(Score score) in /mnt/general/osu/lazergit/osu/osu.Game/Screens/Play/Player.cs:line 939
2021-06-03 14:57:42 [error]: at osu.Game.Screens.Play.Player.<updateCompletionState>b__110_0() in /mnt/general/osu/lazergit/osu/osu.Game/Screens/Play/Player.cs:line 656
```

**Comment by peppy** [comment]
Thanks for the report. This looks to be a regression with recent changes which have not yet been released.

**Comment by coinworld** [comment]
```
2021-06-21 13:37:55 [verbose]: updating selection with beatmap:1373 ruleset:0
2021-06-21 13:37:55 [verbose]: beatmap changed from "TrySail - Utsuroi (0ugi) [Failure's Insane]" to "TrySail - Utsuroi (0ugi) [Kyuuchinyuni's Nightmare]"
2021-06-21 13:37:55 [verbose]: working beatmap updated to TrySail - Utsuroi (0ugi) [Kyuuchinyuni's Nightmare]
2021-06-21 13:37:56 [verbose]: Screen changed → PlayerLoader
2021-06-21 13:37:59 [verbose]: Screen changed → SoloPlayer
2021-06-21 13:38:13 [verbose]: Screen changed ← PlayerLoader
2021-06-21 13:38:15 [verbose]: Screen changed → SoloPlayer
2021-06-21 13:38:25 [verbose]: Screen changed ← PlayerLoader
2021-06-21 13:38:27 [verbose]: Screen changed → SoloPlayer
2021-06-21 13:42:16 [error]: Score import failed!
2021-06-21 13:42:16 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2021-06-21 13:42:16 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2021-06-21 13:42:16 [error]: at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
2021-06-21 13:42:16 [error]: at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
2021-06-21 13:42:16 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.get_replayStringContent() in /mnt/general/osu/lagit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 104
2021-06-21 13:42:16 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.createReplayData() in /mnt/general/osu/lagit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 75
2021-06-21 13:42:16 [error]: at osu.Game.Scoring.Legacy.LegacyScoreEncoder.Encode(Stream stream) in /mnt/general/osu/lagit/osu/osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs:line 63
2021-06-21 13:42:16 [error]: at osu.Game.Screens.Play.Player.ImportScore(Score score) in /mnt/general/osu/lagit/osu/osu.Game/Screens/Play/Player.cs:line 998
2021-06-21 13:42:16 [error]: at osu.Game.Screens.Play.Player.prepareScoreForResults() in /mnt/general/osu/lagit/osu/osu.Game/Screens/Play/Player.cs:line 714
2021-06-21 13:42:17 [verbose]: Screen changed → SoloResultsScreen
```

I am not sure why but this error is still there, just with a bit different stack trace but it isn't happening as frequently as it was when I opened this issue.
This seems to be pretty random for me and my local is at 5b9bf54f1fdff03c7d606d5dd7def0ec388666d2

**Comment by bdach** [comment]
If it's a different stacktrace it's a different error. It happens in a different place. And you even stated yourself that it "isn't happening as frequently", so clearly something's changed.

Possibly a regression related to the recent player logic reorganisation.

**Comment by coinworld** [comment]
There are no specific reproduction steps (at least I can't think of any), because I tried playing the same map after that error happened and my score imported successfully, but I can say that I am having this issue from time to time these days
