### ISSUE TITLE
Unhandled Argument Exception at Player.CreateScore()

### ISSUE THREAD

**Issue by InfinityGhost** [ppy/osu#13510]
**Describe the bug:** 

Playing ingame, at end of the map it freezes. Pressing escape to open the pause menu quits the map and returns to the song select with an unhandled exception.

This may have already been resolved, as I haven't tested on a more recent version.

```
2021-06-16 01:16:48 [error]: An unhandled error has occurred.
2021-06-16 01:16:48 [error]: System.AggregateException: One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))
2021-06-16 01:16:48 [error]: ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
2021-06-16 01:16:48 [error]: at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
2021-06-16 01:16:48 [error]: at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2021-06-16 01:16:48 [error]: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-06-16 01:16:48 [error]: at osu.Game.Screens.Play.Player.CreateScore() in /repos/osu/osu.Game/Screens/Play/Player.cs:line 931
2021-06-16 01:16:48 [error]: at osu.Game.Screens.Play.Player.<updateCompletionState>b__103_0() in /repos/osu/osu.Game/Screens/Play/Player.cs:line 636
2021-06-16 01:16:48 [error]: --- End of inner exception stack trace ---
2021-06-16 01:16:48 [error]: at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2021-06-16 01:16:48 [error]: at osu.Game.Screens.Play.Player.<scheduleCompletion>b__104_0() in /repos/osu/osu.Game/Screens/Play/Player.cs:line 687
2021-06-16 01:16:48 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-06-16 01:16:48 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-16 01:16:48 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-06-16 01:16:48 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-06-16 01:16:48 [error]: An unhandled error has occurred. (inner)
2021-06-16 01:16:48 [error]: System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
2021-06-16 01:16:48 [error]: at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
2021-06-16 01:16:48 [error]: at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2021-06-16 01:16:48 [error]: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-06-16 01:16:48 [error]: at osu.Game.Screens.Play.Player.CreateScore() in /repos/osu/osu.Game/Screens/Play/Player.cs:line 931
2021-06-16 01:16:48 [error]: at osu.Game.Screens.Play.Player.<updateCompletionState>b__103_0() in /repos/osu/osu.Game/Screens/Play/Player.cs:line 636
```

**Screenshots or videos showing encountered issue:** 

![osu_2021-06-15_21-21-50](https://user-images.githubusercontent.com/39218853/122143572-ba4f4f80-ce1f-11eb-84ac-599aa30d14ed.png)

**osu!lazer version:** 

Local build at 7b88ba8c63a3e53be8786146baae8736fcae9df7

**Logs:**

[database.log](https://github.com/ppy/osu/files/6659574/database.log)
[network.log](https://github.com/ppy/osu/files/6659575/network.log)
[performance.log](https://github.com/ppy/osu/files/6659576/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6659577/runtime.log)

**Comment by peppy** [comment]
This should already be fixed via https://github.com/ppy/osu/pull/13324. Please test using the latest head when reporting issues as we most pretty fast.
