### ISSUE TITLE
Threading mode toggle does not work with realm

### ISSUE THREAD

**Issue by bdach** [ppy/osu#13582]
While looking into #13580 on `master`, on most attempts to switch the threading mode, I get:

```
2021-06-19 15:33:42 [error]: System.Exception: Realm accessed from incorrect thread.
2021-06-19 15:33:42 [error]: at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
2021-06-19 15:33:42 [error]: at Realms.SharedRealmHandle.Refresh()
2021-06-19 15:33:42 [error]: at Realms.Realm.Refresh()
2021-06-19 15:33:42 [error]: at osu.Game.Database.RealmContextFactory.Update() in /home/dachb/Dokumenty/opensource/osu/osu.Game/Database/RealmContextFactory.cs:line 84
```

The context was created on the update thread, but is being accessed on the main thread after the threading mode change. I thought this was going to be pretty easy to get past by just purging realm contexts on threading mode switch, so I [applied the following change](https://github.com/ppy/osu/commit/09263171cf76275c3436815be70632529d2f8d7b). But then after some more debugging of the aforementioned issue I was hit by this:

```
2021-06-19 15:29:20 [error]: Realms.Exceptions.RealmClosedException: This object belongs to a closed realm.
2021-06-19 15:29:20 [error]: at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
2021-06-19 15:29:20 [error]: at Realms.ObjectHandle.GetValue(String propertyName, Metadata metadata, Realm realm)
2021-06-19 15:29:20 [error]: at Realms.RealmObjectBase.GetValue(String propertyName)
2021-06-19 15:29:20 [error]: at osu.Game.Input.Bindings.RealmKeyBinding.get_KeyCombinationString()
2021-06-19 15:29:20 [error]: at osu.Game.Input.Bindings.RealmKeyBinding.get_KeyCombination() in /home/dachb/Dokumenty/opensource/osu/osu.Game/Input/Bindings/RealmKeyBinding.cs:line 23
2021-06-19 15:29:20 [error]: at osu.Game.Overlays.Toolbar.ToolbarButton.updateKeyBindingTooltip() in /home/dachb/Dokumenty/opensource/osu/osu.Game/Overlays/Toolbar/ToolbarButton.cs:line 227
```

Which is worse to get past, and is why I'm opening this issue for discussion. It looks like any live objects are no longer safe to hold onto after a threading mode change and they need to all be invalidated. I think `Live<T>` will have to return in some capacity to resolve this; I don't immediately see any other way out.

**Comment by peppy** [comment]
Still not sure a `Live` type is what we want, but would potentially cover this scenario.

Another option is to make thread mode changes restart the game or something like that. Kind of a waste considering the work put in to making it happen without a restart, but depends on how many components are going to run into similar cases (like the GL one you found). May only get worse as time goes on.

**Comment by bdach** [comment]
The worse part of this is that `RealmContextFactory.BlockAllOperations()` has another user, namely the migration screen (and also game disposal, but that one doesn't matter). I haven't checked or tested this thoroughly but it's possible that a migration may also make existing references to live objects invalid for access.

**Comment by peppy** [comment]
It is possible to transfer realm object references across threads (using `ThreadSafeReference`s), but this needs to be done on a per reference basis, which doesn't help us much in our usage scenario.

**Comment by peppy** [comment]
@bdach opinions welcome on this WIP change:

https://github.com/ppy/osu/compare/master...peppy:realm-live-v2?expand=1#diff-4c57b58c12ff7dcf9a006014ce2b9be18a05c3af28aceb3b47e38bc003b49855R170-R179

Note that the branch currently crashes due to issues pointed out in https://github.com/ppy/osu-framework/pull/4533#issuecomment-865875998

**Comment by bdach** [comment]
I've skimmed through that diff and it looks sound. There's still a few things that I'd probably suggest to clean up or write a little differently; I would elaborate, but there's not really any easy way to leave comments on an un-PR'd branch, especially one that spans multiple commits. Other than that it's more or less what I imagined would be necessary to make the threading mode toggle work.

**Comment by peppy** [comment]
No worries. I'll try and get an initial PR out today so you can leave some proper feedback on it.
