### ISSUE TITLE
Transactional/threading issue in FileStore's reference logic

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1361]
```
[performance:verbose] Drawable ["" OsuSpriteText (0,0) 10x10] took 327.53ms to load and was not async!
[performance:verbose] Drawable [OsuTooltipContainer+OsuTooltip (0,0) 0x0] took 329.53ms to load and was not async!
[performance:verbose] Drawable [OsuTooltipContainer (0,0) 1x1] took 351.54ms to load and was not async!
[performance:verbose] Drawable [GlobalKeyBindingInputManager (0,0) 1x1] took 353.75ms to load and was not async!
[performance:verbose] Drawable [RatioAdjust (0,0) 1x1] took 361.55ms to load and was not async!
[runtime:error] ERROR: Could not import beatmap set
[runtime:error] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at osu.Game.IO.FileStore.<Reference>b__11_2(IGrouping`2 f) in C:\projects\osu\osu.Game\IO\FileStore.cs:line 117
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at SQLite.Net.SQLiteConnection.<>c__DisplayClass117_0.<UpdateAll>b__0()
   at SQLite.Net.SQLiteConnection.RunInTransaction(Action action)
   at SQLite.Net.SQLiteConnection.UpdateAll(IEnumerable objects, Boolean runInTransaction)
   at osu.Game.IO.FileStore.<>c__DisplayClass11_0.<Reference>b__0() in C:\projects\osu\osu.Game\IO\FileStore.cs:line 122
   at SQLite.Net.SQLiteConnection.RunInTransaction(Action action)
   at osu.Game.IO.FileStore.Reference(FileInfo[] files) in C:\projects\osu\osu.Game\IO\FileStore.cs:line 113
   at osu.Game.IO.FileStore.Add(Stream data, Boolean reference) in C:\projects\osu\osu.Game\IO\FileStore.cs:line 106
   at osu.Game.Beatmaps.BeatmapManager.importToStorage(ArchiveReader reader) in C:\projects\osu\osu.Game\Beatmaps\BeatmapManager.cs:line 449
   at osu.Game.Beatmaps.BeatmapManager.<>c__DisplayClass35_0.<Import>b__0() in C:\projects\osu\osu.Game\Beatmaps\BeatmapManager.cs:line 171
   at SQLite.Net.SQLiteConnection.RunInTransaction(Action action)
   at osu.Game.Beatmaps.BeatmapManager.Import(ArchiveReader archiveReader) in C:\projects\osu\osu.Game\Beatmaps\BeatmapManager.cs:line 171
   at osu.Game.Beatmaps.BeatmapManager.Import(String[] paths) in C:\projects\osu\osu.Game\Beatmaps\BeatmapManager.cs:line 131
```

As seen in

https://ci.appveyor.com/project/peppy/osu/build/master-4720/tests
https://ci.appveyor.com/project/peppy/osu/build/master-4739/tests

I've looked into this but nothing looks out of place.

**Comment by peppy** [comment]
Fixed with new db code.
