### ISSUE TITLE
osu!lazer won't open

### ISSUE THREAD

**Issue by florent-brotons** [ppy/osu#13722]
**Describe the bug:** 
When I try to open osu!Lazer, nothing happens.

**osu!lazer version:** 
2021.619.0

**Logs:**
[update_success.log](https://github.com/ppy/osu/files/6746925/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/6746926/runtime.log)
[session.log](https://github.com/ppy/osu/files/6746927/session.log)

**Windows Event Watcher:**
https://drive.google.com/file/d/1aUGWySGqfPJnHfpH5tTBu0r_bsKbUwY4/view?usp=sharing

**Comment by peppy** [comment]
The logs you provided are from osu!(stable).

**Comment by florent-brotons** [comment]
> The logs you provided are from osu!(stable).

What should I do? Change osu! to beta or experimental version before uploading the logs?

**Comment by peppy** [comment]
![20210701 182216 (Safari)](https://user-images.githubusercontent.com/191335/124100243-45277f80-da99-11eb-87bd-533b5eed3376.png)

**Comment by florent-brotons** [comment]
Is it any different now?

[session.log](https://github.com/ppy/osu/files/6747058/session.log)
[update_success.log](https://github.com/ppy/osu/files/6747060/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/6747061/runtime.log)

**Comment by smoogipoo** [comment]
No.

But this is in the event viewer logs:
```
Exception Info: System.TypeLoadException: Could not load type 'osu.Game.Rulesets.Mods.ModAutoplay`1' from assembly 'osu.Game, Version=2021.619.0.0, Culture=neutral, PublicKeyToken=null'.
   at osu.Game.Rulesets.Tau.TauRuleset.GetModsFor(ModType type)
   at osu.Game.OsuGameBase.onRulesetChanged(ValueChangedEvent`1 r)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
```

So, try updating and/or remove any custom rulesets you've added.

**Comment by smoogipoo** [comment]
No.

But this is in the event viewer logs:
```
Exception Info: System.TypeLoadException: Could not load type 'osu.Game.Rulesets.Mods.ModAutoplay`1' from assembly 'osu.Game, Version=2021.619.0.0, Culture=neutral, PublicKeyToken=null'.
   at osu.Game.Rulesets.Tau.TauRuleset.GetModsFor(ModType type)
   at osu.Game.OsuGameBase.onRulesetChanged(ValueChangedEvent`1 r)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
```

So, try updating and/or remove any custom rulesets you've added.

**Comment by florent-brotons** [comment]
Updating to 2021.703.0 worked for me, thank you!
