### ISSUE TITLE
osu!lazer no longer starting after updating to 2021.703.0

### ISSUE THREAD

**Issue by SupDos** [ppy/osu#13753]
**Describe the bug:** 
After updating from 2021.623.0 to 2021.703.0, osu!lazer will no longer open
First launch right after updating worked (saw the new disclaimer), however after closing the game and trying to open it again, it no longer opens, 
Tried running the exe's directly from the 623.0 and 703.0 folders, but they both won't budge.
Also tried re-running install.exe, it deleted the 623.0 folder from `%LocalAppData%\osulazer`, however 703.0 still doesn't launch.

**osu!lazer version:** 2021.703.0

**Logs:**
The files in `%AppData%/osu/logs` were last modified in 2020 so I don't think they'd be of any use, however Event Viewer has logs for both osu!.exe and .NET Runtime so will attach those instead

[netError](https://user-images.githubusercontent.com/6813986/124338423-311e7380-dba8-11eb-9053-71844c50ee64.png)
[netError2.txt](https://github.com/ppy/osu/files/6757625/netError2.txt) long error so attached as txt
[appError](https://user-images.githubusercontent.com/6813986/124338432-41365300-dba8-11eb-9596-2530c95ab369.png)

**Comment by frenzibyte** [comment]
```
Exception Info: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing)
   at osu.Game.Database.DatabaseWriteUsage.Dispose()
   at osu.Game.Database.MutableDatabaseBackedStore`1.PurgeDeletable(Expression`1 query)
   at osu.Game.Database.MutableDatabaseBackedStore`1.Cleanup()
   at osu.Game.Database.ArchiveModelManager`2..ctor(Storage storage, IDatabaseContextFactory contextFactory, MutableDatabaseBackedStoreWithFileIncludes`2 modelStore, IIpcHost importHost)
   at osu.Game.Database.DownloadableArchiveModelManager`2..ctor(Storage storage, IDatabaseContextFactory contextFactory, IAPIProvider api, MutableDatabaseBackedStoreWithFileIncludes`2 modelStore, IIpcHost importHost)
   at osu.Game.Beatmaps.BeatmapManager..ctor(Storage storage, IDatabaseContextFactory contextFactory, RulesetStore rulesets, IAPIProvider api, AudioManager audioManager, IResourceStore`1 resources, GameHost host, WorkingBeatmap defaultBeatmap, Boolean performOnlineLookups)
   at osu.Game.OsuGameBase.load()
--- End of stack trace from previous location ---
```

Looks to be an issue with your database file (`client.db`), you can temporarily move it away from its place (resides inside of where your game folder resides in) to get the game working back again, and attach the database file here for reference.

**Comment by SupDos** [comment]
Moving client.db out fixed it, thank you! Also found the correct logs, forgot that I moved the folder at some point whoops

Here is my client.db - https://drive.google.com/file/d/1Qme0Kj9GqY0zn2GZWlVhv68Nqe7z9x8w/view

**Comment by SupDos** [comment]
Accidentally closed, misclick sorry!

**Comment by bdach** [comment]
Attempted to load the attached database file and got a "database file is malformed" error. So I can't really investigate much further as to why this would fail given only the info above.

@SupDos do you recall if you deleted some maps recently?

**Comment by SupDos** [comment]
@bdach yeah, after updating I deleted all beatmaps, collections and scores using the Delete All buttons in Settings, reimported them all again, then I closed the game and it no longer started

**Comment by peppy** [comment]
non actionable due to corrupt database
