### ISSUE TITLE
`SkinProvidingContainer` is very bad code quality

### ISSUE THREAD

**Issue by peppy** [ppy/osu#13794]
While looking into this test failure, I found that `SkinProvidingContainer` is in a very bad state.

```csharp
osu.Game.Tests.Visual.Gameplay.TestSceneSkinEditor.TestToggleEditor

TearDown : System.AggregateException : One or more errors occurred. (The given key 'osu.Game.Skinning.DefaultSkin' was not present in the dictionary.)
  ----> System.Collections.Generic.KeyNotFoundException : The given key 'osu.Game.Skinning.DefaultSkin' was not present in the dictionary.
--TearDown
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at osu.Framework.Testing.TestScene.checkForErrors()
   at osu.Framework.Testing.TestScene.RunTests()
--KeyNotFoundException
```

Opening this as priority zero as it should not exist in the code.

- Bindable list should be removed. As far as I can tell it's only being used within the class itself, and adds complexity everywhere.
- Null checks should be removed. The value in the dictionary can never be null. I'm not sure what the intention was here but it's wrong as it stands and just adds to the confusion:

![20210706 160002 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/124556455-411da800-de73-11eb-8d12-e695fd2c3a3b.png)

- Would be nice to remove the whole dictionary lookup if possible, as well. Not sure if this is possible, needs further investigation.

I will take on this task if @frenzibyte isn't interested in fixing it.

**Comment by peppy** [comment]
The reason for the test failure should be immediately obvious: Lookups are allowed to occur on the dictionary from any firing of `OnSourceChanged`. This could be before the container is loaded, or in any kind of correct state.

So there could be two threads:

A background thread in the process of adding the skin to the dictionary at the purple line
![20210706 161701 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/124558478-a1ade480-de75-11eb-8f9c-5be4e7666f79.png)

A loaded drawable scheduling the `OnSkinChanged` to update thread, which is run at the same time as the above (asynchronous) action:
![20210706 161816 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/124558637-c609c100-de75-11eb-9483-6eddea3e25ff.png)

There's an argument that `SkinReloadableDrawable` is also quite unsafe with this event handling path, due to optimistically running the first `onSkinChanged` to benefit from asynchronous load.
