### ISSUE TITLE
Targetting .NET Standard 2.0

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1398]
For cross-platformness, we need to target .NET Standard 2.0. This allows us to compile/run using .NET Core on Linux/OSX, Xamarin on Android/iOS, and .NET Core/Framework on Windows.

The following branch tracks incremental changes towards the completion of this issue:
1. https://github.com/smoogipoo/osu/tree/net-standard

Related: https://github.com/ppy/osu-framework/issues/1098

The following items are required to be fulfilled before the transition to .NET Standard 2.0 is complete:
- [x] Retarget all projects in osu!.
- [ ] Determine if we want to keep the registry lookup for the osu!stable installation.
- [ ] Determine why OpenTK's drag/drop isn't working.
- [ ] Ensure that deploys work (osu.Desktop.Deploy).
- [ ] Re-integrate updater, at least for Windows.

**Comment by smoogipoo** [comment]
I'm using System.IO.Compression to unzip beatmaps because DotNetZip does not have .NET Standard packages. This change needs to be validated and needs to also be pushed to origin/master.

In particular, I get the following error when importing from osu!direct:
```
Unhandled Exception: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream)
   at osu.Game.Beatmaps.IO.OszArchiveReader..ctor(Stream archiveStream) in /Users/smoogipoo/Repos/osu/osu.Game/Beatmaps/IO/OszArchiveReader.cs:line 19
   at osu.Game.Beatmaps.BeatmapManager.<>c__DisplayClass38_0.<Download>b__1(Byte[] data) in /Users/smoogipoo/Repos/osu/osu.Game/Beatmaps/BeatmapManager.cs:line 250
   at osu.Game.Online.API.APIDownloadRequest.onSuccess() in /Users/smoogipoo/Repos/osu/osu.Game/Online/API/APIRequest.cs:line 48
```

**Comment by smoogipoo** [comment]
The following is a very common startup exception that seems to happen mostly on .NET Core:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at osu.Framework.Graphics.Transforms.TransformCustom`2.getAccessor(String propertyOrFieldName) in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Graphics/Transforms/TransformCustom.cs:line 132
   at osu.Framework.Graphics.Transforms.TransformCustom`2..ctor(String propertyOrFieldName, InterpolationFunc`1 interpolationFunc) in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Graphics/Transforms/TransformCustom.cs:line 161
   at osu.Framework.Graphics.TransformableExtensions.MakeTransform[TThis,TValue](TThis t, String propertyOrFieldName, TValue newValue, Double duration, Easing easing) in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Graphics/TransformableExtensions.cs:line 63
   at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis,TValue](TThis t, String propertyOrFieldName, TValue newValue, Double duration, Easing easing) in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Graphics/TransformableExtensions.cs:line 30
   at osu.Framework.Graphics.TransformableExtensions.FadeColour[T](T drawable, ColourInfo newColour, Double duration, Easing easing) in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Graphics/TransformableExtensions.cs:line 166
   at osu.Game.Graphics.UserInterface.OsuButton.enabled_ValueChanged(Boolean enabled) in /Users/smoogipoo/Repos/osu/osu.Game/Graphics/UserInterface/OsuButton.cs:line 82
   at osu.Framework.Configuration.Bindable`1.TriggerValueChange() in /Users/smoogipoo/Repos/osu/osu-framework/osu.Framework/Configuration/Bindable.cs:line 145
```

This needs to be investigated further.

**Comment by smoogipoo** [comment]
Tracked by https://github.com/ppy/osu/milestone/29.
