### ISSUE TITLE
New lazer version does not recognize the alsa-lib package on linux arch

### ISSUE THREAD

**Issue by BradyAtkinson** [ppy/osu#14122]
Running on linux Arch with kde plasma wayland
**Describe the bug:** 
Osu crashes a few seconds after opening the app. Tried opening with both Lutris and the appImage file and they would both crash. The logs says that I do not have libasound2-dev but I do have alsa-lib installed.
(output of pacman -Q --info alsa-lib)

[fire@castform osu]$ pacman -Q --info alsa-lib
Name            : alsa-lib
Version         : 1.2.5.1-3
Description     : An alternative implementation of Linux sound support
Architecture    : x86_64
URL             : https://www.alsa-project.org
Licenses        : LGPL2.1
Groups          : None
Provides        : libasound.so=2-64  libatopology.so=2-64
Depends On      : glibc  alsa-topology-conf  alsa-ucm-conf
Optional Deps   : None
Required By     : alsa-plugins  audiofile  bluez  chromium  ffmpeg  fluidsynth  gst-plugins-base  jack2  lib32-alsa-lib  libcanberra  mpg123  pipewire  portaudio  wildmidi  zita-alsa-pcmi
Optional For    : jre-openjdk  jre8-openjdk  libsndfile  sdl  sdl2  v4l-utils  vlc  wine-lol  wine-osu  wine-valve
Conflicts With  : None
Replaces        : None
Installed Size  : 1659.72 KiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Mon Jun 14 15:36:33 2021
Install Date    : Tue Aug 3 18:29:33 2021
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature

**osu!lazer version:** 
2021.731.0
**Logs:**

2021-08-03 21:39:40 [verbose]: ----------------------------------------------------------
2021-08-03 21:39:40 [verbose]: runtime Log for fire (LogLevel: Verbose)
2021-08-03 21:39:40 [verbose]: Running osu 2021.731.0.0 on .NET 5.0.6
2021-08-03 21:39:40 [verbose]: Environment: Linux (Unix 5.13.6.1), 8 cores
2021-08-03 21:39:40 [verbose]: ----------------------------------------------------------
2021-08-03 21:39:40 [error]: Couldn't list input devices. Is libasound2-dev installed?
2021-08-03 21:39:40 [error]: System.TypeInitializationException: The type initializer for 'Commons.Music.Midi.MidiAccessManager' threw an exception.
2021-08-03 21:39:40 [error]: ---> AlsaSharp.AlsaException: ALSA exception (error code = -19) : No such device
2021-08-03 21:39:40 [error]: at AlsaSharp.AlsaSequencer..ctor(AlsaIOType ioType, AlsaIOMode ioMode, String driverName)
2021-08-03 21:39:40 [error]: at Commons.Music.Midi.Alsa.AlsaMidiAccess..ctor()
2021-08-03 21:39:40 [error]: at Commons.Music.Midi.MidiAccessManager.InitializeDefault()
2021-08-03 21:39:40 [error]: at Commons.Music.Midi.MidiAccessManager..cctor()
2021-08-03 21:39:40 [error]: --- End of inner exception stack trace ---
2021-08-03 21:39:40 [error]: at Commons.Music.Midi.MidiAccessManager.get_Default()
2021-08-03 21:39:40 [error]: at osu.Framework.Input.Handlers.Midi.MidiHandler.refreshDevices()
2021-08-03 21:39:40 [verbose]: GL Initialized
2021-08-03 21:39:40 [verbose]: GL Version:                 4.6 (Compatibility Profile) Mesa 21.1.6
2021-08-03 21:39:40 [verbose]: GL Renderer:                Mesa Intel(R) UHD Graphics 620 (WHL GT2)
2021-08-03 21:39:40 [verbose]: GL Shader Language version: 4.60
2021-08-03 21:39:40 [verbose]: GL Vendor:                  Intel
2021-08-03 21:39:40 [verbose]: GL Extensions:              GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_vertex_attrib_64bit GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_fragment_shader_interlock GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_INTEL_shader_atomic_float_minmax GL_INTEL_shader_integer_functions2 GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation
2021-08-03 21:39:40 [verbose]: Host execution state changed to Running
2021-08-03 21:39:40 [verbose]: Execution mode changed to MultiThreaded
2021-08-03 21:39:40 [verbose]: BASS Initialized
2021-08-03 21:39:40 [verbose]: BASS Version:               2.4.15.26
2021-08-03 21:39:40 [verbose]: BASS FX Version:            2.4.12.1
2021-08-03 21:39:40 [verbose]: Device:                     Default
2021-08-03 21:39:40 [verbose]: Drive:                      default
2021-08-03 21:39:43 [verbose]: Loading OsuLogo...
2021-08-03 21:39:43 [verbose]: Opened realm "/home/bigboi98/.local/share/osu/client.realm" at version 6
2021-08-03 21:39:43 [verbose]: Loaded OsuLogo!
2021-08-03 21:39:43 [verbose]: Loading Toolbar...

**Comment by peppy** [comment]
You say this happens in a “new” build but don’t state which release worked for you. Please do so.

If in fact *all* releases don’t work then it’s likely something your end.

**Comment by BradyAtkinson** [comment]
Is there a way to see what older versions that you ran because I usually just overwrite the file with a newer version but I could do trial and error until I find what version breaks.

**Comment by BradyAtkinson** [comment]
okay so I have the same error codes while using 724.1 but the game worked and I could play 
logs of the successful 724.1 launch:
2021-08-04 00:11:34 [verbose]: ----------------------------------------------------------
2021-08-04 00:11:34 [verbose]: runtime Log for fire (LogLevel: Verbose)
2021-08-04 00:11:34 [verbose]: Running osu 2021.724.1.0 on .NET 5.0.6
2021-08-04 00:11:34 [verbose]: Environment: Linux (Unix 5.13.6.1), 8 cores
2021-08-04 00:11:34 [verbose]: ----------------------------------------------------------
2021-08-04 00:11:34 [error]: Couldn't list input devices. Is libasound2-dev installed?
2021-08-04 00:11:34 [error]: System.TypeInitializationException: The type initializer for 'Commons.Music.Midi.MidiAccessManager' threw an exception.
2021-08-04 00:11:34 [error]: ---> AlsaSharp.AlsaException: ALSA exception (error code = -19) : No such device
2021-08-04 00:11:34 [error]: at AlsaSharp.AlsaSequencer..ctor(AlsaIOType ioType, AlsaIOMode ioMode, String driverName)
2021-08-04 00:11:34 [error]: at Commons.Music.Midi.Alsa.AlsaMidiAccess..ctor()
2021-08-04 00:11:34 [error]: at Commons.Music.Midi.MidiAccessManager.InitializeDefault()
2021-08-04 00:11:34 [error]: at Commons.Music.Midi.MidiAccessManager..cctor()
2021-08-04 00:11:34 [error]: --- End of inner exception stack trace ---
2021-08-04 00:11:34 [error]: at Commons.Music.Midi.MidiAccessManager.get_Default()
2021-08-04 00:11:34 [error]: at osu.Framework.Input.Handlers.Midi.MidiHandler.refreshDevices()
2021-08-04 00:11:34 [verbose]: GL Initialized
2021-08-04 00:11:34 [verbose]: GL Version:                 4.6 (Compatibility Profile) Mesa 21.1.6
2021-08-04 00:11:34 [verbose]: GL Renderer:                Mesa Intel(R) UHD Graphics 620 (WHL GT2)
2021-08-04 00:11:34 [verbose]: GL Shader Language version: 4.60
2021-08-04 00:11:34 [verbose]: GL Vendor:                  Intel
2021-08-04 00:11:34 [verbose]: GL Extensions:              GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_vertex_attrib_64bit GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_fragment_shader_interlock GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_INTEL_shader_atomic_float_minmax GL_INTEL_shader_integer_functions2 GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation
2021-08-04 00:11:34 [verbose]: Host execution state changed to Running
2021-08-04 00:11:34 [verbose]: Execution mode changed to MultiThreaded
2021-08-04 00:11:35 [verbose]: BASS Initialized
2021-08-04 00:11:35 [verbose]: BASS Version:               2.4.15.26
2021-08-04 00:11:35 [verbose]: BASS FX Version:            2.4.12.1
2021-08-04 00:11:35 [verbose]: Device:                     Default
2021-08-04 00:11:35 [verbose]: Drive:                      default
2021-08-04 00:11:37 [verbose]: Loading OsuLogo...
2021-08-04 00:11:37 [verbose]: Opened realm "/home/bigboi98/.local/share/osu/client.realm" at version 6
2021-08-04 00:11:37 [verbose]: Loaded OsuLogo!
2021-08-04 00:11:37 [verbose]: Loading Toolbar...
2021-08-04 00:11:37 [verbose]: Screen changed → Loader
2021-08-04 00:11:37 [verbose]: Screen changed → Disclaimer
2021-08-04 00:11:37 [verbose]: Loaded Toolbar!
2021-08-04 00:11:37 [verbose]: Loading VolumeOverlay...
2021-08-04 00:11:37 [verbose]: Loaded VolumeOverlay!
2021-08-04 00:11:37 [verbose]: Loading OnScreenDisplay...
2021-08-04 00:11:37 [verbose]: Loaded OnScreenDisplay!
2021-08-04 00:11:37 [verbose]: Loading NotificationOverlay...
2021-08-04 00:11:37 [verbose]: Loaded NotificationOverlay!
2021-08-04 00:11:37 [verbose]: Loading CollectionManager...
2021-08-04 00:11:37 [verbose]: Loaded CollectionManager!
2021-08-04 00:11:37 [verbose]: Loading StableImportManager...
2021-08-04 00:11:37 [verbose]: Loaded StableImportManager!
2021-08-04 00:11:37 [verbose]: Loading ScreenshotManager...
2021-08-04 00:11:37 [verbose]: Loaded ScreenshotManager!
2021-08-04 00:11:37 [verbose]: Loading SimpleUpdateManager...
2021-08-04 00:11:37 [verbose]: Loaded SimpleUpdateManager!
2021-08-04 00:11:37 [verbose]: Loading ManageCollectionsDialog...
2021-08-04 00:11:37 [verbose]: Loaded ManageCollectionsDialog!
2021-08-04 00:11:37 [verbose]: Loading BeatmapListingOverlay...
2021-08-04 00:11:38 [verbose]: Loaded BeatmapListingOverlay!
2021-08-04 00:11:38 [verbose]: Loading DashboardOverlay...
2021-08-04 00:11:38 [verbose]: Loaded DashboardOverlay!
2021-08-04 00:11:38 [verbose]: Loading NewsOverlay...
2021-08-04 00:11:38 [verbose]: Loaded NewsOverlay!
2021-08-04 00:11:38 [verbose]: Loading RankingsOverlay...
2021-08-04 00:11:38 [verbose]: Loaded RankingsOverlay!
2021-08-04 00:11:38 [verbose]: Loading ChannelManager...
2021-08-04 00:11:38 [verbose]: Loaded ChannelManager!
2021-08-04 00:11:38 [verbose]: Loading ChatOverlay...
2021-08-04 00:11:38 [verbose]: Loaded ChatOverlay!
2021-08-04 00:11:38 [verbose]: Loading MessageNotifier...
2021-08-04 00:11:38 [verbose]: Loaded MessageNotifier!
2021-08-04 00:11:38 [verbose]: Loading SettingsOverlay...
2021-08-04 00:11:39 [verbose]: Loaded SettingsOverlay!
2021-08-04 00:11:39 [verbose]: Loading ChangelogOverlay...
2021-08-04 00:11:39 [verbose]: Loaded ChangelogOverlay!
2021-08-04 00:11:39 [verbose]: Loading UserProfileOverlay...
2021-08-04 00:11:39 [verbose]: Loaded UserProfileOverlay!
2021-08-04 00:11:39 [verbose]: Loading BeatmapSetOverlay...
2021-08-04 00:11:40 [verbose]: Loaded BeatmapSetOverlay!
2021-08-04 00:11:40 [verbose]: Loading WikiOverlay...
2021-08-04 00:11:40 [verbose]: Loaded WikiOverlay!
2021-08-04 00:11:40 [verbose]: Loading SkinEditorOverlay...
2021-08-04 00:11:40 [verbose]: Loaded SkinEditorOverlay!
2021-08-04 00:11:40 [verbose]: Loading LoginOverlay...
2021-08-04 00:11:40 [verbose]: Loaded LoginOverlay!
2021-08-04 00:11:40 [verbose]: Loading NowPlayingOverlay...
2021-08-04 00:11:40 [verbose]: Loaded NowPlayingOverlay!
2021-08-04 00:11:40 [verbose]: Loading AccountCreationOverlay...
2021-08-04 00:11:40 [verbose]: Loaded AccountCreationOverlay!
2021-08-04 00:11:40 [verbose]: Loading DialogOverlay...
2021-08-04 00:11:40 [verbose]: Loaded DialogOverlay!
2021-08-04 00:11:40 [verbose]: Loading HighPerformanceSession...
2021-08-04 00:11:40 [verbose]: Loaded HighPerformanceSession!
2021-08-04 00:11:43 [verbose]: Screen changed → IntroTriangles
2021-08-04 00:11:43 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2021-08-04 00:11:46 [verbose]: Screen changed → MainMenu
2021-08-04 00:11:47 [verbose]: ButtonSystem's state changed from Initial to Exit
2021-08-04 00:11:47 [verbose]: Screen changed ← IntroTriangles
2021-08-04 00:11:50 [verbose]: Screen changed ← Disclaimer
2021-08-04 00:11:50 [verbose]: Screen changed ← Loader
2021-08-04 00:11:50 [verbose]: Screen changed ←
2021-08-04 00:11:50 [verbose]: Host execution state changed to Stopping
2021-08-04 00:11:50 [verbose]: Host execution state changed to Stopped

**Comment by gagahpangeran** [comment]
I believe missing libasound-dev does not crash the game in linux. I experienced it multiple time in the past. So, that libasound-dev missing part is not relevant.

Please upload your entire logs folder instead of copy-paste it here.
