### ISSUE TITLE
Cannot join multiplayer rooms anymore

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#14129]
After 8 hours I decided to rise an issue. (Is there https://status.ppy.sh/ for osu!lazer?)
As for now, people can't create a room in multiplayer anymore. They get kicked out immediately.   
The room remains for 30s but you can't join.

**Describe the bug:** 

- Creating a multiplayer room will kick you out immediately.
- History shows lots of rooms without any participants.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/10113399/128256722-60e33cf9-3fb3-41bb-b99b-47b52fb96b57.png)

**osu!lazer version:**   
Running osu 2021.731.0.0 on .NET 5.0.2

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6934464/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6934465/performance.log)
[updater.log](https://github.com/ppy/osu/files/6934466/updater.log)

runtime.log throws
```
2021-08-04 21:21:36 [error]: Failed to join multiplayer room.
2021-08-04 21:21:36 [error]: System.AggregateException: One or more errors occurred. (One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Specified match does not exist.))
2021-08-04 21:21:36 [error]: ---> System.AggregateException: One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Specified match does not exist.)
2021-08-04 21:21:36 [error]: ---> Microsoft.AspNetCore.SignalR.HubException: An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Specified match does not exist.
2021-08-04 21:21:36 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2021-08-04 21:21:36 [error]: at System.Threading.Tasks.ForceAsyncAwaiter`1.GetResult()
2021-08-04 21:21:36 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2021-08-04 21:21:36 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
2021-08-04 21:21:36 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass43_0.<<JoinRoom>b__0>d.MoveNext()
2021-08-04 21:21:36 [error]: --- End of inner exception stack trace ---
2021-08-04 21:21:36 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.JoinRoom(Room room, String password)
2021-08-04 21:21:36 [error]: --- End of inner exception stack trace ---
```

**Comment by peppy** [comment]
This has been fixed. In the future, please bring infrastructure issues *to the team's attention*, rather than opening an issue here. It should not take 4-8 hours for action to occur.
