### ISSUE TITLE
Crash on requesting beatmap scores for unranked maps.

### ISSUE THREAD

**Issue by Flanster** [ppy/osu#1425]
Happens on my own unsubmitted maps so I suppose it's happening due to osu trying to fetch scores that don't exist.

Network log
~~~
24.10.2017 15:03:02: Request to https://osu.ppy.sh/api/v2/beatmaps/0/scores failed with NotFound (FAILED).
~~~

Runtime log
~~~
24.10.2017 15:03:02: System.NullReferenceException: Object reference not set to an instance of an object.
24.10.2017 15:03:02: at osu.Game.Online.API.Requests.GetScoresRequest.onSuccess(GetScoresResponse r)
24.10.2017 15:03:02: at osu.Game.Online.API.APISuccessHandler`1.Invoke(T content)
24.10.2017 15:03:02: at osu.Framework.Threading.Scheduler.Update()
24.10.2017 15:03:02: at osu.Game.OsuGameBase.Update()
24.10.2017 15:03:02: at osu.Framework.Graphics.Drawable.UpdateSubTree()
24.10.2017 15:03:02: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
24.10.2017 15:03:02: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
24.10.2017 15:03:02: at osu.Framework.Platform.GameHost.UpdateFrame()
24.10.2017 15:03:02: at osu.Framework.Threading.GameThread.ProcessFrame()
24.10.2017 15:03:02: at osu.Framework.Threading.GameThread.runWork()
24.10.2017 15:03:02: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
24.10.2017 15:03:02: at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
24.10.2017 15:03:02: at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
24.10.2017 15:03:02: at System.Threading.ThreadHelper.ThreadStart()
~~~

**Comment by peppy** [comment]
cc @smoogipoo WebRequest related (probably fixed already?)

**Comment by peppy** [comment]
There's two levels of fail here:

- Exceptions are not being correctly forwarded (this should have failed with 404). Hopefully will be resolved in https://github.com/ppy/osu-framework/pull/1116
- Migration from the sqlite-net database was a bit broken, so incorrect values entered the database. I'll see if I can add a manual migration to the next build to fix this.

**Comment by peppy** [comment]
Fixed in a way which doesn't require a new migration (but also fixed the underlying incorrect migration).
