### ISSUE TITLE
Animated Avatar/Cover causes STB to fail to load

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu#14417]
**Describe the bug:** 
[My Profile](https://osu.ppy.sh/users/13506780) has an animated cover that triggers an error message once attempted to load. This occurs both after startup once opening the user panel for the first time and in multiplayer lobbies once my profile appears on the list. 
I assume this has more to do with the fact that animated images aren't supported and not with the gif itself?
This is the cover:
<img src="https://assets.ppy.sh/user-profile-covers/13506780/a76538a65407f61652f8cbaf7672dc1b8ee11749a72aec23fcc77a9449087ea3.gif" width="25%">
**Screenshots or videos showing encountered issue:** 
![](https://url.invis.cloud/4pY3kL)
**osu!lazer version:** 
2021.820.0
**Logs:**

```
2021-08-20 18:49:07 [error]: Texture could not be loaded via STB; falling back to ImageSharp.
2021-08-20 18:49:07 [error]: System.ArgumentException: STBI could not load an image from the provided data: 潃牲灵⁴䥇F
2021-08-20 18:49:07 [error]: at StbiSharp.Stbi.LoadFromMemory(ReadOnlySpan`1 data, Int32 desiredNumChannels)
2021-08-20 18:49:07 [error]: at StbiSharp.Stbi.LoadFromMemory(MemoryStream data, Int32 desiredNumChannels)
2021-08-20 18:49:07 [error]: at osu.Framework.Graphics.Textures.TextureUpload.LoadFromStream[TPixel](Stream stream)
2021-08-20 18:49:07 [verbose]: Focus contention triggered by NotificationOverlay.
```

**Comment by bdach** [comment]
stbi has a [dedicated function for gifs](https://github.com/nothings/stb/blob/f67165c2bb2af3060ecae7d20d6f731173485ad0/stb_image.h#L1300) that presumably should be called in this case. Although I do wonder whether animated gifs for profile avatars aren't a touch out of scope...

**Comment by peppy** [comment]
Displaying the animation is out of scope, but avoiding the error message (and fallback to a slower decoder) should definitely be a priority.
