### ISSUE TITLE
Crash when deselecting conversion mods: 'Cannot unbind from a non-DifficultyBindable' 

### ISSUE THREAD

**Issue by TheBicPen** [ppy/osu#14471]
**Describe the bug:** 
Game crashes when deselecting conversion mods.
```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in osu.Game.dll but was not handled in user code: 'Cannot unbind from a non-DifficultyBindable.'
   at osu.Game.Rulesets.Mods.DifficultyBindable.UnbindFrom(IUnbindable them) in C:\Users\mashk\repos\osu\osu.Game\Rulesets\Mods\DifficultyBindable.cs:line 125
   at osu.Framework.Bindables.Bindable`1.UnbindBindings()
   at osu.Framework.Bindables.Bindable`1.UnbindAllInternal()
   at osu.Framework.Bindables.Bindable`1.UnbindAll()
   at osu.Framework.Graphics.Drawable.<>c__DisplayClass14_1.<cacheUnbindActions>b__3(Object target)
   at osu.Framework.Graphics.Drawable.<>c__DisplayClass14_0.<cacheUnbindActions>b__2(Object target)
```
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/23622288/130539851-3e34fc59-5569-460e-b000-94d29f41c979.png)
![image](https://user-images.githubusercontent.com/23622288/130539883-8efb450c-9184-46ef-9f81-478f87c13eac.png)

**osu!lazer version:** 

Built from commit f390e9a156a3090c97d51368b6607fef16f52b4a (latest commit on master at the time)

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/7035740/runtime.log)
[database.log](https://github.com/ppy/osu/files/7035741/database.log)
[network.log](https://github.com/ppy/osu/files/7035742/network.log)
[performance.log](https://github.com/ppy/osu/files/7035743/performance.log)

**Comment by peppy** [comment]
Can't repro on the latest release, so either a regression or more to it.

**Comment by peppy** [comment]
Can't reproduce on master, could you please provide more exact steps?

**Comment by TheBicPen** [comment]
I'm seeing the same issue on the release commit (d3dba296d672afa4d5c4d7c97154fe68117935a1) with these exact steps:
- build and launch game (via vscode debug configuration)
- click osu logo -> play -> solo
- open mod menu with f1
- scroll down and select difficulty adjust.
- deselect difficulty adjust
- Exception has occurred: CLR/System.InvalidOperationException

**Comment by peppy** [comment]
I think this is something your end.

Please test on an actual release binary.

**Comment by TheBicPen** [comment]
Works as expected on the release binary.

**Comment by peppy** [comment]
I'd say you have some outdated dependencies. Please try updating nuget and potentially doing a full clean of the project / your IDE to ensure nothing is being cached in a bad state.

**Comment by peppy** [comment]
Another possibility is that you have a ruleset loaded which is doing something globally it shouldn't be doing. If so, please check rulesets one by one and let us know which this is so we can report upstream.

**Comment by peppy** [comment]
I managed to repro this in a testing scenario, no idea how/why but leaving this here:

![20210824 132713 (JetBrains Rider)](https://user-images.githubusercontent.com/191335/130555806-bbd4dff8-b166-4770-b51d-be6947179f71.png)

I don't have much knowledge of why this exception exists so asking someone else to look into this.

**Comment by peppy** [comment]
Something is catching the exception blindly. This only reproduces with a debugger attached and set to break on all exceptions.
