### ISSUE TITLE
Multiple server disconnections while playing multiplayer

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14691]
During a session on the weekend I got disconnected twice. Others in the room also experience similar issues. Potentially cloudflare related, will be investigating.

If anyone else encounters this please post network log snippets here.

```csharp
2021-09-07 15:36:44 [verbose]: SpectatorClient connection error: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
2021-09-07 15:36:44 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
2021-09-07 15:36:44 [verbose]: at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
2021-09-07 15:36:44 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-09-07 15:36:44 [verbose]: at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
2021-09-07 15:36:44 [verbose]: at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2021-09-07 15:36:44 [verbose]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2021-09-07 15:36:44 [verbose]: at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2021-09-07 15:36:44 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)


2021-09-07 16:13:00 [verbose]: OnlineMultiplayerClient connection error: System.InvalidOperationException: Websocket closed with error: EndpointUnavailable.
2021-09-07 16:13:00 [verbose]: at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
2021-09-07 16:13:00 [verbose]: at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2021-09-07 16:13:00 [verbose]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2021-09-07 16:13:00 [verbose]: at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2021-09-07 16:13:00 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
2021-09-07 16:13:00 [verbose]: Performing request osu.Game.Online.Rooms.SubmitRoomScoreRequest
```

**Comment by maroru** [comment]
This also happened to me several times today. Disconnection happens whether I'm in lobby or while in the middle of a play in multiplayer.
```cs
2021-09-10 19:55:06 [verbose]: SpectatorClient connection error: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
2021-09-10 19:55:06 [verbose]: ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2021-09-10 19:55:06 [verbose]: ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2021-09-10 19:55:06 [verbose]: --- End of inner exception stack trace ---
2021-09-10 19:55:06 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-09-10 19:55:06 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-09-10 19:55:06 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-09-10 19:55:06 [verbose]: at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
2021-09-10 19:55:06 [verbose]: at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
2021-09-10 19:55:06 [verbose]: at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
2021-09-10 19:55:06 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-09-10 19:55:06 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-09-10 19:55:06 [verbose]: at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
2021-09-10 19:55:06 [verbose]: at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2021-09-10 19:55:06 [verbose]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2021-09-10 19:55:06 [verbose]: at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2021-09-10 19:55:06 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
2021-09-10 19:55:09 [verbose]: OnlineMultiplayerClient connection error: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
2021-09-10 19:55:09 [verbose]: ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2021-09-10 19:55:09 [verbose]: ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
2021-09-10 19:55:09 [verbose]: --- End of inner exception stack trace ---
2021-09-10 19:55:09 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-09-10 19:55:09 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-09-10 19:55:09 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-09-10 19:55:09 [verbose]: at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
2021-09-10 19:55:09 [verbose]: at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
2021-09-10 19:55:09 [verbose]: at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
2021-09-10 19:55:09 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-09-10 19:55:09 [verbose]: at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-09-10 19:55:09 [verbose]: at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
2021-09-10 19:55:09 [verbose]: at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2021-09-10 19:55:09 [verbose]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2021-09-10 19:55:09 [verbose]: at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2021-09-10 19:55:09 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
2021-09-10 19:55:09 [verbose]: Performing request osu.Game.Online.Rooms.SubmitRoomScoreRequest
```

**Comment by peppy** [comment]
I haven't noticed this recently. If any players come across these kinds of issues I'd appreciate more logs - it may have been something external which has since been resolved.

**Comment by peppy** [comment]
Closing this one for now. I spent multiple hours in multiplayer over the weekend with no issues.

**Comment by Aldoggen** [comment]
I had been playing in multi for a while. I think (not sure what happened anymore) I clicked the button to start the next map, and this happened. It's not exactly the same error, but I think it is relevant?

```
2022-03-25 11:01:45 [verbose]: Performing request osu.Game.Online.Rooms.PartRoomRequest
2022-03-25 11:01:45 [verbose]: OnlineMultiplayerClient connection error: System.InvalidOperationException: Websocket closed with error: EndpointUnavailable.
2022-03-25 11:01:45 [verbose]: at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
2022-03-25 11:01:45 [verbose]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2022-03-25 11:01:45 [verbose]: at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2022-03-25 11:01:45 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
2022-03-25 11:01:45 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2022-03-25 11:01:45 [verbose]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
```
