### ISSUE TITLE
osu!lazer crashing when clicking the play button without a beatmap selected

### ISSUE THREAD

**Issue by MattiaPette** [ppy/osu#1507]
Steps to replicate the crash:

1. Open osu! and go to the solo play section
2. Search for a beatmap that you don't so that the game shows you "no beatmaps available"
![image](https://user-images.githubusercontent.com/3349243/32825393-259aaba6-c9e5-11e7-868c-59c7a2b43084.png)
3. Click the play button (bottom right corner)

The thrown exception is this:
![image](https://user-images.githubusercontent.com/3349243/32825523-992e3df8-c9e5-11e7-862d-4fe1699444f8.png)

> Exception thrown: 'osu.Game.Rulesets.UI.BeatmapInvalidForRulesetException' in osu.Game.dll
Exception thrown: 'System.NotImplementedException' in osu.Game.dll
[runtime:error] Could not load this beatmap sucessfully (System.NotImplementedException: The method or operation is not implemented.
   at osu.Game.Beatmaps.DummyWorkingBeatmap.DummyRulesetInfo.DummyRuleset.CreateRulesetContainerWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset) in C:\Users\pettemat\Projects\osu\osu.Game\Beatmaps\DummyWorkingBeatmap.cs:line 59
   at osu.Game.Screens.Play.Player.load(AudioManager audio, OsuConfigManager config, APIAccess api) in C:\Users\pettemat\Projects\osu\osu.Game\Screens\Play\Player.cs:line 119)!
[runtime:error] Could not load this beatmap sucessfully (System.NotImplementedException: The method or operation is not implemented.
   at osu.Game.Beatmaps.DummyWorkingBeatmap.DummyRulesetInfo.DummyRuleset.CreateRulesetContainerWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset) in C:\Users\pettemat\Projects\osu\osu.Game\Beatmaps\DummyWorkingBeatmap.cs:line 59
   at osu.Game.Screens.Play.Player.load(AudioManager audio, OsuConfigManager config, APIAccess api) in C:\Users\pettemat\Projects\osu\osu.Game\Screens\Play\Player.cs:line 119)!
Exception thrown: 'System.NullReferenceException' in osu.Game.dll
An exception of type 'System.NullReferenceException' occurred in osu.Game.dll but was not handled in user code
Object reference not set to an instance of an object.

**Comment by UselessToucan** [comment]
As far as I remember, somebody fixed this problem before(press play button when there is no selected beatmap => exception).
Looks like after introducing the Rulesets, it is back.

**Comment by MattiaPette** [comment]
It can easily be fixed by disabling the button when the DummyWorkingBeatmap is selected. But my osu!framework knowledge is not quite good enough (for now) to push a fix

**Comment by MattiaPette** [comment]
Closing the issue, PR #1511 fixes it.
