### ISSUE TITLE
Crashing on entering song select when logged in

### ISSUE THREAD

**Issue by Gunnest663** [ppy/osu#1539]
I cannot seem to play osu!lazer at all since i cannot be signed in and click play at the same time, but when i try to play as a guest i cannot seem to play any beatmaps or find any.

Faulting application name: osu!.exe, version: 2017.1116.0.0, time stamp: 0x5a0c6979
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
Exception code: 0xe0434352
Fault offset: 0x0000000000013fb8
Faulting process id: 0x3618
Faulting application start time: 0x01d3626c988484bf
Faulting application path: C:\Users\joshu\AppData\Local\osulazer\app-2017.1116.0\osu!.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 86f46197-9fdf-4d70-8b1d-15406079e84b
Faulting package full name: 
Faulting package-relative application ID: 

Error i get from event viewer

**Comment by peppy** [comment]
There should be a .NET exception in event viewer (the error you provided is not helpful). Also consider including runtime.log from your osu! logs folder.

**Comment by Gunnest663** [comment]
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetRange(Int32, Int32)
   at osu.Game.Screens.Select.Details.UserRatings.set_Metrics(osu.Game.Beatmaps.BeatmapMetrics)
   at osu.Game.Screens.Select.BeatmapDetails.displayMetrics(osu.Game.Beatmaps.BeatmapMetrics, Boolean)
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<Run>b__90_1(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseUpdateFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(System.Object, System.EventArgs)
   at OpenTK.GameWindow.Run(Double, Double)
   at osu.Framework.Platform.GameHost.Run(osu.Framework.Game)
   at osu.Desktop.Program.Main(System.String[])

You mean this? 
[runtime.log](https://github.com/ppy/osu/files/1489834/runtime.log)

**Comment by peppy** [comment]
Thanks, that's much more helpful.

**Comment by peppy** [comment]
This is also related to exceptions not being thrown by synchronous web requests, i think. can reproduce by hitting `PlaySongSelect` in visualtests (although on a different usage).

**Comment by Gunnest663** [comment]
I have tried 2 different versions of the osu!lazer and they both do the same thing and crash at the same point
