### ISSUE TITLE
Game crash upon starting match in multiplayer

### ISSUE THREAD

**Issue by peppy** [ppy/osu#15997]
Relevant logs:

```csharp

2021-12-07 17:40:50 [verbose]: Screen changed ← Multiplayer
2021-12-07 17:40:50 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2021-12-07 17:41:34 [verbose]: Game-wide working beatmap updated to Paramore - Still Into You (Sped Up & Cut Ver.) (Froskya) [Butterflies]
2021-12-07 17:41:50 [error]: An unhandled error has occurred.
2021-12-07 17:41:50 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.OrderedEnumerable`1.ToArray()
2021-12-07 17:41:50 [error]: at osu.Game.Screens.OnlinePlay.Components.StarRatingRangeDisplay.updateRange(Object sender, NotifyCollectionChangedEventArgs e)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass98_0.<PlaylistItemAdded>b__0()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.GameThread.processFrame()
2021-12-07 17:41:50 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2021-12-07 17:41:50 [error]: An unhandled error has occurred.
2021-12-07 17:41:50 [error]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass100_0.<PlaylistItemChanged>b__0()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.GameThread.processFrame()
2021-12-07 17:41:50 [verbose]: Unhandled exception has been denied .
2021-12-07 17:41:50 [verbose]: Focus contention triggered by NotificationOverlay.
2021-12-07 17:41:50 [verbose]: Screen changed → PlayerLoader

```

### Discussed in https://github.com/ppy/osu/discussions/15986

<div type='discussions-op-text'>

<sup>Originally posted by **Theighlin** December  8, 2021</sup>
Nothing out of the ordinary, everything was working fine until it didn't, although some minutes before that a beatmap got stuck on "importing" on my panel in multi, i instantly checked logs and it said this:

2021-12-07 17:35:18 [important]: The imported beatmap set does not match the online version.

I quit and rejoined, it was there ready to be played.
A bit later the game crashed when another map was starting.

[performance.log](https://github.com/ppy/osu/files/7670679/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7670680/runtime.log)
[database.log](https://github.com/ppy/osu/files/7670681/database.log)
[network.log](https://github.com/ppy/osu/files/7670682/network.log)</div>

**Comment by frenzibyte** [comment]
Has been reopened with further details in https://github.com/ppy/osu/issues/16026.
