### ISSUE TITLE
Multiplayer crashes due to incorrect threading surrounding `Room.Playlist` 

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16026]
This happens because the `Playlist` is modified from arbitrary threads, but operated on as if it is assumed to always be update thread safe.

The case in this reported discussion is likely due to the `CopyFrom` operation, which clears and adds back each playlist item:

https://github.com/ppy/osu/blob/38702beabf47164fcac6db142faf7b9ddd392877/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs#L124

called from:

https://github.com/ppy/osu/blob/38702beabf47164fcac6db142faf7b9ddd392877/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs#L56

@smoogipoo is it a correct assumption that this should be run on the update thread?

### Discussed in https://github.com/ppy/osu/discussions/15986

<div type='discussions-op-text'>

<sup>Originally posted by **Theighlin** December  8, 2021</sup>
Nothing out of the ordinary, everything was working fine until it didn't, although some minutes before that a beatmap got stuck on "importing" on my panel in multi, i instantly checked logs and it said this:

2021-12-07 17:35:18 [important]: The imported beatmap set does not match the online version.

I quit and rejoined, it was there ready to be played.
A bit later the game crashed when another map was starting.

[performance.log](https://github.com/ppy/osu/files/7670679/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7670680/runtime.log)
[database.log](https://github.com/ppy/osu/files/7670681/database.log)
[network.log](https://github.com/ppy/osu/files/7670682/network.log)</div>

```csharp
2021-12-07 17:40:50 [verbose]: Screen changed ← Multiplayer
2021-12-07 17:40:50 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2021-12-07 17:41:34 [verbose]: Game-wide working beatmap updated to Paramore - Still Into You (Sped Up & Cut Ver.) (Froskya) [Butterflies]
2021-12-07 17:41:50 [error]: An unhandled error has occurred.
2021-12-07 17:41:50 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
2021-12-07 17:41:50 [error]: at System.Linq.OrderedEnumerable`1.ToArray()
2021-12-07 17:41:50 [error]: at osu.Game.Screens.OnlinePlay.Components.StarRatingRangeDisplay.updateRange(Object sender, NotifyCollectionChangedEventArgs e)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass98_0.<PlaylistItemAdded>b__0()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.GameThread.processFrame()
2021-12-07 17:41:50 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2021-12-07 17:41:50 [error]: An unhandled error has occurred.
2021-12-07 17:41:50 [error]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Framework.Bindables.BindableList`1.removeAt(Int32 index, BindableList`1 caller)
2021-12-07 17:41:50 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass100_0.<PlaylistItemChanged>b__0()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-12-07 17:41:50 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-12-07 17:41:50 [error]: at osu.Framework.Threading.GameThread.processFrame()
2021-12-07 17:41:50 [verbose]: Unhandled exception has been denied .
```

**Comment by peppy** [comment]
Proposed fix would be:

```diff
diff --git a/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs b/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs
index 02565c6ebe..799e7f2d77 100644
--- a/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs
+++ b/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs
@@ -105,7 +105,7 @@ public virtual void PartRoom()
 
         private readonly HashSet<long> ignoredRooms = new HashSet<long>();
 
-        public void AddOrUpdateRoom(Room room)
+        public void AddOrUpdateRoom(Room room) => Scheduler.Add(() =>
         {
             Debug.Assert(room.RoomID.Value != null);
 
@@ -132,7 +132,7 @@ public void AddOrUpdateRoom(Room room)
             }
 
             notifyRoomsUpdated();
-        }
+        });
 
         public void RemoveRoom(Room room)
         {
```

**Comment by smoogipoo** [comment]
The code should be / is running on the update thread. Have you actually been able to reproduce this?

**Comment by peppy** [comment]
Hmm, didn't realise those were already scheduled on the `IAPIAccess`. Will be some other usage of `Playlist`, I'll keep searching.

**Comment by smoogipoo** [comment]
One way I could see this happening is if a playlist item is changed and then removed, because the `PlaylistItemRemoved` callback can happen before the `PlaylistItemChanged` one completes the async `createPlaylistItem`.

But that's likely not what's going on here. Need more logging...

**Comment by peppy** [comment]
Those are super dodgy. Threading is a mistake.

**Comment by peppy** [comment]
I made a solution to fix this based on the above discussion, but as further discussed in discord, SignalR is *actually single threaded* and waits for a request to complete before handling subsequent requests. So I don't think this will help at all. Will drop here in case it turns out useful in a future:

```diff
diff --git a/osu.Game/Online/Multiplayer/MultiplayerClient.cs b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
index 55b4def908..5682a78169 100644
--- a/osu.Game/Online/Multiplayer/MultiplayerClient.cs
+++ b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
@@ -653,25 +653,35 @@ Task IMultiplayerClient.ResultsReady()
             return Task.CompletedTask;
         }
 
-        public async Task PlaylistItemAdded(MultiplayerPlaylistItem item)
+        /// <summary>
+        /// This is required to ensure that playlist tasks are run sequentially.
+        /// Without this, an add/change operation could take time (waiting on the item fetch/populate from the API via <see cref="GetAPIBeatmap"/>)
+        /// and cause the final scheduled events to fire out of order, leading to unexpected behaviour.
+        /// </summary>
+        private readonly TaskChain playlistItemTaskChain = new TaskChain();
+
+        public Task PlaylistItemAdded(MultiplayerPlaylistItem item)
         {
             if (Room == null)
-                return;
-
-            var playlistItem = await createPlaylistItem(item, true).ConfigureAwait(false);
+                return Task.CompletedTask;
 
-            Scheduler.Add(() =>
+            return playlistItemTaskChain.Add(async () =>
             {
-                if (Room == null)
-                    return;
+                var playlistItem = await createPlaylistItem(item, true).ConfigureAwait(false);
 
-                Debug.Assert(APIRoom != null);
+                Scheduler.Add(() =>
+                {
+                    if (Room == null)
+                        return;
 
-                Room.Playlist.Add(item);
-                APIRoom.Playlist.Add(playlistItem);
+                    Debug.Assert(APIRoom != null);
 
-                ItemAdded?.Invoke(item);
-                RoomUpdated?.Invoke();
+                    Room.Playlist.Add(item);
+                    APIRoom.Playlist.Add(playlistItem);
+
+                    ItemAdded?.Invoke(item);
+                    RoomUpdated?.Invoke();
+                });
             });
         }
 
@@ -680,49 +690,53 @@ public Task PlaylistItemRemoved(long playlistItemId)
             if (Room == null)
                 return Task.CompletedTask;
 
-            Scheduler.Add(() =>
+            return playlistItemTaskChain.Add(() =>
             {
-                if (Room == null)
-                    return;
+                Scheduler.Add(() =>
+                {
+                    if (Room == null)
+                        return;
 
-                Debug.Assert(APIRoom != null);
+                    Debug.Assert(APIRoom != null);
 
-                Room.Playlist.Remove(Room.Playlist.Single(existing => existing.ID == playlistItemId));
-                APIRoom.Playlist.RemoveAll(existing => existing.ID == playlistItemId);
+                    Room.Playlist.Remove(Room.Playlist.Single(existing => existing.ID == playlistItemId));
+                    APIRoom.Playlist.RemoveAll(existing => existing.ID == playlistItemId);
 
-                ItemRemoved?.Invoke(playlistItemId);
-                RoomUpdated?.Invoke();
+                    ItemRemoved?.Invoke(playlistItemId);
+                    RoomUpdated?.Invoke();
+                });
             });
-
-            return Task.CompletedTask;
         }
 
-        public async Task PlaylistItemChanged(MultiplayerPlaylistItem item)
+        public Task PlaylistItemChanged(MultiplayerPlaylistItem item)
         {
             if (Room == null)
-                return;
-
-            var playlistItem = await createPlaylistItem(item, true).ConfigureAwait(false);
+                return Task.CompletedTask;
 
-            Scheduler.Add(() =>
+            return playlistItemTaskChain.Add(async () =>
             {
-                if (Room == null)
-                    return;
+                var playlistItem = await createPlaylistItem(item, true).ConfigureAwait(false);
 
-                Debug.Assert(APIRoom != null);
+                Scheduler.Add(() =>
+                {
+                    if (Room == null)
+                        return;
 
-                Room.Playlist[Room.Playlist.IndexOf(Room.Playlist.Single(existing => existing.ID == item.ID))] = item;
+                    Debug.Assert(APIRoom != null);
 
-                int existingIndex = APIRoom.Playlist.IndexOf(APIRoom.Playlist.Single(existing => existing.ID == item.ID));
-                APIRoom.Playlist.RemoveAt(existingIndex);
-                APIRoom.Playlist.Insert(existingIndex, playlistItem);
+                    Room.Playlist[Room.Playlist.IndexOf(Room.Playlist.Single(existing => existing.ID == item.ID))] = item;
 
-                // If the currently-selected item was the one that got replaced, update the selected item to the new one.
-                if (CurrentMatchPlayingItem.Value?.ID == playlistItem.ID)
-                    CurrentMatchPlayingItem.Value = playlistItem;
+                    int existingIndex = APIRoom.Playlist.IndexOf(APIRoom.Playlist.Single(existing => existing.ID == item.ID));
+                    APIRoom.Playlist.RemoveAt(existingIndex);
+                    APIRoom.Playlist.Insert(existingIndex, playlistItem);
 
-                ItemChanged?.Invoke(item);
-                RoomUpdated?.Invoke();
+                    // If the currently-selected item was the one that got replaced, update the selected item to the new one.
+                    if (CurrentMatchPlayingItem.Value?.ID == playlistItem.ID)
+                        CurrentMatchPlayingItem.Value = playlistItem;
+
+                    ItemChanged?.Invoke(item);
+                    RoomUpdated?.Invoke();
+                });
             });
         }
 


```

**Comment by peppy** [comment]
Let me add that the `The imported beatmap set does not match the online version.` message is 100% reproducible by starting a multiplayer game, deleting the beatmap (using maintenance options for example) then letting it re-download. This only happens once from game startup, and it likely an EF quirk. I wouldn't recommend looking into this for now.

**Comment by peppy** [comment]
I guess there's a small chance that #16045 will solve this one?

**Comment by smoogipoo** [comment]
Possibly. I can think of one more way this can happen, though.

It's a race condition that's been on my mind for a little while. There's some time between the room is joined to when the first schedule runs in which the `Room` variable is updated:
https://github.com/ppy/osu/blob/c375c8709430e573d4d2ea01e6f64dd9d8eb4dfd/osu.Game/Online/Multiplayer/MultiplayerClient.cs#L165-L182
Without the `Room` variable updated, callbacks from the server (e.g. `PlaylistItemAdded`) exit early. This race is also present with everything else like the room settings too - e.g. there's some time where if the room's name is updated the client will simply discard the callback.

**Comment by peppy** [comment]
Removing priority due to low occurrence and because we are aware of the bank around `Playlist` access in these models.
