### ISSUE TITLE
Error at song select during score sorting operations

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16211]
```csharp

2021-12-22 07:51:43 [verbose]: updating selection with beatmap:null ruleset:0
2021-12-22 07:51:43 [verbose]: beatmap changed from "KASAI HARCORES - Cycle Hit (Worminators) [Home Run]" to ""
2021-12-22 07:51:43 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2021-12-22 07:51:43 [error]: An unobserved error has occurred.
2021-12-22 07:51:43 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
2021-12-22 07:51:43 [error]: ---> System.NullReferenceException: Object reference not set to an instance of an object.
2021-12-22 07:51:43 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.GetDifficultyAsync(IBeatmapInfo beatmapInfo, IRulesetInfo rulesetInfo, IEnumerable`1 mods, CancellationToken cancellationToken)
2021-12-22 07:51:43 [error]: at osu.Game.Scoring.ScoreManager.OrderByTotalScoreAsync(ScoreInfo[] scores, CancellationToken cancellationToken)
2021-12-22 07:51:43 [error]: --- End of inner exception stack trace ---
2021-12-22 07:51:43 [error]: An unobserved error has occurred. (inner)
2021-12-22 07:51:43 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-12-22 07:51:43 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.GetDifficultyAsync(IBeatmapInfo beatmapInfo, IRulesetInfo rulesetInfo, IEnumerable`1 mods, CancellationToken cancellationToken)
2021-12-22 07:51:43 [error]: at osu.Game.Scoring.ScoreManager.OrderByTotalScoreAsync(ScoreInfo[] scores, CancellationToken cancellationToken)
2021-12-22 07:51:43 [verbose]: Focus contention triggered by NotificationOverlay.
2021-12-22 07:51:43 [verbose]: updating selection with beatmap:921 ruleset:0
2021-12-22 07:51:43 [verbose]: beatmap changed from "please load a beatmap! - no beatmaps available!" to "UNDEAD CORPORATION - The Empress (Plutia) [STARBOW BREAK!]"
```

unobserved exception likely due to changing beatmap during the process. will take a look.

### Discussed in https://github.com/ppy/osu/discussions/16210

<div type='discussions-op-text'>

<sup>Originally posted by **mouzedrift** December 22, 2021</sup>
i just tried to search for ``stars>=5`` and suddenly osu threw an error but this doesn't seem to happen very frequently.

[runtime.log](https://github.com/ppy/osu/files/7760966/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7760967/updater.log)
[database.log](https://github.com/ppy/osu/files/7760968/database.log)
[network.log](https://github.com/ppy/osu/files/7760969/network.log)
[performance.log](https://github.com/ppy/osu/files/7760970/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/7760971/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7760972/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/7760973/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7760974/performance-update.log)
</div>

**Comment by peppy** [comment]
Downgrading to p1 as this isn't a crash, even though it was reported as one.
