### ISSUE TITLE
Debug build of lazer crashes on launch when migrating to Realm

### ISSUE THREAD

**Issue by Henry-YSLin** [ppy/osu#16531]
# Steps to repro

1. Delete lazer data folder.
2. Checkout 2ad0ea35be5c170546b8cfca8f7cae0939567bcd and run that version. (Probably not related to that specific commit, it's just the commit I happened to be on when I first found the bug.)
3. Choose to start fresh at the specified location when prompted.
4. Close the game.
5. Check out master (at 1a207251628d50ae701ec73a4c47f0f27ca29930 right now) and run the game.
6. Game fails to launch with an IOException:
<details>
<summary>Stack Trace</summary>

```
2022-01-20 13:43:20 [verbose]: Beginning realm file store cleanup
2022-01-20 13:43:20 [verbose]: Finished realm file store cleanup (0 of 0 deleted)
2022-01-20 13:43:21 [important]: Your development database has been fully migrated to realm. If you switch back to a pre-realm branch and need your previous database, rename the backup file back to "client.db".
2022-01-20 13:43:21 [important]: 
2022-01-20 13:43:21 [important]: Note that doing this can potentially leave your file store in a bad state.
2022-01-20 13:43:21 [error]: An unhandled error has occurred.
2022-01-20 13:43:21 [error]: System.IO.IOException: The process cannot access the file 'D:\Games\osu!lazer\data\client.db' because it is being used by another process.
2022-01-20 13:43:21 [error]: at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2022-01-20 13:43:21 [error]: at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2022-01-20 13:43:21 [error]: at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2022-01-20 13:43:21 [error]: at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2022-01-20 13:43:21 [error]: at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
2022-01-20 13:43:21 [error]: at osu.Framework.Platform.NativeStorage.GetStream(String path, FileAccess access, FileMode mode)
2022-01-20 13:43:21 [error]: at osu.Game.IO.WrappedStorage.GetStream(String path, FileAccess access, FileMode mode) in D:\Projects\OSU\osu\osu.Game\IO\WrappedStorage.cs:line 71
2022-01-20 13:43:21 [error]: at osu.Game.Database.DatabaseContextFactory.CreateBackup(String backupFilename) in D:\Projects\OSU\osu\osu.Game\Database\DatabaseContextFactory.cs:line 157
2022-01-20 13:43:21 [error]: at osu.Game.Database.EFToRealmMigrator.ensureBackup() in D:\Projects\OSU\osu\osu.Game\Database\EFToRealmMigrator.cs:line 409
2022-01-20 13:43:21 [error]: at osu.Game.Database.EFToRealmMigrator.migrateBeatmaps(OsuDbContext ef) in D:\Projects\OSU\osu\osu.Game\Database\EFToRealmMigrator.cs:line 80
2022-01-20 13:43:21 [error]: at osu.Game.Database.EFToRealmMigrator.Run() in D:\Projects\OSU\osu\osu.Game\Database\EFToRealmMigrator.cs:line 45
2022-01-20 13:43:21 [error]: at osu.Game.OsuGameBase.load(ReadableKeyCombinationProvider keyCombinationProvider) in D:\Projects\OSU\osu\osu.Game\OsuGameBase.cs:line 198
```
</details>

Here's how the data folder looks like after the crash: (Backup files are missing)
![image](https://user-images.githubusercontent.com/25472513/150352274-c9ff4ae2-d230-45b3-8344-b29604a10390.png)

I can confirm that the migration itself is successful since the game launches just fine if I delete `client.db`. Modified settings are still persisted. It is only crashing in the backup creation part.

# Logs
[performance.log](https://github.com/ppy/osu/files/7905701/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7905702/runtime.log)
[database.log](https://github.com/ppy/osu/files/7905703/database.log)
[network.log](https://github.com/ppy/osu/files/7905704/network.log)

**Comment by frenzibyte** [comment]
I'm not really sure there's anything to do for `The process cannot access the file 'D:\Games\osu!lazer\data\client.db' because it is being used by another process.` other than to skip the migration and notify about that.

On game release, the user should have everything migrated to Realm and have their legacy EF database deleted on the first run, so I don't think this will occur for users. (unless they interrupt the migration process, at which point that'll be their fault)

**Comment by peppy** [comment]
Please create discussions in the future, not issues.

Can you try #16532 to see if it fixes the issue for you?

**Comment by bdach** [comment]
I think windows may be exclusive-locking the database file during operation. [There are traces of `LockFileEx()` calls, at least](https://github.com/realm/realm-core/blob/3173de739d953b96a1b3f3440fb3f9a6189b7c97/src/realm/util/file.cpp#L1036-L1062).

**Comment by peppy** [comment]
I've added basic retry logic, please give it another try.

**Comment by Henry-YSLin** [comment]
> Are you running from a weird file system or hardware?

Not really? The D drive is a Verbatim Vi550 S3 1TB SSD with NTFS file system.

> I've added basic retry logic, please give it another try.

Tested several times. It seems to work reliably now.
