### ISSUE TITLE
Crash when trying to present newly imported score while different ruleset is selected

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16691]
Just found this randomly when checking something else. Reproduction steps:

1. Change ruleset e.g. to taiko
2. Import an osu! score
3. Wait for import, click notification to present score
4. Crashes with

```
[runtime] 2022-01-28 20:17:40 [debug]: ClickEvent(Left) handled by ProgressCompletionNotification.
[runtime] 2022-01-28 20:17:40 [debug]: MouseClick handled by ProgressCompletionNotification.
[runtime] 2022-01-28 20:17:40 [debug]: Focus changed from NotificationOverlay to nothing.
[runtime] 2022-01-28 20:17:40 [verbose]: Song select working beatmap updated to Reol - No title (VINXIS) [toybot's Insane]
[runtime] 2022-01-28 20:17:40 [verbose]: Game-wide working beatmap updated to Reol - No title (VINXIS) [toybot's Insane]
[runtime] 2022-01-28 20:17:40 [verbose]: 📺 OsuScreenStack#397(depth:4) suspended PlaySongSelect#608 (waiting on SoloResultsScreen#650)
[runtime] 2022-01-28 20:17:40 [verbose]: 📺 OsuScreenStack#397(depth:5) loading SoloResultsScreen#650
[runtime] 2022-01-28 20:17:41 [verbose]: updating selection with beatmap:efd087db-e8b9-467e-88a8-bc0816e3c32b ruleset:osu
[runtime] 2022-01-28 20:17:41 [verbose]: decoupled ruleset transferred ("osu!catch" -> "osu!")
[runtime] 2022-01-28 20:17:41 [error]: An unhandled error has occurred.
[runtime] 2022-01-28 20:17:41 [error]: System.InvalidOperationException: Can not set value to "osu!" as bindable is disabled.
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
[runtime] 2022-01-28 20:17:41 [error]: at osu.Game.Screens.Select.SongSelect.transferRulesetValue() in /home/dachb/Dokumenty/opensource/osu/osu.Game/Screens/Select/SongSelect.cs:line 800
[runtime] 2022-01-28 20:17:41 [error]: at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass89_0.<performUpdateSelected>g__run|0() in /home/dachb/Dokumenty/opensource/osu/osu.Game/Screens/Select/SongSelect.cs:line 507
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Threading.Scheduler.Update()
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
[runtime] 2022-01-28 20:17:41 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()

```

**Comment by bdach** [comment]
Note that this is supposed to have test coverage but that test coverage is leaky as it appears song select is never actually entered until the following diff is applied:

```diff
diff --git a/osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs b/osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
index 7656bf79dc..6c32171b29 100644
--- a/osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
+++ b/osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
@@ -16,6 +16,7 @@
 using osu.Game.Screens.Menu;
 using osu.Game.Screens.Play;
 using osu.Game.Screens.Ranking;
+using osu.Game.Screens.Select;
 
 namespace osu.Game.Tests.Visual.Navigation
 {
@@ -92,6 +93,9 @@ public void TestFromMainMenuDifferentRuleset([Values] ScorePresentType type)
         [Test]
         public void TestFromSongSelect([Values] ScorePresentType type)
         {
+            AddStep("enter song select", () => Game.ChildrenOfType<ButtonSystem>().Single().OnSolo.Invoke());
+            AddUntilStep("song select is current", () => Game.ScreenStack.CurrentScreen is PlaySongSelect songSelect && songSelect.BeatmapSetsLoaded);
+
             var firstImport = importScore(1);
             presentAndConfirm(firstImport, type);
 
@@ -102,6 +106,9 @@ public void TestFromSongSelect([Values] ScorePresentType type)
         [Test]
         public void TestFromSongSelectDifferentRuleset([Values] ScorePresentType type)
         {
+            AddStep("enter song select", () => Game.ChildrenOfType<ButtonSystem>().Single().OnSolo.Invoke());
+            AddUntilStep("song select is current", () => Game.ScreenStack.CurrentScreen is PlaySongSelect songSelect && songSelect.BeatmapSetsLoaded);
+
             var firstImport = importScore(1);
             presentAndConfirm(firstImport, type);
```

**Comment by peppy** [comment]
This is a pretty unfortunate one. `SongSelect` creates a "decoupled" ruleset to expose to its local children, but as it turns out this is also (incorrectly) exposed to child screens. This means when `ReplayLoader` tries to change the ruleset, it's actually changing the decoupled instance, which then tries to forward the value to change to `SongSelect`'s ruleset bindable, which is no longer the lease holder.

I think we need to limit the exposure of `decoupledRuleset` to only direct children. A bit ugly to make happen (will need a container to place that dependency in).

**Comment by bdach** [comment]
Yeah, that checks out with my initial investigation. I tried to add some `IsCurrentScreen()` checks as a very simple fix but to no avail, so not exposing the decoupled bindable to other screens sounds like a promising alternative.

**Comment by peppy** [comment]
Turns out the exposing part alone isn't enough, though. The more important oversight is that `FinaliseSelection` isn't being called..

I have tests passing now without changing the caching, but I think it's more sane to fix that too?

**Comment by peppy** [comment]
Actually somehow the caching is already correct, against expectations.
