### ISSUE TITLE
Selecting osu!taiko Swap Mod as FreeMod Crashes in Multiplayer

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16730]
```csharp
2022-02-01 07:08:18 [verbose]: Focus contention triggered by UserModSelectOverlay.
2022-02-01 07:08:20 [error]: An unhandled error has occurred.
2022-02-01 07:08:20 [error]: System.InvalidOperationException: There is no mod in the ruleset (osu) matching the acronym SW.
2022-02-01 07:08:20 [error]: at osu.Game.Online.API.APIMod.ToMod(Ruleset ruleset)
2022-02-01 07:08:20 [error]: at osu.Game.Screens.OnlinePlay.Multiplayer.Participants.ParticipantPanel.<>c__DisplayClass16_0.<OnRoomUpdated>b__1(APIMod m)
2022-02-01 07:08:20 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
2022-02-01 07:08:20 [error]: at osu.Game.Screens.OnlinePlay.Multiplayer.Participants.ParticipantPanel.<>c__DisplayClass16_0.<OnRoomUpdated>b__0()
2022-02-01 07:08:20 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-02-01 07:08:20 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-02-01 07:08:20 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-02-01 07:08:20 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

### Discussed in https://github.com/ppy/osu/discussions/16729

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** February  1, 2022</sup>
Initially shown in https://youtu.be/DDVeIYY3pYw?t=695 but replicated in the current version of 2022.128.0 for logs.
This doesn't occur when adding Swap globally, only when available as a FreeMod. I'd wager that this is due to the incorrect ruleset being applied and thus can be replicated with any mod not available in std, but I don't want to open a bajillion lobbies to find out

https://user-images.githubusercontent.com/74262407/151927968-4e69c5c3-1fe8-4b70-869d-28d44189119a.mp4

Applicable portions of [runtime.log.txt](https://github.com/ppy/osu/files/7976562/runtime.log.txt)
.</div>

**Comment by frenzibyte** [comment]
Looks to stem from this TODO left from the multiplayer queue mode changes:
https://github.com/ppy/osu/blob/53a6ef22ceb9122faff7a0b538dbf654246b0da1/osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs#L187-L188

At first I thought `SelectedItem` is the immediate answer, yet it seems to be updated later than `OnRoomUpdated` gets invoked. Alternative working solutions would be:
 - Querying the selected item from the playlist directly via `Playlist.SingleOrDefault(i => i.ID == Room.Settings.PlaylistItemId)`; could be considered but in a more general way at a `MultiplayerRoomComposite` level.
 - Using the game-wide ruleset bindable instead; seems to work but that might be a bit hacky to use in a multiplayer room component.

**Comment by smoogipoo** [comment]
Regarding the `SelectedItem` jankery - I hope some changes I have in the pipeline will improve that in the future, namely that the beatmap is going to be queried at every level that requires it instead of as a precursor to `SelectedItem` being set non-null.
