### ISSUE TITLE
Markdown related null reference when opening beatmap set overlay

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16808]
```csharp
2022-02-07 00:45:31 [error]: An unhandled error has occurred.
2022-02-07 00:45:31 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-02-07 00:45:31 [error]: at osu.Framework.Graphics.Containers.Markdown.MarkdownFencedCodeBlock.load()
2022-02-07 00:45:31 [error]: --- End of stack trace from previous location ---
2022-02-07 00:45:31 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2022-02-07 00:45:31 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-07 00:45:31 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-02-07 00:45:31 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-02-07 00:45:31 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
```

### Discussed in https://github.com/ppy/osu/discussions/16807

<div type='discussions-op-text'>

<sup>Originally posted by **iSimpFor** February  7, 2022</sup>
https://osu.ppy.sh/beatmapsets/1113533

when opening the mapset above in osu!direct, the game crashes

parameters before crash:
filters: osu!standard, ranked maps only, sorted by difficulty(descending) 

[runtime.log](https://github.com/ppy/osu/files/8011579/runtime.log)
[performance-update.log](https://github.com/ppy/osu/files/8011580/performance-update.log)
[performance-input.log](https://github.com/ppy/osu/files/8011581/performance-input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/8011582/performance-gamethread.update.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/8011583/performance-gamethread.input.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/8011584/performance-gamethread.draw.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/8011585/performance-gamethread.audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8011586/performance-draw.log)
[performance-audio.log](https://github.com/ppy/osu/files/8011587/performance-audio.log)
[performance.log](https://github.com/ppy/osu/files/8011588/performance.log)
[network.log](https://github.com/ppy/osu/files/8011589/network.log)
[database.log](https://github.com/ppy/osu/files/8011590/database.log)

version: 2022.205.0</div>

**Comment by peppy** [comment]
Looks like this may require a framework side fix. The incoming `FencedCodeBlock` seems to be null itself.

**Comment by frenzibyte** [comment]
Interestingly I can't reproduce this locally, trying both Debug and Release configurations. Was the comment affecting this (assuming it's a comment) deleted already?
