### ISSUE TITLE
JPG elements and skin.ini not being used anymore in lazer

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu#17684]
### Type

Game behaviour

### Bug description

I updated osu!lazer and now all the elements, that are blank png elements, are now default. My mania skin is completely messed up too which is probably because there is no skin.ini. This applies to everything btw not just mania.

### Screenshots or videos

![osu_2022-04-06_08-32-32](https://user-images.githubusercontent.com/52920930/161986673-8c87ca32-bce7-4e85-8399-392e737b2f93.jpg)

### Version

2022.405.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8427300/database.log)
[network.log](https://github.com/ppy/osu/files/8427301/network.log)
[performance.log](https://github.com/ppy/osu/files/8427302/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8427303/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8427304/updater.log)

**Comment by bdach** [comment]
You need to actually enable access to this google drive file.

![2022-04-06-200351_422x219_scrot](https://user-images.githubusercontent.com/20418176/162039437-2fbb699c-c27b-4158-ba0f-cc4307bc312a.png)

(I would propose that you attach the skin via github directly but I presume it's too large to fit,)

**Comment by WinterIsPretty** [comment]
oh sorry I am on school chromebook it defaults to the school directory only

**Comment by bdach** [comment]
Thanks, can reproduce.

Bisect turns up 6b5ee6d89dbf64de2003f0b8cb9e77da75def66b (framework bump!). Guessing it's the imagesharp bump causing it, but I don't know for sure yet.

**Comment by bdach** [comment]
Yep, with a local checkout I see the following error:

```
SixLabors.ImageSharp.InvalidImageContentException: CRC Error. PNG IDAT chunk is corrupt!
   at SixLabors.ImageSharp.Formats.Png.PngThrowHelper.ThrowInvalidChunkCrc(String chunkTypeName)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ValidateChunk(PngChunk& chunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.TryReadChunk(PngChunk& chunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
```

which tracks back to https://github.com/SixLabors/ImageSharp/pull/1898 which would have first been included in our releases with aforementioned bump. That said, both imagesharp and stbi fall over on several PNGs in the attached skin, so at that point it seems more like the skin is broken? Re-exporting the PNGs involved in gimp fixes this issue for me.

@WinterIsPretty can you shine a light on how this skin was made? Did you download it from somewhere, or made it on your own? If it's the former, what tool did you use for it?

**Comment by peppy** [comment]
The cause has already been determined, please refrain from posting further. It's unnecessary.

The next step would be to find the precise cause of the incompatibility and report upstream. But as long as this only affects one user/skin combination I'd also say this is low priority and doesn't require p0 action.

**Comment by frenzibyte** [comment]
Going to add to this that the PNGs in the skin look to be completely corrupted on a quick byte-per-byte check:

<img width="1264" alt="CleanShot 2022-04-12 at 23 04 24@2x" src="https://user-images.githubusercontent.com/22781491/163044396-3e9f8932-d676-414d-adcd-1efc3700550c.png">

The original (corrupted) PNG is by itself missing the `IEND` (image trailer) chunk, [which is essential to any PNG](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html):
<img width="598" alt="CleanShot 2022-04-12 at 23 38 58@2x" src="https://user-images.githubusercontent.com/22781491/163049682-efa8daf9-6bfb-44a2-bd74-b5b173781730.png">

Exporting via GIMP and compressing via TinyPNG as mentioned above still results in correct PNG files (in fact, trying to compress the skin's PNG files in TinyPNG yield "Image could not be decoded").

That makes me wonder if we still want this issue thread open, as this looks to be 100% the skin's fault, and it doesn't seem like there's any other skin with the same issue so far.

**Comment by WinterIsPretty** [comment]
This is even more confusing, what even happened to my skin... what the.... so I guess this should be closed then since this happened

**Comment by frenzibyte** [comment]
It's specific to those 1x1 images, which look to have been copied across most sprites in the skin. The rest are fine. Will leave this open until a decision is taken.
