### ISSUE TITLE
The game throws some exceptions when the tablet is disconnected and then reconnected

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#17711]
### Type

Game behaviour

### Bug description

The game throws some exceptions when my tablet is disconnected and then reconnected.
The issue seems to happen only after I enable and then disable the "Tablet" option (as you can see in the video below).
Notes:
- I never touched the tablet in this recording, I just disconnected/reconnected it.
- You can hear when the tablet is disconnected/connected in the video
- The tablet is a "Wacom CTL-472"

### Screenshots or videos

https://user-images.githubusercontent.com/43073074/162208858-60ca0553-e727-4b17-b20f-ec147c7d5420.mp4

### Version

2022.405.0-lazer

### Logs

Here's the [`runtime.log`](https://github.com/ppy/osu/files/8443144/runtime.log) of the recording

**Comment by peppy** [comment]
```csharp
2022-04-07 13:11:40 [verbose]: Detect: Searching for tablets...
2022-04-07 13:11:40 [verbose]: Detect: Found tablet 'Wacom CTL-472'
2022-04-07 13:11:45 [error]: An unobserved error has occurred.
2022-04-07 13:11:45 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
2022-04-07 13:11:45 [error]: ---> System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.<>c__DisplayClass17_0.<Initialize>b__5(Object s, IEnumerable`1 e)
2022-04-07 13:11:45 [error]: at OpenTabletDriver.Driver.Detect()
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.TabletDriver.detectAsync(CancellationToken cancellationToken)
2022-04-07 13:11:45 [error]: --- End of inner exception stack trace ---
2022-04-07 13:11:45 [error]: An unobserved error has occurred. (inner)
2022-04-07 13:11:45 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.<>c__DisplayClass17_0.<Initialize>b__5(Object s, IEnumerable`1 e)
2022-04-07 13:11:45 [error]: at OpenTabletDriver.Driver.Detect()
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.TabletDriver.detectAsync(CancellationToken cancellationToken)
2022-04-07 13:11:45 [verbose]: ⚠️ An unobserved error has occurred.
```

@infinityghost can you take a look at this? something is null in the `tabletDriver.DeviceReported` that we're not expecting to be null.
