### ISSUE TITLE
Multiplayer crash upon entering gameplay

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#17713]
### Type

Crash to desktop

### Bug description

I was readied up in a multiplayer lobby, the game started via a manual countdown and it crashed.

### Version

2022.405.0

### Logs

[performance.log](https://github.com/ppy/osu/files/8446254/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8446255/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8446256/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8446257/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8446258/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8446259/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8446260/updater.log)
[database.log](https://github.com/ppy/osu/files/8446261/database.log)
[network.log](https://github.com/ppy/osu/files/8446263/network.log)

**Comment by bdach** [comment]
from the log:

```
2022-04-07 19:11:55 [error]: An unhandled error has occurred.
2022-04-07 19:11:55 [error]: System.InvalidOperationException: Sequence contains no matching element
2022-04-07 19:11:55 [error]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2022-04-07 19:11:55 [error]: at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
2022-04-07 19:11:55 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass91_0.<osu.Game.Online.Multiplayer.IMultiplayerClient.UserStateChanged>b__0()
```

which is interesting because it's this `Single()` call:

https://github.com/ppy/osu/blob/d256bd2cc793d0ea296eea9a75ab09aa5fd92c63/osu.Game/Online/Multiplayer/MultiplayerClient.cs#L497

No idea how it can fail, though.

**Comment by peppy** [comment]
I think the reason for this failure might be very obvious (unless I'm missing something). Users are only added to the `Room.Users` list after the initial user metadata population has completed... which is an async operation:

https://github.com/ppy/osu/blob/f92a31cd3994c59fa6e4a909180f10868f58c0c2/osu.Game/Online/Multiplayer/MultiplayerClient.cs#L384

Potentially one of those "how did this ever work" moments..

**Comment by peppy** [comment]
Or.. the above could not be an issue due to the hidden behaviour where SignalR is single-threaded in its invocation of messages. There must be something else at play in that case.

**Comment by peppy** [comment]
The cause of this was already found (discussion followed on discord) but for documentation purposes:

```diff
diff --git a/osu.Game/Online/Multiplayer/MultiplayerClient.cs b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
index d6099e5f72..0aa9e01430 100644
--- a/osu.Game/Online/Multiplayer/MultiplayerClient.cs
+++ b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
@@ -148,6 +148,8 @@ private void load()
         /// <param name="password">An optional password to use for the join operation.</param>
         public async Task JoinRoom(Room room, string? password = null)
         {
+            // BUG: this thread is running from a different thread.
+
             var cancellationSource = joinCancellationSource = new CancellationTokenSource();
 
             await joinOrLeaveTaskChain.Add(async () =>
@@ -161,6 +163,13 @@ public async Task JoinRoom(Room room, string? password = null)
                 var joinedRoom = await JoinRoom(room.RoomID.Value.Value, password ?? room.Password.Value).ConfigureAwait(false);
                 Debug.Assert(joinedRoom != null);
 
+                // BUG: the above awaited call does the signalr join, but the room is only set below, after further operations.
+                // BUG: during this period, new messages may arrive from signalr and be dropped due to the room being null.
+
+                // repro with the following, with a second client joining the room during the delay:
+                if (joinedRoom.Users.Count == 1)
+                    await Task.Delay(30000);
+
                 // Populate users.
                 Debug.Assert(joinedRoom.Users != null);
                 await Task.WhenAll(joinedRoom.Users.Select(PopulateUser)).ConfigureAwait(false);
@@ -168,6 +177,7 @@ public async Task JoinRoom(Room room, string? password = null)
                 // Update the stored room (must be done on update thread for thread-safety).
                 await scheduleAsync(() =>
                 {
+                    // Room is finally set here, but it's potentially too late.
                     Room = joinedRoom;
                     APIRoom = room;
 
@@ -378,26 +388,31 @@ Task IMultiplayerClient.RoomStateChanged(MultiplayerRoomState state)
 
         async Task IMultiplayerClient.UserJoined(MultiplayerRoomUser user)
         {
-            if (Room == null)
-                return;
-
-            await PopulateUser(user).ConfigureAwait(false);
-
-            Scheduler.Add(() =>
+            await joinOrLeaveTaskChain.Add(async () =>
             {
+                // BUG: this could be hit during the join sequence, meaning some users join the room but this is not announced to the client.
                 if (Room == null)
                     return;
 
-                // for sanity, ensure that there can be no duplicate users in the room user list.
-                if (Room.Users.Any(existing => existing.UserID == user.UserID))
-                    return;
+                await PopulateUser(user).ConfigureAwait(false);
 
-                Room.Users.Add(user);
+                Scheduler.Add(() =>
+                {
+                    // BUG: this could be hit during the join sequence, meaning some users join the room but this is not announced to the client.
+                    if (Room == null)
+                        return;
 
-                addUserToAPIRoom(user);
+                    // for sanity, ensure that there can be no duplicate users in the room user list.
+                    if (Room.Users.Any(existing => existing.UserID == user.UserID))
+                        return;
 
-                UserJoined?.Invoke(user);
-                RoomUpdated?.Invoke();
+                    Room.Users.Add(user);
+
+                    addUserToAPIRoom(user);
+
+                    UserJoined?.Invoke(user);
+                    RoomUpdated?.Invoke();
+                });
             });
         }
 
@@ -484,24 +499,25 @@ Task IMultiplayerClient.SettingsChanged(MultiplayerRoomSettings newSettings)
             return Task.CompletedTask;
         }
 
-        Task IMultiplayerClient.UserStateChanged(int userId, MultiplayerUserState state)
+        async Task IMultiplayerClient.UserStateChanged(int userId, MultiplayerUserState state)
         {
-            if (Room == null)
-                return Task.CompletedTask;
-
-            Scheduler.Add(() =>
+            await joinOrLeaveTaskChain.Add(() =>
             {
                 if (Room == null)
                     return;
 
-                Room.Users.Single(u => u.UserID == userId).State = state;
+                Schedule(() =>
+                {
+                    if (Room == null)
+                        return;
 
-                updateUserPlayingState(userId, state);
+                    Room.Users.Single(u => u.UserID == userId).State = state;
 
-                RoomUpdated?.Invoke();
-            }, false);
+                    updateUserPlayingState(userId, state);
 
-            return Task.CompletedTask;
+                    RoomUpdated?.Invoke();
+                });
+            });
         }
 
         Task IMultiplayerClient.MatchUserStateChanged(int userId, MatchUserState state)
```
