### ISSUE TITLE
First opening of settings after startup gives error "Failed to load ruleset settings"

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#17968]
### Type

Game behaviour

### Bug description

The first time i open the settings overlay after launching the game gives me this error. (I only play standard, that's the ruleset the game is closed and opened with)

### Version

2022.424.1

### Logs

[network.log](https://github.com/ppy/osu/files/8550555/network.log)
[performance.log](https://github.com/ppy/osu/files/8550556/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8550557/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8550558/updater.log)
[database.log](https://github.com/ppy/osu/files/8550559/database.log)

```2022-04-24 21:41:33 [verbose]: Chat is now polling every 60000 ms
2022-04-24 21:41:33 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2022-04-24 21:41:36 [verbose]: ⚠️ Failed to load ruleset settings
2022-04-24 21:41:36 [verbose]: 
2022-04-24 21:41:36 [verbose]: This error has been automatically reported to the devs.
2022-04-24 21:41:37 [error]: Failed to load ruleset settings
2022-04-24 21:41:37 [error]: osu.Framework.Allocation.DependencyNotRegisteredException: The type SandboxSettingsSubsection has a dependency on NotificationOverlay, but the dependency is not registered.
2022-04-24 21:41:37 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass7_0.<getDependency>b__0(IReadOnlyDependencyContainer dc)
2022-04-24 21:41:37 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_1.<CreateActivator>b__2(Object target, IReadOnlyDependencyContainer dc)
2022-04-24 21:41:37 [error]: at osu.Framework.Allocation.ResolvedAttribute.<>c__DisplayClass6_0.<CreateActivator>b__1(Object target, IReadOnlyDependencyContainer dc)
2022-04-24 21:41:37 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-04-24 21:41:37 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-04-24 21:41:37 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-04-24 21:41:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-04-24 21:41:37 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-04-24 21:41:37 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2022-04-24 21:41:37 [error]: at osu.Game.Overlays.Settings.Sections.RulesetSection.load(RulesetStore rulesets)
2022-04-24 21:41:40 [verbose]: ButtonSystem's state changed from TopLevel to Exit```

**Comment by Theighlin** [comment]
After re-reading the error, i saw it had to do with the sandbox ruleset, updating it fixed the issue.

**Comment by peppy** [comment]
Rulesets should not be touching this component. Please delete said ruleset as it may be doing something nefarious.

**Comment by Coppertine** [comment]
Just to let Theighlin know, this is from the Sandbox ruleset, the function of the NoficiationOverlay is to let the player know that the "Open Main Screen" button can only be used in the main menu.
No intention to necropost and want to give clarification as to what the ruleset does.
