### ISSUE TITLE
Consistent Could Not Load Rulest Settings Error Message Bug In Options

### ISSUE THREAD

**Issue by SealsarecuteR** [ppy/osu#18268]
### Type

Game behaviour

### Bug description

About 2 weeks ago, I started getting this Could not load ruleset settings error message in the notifications bar when I click on the settings button, but it always loads the 2nd time, so it can load it. Any ideas of how its happening, or how to stop it from doing it?

### Screenshots or videos

![Bug](https://user-images.githubusercontent.com/104747740/168446891-cda8640c-a1ab-46e2-87c3-9379a813c3a5.jpg)

### Version

2022.509.0-Lazer

### Logs

[database.log](https://githu
[performance-draw.log](https://github.com/ppy/osu/files/8693786/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8693787/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8693788/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8693789/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8693790/updater.log)
b.com/ppy/osu/files/8693782/database.log)
[network.log](https://github.com/ppy/osu/files/8693783/network.log)
[performance.log](https://github.com/ppy/osu/files/8693784/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8693785/performance-audio.log)

**Comment by frenzibyte** [comment]
```
2022-05-14 20:17:01 [error]: Failed to load ruleset settings
2022-05-14 20:17:01 [error]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
2022-05-14 20:17:01 [error]: ---> System.MissingMethodException: Method not found: 'System.Span`1<!0> SixLabors.ImageSharp.Image`1.GetPixelRowSpan(Int32)'.
2022-05-14 20:17:01 [error]: at osu.Game.Rulesets.Hitokori.TextureGeneration.Generate(Int32 width, Int32 height, Func`3 generator)
2022-05-14 20:17:01 [error]: at osu.Game.Rulesets.Hitokori.TextureGeneration.HSVCircle(Int32 size, Single innerRadius, Single outerRadius, Single saturation, Single value, Single fadeDistance, Nullable`1 discreteCount)
2022-05-14 20:17:01 [error]: at osu.Game.Rulesets.Hitokori.UI.ColorPickerControl.HuePicker..ctor()
2022-05-14 20:17:01 [error]: at osu.Game.Rulesets.Hitokori.UI.ColorPickerControl..ctor()
2022-05-14 20:17:01 [error]: at osu.Game.Rulesets.Hitokori.UI.OrbitalColorPicker..ctor()
2022-05-14 20:17:01 [error]: at System.RuntimeType.CreateInstanceOfT()
```

The ruleset "hitokori" is old enough to run on latest release, please consider updating it if you're not running latest version, otherwise consult the ruleset author.
