### ISSUE TITLE
Errors + crash in lazer editor

### ISSUE THREAD

**Issue by Morco011** [ppy/osu#18373]
### Type

Crash to desktop

### Bug description

I was testing the new feature for timing in the editor, and when I press "play from start" there is an error. And when I pressed my space bar to play the music, an other error then the game crashed. (video when it turns black)
Other small issue : the red line of the bottom timeline is in an another dimention (video)

### Screenshots or videos

https://streamable.com/8xys0n

### Version

2022.523.0.0

### Logs

[updater.log](https://github.com/ppy/osu/files/8757257/updater.log)
[database.log](https://github.com/ppy/osu/files/8757259/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8757260/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8757261/network.log)
[performance.log](https://github.com/ppy/osu/files/8757263/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8757265/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8757266/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/8757267/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8757268/runtime.log)

**Comment by bdach** [comment]
I have no idea how you've managed to enter this broken state. Can you show a video of this issue but with the beatmap creation process shown from start to finish? As in, what you did exactly from the very moment you entered editor?

**Comment by Morco011** [comment]
I don't know how I did it and I can't do it anymore even if I do the exact same thing
I recorded it after I saw the first error and the redline

**Comment by bdach** [comment]
Well either way it's going to be related to this, whatever caused it:

```
2022-05-23 11:47:13 [error]: An unhandled error has occurred.
2022-05-23 11:47:13 [error]: System.ObjectDisposedException: Can not start disposed tracks.
2022-05-23 11:47:13 [error]: Object name: 'osu.Framework.Audio.Track.TrackBass'.
2022-05-23 11:47:13 [error]: at osu.Framework.Audio.Track.Track.Start()
2022-05-23 11:47:13 [error]: at osu.Framework.Audio.Track.TrackBass.Start()
2022-05-23 11:47:13 [error]: at osu.Framework.Timing.DecoupleableInterpolatingFramedClock.Start()
2022-05-23 11:47:13 [error]: at osu.Game.Screens.Edit.EditorClock.Start()
2022-05-23 11:47:13 [error]: at osu.Game.Screens.Edit.Timing.TapTimingControl.tap()
```

No idea what could have disposed the track, though. Could have been a finaliser for all I know.

**Comment by Morco011** [comment]
If I get it once more I will try to understand what I did but now it works fine so I can't give more info yet
