### ISSUE TITLE
Crash to desktop after trying to open a multiplayer lobby

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#18466]
### Type

Crash to desktop

### Bug description

Just a crash after trying to open a multiplayer lobby (see logs)

### Version

2022.528.0

### Logs

[performance.log](https://github.com/ppy/osu/files/8791773/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8791774/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8791775/updater.log)
[database.log](https://github.com/ppy/osu/files/8791776/database.log)
[network.log](https://github.com/ppy/osu/files/8791777/network.log)

**Comment by bdach** [comment]
So this one is interesting, because on the face of it it's a bogstandard `InvalidThreadForMutationException`, which would normally be patched with a schedule, which was my first instinct too - but then I started to wonder why this fade apparently fails when I've seen it work many times previously. And the answer is a bit further down the call stack:

```
2022-05-28 19:51:20 [error]: at osu.Game.Online.API.APIRequest.Fail(Exception e)
2022-05-28 19:51:20 [error]: at osu.Game.Online.API.APIAccess.flushQueue(Boolean failOldRequests)
2022-05-28 19:51:20 [error]: at osu.Game.Online.API.APIAccess.handleFailure()
2022-05-28 19:51:20 [error]: at osu.Game.Online.API.APIAccess.handleWebException(WebException we)
2022-05-28 19:51:20 [error]: at osu.Game.Online.API.APIAccess.handleRequest(APIRequest req)
```

This is evidence of a possible entire class of bugs stemming from the fact that when connectivity is lost due to enough consecutive requests failing, the request queue is flushed by failing all subsequent requests. But notably, the flushed requests don't get `Perform(IAPIProvider)` called on them, which means that they can't internally store it:

https://github.com/ppy/osu/blob/80fc13fc1f2952a1b376f8c73429f5864c95566f/osu.Game/Online/API/APIRequest.cs#L108

Normally success/failure callbacks are internally scheduled by `APIRequest` onto the `APIAccess` that they receive in `Perform()` - but in this case this hasn't happened, so the callbacks are executed unscheduled:

https://github.com/ppy/osu/blob/80fc13fc1f2952a1b376f8c73429f5864c95566f/osu.Game/Online/API/APIRequest.cs#L167-L170

which means that at present, it is really generally not safe to assume that _any_ callbacks are scheduled - because they won't be if they are failed due to flushing the request queue.

Therefore, my question here would be - maybe we want to approach this one differently and provide a way to provide the `APIAccess` even in the flush scenario?

**Comment by smoogipoo** [comment]
In general, anything to do with the API should be scheduled to the local `Drawable`, including `Success`/`Failure` but also `IAPIAccess.LocalUser`/`IAPIAccess.State` change events.

This is because there's two points of failure - one being the `InvalidThreadForMutation` exception you're seeing there, but there's also a second one which is a request potentially changing a `Drawable` after it's been disposed.

I think, however you'd change the callbacks here, you're still going to have an `API == null` case. For example I could imagine a complicated scenario in which a web request is constructed but cancelled before it's ever enqueued. The only way to get around this would be to have everything go via `APIAccess` in the first place - like `var req = APIAccess.CreateRequest()` of some kind.

**Comment by peppy** [comment]
I wouldn't focus too much on the `API` null part of the flush flow. We're generally aware that `APIAccess` isn't great, especially on the resiliency front (and the code quality surrounding the paths of resiliency) so I'd see that being refactored in the future.

Maybe mark as `CanBeNull` (or nullable the class) and add null checks in usage locations.
