### ISSUE TITLE
beatmap import

### ISSUE THREAD

**Issue by githubforzack** [ppy/osu#18520]
### Type

Crash to desktop

### Bug description

osu!stable isn't detected, and then when I try to navigate to where it is, 1. it won't open the directory and 2. it crashes after too many tries

MacBook air mid-2012 updated to 10.15.7

was trying to get my beatmaps imported btw on the setup tutorial by the way

### Screenshots or videos

none

### Version

osu! 2022.528.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8819202/database.log)
[network.log](https://github.com/ppy/osu/files/8819203/network.log)
[performance.log](https://github.com/ppy/osu/files/8819204/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8819205/runtime.log)

**Comment by frenzibyte** [comment]
Relevant log:
```
2022-06-01 22:54:00 [error]: An unhandled error has occurred.
2022-06-01 22:54:00 [error]: System.UnauthorizedAccessException: Access to the path '/Users/lihongwei/Desktop' is denied.
2022-06-01 22:54:00 [error]: ---> System.IO.IOException: Operation not permitted
2022-06-01 22:54:00 [error]: --- End of inner exception stack trace ---
2022-06-01 22:54:00 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
2022-06-01 22:54:00 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.Init()
2022-06-01 22:54:00 [error]: at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
2022-06-01 22:54:00 [error]: at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
2022-06-01 22:54:00 [error]: at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
2022-06-01 22:54:00 [error]: at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
2022-06-01 22:54:00 [error]: at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
2022-06-01 22:54:00 [error]: at System.IO.DirectoryInfo.GetFiles(String searchPattern)
2022-06-01 22:54:00 [error]: at osu.Game.Overlays.Settings.Sections.Maintenance.StableDirectorySelectScreen.IsValidDirectory(DirectoryInfo info) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/Sections/Maintenance/StableDirectorySelectScreen.cs:line 18
2022-06-01 22:54:00 [error]: at osu.Game.Overlays.Settings.Sections.Maintenance.DirectorySelectScreen.<LoadComplete>b__9_0(ValueChangedEvent`1 e) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/Sections/Maintenance/DirectorySelectScreen.cs:line 123
2022-06-01 22:54:00 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-06-01 22:54:00 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-06-01 22:54:00 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2022-06-01 22:54:00 [error]: at osu.Framework.Graphics.UserInterface.DirectorySelectorDirectory.OnClick(ClickEvent e)
2022-06-01 22:54:00 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2022-06-01 22:54:00 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.StateChanges.MouseButtonInput.Apply(InputState state, IInputStateChangeHandler handler)
2022-06-01 22:54:00 [error]: at osu.Framework.Input.InputManager.Update()
2022-06-01 22:54:00 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2022-06-01 22:54:00 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-06-01 22:54:00 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-06-01 22:54:00 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-06-01 22:54:00 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

Did you deny osu! from accessing your "Downloads" folder? Head over to System Preferences -> Security & Privacy -> Privacy -> Files and Folders, and check if osu! is allowed to access as such.
