### ISSUE TITLE
Osu Lazer does not run on Windows 7 x64

### ISSUE THREAD

**Issue by FrostyWalker24** [ppy/osu#18605]
### Type

Crash to desktop

### Bug description

When I try to run the .exe file, it shows up on task manager for a little while, then it disappears.
I've looked into this issue and tried installing .NET 6.0 to no avail.

### Version

2022.605.1

### Logs

2022-06-07 11:04:43 [verbose]: ----------------------------------------------------------
2022-06-07 11:04:43 [verbose]: runtime Log for Calvin (LogLevel: Verbose)
2022-06-07 11:04:43 [verbose]: Running osu 2022.605.1.0 on .NET 6.0.2
2022-06-07 11:04:43 [verbose]: Environment: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1), 4 cores
2022-06-07 11:04:43 [verbose]: ----------------------------------------------------------
2022-06-07 11:04:43 [verbose]: Detect: Searching for tablets...
2022-06-07 11:04:43 [verbose]: Detect: No tablets were detected.
2022-06-07 11:04:43 [verbose]: GL Initialized
2022-06-07 11:04:43 [verbose]: GL Version:                 4.4.0 - Build 20.19.15.5126
2022-06-07 11:04:43 [verbose]: GL Renderer:                Intel(R) HD Graphics 5500
2022-06-07 11:04:43 [verbose]: GL Shader Language version: 4.40 - Build 20.19.15.5126
2022-06-07 11:04:43 [verbose]: GL Vendor:                  Intel
2022-06-07 11:04:43 [verbose]: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_ARB_conservative_depth GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_ARB_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_SUN_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_ARB_texture_barrier GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_ARB_texture_swizzle GL_EXT_texture_swizzle GL_ARB_texture_gather GL_ARB_sync GL_ARB_cl_event GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_ARB_transform_feedback2 GL_ARB_draw_indirect GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_ARB_framebuffer_no_attachments GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_ARB_texture_buffer_range GL_EXT_texture_snorm GL_ARB_blend_func_extended GL_INTEL_performance_query GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_geometry_shader4 GL_EXT_geometry_shader4 GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_EXT_shader_integer_mix GL_ARB_instanced_arrays GL_ARB_base_instance GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_texture_multisample GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_timer_query GL_EXT_timer_query GL_ARB_tessellation_shader GL_ARB_vertex_array_object GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_texture_cube_map_array GL_EXT_gpu_shader4 GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_INTEL_fragment_shader_ordering GL_ARB_fragment_shader_interlock GL_ARB_clip_control GL_ARB_shader_subroutine GL_ARB_transform_feedback3 GL_ARB_get_program_binary GL_ARB_separate_shader_objects GL_ARB_shader_precision GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_ARB_transform_feedback_instanced GL_ARB_compressed_texture_pixel_storage GL_ARB_shader_atomic_counters GL_ARB_shading_language_packing GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_texture_storage GL_EXT_texture_storage GL_ARB_compute_shader GL_ARB_vertex_attrib_binding GL_ARB_texture_view GL_ARB_fragment_layer_viewport GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_texture_storage_multisample GL_ARB_buffer_storage GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_query_buffer_object GL_EXT_polygon_offset_clamp GL_ARB_clear_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_debug_output GL_ARB_enhanced_layouts GL_KHR_debug GL_ARB_arrays_of_arrays GL_ARB_texture_query_levels GL_ARB_invalidate_subdata GL_ARB_clear_buffer_object GL_INTEL_map_texture GL_ARB_texture_compression_bptc GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_robustness GL_ARB_robust_buffer_access_behavior GL_EXT_texture_sRGB_decode GL_ARB_copy_image GL_KHR_blend_equation_advanced GL_EXT_direct_state_access GL_ARB_stencil_texturing GL_ARB_texture_stencil8 GL_ARB_explicit_uniform_location GL_ARB_multi_bind GL_ARB_indirect_parameters
2022-06-07 11:04:43 [verbose]: Stored display index (-1) doesn't match current index (0)
2022-06-07 11:04:43 [verbose]: Updated display mode to desktop resolution: 1366x768@60, SDL_PIXELFORMAT_RGB888
2022-06-07 11:04:43 [verbose]: Host execution state changed to Running
2022-06-07 11:04:43 [verbose]: Execution mode changed to MultiThreaded
2022-06-07 11:04:44 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2022-06-07 11:04:44 [error]: System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
2022-06-07 11:04:44 [error]: ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.Initialize()
2022-06-07 11:04:44 [error]: at Realms.NativeCommon.Initialize()
2022-06-07 11:04:44 [error]: at Realms.SharedRealmHandle..cctor()
2022-06-07 11:04:44 [error]: --- End of inner exception stack trace ---
2022-06-07 11:04:44 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
2022-06-07 11:04:44 [error]: at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
2022-06-07 11:04:44 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2022-06-07 11:04:44 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess.cleanupPendingDeletions()
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess..ctor(Storage storage, String filename, GameThread updateThread, IDatabaseContextFactory efContextFactory)
2022-06-07 11:04:44 [verbose]: 🔈 BASS initialised
2022-06-07 11:04:44 [verbose]: BASS version:           2.4.16.7
2022-06-07 11:04:44 [verbose]: BASS FX version:        2.4.12.6
2022-06-07 11:04:44 [verbose]: BASS MIX version:       2.4.11.1
2022-06-07 11:04:44 [verbose]: Device:                 Default
2022-06-07 11:04:44 [verbose]: Driver:
2022-06-07 11:04:44 [verbose]: Update period:          5 ms
2022-06-07 11:04:44 [verbose]: Device buffer length:   10 ms
2022-06-07 11:04:44 [verbose]: Playback buffer length: 100 ms
2022-06-07 11:04:44 [error]: An unhandled error has occurred.
2022-06-07 11:04:44 [error]: System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
2022-06-07 11:04:44 [error]: ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.Initialize()
2022-06-07 11:04:44 [error]: at Realms.NativeCommon.Initialize()
2022-06-07 11:04:44 [error]: at Realms.SharedRealmHandle..cctor()
2022-06-07 11:04:44 [error]: --- End of inner exception stack trace ---
2022-06-07 11:04:44 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
2022-06-07 11:04:44 [error]: at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
2022-06-07 11:04:44 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2022-06-07 11:04:44 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2022-06-07 11:04:44 [error]: at Realms.Realm.Compact(RealmConfigurationBase config)
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess.Compact()
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess.BlockAllOperations()
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess.CreateBackup(String backupFilename)
2022-06-07 11:04:44 [error]: at osu.Game.Database.RealmAccess..ctor(Storage storage, String filename, GameThread updateThread, IDatabaseContextFactory efContextFactory)
2022-06-07 11:04:44 [error]: at osu.Game.OsuGameBase.load(ReadableKeyCombinationProvider keyCombinationProvider)
2022-06-07 11:04:44 [error]: --- End of stack trace from previous location ---
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-06-07 11:04:44 [error]: --- End of stack trace from previous location ---
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-06-07 11:04:44 [error]: --- End of stack trace from previous location ---
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-06-07 11:04:44 [error]: --- End of stack trace from previous location ---
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-06-07 11:04:44 [error]: --- End of stack trace from previous location ---
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-06-07 11:04:44 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-06-07 11:04:44 [error]: at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game)
2022-06-07 11:04:44 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
2022-06-07 11:04:44 [error]: at osu.Desktop.Program.Main(String[] args)
2022-06-07 11:04:44 [error]: An unhandled error has occurred. (inner)
2022-06-07 11:04:44 [error]: System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.install_scheduler_callbacks(get_context get, post_on_context post, release_context release, is_on_context is_on)
2022-06-07 11:04:44 [error]: at Realms.SynchronizationContextScheduler.Initialize()
2022-06-07 11:04:44 [error]: at Realms.NativeCommon.Initialize()
2022-06-07 11:04:44 [error]: at Realms.SharedRealmHandle..cctor()
2022-06-07 11:04:44 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .

**Comment by Theighlin** [comment]
From the README.

Lazer does not support windows 7.

![Screenshot_2022-06-07-13-20-38-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/53081750/172367431-cb7e7685-9f3f-48bb-97f6-b093b8db8ade.jpg)

**Comment by darkralts** [comment]
why not? surely there must be a reason why it doesn't run, windows is windows after all

**Comment by uzervlad** [comment]
#13769
