### ISSUE TITLE
 Unable to load shared library 'SDL2' or one of its dependencies

### ISSUE THREAD

**Issue by Itzbenz** [ppy/osu#18628]
### Type

Crash to desktop

### Bug description

OS : Debian 10.5 Buster Linux 4.19.0-20-amd64
Use commit 795c9fcbc9cfa9345d9ed1cbde3a8e9fc4a7606d or later 

```cs
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.INTERNAL_SDL_SetHint(Byte* name, Byte* value)
   at SDL2.SDL.SDL_SetHint(String name, String value)
   at osu.Framework.Platform.Linux.LinuxGameHost.SetupForRun()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/Program.cs:line 105
```

installing this `apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-gfx-dev` would have different error

```cs
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'SDL_SetWindowMouseRect' in shared library 'SDL2'.
   at SDL2.SDL.SDL_SetWindowMouseRect(IntPtr window, IntPtr rect)
   at osu.Framework.Platform.SDL2DesktopWindow.<>c__DisplayClass89_0.<updateCursorConfinement>b__1()
   at osu.Framework.Threading.Scheduler.Add(Action task, Boolean forceScheduled)
   at osu.Framework.Platform.SDL2DesktopWindow.ScheduleCommand(Action action)
   at osu.Framework.Platform.SDL2DesktopWindow.updateCursorConfinement()
   at osu.Framework.Platform.SDL2DesktopWindow.<.ctor>b__126_0(ValueChangedEvent`1 evt)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Framework.Platform.SDL2DesktopWindow.set_CursorState(CursorState value)
   at osu.Desktop.OsuGameDesktop.SetHost(GameHost host) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/OsuGameDesktop.cs:line 129
   at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/Program.cs:line 105
```

### Version

795c9fcbc9cfa9345d9ed1cbde3a8e9fc4a7606d

### Logs

```
[runtime] 2022-06-09 00:40:20 [verbose]: Starting legacy IPC provider...
[runtime] 2022-06-09 00:40:22 [verbose]: Detect: Searching for tablets...
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet '10moon 1060N'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Acepen AP 1060'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Artisul M0610 Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon 1060 Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M106K Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M106K'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M10K Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M10K'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M1220'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon M1230'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon PD1161'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon PD1560'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon S56K'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon S620'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Gaomon S630'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Genius G-Pen 560'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Genius i608x'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion 420'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion G10T'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion GC610'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion GT-220 V2'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion GT-221 Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H1060P'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H1161'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H420'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H420X'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H430P'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H610 Pro V2'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H610 Pro'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H640P'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion H950P'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion HC16'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion HS610'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion HS611'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion HS64'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas 13'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas 16 (2021)'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas 16'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas 20'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas 22 Plus'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas Pro 12'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas Pro 13'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas Pro 16'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Kamvas Pro 20'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion New 1060 Plus (2048)'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion New 1060 Plus'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Q11K V2'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Q11K'
[runtime] 2022-06-09 00:40:22 [debug]: Detect: Searching for tablet 'Huion Q620M'
Console output is being limited. Please check runtime.log for full logs.
[runtime] 2022-06-09 00:40:22 [verbose]: Detect: No tablets were detected.
[runtime] 2022-06-09 00:40:22 [verbose]: Connected MIDI device: Midi Through Port-0
[runtime] 2022-06-09 00:40:22 [verbose]: GL Initialized
[runtime] 2022-06-09 00:40:22 [verbose]: GL Version:                 4.5 (Compatibility Profile) Mesa 18.3.6
[runtime] 2022-06-09 00:40:22 [verbose]: GL Renderer:                AMD CARRIZO (DRM 3.27.0, 4.19.0-20-amd64, LLVM 7.0.1)
[runtime] 2022-06-09 00:40:22 [verbose]: GL Shader Language version: 4.50
[runtime] 2022-06-09 00:40:22 [verbose]: GL Vendor:                  X.Org
[runtime] 2022-06-09 00:40:22 [verbose]: GL Extensions:              GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_vertex_attrib_64bit GL_NV_vdpau_interop GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_bindless_texture GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_sparse_buffer GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_AMD_framebuffer_multisample_advanced
[runtime] 2022-06-09 00:40:22 [verbose]: Stored display index (-1) doesn't match current index (0)
[runtime] 2022-06-09 00:40:22 [verbose]: Updated display mode to desktop resolution: 1360x768@60, SDL_PIXELFORMAT_RGB888
[runtime] 2022-06-09 00:40:22 [verbose]: Host execution state changed to Running
[runtime] 2022-06-09 00:40:22 [verbose]: Execution mode changed to MultiThreaded
[runtime] 2022-06-09 00:40:22 [error]: An unhandled error has occurred.
[runtime] 2022-06-09 00:40:22 [error]: System.EntryPointNotFoundException: Unable to find an entry point named 'SDL_SetWindowMouseRect' in shared library 'SDL2'.
[runtime] 2022-06-09 00:40:22 [error]: at SDL2.SDL.SDL_SetWindowMouseRect(IntPtr window, IntPtr rect)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.<>c__DisplayClass89_0.<updateCursorConfinement>b__1()
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Threading.Scheduler.Add(Action task, Boolean forceScheduled)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.ScheduleCommand(Action action)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.updateCursorConfinement()
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.<.ctor>b__126_0(ValueChangedEvent`1 evt)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.set_CursorState(CursorState value)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Desktop.OsuGameDesktop.SetHost(GameHost host) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/OsuGameDesktop.cs:line 129
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
[runtime] 2022-06-09 00:40:22 [error]: at osu.Desktop.Program.Main(String[] args) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/Program.cs:line 105
[runtime] 2022-06-09 00:40:22 [verbose]: Unhandled exception has been denied .
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'SDL_SetWindowMouseRect' in shared library 'SDL2'.
   at SDL2.SDL.SDL_SetWindowMouseRect(IntPtr window, IntPtr rect)
   at osu.Framework.Platform.SDL2DesktopWindow.<>c__DisplayClass89_0.<updateCursorConfinement>b__1()
   at osu.Framework.Threading.Scheduler.Add(Action task, Boolean forceScheduled)
   at osu.Framework.Platform.SDL2DesktopWindow.ScheduleCommand(Action action)
   at osu.Framework.Platform.SDL2DesktopWindow.updateCursorConfinement()
   at osu.Framework.Platform.SDL2DesktopWindow.<.ctor>b__126_0(ValueChangedEvent`1 evt)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Framework.Platform.SDL2DesktopWindow.set_CursorState(CursorState value)
   at osu.Desktop.OsuGameDesktop.SetHost(GameHost host) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/OsuGameDesktop.cs:line 129
   at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/Program.cs:line 105

Process finished with exit code 134.

```

**Comment by bdach** [comment]
First of all, from the log attached I assume you're building from source, correct?

Secondly, please run the game with `LD_DEBUG=libs` and attach the output to this issue as a file (will be long).

I think it's likely that the failure is caused by your system having an incompatible (too old) glibc version, but I can't confirm without the above information.

**Comment by Itzbenz** [comment]
[795c9fc without libsdl2-dev.txt](https://github.com/ppy/osu/files/8867527/795c9fc.without.libsdl2-dev.txt)
[795c9fc with libsdl2-dev.txt](https://github.com/ppy/osu/files/8867529/795c9fc.with.libsdl2-dev.txt)

probably libsdl2-dev don't have any effect, but I attach it anyway

also, using release version 2022.528.0 or later would have produce the same error

**Comment by smoogipoo** [comment]
`     12241:	/lib/x86_64-linux-gnu/libm.so.6: error: version lookup error: version `GLIBC_2.29' not found (required by /media/itzbenz/PROJECT/Atomic/osu/osu.Desktop/bin/Debug/net6.0/runtimes/linux-x64/native/libSDL2.so) (fatal)`

Pretty indicative of what's going on. Debian 10 "buster" doesn't support `libc6 2.29`, which is required by our SDL2 (and all SDL2 releases going forward). We recommend upgrading your system and do not upgrade `libc6` as it will likely break your system.

**Comment by bzbk** [comment]
我尝试在RAM架构的Linux上编译OSU！也遇到了这个问题。和楼主一模一样。
我还尝试从源码安装了SDL2，然而并没有任何效果。

操作系统：Linux OrangePi5 5.10.110-rockchip-rk3588 #1.0.0 SMP Fri Dec 2 18:16:11 CST 2022 aarch64 GNU/Linux
