### ISSUE TITLE
Editor doesn't save created maps anywhere Linux 

### ISSUE THREAD

**Issue by LargerManZ** [ppy/osu#18858]
### Type

Game behaviour

### Bug description

I created a map using the editor, I accidentally had it set to taiko when making it, so I created a new difficulty and gave it a name and an audio file and filled out some of the boxes for information, like the artist. I went through and timed it and then placed some circles and then saved it using the save button in the File menu. I then closed it and it asked me if I wanted to save, to which I said yes. (couldn't be too careful) And low and behold. Looking for my song in my songs list, it isn't there. And there is no way to open up other projects in the editor menus so I don't even know if it's in the files whatsoever. 

_(make a way to delete difficulties inside the setup menu pls)_ 

No disclaimer that the beatmap creation is completely dysfunctional or doesn't save maps, so I'm not sure if it just isn't flushed out yet or if this is a linux unique bug or something.

### Version

Lazer 2022.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/8987872/database.log)
[network.log](https://github.com/ppy/osu/files/8987873/network.log)
[performance.log](https://github.com/ppy/osu/files/8987874/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8987875/runtime.log)

**Comment by smoogipoo** [comment]
Do you have the correct ruleset selected in the top-left of the toolbar? And/or perhaps this setting turned off in the top right of song select?:
![image](https://user-images.githubusercontent.com/1329837/175855526-7e81cdf1-718f-432a-8e3a-654c12920f61.png)

**Comment by LargerManZ** [comment]
yes I do have [show converted] on, and the song I made doesn't show up regardless of the gamemode I have it set to.

**Comment by peppy** [comment]
From your logs:

```csharp
2022-06-26 23:54:01 [error]: Camellia · Nanahira - Artificial Intelligence (BreadKnightRG) already has a difficulty with the name of 'Automaton'.
2022-06-26 23:54:01 [error]: System.InvalidOperationException: Camellia · Nanahira - Artificial Intelligence (BreadKnightRG) already has a difficulty with the name of 'Automaton'.
2022-06-26 23:54:01 [error]: at osu.Game.Beatmaps.BeatmapManager.Save(BeatmapInfo beatmapInfo, IBeatmap beatmapContent, ISkin beatmapSkin) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Beatmaps/BeatmapManager.cs:line 307
2022-06-26 23:54:01 [error]: at osu.Game.Screens.Edit.Editor.Save() in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Screens/Edit/Editor.cs:line 369
2022-06-26 23:54:01 [verbose]: ⚠️ Camellia · Nanahira - Artificial Intelligence (BreadKnightRG) already has a difficulty with the name of 'Automaton'.
```

Note that this should have also shown up as a notification, did you dismiss is?

**Comment by LargerManZ** [comment]
yes, and I read it so I saved it as something else afterwards. I gave the difficulty a different name. I named it Auto-MAGIC!!.

**Comment by peppy** [comment]
Please attach your `client.db`.

**Comment by LargerManZ** [comment]
I don't have one in my folder, I searched by that file name.

**Comment by peppy** [comment]
`client.realm`, sorry.

**Comment by LargerManZ** [comment]
Github doesn't support that file type how do I go about this
