### ISSUE TITLE
Playlist submit fails on partial Classic customization

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18950]
Extracted from `runtime.log`:

```csharp
2022-06-28 03:03:49 [error]: An unhandled error has occurred.
2022-06-28 03:03:49 [error]: System.InvalidCastException: Null object cannot be converted to a value type.
2022-06-28 03:03:49 [error]: at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
2022-06-28 03:03:49 [error]: at osu.Framework.Bindables.Bindable`1.Parse(Object input)
2022-06-28 03:03:49 [error]: at osu.Game.Online.API.APIMod.ToMod(Ruleset ruleset)
2022-06-28 03:03:49 [error]: at osu.Game.Screens.OnlinePlay.Match.RoomSubScreen.<>c__DisplayClass53_0.<UpdateMods>b__0(APIMod m)
2022-06-28 03:03:49 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
2022-06-28 03:03:49 [error]: at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
2022-06-28 03:03:49 [error]: at System.Linq.Enumerable.ConcatIterator`1.ToList()
2022-06-28 03:03:49 [error]: at osu.Game.Screens.OnlinePlay.Match.RoomSubScreen.UpdateMods()

```

### Discussed in https://github.com/ppy/osu/discussions/18946

<div type='discussions-op-text'>

<sup>Originally posted by **itotallygetthat** June 30, 2022</sup>
[database.log](https://github.com/ppy/osu/files/9015688/database.log)
[network.log](https://github.com/ppy/osu/files/9015689/network.log)
[performance.log](https://github.com/ppy/osu/files/9015690/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9015691/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9015692/updater.log)

Logs from early Tuesday UTC on version 2022.621.0 , but the same issue appears to still exist in 2022.630.0

On the Playlist edit screen:
When hitting "Create", the client lags for a few seconds then crashes.    The playlist submits corrupted (name, length, time, duration are correct, but no maps are returned).

This error only seems to occur if you have the Custom mod enabled AND some of the options are toggled off.   

I can't submit any more playlists for now due to max 5 open playlists per account to test more combinations of Classic customization toggles.  Here's what I found so far:
"No slider head movement" = True, the other 3 options = False. => crash
All 4 options = True => no crash

I successfully submitted a playlist with partial Classic on 2022-06-20, so something seemed to change since version 2022.615.  (Or maybe something on the backend doesn't like the partial customization?)</div>

**Comment by smoogipoo** [comment]
Seems like this should be a server-side issue. Those mod values are being serialized as `false` but are arriving back to the client as `null`. Seems also like this is only happening on prod and not dev, but I'm not sure which one/whether both are using the osu-tools output.

**Comment by peppy** [comment]
I think they both should be, but they wouldn't have been updated since the dropping of slider head movement. Would an update there be enough to fix this issue?

**Comment by smoogipoo** [comment]
I don't know/don't think so. The members haven't changed, only one was removed, so everything should still work as normal.

**Comment by nanaya** [comment]
I don't have the tools installed yet 😄 unless I get pinged every time mod is updated, it's faster to have anyone who update (or reviewed/etc) the mod to make the new json and pr to osu-web

**Comment by smoogipoo** [comment]
Again, not sure if this will fix anything, but here's the updated `mods.json`:
[mods.json.txt](https://github.com/ppy/osu/files/9017584/mods.json.txt)

**Comment by nanaya** [comment]
Looks like there's only removal of `fixed_follow_circle_hit_area` since. Not sure how that'll help here...
