### ISSUE TITLE
Realm restoration happens after game exists in migration tests

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#18952]
### Type

Other

### Bug description

Documenting this one for the time being.

1. After blocking all operations, access is restored via posting to the sync context that runs on the update thread: https://github.com/ppy/osu/blob/e89f220e9acbafe8603c7af744e6f94086b6e8ac/osu.Game/Database/RealmAccess.cs#L891-L903
2. Most of the tests in [`CustomDataDirectoryTest`](https://github.com/ppy/osu/blob/master/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs) cleanup the migration path on exit: https://github.com/ppy/osu/blob/e89f220e9acbafe8603c7af744e6f94086b6e8ac/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs#L298-L302
3. Sometimes, this cleanup happens to occur right as the `Realm.GetInstance()` call is being processed during the restoration: https://github.com/ppy/osu/blob/e89f220e9acbafe8603c7af744e6f94086b6e8ac/osu.Game/Database/RealmAccess.cs#L566-L591

This can be reproed with the following:
```diff
diff --git a/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs b/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
index a803974d30..d864fee3fe 100644
--- a/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
+++ b/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
@@ -13,6 +13,7 @@
 using osu.Framework.Platform;
 using osu.Framework.Testing;
 using osu.Game.Configuration;
+using osu.Game.Database;
 using osu.Game.IO;
 
 namespace osu.Game.Tests.NonVisual
@@ -223,7 +224,6 @@ public void TestMigrationToSameTargetFails()
                     var osu = LoadOsuIntoHost(host);
 
                     Assert.DoesNotThrow(() => osu.Migrate(customPath));
-                    Assert.Throws<ArgumentException>(() => osu.Migrate(customPath));
                 }
                 finally
                 {
diff --git a/osu.Game/Database/RealmAccess.cs b/osu.Game/Database/RealmAccess.cs
index cb34a92702..e7dfd796e0 100644
--- a/osu.Game/Database/RealmAccess.cs
+++ b/osu.Game/Database/RealmAccess.cs
@@ -587,7 +587,15 @@ private Realm getRealmInstance()
 
                 realm_instances_created.Value++;
 
-                return Realm.GetInstance(getConfiguration());
+                try
+                {
+                    return Realm.GetInstance(getConfiguration());
+                }
+                catch
+                {
+                    Environment.FailFast("Storage deleted before realm could finish restoring.");
+                    throw;
+                }
             }
             // Catch can be removed along with entity framework. Is specifically to allow a failure message to arrive to the user (see similar catches in EFToRealmMigrator).
             catch (AggregateException ae) when (RuntimeInfo.OS == RuntimeInfo.Platform.macOS && ae.Flatten().InnerException is TypeInitializationException)
@@ -612,12 +620,18 @@ private RealmConfiguration getConfiguration(string? filename = null)
             if (!Directory.Exists(tempPathLocation))
                 Directory.CreateDirectory(tempPathLocation);
 
-            return new RealmConfiguration(storage.GetFullPath(filename ?? Filename, true))
+            var config = new RealmConfiguration(storage.GetFullPath(filename ?? Filename, true))
             {
                 SchemaVersion = schema_version,
                 MigrationCallback = onMigration,
                 FallbackPipePath = tempPathLocation,
             };
+
+            while (Signal && Directory.Exists(Path.GetDirectoryName(config.DatabasePath)))
+            {
+            }
+
+            return config;
         }
 
         private void onMigration(Migration migration, ulong lastSchemaVersion)
@@ -903,6 +917,8 @@ void restoreOperation()
             }
         }
 
+        public static bool Signal;
+
         // https://github.com/realm/realm-dotnet/blob/32f4ebcc88b3e80a3b254412665340cd9f3bd6b5/Realm/Realm/Extensions/ReflectionExtensions.cs#L46
         private static string getMappedOrOriginalName(MemberInfo member) => member.GetCustomAttribute<MapToAttribute>()?.Mapping ?? member.Name;
 
diff --git a/osu.Game/OsuGameBase.cs b/osu.Game/OsuGameBase.cs
index 57369419d2..6b995015d8 100644
--- a/osu.Game/OsuGameBase.cs
+++ b/osu.Game/OsuGameBase.cs
@@ -461,6 +461,7 @@ public bool Migrate(string path)
             }
             finally
             {
+                RealmAccess.Signal = true;
                 realmBlocker?.Dispose();
             }
         }
```
Run `TestMigrationToSameTargetFails` which will either:
1) Result in the timeouts mentioned above.
2) You should be able to breakpoint inside the catch that was added in `getRealmInstance()` to observe the exception being thrown.

### Version

e89f220e9acbafe8603c7af744e6f94086b6e8ac

### Logs

This manifests in either a crash:
```
  Failed TestMigrationToSeeminglyNestedTarget [2 s]
  Error Message:
   System.IO.FileNotFoundException : Could not find file '/tmp/of-test-headless/custom-path-6bf23224-3c79-45db-81c7-3cdd359b7609/_framework.ini_3724d3d5-318a-462f-9f65-df71c659f888'.
  Stack Trace:
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at osu.Game.IO.MigratableStorage.<>c__DisplayClass7_1.<CopyRecursive>b__0() in /home/runner/work/osu/osu/osu.Game/IO/MigratableStorage.cs:line 104
   at osu.Game.IO.MigratableStorage.AttemptOperation(Action action, Int32 attempts, Boolean throwOnFailure) in /home/runner/work/osu/osu/osu.Game/IO/MigratableStorage.cs:line 128
   at osu.Game.IO.MigratableStorage.CopyRecursive(DirectoryInfo source, DirectoryInfo destination, Boolean topLevelExcludes) in /home/runner/work/osu/osu/osu.Game/IO/MigratableStorage.cs:line 104
   at osu.Game.IO.MigratableStorage.Migrate(Storage newStorage) in /home/runner/work/osu/osu/osu.Game/IO/MigratableStorage.cs:line 61
   at osu.Game.IO.OsuStorage.Migrate(Storage newStorage) in /home/runner/work/osu/osu/osu.Game/IO/OsuStorage.cs:line 130
   at osu.Game.OsuGameBase.Migrate(String path) in /home/runner/work/osu/osu/osu.Game/OsuGameBase.cs:line 457
   at osu.Game.Tests.NonVisual.CustomDataDirectoryTest.TestMigrationToSeeminglyNestedTarget() in /home/runner/work/osu/osu/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs:line 326
```

A test timeout:
```
System.InvalidOperationException : Game stuck in runnning state.

  1)   Expected: <System.ArgumentException>
  But was:  <System.TimeoutException: Attempting to block for migration took too long.
   at osu.Game.OsuGameBase.Migrate(String path) in /opt/buildagent/work/ecd860037212ac52/osu.Game/OsuGameBase.cs:line 455
   at osu.Game.Tests.NonVisual.CustomDataDirectoryTest.<>c__DisplayClass5_1.<TestMigrationToSameTargetFails>b__1() in /opt/buildagent/work/ecd860037212ac52/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs:line 226
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
   at osu.Framework.Platform.GameHost.Dispose(Boolean disposing)
   at osu.Framework.Testing.TestRunHeadlessGameHost.Dispose(Boolean isDisposing)
   at osu.Game.Tests.NonVisual.CustomDataDirectoryTest.CustomTestHeadlessGameHost.Dispose(Boolean isDisposing) in /opt/buildagent/work/ecd860037212ac52/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs:line 375
   at osu.Framework.Platform.GameHost.Dispose()
   at osu.Game.Tests.NonVisual.CustomDataDirectoryTest.TestMigrationToSameTargetFails() in /opt/buildagent/work/ecd860037212ac52/osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs:line 233
```

Or a deadlock, where the update thread has crashed and:
1. `ThreadRunner` attempts to join the thread, waiting the full timeout duration: https://github.com/ppy/osu-framework/blob/e53bbf852b73339ffd40f99d95f857895f860cb1/osu.Framework/Platform/ThreadRunner.cs#L155-L156
2. The unhandled exception handler tries to post a message to the input thread, that has since been joined: https://github.com/ppy/osu-framework/blob/e53bbf852b73339ffd40f99d95f857895f860cb1/osu.Framework/Platform/GameHost.cs#L407, causing another 10s timeout.

**Comment by peppy** [comment]
I'll get to this today.

**Comment by peppy** [comment]
So the real issue here is that the scheduler is still processing post-`host.Exit`, which is considered to be a blocking exit call in those tests. Which I think is completely incorrect.

Moving the cleanup in the tests outside the `finally` seems most logical. Does that align with your expectations?

**Comment by smoogipoo** [comment]
That should be fine I think.

Though I question if `OsuTestScene` could go wrong in a similar case due to its cleanup on dispose, but it's hard to say.

**Comment by peppy** [comment]
The assumption is the restore logic is always on the `SynchronizationContext`, which requires the update thread to be running it. As long as that holds, I think we're okay.

**Comment by smoogipoo** [comment]
To be more clear, the issue occurs when we're recycling storage while the update thread is still running. Which I'm not sure of but probably is also the case with `OsuTestScene` and the cleanup it does.
