### ISSUE TITLE
HR+Auto mod causes osu! to crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#1904]
i tried to select HR + Auto on a map but it crashes. HD etc. are working just fine.

**Comment by aQaTL** [comment]
After a bit of testing it looks like it crashes when you try to play with HR on a map with approach rate  ~9 or higher. It doesn't matter if there's auto mod. 
The top of the exception thrown looks like this: 
```
[runtime:error] fatal error:
[runtime:important] System.ArgumentOutOfRangeException: duration must be positive.
Parameter name: duration
   at osu.Framework.Graphics.TransformableExtensions.PopulateTransform[TValue,TThis](TThis t, Transform`2 transform, TValue newValue, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformableExtensions.cs:line 83
   at osu.Framework.Graphics.TransformableExtensions.MakeTransform[TThis,TValue](TThis t, String propertyOrFieldName, TValue newValue, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformableExtensions.cs:line 63
   at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis,TValue](TThis t, String propertyOrFieldName, TValue newValue, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformableExtensions.cs:line 30
   at osu.Framework.Graphics.TransformableExtensions.ScaleTo[T](T drawable, Vector2 newScale, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformableExtensions.cs:line 272
   at osu.Framework.Graphics.TransformableExtensions.ScaleTo[T](T drawable, Single newScale, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformableExtensions.cs:line 265
   at osu.Framework.Graphics.TransformSequenceExtensions.<>c__DisplayClass13_0`1.<ScaleTo>b__0(T o) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformSequenceExtensions.cs:line 106
   at osu.Framework.Graphics.Transforms.TransformSequence`1.Append(Generator childGenerator) in C:\dev\osu\osu-framework\osu.Framework\Graphics\Transforms\TransformSequence.cs:line 126
   at osu.Framework.Graphics.TransformSequenceExtensions.ScaleTo[T](TransformSequence`1 t, Single newScale, Double duration, Easing easing) in C:\dev\osu\osu-framework\osu.Framework\Graphics\TransformSequenceExtensions.cs:line 106
   at osu.Game.Rulesets.Osu.Objects.Drawables.DrawableSpinner.UpdatePreemptState() in C:\dev\osu\osu.Game.Rulesets.Osu\Objects\Drawables\DrawableSpinner.cs:line 199
   at osu.Game.Rulesets.Osu.Objects.Drawables.DrawableOsuHitObject.UpdateState(ArmedState state) in C:\dev\osu\osu.Game.Rulesets.Osu\Objects\Drawables\DrawableOsuHitObject.cs:line 31
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.<LoadComplete>b__44_0(ArmedState state) in C:\dev\osu\osu.Game\Rulesets\Objects\Drawables\DrawableHitObject.cs:line 119
   at osu.Framework.Configuration.Bindable`1.TriggerValueChange(Boolean propagateToBindings) in C:\dev\osu\osu-framework\osu.Framework\Configuration\Bindable.cs:line 145
   at osu.Framework.Configuration.Bindable`1.TriggerChange() in C:\dev\osu\osu-framework\osu.Framework\Configuration\Bindable.cs:line 139
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.LoadComplete() in C:\dev\osu\osu.Game\Rulesets\Objects\Drawables\DrawableHitObject.cs:line 128
   at osu.Framework.Graphics.Drawable.loadComplete() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Drawable.cs:line 228
   at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Drawable.cs:line 339
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 469
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Game.Rulesets.UI.RulesetInputManager`1.UpdateSubTree() in C:\dev\osu\osu.Game\Rulesets\UI\RulesetInputManager.cs:line 139
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\dev\osu\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 488
   at osu.Framework.Platform.GameHost.UpdateFrame() in C:\dev\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 250
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\dev\osu\osu-framework\osu.Framework\Threading\GameThread.cs:line 115
   at osu.Framework.Threading.GameThread.runWork() in C:\dev\osu\osu-framework\osu.Framework\Threading\GameThread.cs:line 104
```
I don't know the code base very well, but I managed to discover that game crashes when in `ApplyDefaultsToSelf` method in `OsuHitObject` class in line 79 and 80 `TimePreempt` and `TimeFadein` are calculated to < 0. 
I hope this will help.

**Comment by aQaTL** [comment]
So, crash occurs, because there isn't any cap on `BeatmapDifficulty.ApproachRate` and `BeatmapDifficulty.DifficultyRange` will return bad result if the `difficulty` parameter (AR) is outside of <0, 10> range. AR is calculated in `HardRockMode.ApplyToDifficulty`  like that: `difficulty.ApproachRate *= ratio;`. 
So, while adding after that the following line
```
difficulty.ApproachRate = difficulty.ApproachRate > 10 ? 10 : difficulty.ApproachRate;
```
fixes the crash, I think there's yet another problem -> calculating ApproachRate with DT on. So, I couldn't find the place when ApproachRate is affected by DT mod and after checking `OsuHitObject.TimePreempt` and `OsuHitObject.TimeFadein` value with and without DT on -> its the same. IIRC on stable changing DT does changes the AR. 
I wanted to add `ApplyToDifficulty` method to `ModDoubleTime`, but if HR is selected, this method would receive `BeatmapDifficulty` parameter with `ApproachRate` already changed by `ModHardRock`.

**Comment by smoogipoo** [comment]
Fixed by https://github.com/ppy/osu/pull/1916
