### ISSUE TITLE
Osu Instantly Crashes Upon Changing Monitor Configuration

### ISSUE THREAD

**Issue by FlankMaster** [ppy/osu#19064]
### Type

Crash to desktop

### Bug description

I had my game open on another monitor, such that the last monitor refenced in the framework.ini file is "Second" upon closing. After having gone in the windows settings to disable that monitor, it still exists, but is disabled, so the game runs into an exeption and instantly crashes (see log). This can be fixed pretty easily by going into the framework.ini file and changing it back, but should the user not know to do this, the game becomes unplayable.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44759535/178127578-c5121f45-739a-4ac9-b943-5c20a10d589c.png)
![image](https://user-images.githubusercontent.com/44759535/178127595-92d759e3-9317-442b-b84c-7c5d8615f418.png)

### Version

2022.709.1

### Logs

*Note: Some parts of the log are excluded.

2022-07-10 01:09:21 [verbose]: Stored display index (-1) doesn't match current index (1)
2022-07-10 01:09:21 [verbose]: Updated display mode to desktop resolution: 2400x1350@60, SDL_PIXELFORMAT_RGB888

2022-07-10 01:09:22 [verbose]: SDL error log [debug]: Couldn't find display mode match
2022-07-10 01:09:22 [verbose]: Loading VersionManager...
2022-07-10 01:09:22 [error]: An unhandled error has occurred.
2022-07-10 01:09:22 [error]: System.InvalidOperationException: couldn't retrieve valid display mode
2022-07-10 01:09:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.getClosestDisplayMode(Size size, Int32 refreshRate, Int32 displayIndex)
2022-07-10 01:09:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.updateWindowStateAndSize()
2022-07-10 01:09:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.updateWindowSpecifics()
2022-07-10 01:09:22 [error]: at osu.Framework.Platform.SDL2DesktopWindow.Run()
2022-07-10 01:09:22 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
2022-07-10 01:09:22 [error]: at osu.Desktop.Program.Main(String[] args)
2022-07-10 01:09:22 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-07-10 01:09:23 [verbose]: Host execution state changed to Stopping
2022-07-10 01:09:24 [verbose]: Loaded VersionManager!
2022-07-10 01:09:24 [verbose]: Loading OsuLogo...
2022-07-10 01:09:24 [verbose]: Loaded OsuLogo!
2022-07-10 01:09:24 [verbose]: Loading Toolbar...
2022-07-10 01:09:24 [verbose]: Host execution state changed to Stopped
2022-07-10 01:09:24 [verbose]: Loading VolumeOverlay...
2022-07-10 01:09:24 [verbose]: Loading OnScreenDisplay...
2022-07-10 01:09:24 [verbose]: Loading NotificationOverlay...
2022-07-10 01:09:24 [verbose]: Loading CollectionManager...
2022-07-10 01:09:24 [verbose]: Loading LegacyImportManager...
2022-07-10 01:09:24 [verbose]: Loading ScreenshotManager...
2022-07-10 01:09:24 [verbose]: Loading SquirrelUpdateManager...
2022-07-10 01:09:24 [verbose]: Loading FirstRunSetupOverlay...
2022-07-10 01:09:24 [verbose]: Loading ManageCollectionsDialog...
2022-07-10 01:09:24 [verbose]: Loading BeatmapListingOverlay...
2022-07-10 01:09:24 [verbose]: Loading DashboardOverlay...
2022-07-10 01:09:24 [verbose]: Loading NewsOverlay...
2022-07-10 01:09:24 [verbose]: Loading RankingsOverlay...
2022-07-10 01:09:24 [verbose]: Loading ChannelManager...
2022-07-10 01:09:24 [verbose]: Loading ChatOverlay...
2022-07-10 01:09:24 [verbose]: Loading MessageNotifier...
2022-07-10 01:09:24 [verbose]: Loading SettingsOverlay...
2022-07-10 01:09:24 [verbose]: Loading ChangelogOverlay...
2022-07-10 01:09:24 [verbose]: Loading UserProfileOverlay...
2022-07-10 01:09:24 [verbose]: Loading BeatmapSetOverlay...
2022-07-10 01:09:24 [verbose]: Loading WikiOverlay...
2022-07-10 01:09:24 [verbose]: Loading SkinEditorOverlay...
2022-07-10 01:09:24 [verbose]: Loading LoginOverlay...
2022-07-10 01:09:24 [verbose]: Loading NowPlayingOverlay...
2022-07-10 01:09:24 [verbose]: Loading AccountCreationOverlay...
2022-07-10 01:09:24 [verbose]: Loading DialogOverlay...
2022-07-10 01:09:24 [verbose]: Loading HighPerformanceSession...

**Comment by 3stantedja** [comment]
Ran across a similar, if not identical, crash as well on macOS; the logs are provided below:
[osu-crash-2022-07-11.zip](https://github.com/ppy/osu/files/9084908/osu-crash-2022-07-11.zip)

for posterity, here are the two configuration files (`framework.ini` and a redacted `game.ini`) alongside my display setup.
[config.zip](https://github.com/ppy/osu/files/9084981/config.zip)

<img width="780" alt="Screen Shot 2022-07-11 at 08 40 48" src="https://user-images.githubusercontent.com/3055647/178290476-daeb1a32-cbfb-42ac-9666-394af95a3cc7.png">
<img width="780" alt="Screen Shot 2022-07-11 at 08 40 45" src="https://user-images.githubusercontent.com/3055647/178290483-b8f8d354-c2cb-4eec-b076-512b5e0ea697.png">
<img width="780" alt="Screen Shot 2022-07-11 at 08 40 22" src="https://user-images.githubusercontent.com/3055647/178290490-9d5c2ee4-e64e-4144-a049-d00284d166c7.png">
<img width="698" alt="Screen Shot 2022-07-11 at 08 43 01" src="https://user-images.githubusercontent.com/3055647/178290884-b5d9e0d0-d8f3-4db4-b6e1-5abf2d73fee4.png">

(for completeness sake it's a MacBook Pro 16" (2019))

**Comment by Susko3** [comment]
@3stantedja your issue is different. Likely the same as https://github.com/ppy/osu/issues/18983 / https://github.com/ppy/osu-framework/issues/5190.

From your logs:
```
2022-07-11 13:54:43 [verbose]: SDL error log [debug]: Couldn't find the display where the window is attached to.
```

**Comment by FlankMaster** [comment]
It seems we encountered an error with the same root cause via different methods interestingly. After some fiddling around with it I realise it only encounters the crash the person in #18983 describes when it attempts to full screen on a monitor that isn't my "main display" according to windows. If I try to open it again after that crash I get the same result as I'm describing here. Only difference is that I was easily able to play on another monitor fullscreen unitentionally via a Windows profile switcher, which automatically enables my TV in the settings as well as make it my "main display" (I do this to prevent burn in on my OLED panel).

**Comment by Susko3** [comment]
There have been recent changes should fix your issue. Could you try to reproduce the crash again and report back? (Make sure to install the latest version!)
