### ISSUE TITLE
`ObjectDisposedException` when logging out after having entered a playlist screen

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#19494]
Haven't checked how this is handled in other places yet (if at all).

### Discussed in https://github.com/ppy/osu/discussions/19485

<div type='discussions-op-text'>

<sup>Originally posted by **Stedoss** July 31, 2022</sup>
Sorry if the title doesn't make sense, hopefully the repro steps make up for it!

This is really niche, however I noticed this whilst fiddling around with online state. It doesn't really seem to break anything, but I thought I would report it in case it's related to something that _could_ be more nasty.

Reproduction steps:
1) Start osu!
2) Login
3) On the main menu, select `play` then `playlists`
4) Enter any playlist from the lounge (will take you to the `Playlist` screen)
5) On this screen, logout. You will get a notification of `API connection was lost, can't continue with online play`
6) Login again
7) You will be logged back in, however an exception of type `System.ObjectDisposedException` is thrown

Video:
Sorry for the crude censor on the password

https://user-images.githubusercontent.com/29103029/182004237-ce58c209-c788-41eb-b24c-7fe26106438d.mp4

Logs:
[database.log](https://github.com/ppy/osu/files/9227781/database.log)
[updater.log](https://github.com/ppy/osu/files/9227782/updater.log)
[runtime.log](https://github.com/ppy/osu/files/9227783/runtime.log)
[network.log](https://github.com/ppy/osu/files/9227784/network.log)
[performance.log](https://github.com/ppy/osu/files/9227785/performance.log)

Relevent log entry:
```c
2022-07-31 00:03:59 [error]: An unhandled error has occurred.
2022-07-31 00:03:59 [error]: System.ObjectDisposedException: Children cannot be cleared on a disposed drawable.
2022-07-31 00:03:59 [error]: Object name: 'Menu+ItemsFlow'.
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.UserInterface.Menu.Clear()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.setItems(IEnumerable`1 items)
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.set_Items(IEnumerable`1 value)
2022-07-31 00:03:59 [error]: at osu.Game.Screens.OnlinePlay.Playlists.PlaylistsRoomSettingsOverlay.MatchSettings.populateDurations(ValueChangedEvent`1 user)
2022-07-31 00:03:59 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-07-31 00:03:59 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2022-07-31 00:03:59 [error]: at osu.Game.Online.API.APIAccess.<run>b__46_2(APIUser u)
2022-07-31 00:03:59 [error]: at osu.Game.Online.API.APIRequest`1.<.ctor>b__8_0()
2022-07-31 00:03:59 [error]: at osu.Game.Online.API.APIRequest.<TriggerSuccess>b__24_0()
2022-07-31 00:03:59 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-07-31 00:03:59 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 00:03:59 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-07-31 00:03:59 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-07-31 00:03:59 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
```

</div>

**Comment by Stedoss** [comment]
After doing a little more testing on this (not sure if this info is of much use, but it adds to the repro steps above), you do not actually need to logout explicitly on the `Playlist` screen, you just need to have opened it in your login session. The same error will occur if you logout in solo play, for example (error occurs on logout in this case):

https://user-images.githubusercontent.com/29103029/182038314-8cd2dbc0-069e-4d78-9bb2-1b3aba8a8edc.mp4

Logs:
[database.log](https://github.com/ppy/osu/files/9229376/database.log)
[updater.log](https://github.com/ppy/osu/files/9229377/updater.log)
[runtime.log](https://github.com/ppy/osu/files/9229378/runtime.log)
[network.log](https://github.com/ppy/osu/files/9229379/network.log)
[performance.log](https://github.com/ppy/osu/files/9229380/performance.log)
