### ISSUE TITLE
Crash when running `ManiaPlayer` test scene twice

### ISSUE THREAD

**Issue by peppy** [ppy/osu#19641]
```csharp
[runtime] 2022-08-08 07:53:40 [error]: An unhandled error has occurred.
[runtime] 2022-08-08 07:53:40 [error]: System.InvalidOperationException: Cannot invoke BeginPlaying when already playing
[runtime] 2022-08-08 07:53:40 [error]: at osu.Game.Online.Spectator.SpectatorClient.<>c__DisplayClass35_0.<BeginPlaying>b__0() in /Users/dean/Projects/osu/osu.Game/Online/Spectator/SpectatorClient.cs:line 164
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Threading.Scheduler.Update()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
[runtime] 2022-08-08 07:53:40 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

**Comment by Flutterish** [comment]
This also happens for the default players for custom ruleset testing. I think it might just be all test players.
