### ISSUE TITLE
Crash when entering gameplay while typing another character (again)

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#19803]
### Type

Game behaviour

### Bug description

It happened to me a short time ago. Usually, when I start a beatmap with the <kbd>enter</kbd> key, I happen to press another key (in my layout, it's the <kbd>ù</kbd> character). The issue can be reproduced if you start the currently selected beatmap while filtering the carousel trying to show 0 beatmaps (so the game "selects" the `null` beatmap at that exact moment)

### Screenshots or videos

https://user-images.githubusercontent.com/43073074/184869039-9f6130b9-53ed-4202-9cfc-7ddab1f5816c.mp4

### Version

2022.810.2

### Logs

Here's the error inside the logs:
```
2022-08-16 11:25:40 [verbose]: Game-wide working beatmap updated to Kenji Ninuma - DISCO★PRINCE (peppy) [Normal]
2022-08-16 11:25:40 [verbose]: Song select working beatmap updated to Kenji Ninuma - DISCO★PRINCE (peppy) [Normal]
2022-08-16 11:25:40 [verbose]: Song select decided to ensurePlayingSelected
2022-08-16 11:25:41 [verbose]: 📺 OsuScreenStack#425(depth:5) suspended PlaySongSelect#311 (waiting on PlayerLoader#126)
2022-08-16 11:25:41 [verbose]: 📺 OsuScreenStack#425(depth:6) loading PlayerLoader#126
2022-08-16 11:25:41 [verbose]: 📺 OsuScreenStack#425(depth:6) entered PlayerLoader#126
2022-08-16 11:25:41 [verbose]: Song select updating selection with beatmap:null ruleset:osu
2022-08-16 11:25:41 [verbose]: Song select changing beatmap from "Kenji Ninuma - DISCO★PRINCE (peppy) [Normal]" to "null"
2022-08-16 11:25:41 [error]: An unhandled error has occurred.
2022-08-16 11:25:41 [error]: System.InvalidOperationException: Can not set value to "please load a beatmap! - no beatmaps available!" as bindable is disabled.
2022-08-16 11:25:41 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2022-08-16 11:25:41 [error]: at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass94_0.<performUpdateSelected>g__run|0()
2022-08-16 11:25:41 [error]: at osu.Game.Screens.Select.SongSelect.performUpdateSelected()
2022-08-16 11:25:41 [error]: at osu.Game.Screens.Select.BeatmapCarousel.updateYPositions()
2022-08-16 11:25:41 [error]: at osu.Game.Screens.Select.BeatmapCarousel.Update()
2022-08-16 11:25:41 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-08-16 11:25:41 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

**Comment by amadeus4170** [comment]
the name you wrote is not the same as the map therefor it crash.

**Comment by peppy** [comment]
@Gabixel Could you please provide your whole log file? The context before the error occurred may be of use.

**Comment by peppy** [comment]
This has come up in the past and we already guard against this case. I also can't seem to reproduce. Could it be something specific to the way that `ù` character is input? Does it require holding down another modifier key that could be bypassing checks?

**Comment by Gabixel** [comment]
It seems to be just a matter of timing. Because it filters very quickly, you should press the enter key and the character to filter almost simultaneously.
I currently have a lot of beatmaps, so it's hard to find a character that quickly shows zero of them. I might ask if there is a way to temporarily reset the database, but I see that as a risk for now.

Fortunately, however, I found some other characters to show zero maps, so it doesn't seem to be a specific thing with the <kbd>ù</kbd>.

Here's an updated log (where I performed the error a couple of times):
[runtime.log](https://github.com/ppy/osu/files/9358763/runtime.log)

**Comment by peppy** [comment]
I think the next step in addressing this is making a test that can repro this 100%. Hopefully shouldn't be too hard.

**Comment by peppy** [comment]
Tracking via #21120
