### ISSUE TITLE
osu! unable to install correctly

### ISSUE THREAD

**Issue by HaloExpert422** [ppy/osu#19846]
### Type

Other

### Bug description

for the record i'm pretty sure this is a problem with my pc specifically but

anyway, so i tried installing lazer recently, and it wouldn't open - no game window, no setup wizard, nothing - with the exception of the osu!cookie and its little green bar

i thought it might have been because i had remnants of a slightly corrupted version of lazer due to a pc issue, but i deleted the lazer folder, ran the installer again, and the same thing happened

not sure what to do

(also yes the log files have those date markers because of something related to that same pc issue)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/20484272/185519527-d920988f-6183-4e4f-933c-122aa817eefd.png)

### Version

2022.816.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9378463/runtime.log)
[updater (2022_07_16 02_59_29 UTC).log](https://github.com/ppy/osu/files/9378464/updater.2022_07_16.02_59_29.UTC.log)
[performance.log](https://github.com/ppy/osu/files/9378465/performance.log)
[network (2022_07_16 02_59_29 UTC).log](https://github.com/ppy/osu/files/9378466/network.2022_07_16.02_59_29.UTC.log)
[database (2022_07_16 02_59_29 UTC).log](https://github.com/ppy/osu/files/9378468/database.2022_07_16.02_59_29.UTC.log)

**Comment by peppy** [comment]
Relevant excerpt:

```csharp
2022-08-19 00:55:02 [error]: An unhandled error has occurred.
2022-08-19 00:55:02 [error]: System.FormatException: Input string was not in a correct format.
2022-08-19 00:55:02 [error]: at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
2022-08-19 00:55:02 [error]: at osu.Framework.IO.Stores.RawCachingGlyphStore.createCachedPageInfo(Int32 page)
2022-08-19 00:55:02 [error]: at osu.Framework.IO.Stores.RawCachingGlyphStore.LoadCharacter(Character character)
2022-08-19 00:55:02 [error]: at osu.Framework.IO.Stores.GlyphStore.Get(String name)
2022-08-19 00:55:02 [error]: at osu.Framework.IO.Stores.ResourceStore`1.Get(String name)
2022-08-19 00:55:02 [error]: at osu.Framework.Graphics.Textures.TextureStore.get(String name, WrapMode wrapModeS, WrapMode wrapModeT)
2022-08-19 00:55:02 [error]: at osu.Framework.Graphics.Textures.TextureStore.Get(String name, WrapMode wrapModeS, WrapMode wrapModeT)
2022-08-19 00:55:02 [error]: at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character)
2022-08-19 00:55:02 [error]: at osu.Framework.Graphics.Sprites.SpriteText.load(ShaderManager shaders)
```

Not immediately understanding what's going on here..

**Comment by smoogipoo** [comment]
Please take a screenshot of the `%AppData%/osu/cache` folder.

**Comment by HaloExpert422** [comment]
![image](https://user-images.githubusercontent.com/20484272/185761782-d62fbb3f-ce16-4793-8bc2-41060eadb3e4.png)

**Comment by peppy** [comment]
Please show the contents of that `fonts` folder.

**Comment by HaloExpert422** [comment]
![image](https://user-images.githubusercontent.com/20484272/185764017-d45fa30c-5b86-4b82-8be7-ba173f1b010a.png)
![image](https://user-images.githubusercontent.com/20484272/185764034-12a548b3-2f19-4d33-adcc-9f0477ed249c.png)
![image](https://user-images.githubusercontent.com/20484272/185764039-6d777513-4b94-40ae-815d-90ca34327e87.png)

all the files in the fonts folder

**Comment by peppy** [comment]
Thanks. Are you able to delete that folder and see if the game works better?

**Comment by HaloExpert422** [comment]
it worked, thank you!
![osu_2022-08-20_15-46-42](https://user-images.githubusercontent.com/20484272/185765448-f33719e8-f85a-44f1-9db6-aab2c23d8b32.jpg)
