### ISSUE TITLE
First-time setup crashes if case doesn't match between osu!stable's BeatmapDirectory and the actual songs directory

### ISSUE THREAD

**Issue by khang06** [ppy/osu#19996]
### Type

Crash to desktop

### Bug description

A friend ran into this issue when trying to set up lazer because he decided to install his osu!stable beatmaps to another directory, but the directory's case was different between his config and the name of the folder itself, which worked fine on stable because it was on a case-insensitive filesystem. This is a strange and rare scenario, but it shouldn't outright crash the game.

The provided logs are from my reproduction of the issue where my osu!stable user config has `BeatmapDirectory = D:\oSuSoNgS` while the folder itself is at `D:\osusongs`.

```
2022-08-28 04:55:52 [error]: An unhandled error has occurred.
2022-08-28 04:55:52 [error]: System.AggregateException: One or more errors occurred. ("D:\osusongs\1033730 Demetori - Warabe Matsuri ~ Innocent Treasures" does not start with "D:\oSuSoNgS" and is probably malformed)
2022-08-28 04:55:52 [error]: ---> System.ArgumentException: "D:\osusongs\1033730 Demetori - Warabe Matsuri ~ Innocent Treasures" does not start with "D:\oSuSoNgS" and is probably malformed
2022-08-28 04:55:52 [error]: at osu.Framework.Platform.NativeStorage.<>c__DisplayClass9_0.<getRelativePaths>b__0(String path)
2022-08-28 04:55:52 [error]: at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
2022-08-28 04:55:52 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
2022-08-28 04:55:52 [error]: at osu.Game.Database.LegacyBeatmapImporter.GetStableImportPaths(Storage storage)+MoveNext()
2022-08-28 04:55:52 [error]: at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
2022-08-28 04:55:52 [error]: at osu.Game.Database.LegacyModelImporter`1.<>c__DisplayClass5_0.<GetAvailableCount>b__0()
2022-08-28 04:55:52 [error]: at System.Threading.Tasks.Task`1.InnerInvoke()
2022-08-28 04:55:52 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Version

2022.821.0

### Logs

[network.log](https://github.com/ppy/osu/files/9439114/network.log)
[performance.log](https://github.com/ppy/osu/files/9439115/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9439116/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9439117/updater.log)
[database.log](https://github.com/ppy/osu/files/9439118/database.log)

**Comment by bdach** [comment]
Likely fixable by replacing the misguided [framework-side `.StartsWith()` calls](https://github.com/ppy/osu-framework/blob/a961c2ef973c4a887709640d136975b0b981ec16/osu.Framework/Platform/NativeStorage.cs#L62) on paths with [`Path.GetRelativePath()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getrelativepath?view=netstandard-2.1) or similar. Needs testing on multiple platforms, however.

**Comment by peppy** [comment]
I think making the checks ignore case is probably fine. The main goal is to protect against escaping the root path of the parent `Storage`. Actual non-existent directories should throw elsewhere (in the case of actual file sensitive disks).

**Comment by bdach** [comment]
@khang06 I am trying to reproduce this issue to verify the fix linked above but am unable to. Are you able to provide more detailed reproduction steps? A video, perhaps? I'm trying the obvious way but it works just fine here even without the fix.

Exact details of the filesystem in question could possibly also help.

**Comment by khang06** [comment]
Here you go: https://user-images.githubusercontent.com/11239786/187543547-77ec202e-0dc7-4942-9d1f-86f3c1e2251e.mp4

My osu!stable user folder is in my C: drive in the default location. Both C: and D: are NTFS and I'm on Windows 11 22000.856. My friend's crash was from a more convoluted setup in which he replaced his `Songs` folder on stable with a junction to a folder on another drive, but his junction's folder name was `songs` instead of `Songs`, causing a crash because he didn't change `BeatmapDirectory` in his config.

**Comment by bdach** [comment]
Interesting that you got it to trigger via the setup screen, I was trying to do it via the "import beatmaps" button in maintenance settings. Will have another try tomorrow and see what falls out...

**Comment by khang06** [comment]
I tried using that button when trying to reproduce this too. IIRC it looked like it didn't do anything, but it silently throws an exception which should still be in runtime.log
