### ISSUE TITLE
osu!lazer keeps crashing upon opening on my mobile device.

### ISSUE THREAD

**Issue by ranokhui** [ppy/osu#20614]
### Type

Other

### Bug description

I am currently using a Mi 10T Pro. I've updated to the latest version (8/10 in Day/Month). Every time I open the apk, it freezes my device for a bit then crashes.

### Screenshots or videos

https://youtu.be/6S0D-0C86is

### Version

2022.1008.0

### Logs

android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'osu.Game.Database.RealmObjectExtensions' threw an exception. ---> System.TypeInitializationException: The type initializer for 'AutoMapper.Internal.Mappers.StringToEnumMapper' threw an exception. ---> System.ArgumentOutOfRangeException: Cannot find suitable method System.Enum.Parse(2 parameters).
Parameter name: methodName
  at AutoMapper.Internal.TypeExtensions.StaticGenericMethod (System.Type type, System.String methodName, System.Int32 parametersCount) [0x0004e] in <6eb4404bd9b845708371aece5dce0d79>:0 
  at AutoMapper.Internal.Mappers.StringToEnumMapper..cctor () [0x00019] in <6eb4404bd9b845708371aece5dce0d79>:0 
   --- End of inner exception stack trace ---
  at AutoMapper.Internal.Mappers.MapperRegistry.Mappers () [0x00049] in <6eb4404bd9b845708371aece5dce0d79>:0 
  at AutoMapper.MapperConfigurationExpression..ctor () [0x00040] in <6eb4404bd9b845708371aece5dce0d79>:0 
  at AutoMapper.MapperConfiguration.Build (System.Action`1[T] configure) [0x00000] in <6eb4404bd9b845708371aece5dce0d79>:0 
  at AutoMapper.MapperConfiguration..ctor (System.Action`1[T] configure) [0x00000] in <6eb4404bd9b845708371aece5dce0d79>:0 
  at osu.Game.Database.RealmObjectExtensions..cctor () [0x00000] in <94278be4c40c42989a893e545b1d3371>:0 
   --- End of inner exception stack trace ---
  at osu.Game.Skinning.SkinManager..ctor (osu.Framework.Platform.Storage storage, osu.Game.Database.RealmAccess realm, osu.Framework.Platform.GameHost host, osu.Framework.IO.Stores.IResourceStore`1[T] resources, osu.Framework.Audio.AudioManager audio, osu.Framework.Threading.Scheduler scheduler) [0x00012] in <94278be4c40c42989a893e545b1d3371>:0 
  at osu.Game.OsuGameBase.load (osu.Framework.Input.ReadableKeyCombinationProvider keyCombinationProvider) [0x001ae] in <94278be4c40c42989a893e545b1d3371>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <4135fbbd516c4068a1e815a5eac5246f>:0 
--- End of stack trace from previous location where exception was thrown ---

  at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_0.<CreateActivator>b__3 (System.Object target, osu.Framework.Allocation.IReadOnlyDependencyContainer dc) [0x0004c] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00028] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.Activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000b] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyContainer.Inject[T] (T instance) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000d] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00066] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.Load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies, System.Boolean isDirectAsyncContext) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild (osu.Framework.Graphics.Drawable child) [0x00026] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.load (osu.Framework.Graphics.Shaders.ShaderManager shaders, System.Nullable`1[T] cancellation) [0x00086] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <4135fbbd516c4068a1e815a5eac5246f>:0 
--- End of stack trace from previous location where exception was thrown ---

  at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_0.<CreateActivator>b__3 (System.Object target, osu.Framework.Allocation.IReadOnlyDependencyContainer dc) [0x0004c] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00028] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.Activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000b] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyContainer.Inject[T] (T instance) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000d] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00066] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.Load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies, System.Boolean isDirectAsyncContext) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild (osu.Framework.Graphics.Drawable child) [0x00026] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.load (osu.Framework.Graphics.Shaders.ShaderManager shaders, System.Nullable`1[T] cancellation) [0x00086] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <4135fbbd516c4068a1e815a5eac5246f>:0 
--- End of stack trace from previous location where exception was thrown ---

  at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_0.<CreateActivator>b__3 (System.Object target, osu.Framework.Allocation.IReadOnlyDependencyContainer dc) [0x0004c] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00028] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.Activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000b] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyContainer.Inject[T] (T instance) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000d] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00066] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.Load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies, System.Boolean isDirectAsyncContext) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild (osu.Framework.Graphics.Drawable child) [0x00026] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.load (osu.Framework.Graphics.Shaders.ShaderManager shaders, System.Nullable`1[T] cancellation) [0x00086] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <4135fbbd516c4068a1e815a5eac5246f>:0 
--- End of stack trace from previous location where exception was thrown ---

  at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_0.<CreateActivator>b__3 (System.Object target, osu.Framework.Allocation.IReadOnlyDependencyContainer dc) [0x0004c] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00028] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.Activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000b] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyContainer.Inject[T] (T instance) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000d] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00066] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.Load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies, System.Boolean isDirectAsyncContext) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild (osu.Framework.Graphics.Drawable child) [0x00026] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.load (osu.Framework.Graphics.Shaders.ShaderManager shaders, System.Nullable`1[T] cancellation) [0x00086] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <4135fbbd516c4068a1e815a5eac5246f>:0 
--- End of stack trace from previous location where exception was thrown ---

  at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_0.<CreateActivator>b__3 (System.Object target, osu.Framework.Allocation.IReadOnlyDependencyContainer dc) [0x0004c] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00028] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000a] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyActivator.Activate (System.Object obj, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000b] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Allocation.DependencyContainer.Inject[T] (T instance) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00000] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies (osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x0000d] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies) [0x00066] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Graphics.Drawable.Load (osu.Framework.Timing.IFrameBasedClock clock, osu.Framework.Allocation.IReadOnlyDependencyContainer dependencies, System.Boolean isDirectAsyncContext) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Platform.GameHost.bootstrapSceneGraph (osu.Framework.Game game) [0x00063] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Platform.GameHost.Run (osu.Framework.Game game) [0x002c9] in <f99eae368ef5414fb6be4c6d94dc6594>:0 
  at osu.Framework.Android.AndroidGameView.RenderGame () [0x00048] in <e6086f5a35414e4088508fcf21afdae4>:0 
  at osu.Framework.Android.AndroidGameView.OnLoad (System.EventArgs e) [0x0000f] in <e6086f5a35414e4088508fcf21afdae4>:0 
  at osuTK.Android.AndroidGameView.LoadInternal (System.EventArgs e) [0x00000] in <13b732d8d68f4de3bc0d06175609beb8>:0 
  at osuTK.Android.AndroidGameView.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x00052] in <13b732d8d68f4de3bc0d06175609beb8>:0 
  at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceCreated_Landroid_view_SurfaceHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder) [0x0000f] in <d7dd282dbf1f44888afc3f9beaeb06bf>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.14(intptr,intptr,intptr)
	at osutk.android.AndroidGameView.n_surfaceCreated(Native Method)
	at osutk.android.AndroidGameView.surfaceCreated(Unknown Source:0)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:996)
	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:152)
	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2879)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1842)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1052)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1037)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by toadsworth-jr** [comment]
Yeah, this also happened back in https://github.com/ppy/osu/issues/19049
Although the reason for the crash that issue mentioned was due to Mono being weird.
I'm not sure about this one, though.

**Comment by ranokhui** [comment]
Realized I pasted the wrong thing in logs. Here are the log files.
[database.log](https://github.com/ppy/osu/files/9739116/database.log)
[network.log](https://github.com/ppy/osu/files/9739117/network.log)
[performance.log](https://github.com/ppy/osu/files/9739118/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739119/runtime.log)

**Comment by r0xANDt0l** [comment]
Same thing happening to me, using a Realme 8i

**Comment by peppy** [comment]
This will be fixed in a hotfix release soon. You can use the previous release until that drops.

**Comment by chrisstaley** [comment]
@peppy Can you point me in the direction of the change that was made to fix this? I'm running into this exact same issue in my app, but Google says this is the only thing on the interwebs related to this issue. 😉

**Comment by chrisstaley** [comment]
NM. I figured out a workaround. In case others stumble upon this thread, I simply downgraded AutoMapper 12.0 to 11.0.1 and the "Cannot find suitable method System.Enum.Parse(2 parameters)" error stopped happening on Android.

**Comment by peppy** [comment]
Yeah sorry about that. We did just revert the update for now and have not investigated further.
