### ISSUE TITLE
Exception thrown while playing a beatmap

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2068]
Exact things I did before (may not actually reproduce):
- Build latest code
- Reset FPS Limiter to default, then set to unlimited
- Selected mod Hidden
- Ran beatmap, increased blur to 100% (from 0)
- Restarted before beatmap began, and set blur to 0 (from 100%)
- Restarted once more, and set dim to 0 (from 100%) and blur to 100% (from 0)
- Final restart, where dim set to 100% (from 0), and blur to 0 (from 100%)
- Played map, failed
- Restarted, failed again
- Changed map, and once more failed
- Attempted another restart, suddenly..

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at osu.Framework.Graphics.Lines.PathDrawNode.updateVertexBuffer() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Lines\PathDrawNode.cs:line 183
   at osu.Framework.Graphics.Lines.PathDrawNode.Draw(Action`1 vertexAction) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Lines\PathDrawNode.cs:line 203
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 226
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.drawChildren(Action`1 vertexAction, Vector2 frameBufferSize) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Containers\BufferedContainerDrawNode.cs:line 109
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.Draw(Action`1 vertexAction) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Containers\BufferedContainerDrawNode.cs:line 183
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 226
   at osu.Framework.Platform.GameHost.DrawFrame() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Platform\GameHost.cs:line 287
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Threading\GameThread.cs:line 127
   at osu.Framework.Threading.GameThread.runWork() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Threading\GameThread.cs:line 106
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass74_0.<exceptionHandler>b__0() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Platform\GameHost.cs:line 192
   at osu.Framework.Threading.Scheduler.Update() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Threading\Scheduler.cs:line 148
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Threading\GameThread.cs:line 124
   at osu.Framework.Threading.InputThread.RunUpdate() in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Threading\InputThread.cs:line 23
   at osu.Framework.Platform.GameHost.<Run>b__89_1(Object <p0>, FrameEventArgs <p1>) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Platform\GameHost.cs:line 372
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu-framework\osu.Framework\Platform\GameHost.cs:line 382
   at osu.Desktop.Program.Main(String[] args) in C:\Users\arizv\Documents\GitKraken\Frontear\osuKyzer\osu.Desktop\Program.cs:line 43
```

**Comment by peppy** [comment]
Fixed by https://github.com/ppy/osu-framework/pull/1392.
