### ISSUE TITLE
Something is wrong with `DrawableJudgement` pooling

### ISSUE THREAD

**Issue by peppy** [ppy/osu#20737]
Yesterday I ran into a full game crash with the following:

```csharp
[runtime] 2022-10-12 04:49:54 [verbose]: Unhandled exception has been denied .
Unhandled exception. System.ObjectDisposedException: Disposed Drawables may never be in the scene graph.
Object name: 'ArgonJudgementPiece'.
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

I did some preliminary investigation but haven't come up with anything yet.

**Comment by bdach** [comment]
Difficult to tell from the OP, but is there a chance that replay rewind was involved in this? Asking because if it is, then this may be #11980 or an adjacent issue.

**Comment by peppy** [comment]
> Difficult to tell from the OP, but is there a chance that replay rewind was involved in this? Asking because if it is, then this may be #11980 or an adjacent issue.

Yes, it is only an issue during rewind.
