### ISSUE TITLE
Game crashing after map loaded from the editor.

### ISSUE THREAD

**Issue by BlestLace** [ppy/osu#20762]
### Type

Crash to desktop

### Bug description

I was using osu! **without an internet connection** and wanted to play some maps, I got to the song selector and loaded a map, but **it was taking a lot of time**, so I canceled the map and reloaded another one.

The same thing happened, so I loaded another map in the editor to see if there was something wrong, but there wasn't. So I played the map from the editor this time, everything was going well, but after 3/4 seconds of playing, **the game froze**, but the audio was still playing.

5 seconds later **the screen went black**, but the audio was still playing. 10 seconds after that, **the audio stopped playing**, and the usual _"osu!lazer has stopped working."_ popped up, but I was waiting, then **the game played audio again**, but the screen was still black. 

**The game crashed** after like **3 seconds**.

This stopped happening after I wrote this and I still don't know what caused this reactive behavior.

### Screenshots or videos

I don't have any photos/videos that show this in action.

### Version

osu! 2022.1008.2-lazer

### Logs

I'm going to send them all, but I found that runtime is most interesting...

[database.log](https://github.com/ppy/osu/files/9785324/database.log)
[input.log](https://github.com/ppy/osu/files/9785326/input.log)
[network.log](https://github.com/ppy/osu/files/9785327/network.log)
[performance.log](https://github.com/ppy/osu/files/9785328/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9785329/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9785330/updater.log)

**Comment by bdach** [comment]
This one is a bit of a trainwreck:

```
2022-10-14 10:11:57 [verbose]: 📺 OsuScreenStack#449(depth:8) suspended EditorPlayerLoader#590 (waiting on EditorPlayer#630)
2022-10-14 10:11:57 [verbose]: 📺 OsuScreenStack#449(depth:9) entered EditorPlayer#630
2022-10-14 10:11:57 [verbose]: GameplayClockContainer seeking to 0
2022-10-14 10:12:00 [verbose]: Current channel changed to BanchoBot
2022-10-14 10:12:00 [verbose]: Score submission token retrieved (52874322)
2022-10-14 10:12:00 [error]: An unhandled error has occurred.
2022-10-14 10:12:00 [error]: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
2022-10-14 10:12:00 [error]: at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
2022-10-14 10:12:00 [error]: at osu.Game.Screens.Play.SubmittingPlayer.<>c__DisplayClass12_0.<handleTokenRetrieval>b__1(APIScoreToken r)
2022-10-14 10:12:00 [error]: at osu.Game.Online.API.APIRequest`1.<.ctor>b__8_0()
2022-10-14 10:12:00 [error]: at osu.Game.Online.API.APIRequest.<TriggerSuccess>b__24_0()
2022-10-14 10:12:00 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-10-14 10:12:00 [error]: at osu.Framework.Threading.Scheduler.Update()
```

I'm not sure how this can happen. It can't be the editor player trying to submit. It [inherits from `Player`](https://github.com/ppy/osu/blob/b72c117333c3efe0ff6150fa0c2774ed33448ff7/osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs#L14) rather than [`SubmittingPlayer`](https://github.com/ppy/osu/blob/b72c117333c3efe0ff6150fa0c2774ed33448ff7/osu.Game/Screens/Play/SubmittingPlayer.cs)

Network log shows that internet connectivity was restored just moments before:

```
2022-10-14 10:11:59 [verbose]: osu.Game.Online.API.Requests.GetUserRequest finished with response size of 5,618 bytes
2022-10-14 10:11:59 [verbose]: Performing request osu.Game.Online.API.Requests.GetFriendsRequest
2022-10-14 10:11:59 [verbose]: Performing request osu.Game.Online.API.Requests.GetSeasonalBackgroundsRequest
2022-10-14 10:11:59 [verbose]: OnlineMultiplayerClient connecting...
2022-10-14 10:11:59 [verbose]: SpectatorClient connecting...
2022-10-14 10:11:59 [verbose]: OnlineMetadataClient connecting...
2022-10-14 10:11:59 [verbose]: Request to https://osu.ppy.sh/api/v2/friends successfully completed!
```

So a queued failing request that finally executed when connectivity came back, but then failed because the submission completion source was already cancelled, perhaps?

**Comment by frenzibyte** [comment]
That sounds like the score submission request is coming from the previous player session that OP initiated before opening editor, which set a result for the task due to waiting forever without response from the API request:
```
022-10-14 10:09:52 [verbose]: Score submission token retrieval failed (Token retrieval timed out (request never run))
```

https://github.com/ppy/osu/blob/65369e96ebf1ee90e5a74dba974a79824b8e54f3/osu.Game/Screens/Play/SubmittingPlayer.cs#L87-L89

https://github.com/ppy/osu/blob/65369e96ebf1ee90e5a74dba974a79824b8e54f3/osu.Game/Screens/Play/SubmittingPlayer.cs#L93-L98

But then actually succeed once internet connection returns despite the user already having exited gameplay, due to the API request callbacks keeping the `SubmittingPlayer` instance existing until the request is processed and removed from the queue (as far as my knowledge goes).

I think cancelling the API request during the task timeout makes sense the most here, since it's not required anymore and likely to not return any helpful information if it didn't already within the past minute.
