### ISSUE TITLE
Lazer tournament client could only support maxinum 64 teams.

### ISSUE THREAD

**Issue by RushFTK** [ppy/osu#20781]
### Type

Other

### Bug description

We are preparing the qualifier result showcase tomorrow but suddenly noticed that there are 64 teams caps for each map.
How to set it longer or this might a bug?

### Screenshots or videos

![image](https://user-images.githubusercontent.com/20500319/196034676-c50f564b-3994-4736-b40c-fde719f7e585.png)
sub-maps could only setted / displayed as maxinum 64 seeds. while source data needs more.
![image](https://user-images.githubusercontent.com/20500319/196034720-fed24eaa-2ed5-46d9-9d3b-e2437af19a44.png)
in this example is about 90

### Version

2022.911.0-lazer

### Logs

*this is functional issue so needn't log i guess*

**Comment by peppy** [comment]
How high do you require it to be?

It was limited to allow the slider bar in the editor UI to be easier to adjust, but we can easily set it higher.

Also, so I can provide you a temporary build which fixes the issue, can you let me know which OS you are running on?

**Comment by RushFTK** [comment]
maximum 256 for individual matches I guess? IDK if `osu!` mode tournament needs a larger number.
Most large tournament usually uses the script to output results,  and directly edit `bracket.json` to import into `osu!lazer` tournament client. so hiding the slider if we have seeds larger than 64 is ok.

our OS is Windows 10 64bit.

**Comment by peppy** [comment]
Can you try extracting these into your lazer folder (the one with `osu!.exe`), overwriting existing files?

[large-seed-size.zip](https://github.com/ppy/osu/files/9794480/large-seed-size.zip)

I'll look at applying a better fix in the next release. You can revert to the latest release at any point by running the installer again (it will remove the files above).

**Comment by RushFTK** [comment]
ok thx very much and thx for timely feedback <3

**Comment by RushFTK** [comment]
![C 80QRGJ3I@IVO%KF%R1I00](https://user-images.githubusercontent.com/20500319/196036025-995577da-0b91-46c4-9676-fcbb8cea12a8.png)
hmmm, i will make a rollback and check reason

**Comment by peppy** [comment]
Hopefully there aren't any more I missed:

[osu.Framework.dll.zip](https://github.com/ppy/osu/files/9794509/osu.Framework.dll.zip)

**Comment by RushFTK** [comment]
ok.... now i could join the game but a bug rasied when i join in, i could confirm everythings works fine before relacing file
![image](https://user-images.githubusercontent.com/20500319/196036402-ee3bc93c-0c35-4819-b15c-a5c40c315074.png)
i checked log, i think these part may useful:
````
...
2022-10-16 12:51:16 [error]: Could not load ruleset osu.Game.Rulesets.Catch, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'CatchFlashlight' from assembly 'osu.Game.Rulesets.Catch, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'CatchFlashlight' from assembly 'osu.Game.Rulesets.Catch, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu.Game.Rulesets.Mania, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'ManiaFlashlight' from assembly 'osu.Game.Rulesets.Mania, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'ManiaFlashlight' from assembly 'osu.Game.Rulesets.Mania, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu.Game.Rulesets.Osu, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'OsuFlashlight' from assembly 'osu.Game.Rulesets.Osu, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'OsuFlashlight' from assembly 'osu.Game.Rulesets.Osu, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu.Game.Rulesets.Taiko, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'TaikoFlashlight' from assembly 'osu.Game.Rulesets.Taiko, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'TaikoFlashlight' from assembly 'osu.Game.Rulesets.Taiko, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu!. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'OsuFlashlight' from assembly 'osu.Game.Rulesets.Osu, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.<prepareDetachedRulesets>b__4_0(Realm realm)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'OsuFlashlight' from assembly 'osu.Game.Rulesets.Osu, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu!taiko. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'TaikoFlashlight' from assembly 'osu.Game.Rulesets.Taiko, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.<prepareDetachedRulesets>b__4_0(Realm realm)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'TaikoFlashlight' from assembly 'osu.Game.Rulesets.Taiko, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu!catch. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'CatchFlashlight' from assembly 'osu.Game.Rulesets.Catch, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.<prepareDetachedRulesets>b__4_0(Realm realm)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'CatchFlashlight' from assembly 'osu.Game.Rulesets.Catch, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [error]: Could not load ruleset osu!mania. Please check for an update from the developer.
2022-10-16 12:51:16 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2022-10-16 12:51:16 [verbose]: Method 'UpdateFlashlightSize' in type 'ManiaFlashlight' from assembly 'osu.Game.Rulesets.Mania, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2022-10-16 12:51:16 [verbose]: at System.Reflection.Assembly.GetTypes()
2022-10-16 12:51:16 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.<prepareDetachedRulesets>b__4_0(Realm realm)
2022-10-16 12:51:16 [verbose]: System.TypeLoadException: Method 'UpdateFlashlightSize' in type 'ManiaFlashlight' from assembly 'osu.Game.Rulesets.Mania, Version=2022.1008.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2022-10-16 12:51:16 [verbose]: Opened realm "C:\Users\FTK\AppData\Roaming\osu\client.realm" at version 25
2022-10-16 12:51:16 [verbose]: Using tournament storage: C:\Users\FTK\AppData\Roaming\osu\tournaments\GBC 2022 Autumn\
2022-10-16 12:51:17 [verbose]: Updated display mode to desktop resolution: 1920x1080@60, SDL_PIXELFORMAT_RGB888
2022-10-16 12:51:21 [verbose]: Inhibiting bracket save as bracket parsing failed
2022-10-16 12:51:21 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_DXVA2 for codec h264
2022-10-16 12:51:21 [verbose]: Successfully initialized decoder: h264
2022-10-16 12:51:22 [verbose]: Requesting catch-up from 7056847
2022-10-16 12:51:22 [verbose]: Requesting any changes since last known queue id 7056847
2022-10-16 12:51:22 [verbose]: Requesting catch-up from 7056858
2022-10-16 12:51:22 [verbose]: Requesting any changes since last known queue id 7056858
2022-10-16 12:51:23 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_DXVA2 for codec h264
2022-10-16 12:51:23 [verbose]: Successfully initialized decoder: h264
2022-10-16 12:51:23 [verbose]: Catch-up complete at 7056858
2022-10-16 12:51:23 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_DXVA2 for codec h264
2022-10-16 12:51:23 [verbose]: Successfully initialized decoder: h264
2022-10-16 12:51:24 [verbose]: Successfully opened hardware video decoder context AV_HWDEVICE_TYPE_DXVA2 for codec h264
2022-10-16 12:51:24 [verbose]: Successfully initialized decoder: h264
2022-10-16 12:51:24 [error]: An unhandled error has occurred.
2022-10-16 12:51:24 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-10-16 12:51:24 [error]: at osu.Game.Tournament.Components.SongBar.update()
2022-10-16 12:51:24 [error]: at osu.Game.Tournament.Components.SongBar.set_Beatmap(TournamentBeatmap value)
2022-10-16 12:51:24 [error]: at osu.Game.Tournament.Screens.BeatmapInfoScreen.beatmapChanged(ValueChangedEvent`1 beatmap)
2022-10-16 12:51:24 [error]: at osu.Game.Tournament.Screens.BeatmapInfoScreen.load(MatchIPCInfo ipc)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.set_InternalChildrenEnumerable(IEnumerable`1 value)
2022-10-16 12:51:24 [error]: at osu.Game.Tournament.TournamentSceneManager.load()
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__3(Object target, IReadOnlyDependencyContainer dc)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyActivator.Activate(Object obj, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_0`1.<LoadComponentsAsync>b__1()
2022-10-16 12:51:24 [error]: at System.Threading.Tasks.Task.InnerInvoke()
2022-10-16 12:51:24 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-10-16 12:51:24 [error]: --- End of stack trace from previous location ---
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_2`1.<LoadComponentsAsync>b__4()
2022-10-16 12:51:24 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-10-16 12:51:24 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-10-16 12:51:24 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-10-16 12:51:24 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-10-16 12:51:24 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-10-16 12:51:31 [verbose]: Host execution state changed to Stopping
2022-10-16 12:51:31 [verbose]: Host execution state changed to Stopped
````

**Comment by peppy** [comment]
Here's all files:

https://drive.google.com/file/d/1H2ohfz8aEIJcnxcnsZmpQxciLqP_8H36/view?usp=sharing

**Comment by RushFTK** [comment]
A good things is it running correctly now.
but bad things is individual maps seed still have 64 caps
![image](https://user-images.githubusercontent.com/20500319/196037100-c52a756d-714e-4f35-b163-f09e3dd974d4.png)
![image](https://user-images.githubusercontent.com/20500319/196037122-7df5c72b-3a22-4f40-8700-12b52ff10fc0.png)

**Comment by RushFTK** [comment]
this is my bad that haven't say this things correctly, each invidual maps's seed caps are also need a maxinum of 256, sorry for trouble.

**Comment by peppy** [comment]
Oops, this should fix the remaining issue:

[osu.Game.Tournament.dll.zip](https://github.com/ppy/osu/files/9794717/osu.Game.Tournament.dll.zip)

**Comment by RushFTK** [comment]
![image](https://user-images.githubusercontent.com/20500319/196039372-4baccc41-bcf7-47fd-abdb-8d5219186bdb.png)
ok it worked now

**Comment by RushFTK** [comment]
This modified lazer version works fine on [actual qualifier showcase](https://b23.tv/SsYa1Dt), thx for help again
