### ISSUE TITLE
install.exe not working

### ISSUE THREAD

**Issue by f1refa11** [ppy/osu#20868]
### Type

Other

### Bug description

After running the install.exe, the error appears.
Setup encountered fatal error: One or more errors occurred.
(Invalid URI: The hostname could not be parsed.)
There may be more detailed information in %localappdata%\SquirrelClowdTemp\Squirrel.log

### Screenshots or videos

![squ3A6B tmp_89GhTVIqfS](https://user-images.githubusercontent.com/58619409/197358283-308e29fe-b356-4167-a273-37e714127892.png)

### Version

2022.1022.0

### Logs
```
2022-06-01 07:45:09.9512 [INFO] - Program: Starting Squirrel Updater: --setup C:\Users\firef\AppData\Local\Temp\squCC48.tmp.nupkg
2022-06-01 07:45:10.0322 [INFO] - Program: Extracting bundled app data from 'C:\Users\firef\AppData\Local\Temp\squCC48.tmp.nupkg'.
2022-06-01 07:45:10.2666 [INFO] - User32SplashWindow: Image dpi is 95,9866, screen dpi is 96. Rendering image at [896,456,128,128]
2022-06-01 07:45:10.2666 [INFO] - User32SplashWindow: There were 1 frames detected in the splash image (it's not animated).
2022-06-01 07:45:10.2735 [INFO] - Program: Starting package install from directory C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-06-01 07:45:10.7581 [INFO] - Program: Starting install, writing to C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-06-01 07:45:10.7857 [INFO] - Program: About to install to: C:\Users\firef\AppData\Local\osulazer
2022-06-01 07:45:10.8184 [INFO] - SimpleFileSource: Reading RELEASES from 'C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa\RELEASES'
2022-06-01 07:45:10.8184 [INFO] - UpdateManager: First run, starting from scratch
2022-06-01 07:45:11.2752 [INFO] - ApplyReleasesImpl: Writing files to app directory: C:\Users\firef\AppData\Local\osulazer\app-2022.528.0
2022-06-01 07:45:11.6263 [INFO] - LogHost: Rigging execution stub for createdump_ExecutionStub.exe to C:\Users\firef\AppData\Local\osulazer\createdump.exe
2022-06-01 07:45:12.1389 [INFO] - LogHost: Rigging execution stub for osu!_ExecutionStub.exe to C:\Users\firef\AppData\Local\osulazer\osu!.exe
2022-06-01 07:45:14.1653 [INFO] - ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\firef\AppData\Local\osulazer\app-2022.528.0\osu!.exe]
2022-06-01 07:45:15.1029 [INFO] - ApplyReleasesImpl: Starting fixPinnedExecutables
2022-06-01 07:45:15.1414 [INFO] - ApplyReleasesImpl: cleanDeadVersions: checking for version 2022.528.0
2022-06-01 07:45:15.1414 [INFO] - ApplyReleasesImpl: cleanDeadVersions: exclude new version folder app-2022.528.0
2022-06-01 07:45:15.5334 [INFO] - InstallHelperImpl: Writing uninstaller registry entry
2022-06-01 07:45:15.5334 [INFO] - InstallHelperImpl: File 'C:\Users\firef\AppData\Local\osulazer\app.ico' is being used for uninstall icon.
2022-06-01 07:45:15.5802 [INFO] - Program: Finished Squirrel Updater
2022-06-01 14:19:41.2041 [INFO] - Program: Starting Squirrel Updater: --uninstall
2022-06-01 14:19:41.2688 [INFO] - Program: Starting uninstall for app: 
2022-06-01 14:19:41.3836 [INFO] - ApplyReleasesImpl: Starting full uninstall
2022-06-01 14:19:42.2538 [WARN] - Utility: Unable to delete child 'C:\Users\firef\AppData\Local\osulazer': System.UnauthorizedAccessException: Access to the path 'Update.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String , WIN32_FIND_DATA& , Boolean )
   at System.IO.FileSystem.RemoveDirectory(String , Boolean )
   at System.IO.Directory.Delete(String , Boolean )
   at Squirrel.Utility.<>c__DisplayClass31_0.<DeleteFsiVeryHard>b__0() in ./Internal/Utility.cs:line 487
   at Squirrel.Utility.<>c__DisplayClass31_0.<DeleteFsiVeryHard>b__2() in ./Internal/Utility.cs:line 499
   at Squirrel.Utility.<>c__DisplayClass11_0.<Retry>b__0() in ./Internal/Utility.cs:line 152
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries, Int32 retryDelay) in ./Internal/Utility.cs:line 164
   at Squirrel.Utility.DeleteFsiVeryHard(FileSystemInfo fileSystemInfo) in ./Internal/Utility.cs:line 504
2022-06-01 14:19:42.2538 [ERROR] - Utility: Unable to delete 'C:\Users\firef\AppData\Local\osulazer': System.UnauthorizedAccessException: Access to the path 'Update.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String , WIN32_FIND_DATA& , Boolean )
   at System.IO.FileSystem.RemoveDirectory(String , Boolean )
   at System.IO.Directory.Delete(String , Boolean )
   at Squirrel.Utility.<>c__DisplayClass31_0.<DeleteFsiVeryHard>b__0() in ./Internal/Utility.cs:line 487
   at Squirrel.Utility.<>c__DisplayClass31_0.<DeleteFsiVeryHard>b__2() in ./Internal/Utility.cs:line 499
   at Squirrel.Utility.<>c__DisplayClass11_0.<Retry>b__0() in ./Internal/Utility.cs:line 152
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries, Int32 retryDelay) in ./Internal/Utility.cs:line 164
   at Squirrel.Utility.DeleteFsiVeryHard(FileSystemInfo fileSystemInfo) in ./Internal/Utility.cs:line 504
   at Squirrel.Utility.DeleteFsiTree(FileSystemInfo fileSystemInfo) in ./Internal/Utility.cs:line 472
   at Squirrel.Utility.DeleteFileOrDirectoryHard(String path, Boolean throwOnFailure) in ./Internal/Utility.cs:line 436
2022-06-01 14:19:42.2682 [INFO] - Program: Finished Squirrel Updater
2022-10-22 22:00:20.7918 [INFO] - Program: Starting Squirrel Updater: --setup C:\Users\firef\AppData\Local\Temp\squ3A6C.tmp.nupkg
2022-10-22 22:00:20.8742 [INFO] - Program: Extracting bundled app data from 'C:\Users\firef\AppData\Local\Temp\squ3A6C.tmp.nupkg'.
2022-10-22 22:00:21.1115 [INFO] - User32SplashWindow: Image dpi is 95,9866, screen dpi is 96. Rendering image at [896,456,128,128]
2022-10-22 22:00:21.1115 [INFO] - User32SplashWindow: There were 1 frames detected in the splash image (it's not animated).
2022-10-22 22:00:21.1115 [INFO] - Program: Starting package install from directory C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-10-22 22:00:21.7470 [INFO] - Program: Starting install, writing to C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-10-22 22:00:21.8579 [INFO] - Program: About to install to: C:\Users\firef\AppData\Local\osulazer
2022-10-22 22:00:21.8579 [WARN] - Program: Install path C:\Users\firef\AppData\Local\osulazer already exists, burning it to the ground
2022-10-22 22:00:22.4272 [FATAL] - Program: Encountered fatal unhandled exception.: System.AggregateException: One or more errors occurred. (Invalid URI: The hostname could not be parsed.)
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String , Boolean , UriKind , UriCreationOptions& )
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Squirrel.Utility.NormalizePath(String path) in ./Internal/Utility.cs:line 82
   at Squirrel.Utility.IsFileInDirectory(String file, String directory) in ./Internal/Utility.cs:line 89
   at Squirrel.UpdateManager.InstallHelperImpl.<>c__DisplayClass5_0.<KillAllProcessesBelongingToPackage>b__0(ValueTuple`2 x) in ./UpdateManager.InstallHelpers.cs:line 114
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext) in ./Internal/EnumerableExtensions.cs:line 59
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage() in ./UpdateManager.InstallHelpers.cs:line 107
   at Squirrel.UpdateManager.KillAllExecutablesBelongingToPackage() in ./UpdateManager.cs:line 248
   at Squirrel.Update.Program.Install(Boolean silentInstall, ProgressSource progressSource, String sourceDirectory) in ./Program.cs:line 293
   at Squirrel.Update.Program.Setup(String setupPath, Boolean silentInstall, Boolean checkInstall) in ./Program.cs:line 259
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args) in ./Program.cs:line 85
2022-10-22 22:00:33.3225 [INFO] - Program: Finished Squirrel Updater
2022-10-22 22:03:53.2467 [INFO] - Program: Starting Squirrel Updater: --setup C:\Users\firef\AppData\Local\Temp\squ7A93.tmp.nupkg
2022-10-22 22:03:53.3189 [INFO] - Program: Extracting bundled app data from 'C:\Users\firef\AppData\Local\Temp\squ7A93.tmp.nupkg'.
2022-10-22 22:03:53.5448 [INFO] - User32SplashWindow: Image dpi is 95,9866, screen dpi is 96. Rendering image at [896,456,128,128]
2022-10-22 22:03:53.5514 [INFO] - User32SplashWindow: There were 1 frames detected in the splash image (it's not animated).
2022-10-22 22:03:53.5514 [INFO] - Program: Starting package install from directory C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-10-22 22:03:54.0400 [INFO] - Program: Starting install, writing to C:\Users\firef\AppData\Local\SquirrelClowdTemp\tempa
2022-10-22 22:03:54.0618 [INFO] - Program: About to install to: C:\Users\firef\AppData\Local\osulazer
2022-10-22 22:03:54.0618 [WARN] - Program: Install path C:\Users\firef\AppData\Local\osulazer already exists, burning it to the ground
2022-10-22 22:03:54.1935 [FATAL] - Program: Encountered fatal unhandled exception.: System.AggregateException: One or more errors occurred. (Invalid URI: The hostname could not be parsed.)
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String , Boolean , UriKind , UriCreationOptions& )
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Squirrel.Utility.NormalizePath(String path) in ./Internal/Utility.cs:line 82
   at Squirrel.Utility.IsFileInDirectory(String file, String directory) in ./Internal/Utility.cs:line 89
   at Squirrel.UpdateManager.InstallHelperImpl.<>c__DisplayClass5_0.<KillAllProcessesBelongingToPackage>b__0(ValueTuple`2 x) in ./UpdateManager.InstallHelpers.cs:line 114
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext) in ./Internal/EnumerableExtensions.cs:line 59
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage() in ./UpdateManager.InstallHelpers.cs:line 107
   at Squirrel.UpdateManager.KillAllExecutablesBelongingToPackage() in ./UpdateManager.cs:line 248
   at Squirrel.Update.Program.Install(Boolean silentInstall, ProgressSource progressSource, String sourceDirectory) in ./Program.cs:line 293
   at Squirrel.Update.Program.Setup(String setupPath, Boolean silentInstall, Boolean checkInstall) in ./Program.cs:line 259
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args) in ./Program.cs:line 85
2022-10-22 22:03:58.6444 [INFO] - Program: Finished Squirrel Updater
```

**Comment by peppy** [comment]
@caesay have you seen this one before?

**Comment by caesay** [comment]
I have not seen this before. It looks like the app was installed, then uninstalled. That may have failed due to Update.exe running. When re-installing, it also failed to remove the previous application directory during `KillAllExecutablesBelongingToPackage()`. 

Can you please provide a list or screenshot of the files that are in `C:\Users\firef\AppData\Local\osulazer` for debugging purposes? You can then delete that folder and you should be able to re-install. If you are still unable to delete that folder manually, you may want to try a restart first.

**Comment by f1refa11** [comment]
![explorer_kMQiOaVjna](https://user-images.githubusercontent.com/58619409/197378317-f4014d68-9401-474d-8885-b13fdd887354.png)
Here is the screenshot of the files in osulazer folder.

**Comment by Erasings** [comment]
This means that it was uninstalled, but couldn't delete directory. Deleting osulazer and the other lazer-related directories should fix it,

**Comment by f1refa11** [comment]
The install.exe installed osu!lazer after I deleted the osulazer folder, so the problem is solved.
