### ISSUE TITLE
osu!lazer crashing after unplugging graphical tablet

### ISSUE THREAD

**Issue by i2021** [ppy/osu#21078]
### Type

Crash to desktop

### Bug description

Crash to desktop occured ón song select after unplugging graphical tablet using integrated drives in osu!lazer.

### Version

2022.1101.0

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9923403/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9923404/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9923405/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9923406/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9923407/runtime.log)
[network.log](https://github.com/ppy/osu/files/9923408/network.log)
[performance.log](https://github.com/ppy/osu/files/9923409/performance.log)
[updater.log](https://github.com/ppy/osu/files/9923410/updater.log)
[input.log](https://github.com/ppy/osu/files/9923411/input.log)
[database.log](https://github.com/ppy/osu/files/9923412/database.log)

**Comment by bdach** [comment]
This appears to be going wrong somewhere upstream:

```
2022-11-02 19:04:35 [error]: An unhandled error has occurred.
2022-11-02 19:04:35 [error]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
2022-11-02 19:04:35 [error]: at System.Collections.Generic.List`1.RemoveAt(Int32 index)
2022-11-02 19:04:35 [error]: at System.Collections.ObjectModel.Collection`1.RemoveItem(Int32 index)
2022-11-02 19:04:35 [error]: at System.Collections.ObjectModel.Collection`1.Remove(T item)
2022-11-02 19:04:35 [error]: at OpenTabletDriver.Driver.<>c__DisplayClass15_0.<Detect>b__0(Object sender, EventArgs e)
2022-11-02 19:04:35 [error]: at OpenTabletDriver.InputDeviceTree.<.ctor>b__0_0(Object sender, Boolean reading)
2022-11-02 19:04:35 [error]: at OpenTabletDriver.Devices.DeviceReader`1.Main()
2022-11-02 19:04:35 [error]: at System.Threading.Thread.StartHelper.Callback(Object stat
```

@InfinityGhost mind taking a look at this one?

**Comment by X9VoiD** [comment]
@i2021 Is the issue 100% reproducible?

**Comment by i2021** [comment]
> @i2021 Is the issue 100% reproducible?

was not able to reproduce it
