### ISSUE TITLE
osu Lazer crash on setup import

### ISSUE THREAD

**Issue by DashhPC** [ppy/osu#21077]
### Type

Crash to desktop

### Bug description

Installed lazer, go through setup and when I get to import from osu std my game crashes with a popup at the top right saying "_An unobserved error has occured_"

When cancelling setup and importing through settings, the game no longer crashes but the same error pops up.

### Version

latest / 2022.1101.0 / f1138f5

### Logs

edit : removed incorrect logs

**Comment by DashhPC** [comment]
https://streamable.com/1d5ff3 Clip of the issue

**Comment by bdach** [comment]
The logs attached are from stable rather than lazer. Please double-check the path (should be `%AppData%/osu/logs`) and upload again.

**Comment by DashhPC** [comment]
[performance.log](https://github.com/ppy/osu/files/9924078/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9924079/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9924080/updater.log)
[database.log](https://github.com/ppy/osu/files/9924081/database.log)
[input.log](https://github.com/ppy/osu/files/9924082/input.log)
[network.log](https://github.com/ppy/osu/files/9924083/network.log)


> %AppData%/osu/logs

**Comment by bdach** [comment]
Well...

```
2022-11-02 19:02:19 [error]: System.IO.IOException: The file or directory is corrupted and unreadable. : 'D:\Osu\osu!\Songs\1101604 yuikonnu - caramel heaven'
2022-11-02 19:02:19 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
2022-11-02 19:02:19 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.Init()
2022-11-02 19:02:19 [error]: at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
2022-11-02 19:02:19 [error]: at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
2022-11-02 19:02:19 [error]: at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
2022-11-02 19:02:19 [error]: at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
2022-11-02 19:02:19 [error]: at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
2022-11-02 19:02:19 [error]: at System.IO.Directory.GetFiles(String path, String searchPattern)
2022-11-02 19:02:19 [error]: at osu.Framework.Platform.NativeStorage.GetFiles(String path, String pattern)
2022-11-02 19:02:19 [error]: at osu.Game.Database.LegacyBeatmapImporter.GetStableImportPaths(Storage storage)+MoveNext()
2022-11-02 19:02:19 [error]: at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
2022-11-02 19:02:19 [error]: at osu.Game.Database.LegacyModelImporter`1.<>c__DisplayClass5_0.<GetAvailableCount>b__0()
2022-11-02 19:02:19 [error]: at System.Threading.Tasks.Task`1.InnerInvoke()
2022-11-02 19:02:19 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2022-11-02 19:02:19 [error]: --- End of stack trace from previous location ---
2022-11-02 19:02:19 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-11-02 19:02:19 [error]: --- End of stack trace from previous location ---
2022-11-02 19:02:19 [error]: at osu.Game.Database.LegacyImportManager.GetImportCount(StableContent content, CancellationToken cancellationToken)
2022-11-02 19:02:19 [verbose]: Unhandled exception has been denied .
```

Needs to be fixed on our side to not crash for sure, but you may want to look into what's causing that.

**Comment by DashhPC** [comment]
Appreciate the response, tried multiple ways of moving/removing/replacing the corrupt song folder to no avail, i'm not sure of a work around, suggestions would be appreciated

**Comment by peppy** [comment]
A good start would be to run disk check on windows. This looks like a filesystem or hardware issue.

**Comment by peppy** [comment]
As for how this should be fixed to avoid the crash, I do believe that handling would need to be at the osu! side. The framework `NativeStorage` methods should probably be marked as potentially throwing an `IOException`, but handling it framework side is likely not what we want beyond that.

**Comment by DashhPC** [comment]
> A good start would be to run disk check on windows. This looks like a filesystem or hardware issue.

Thanks for the suggestion this cleared off the corrupt folder. The setup wizard no longer crashes me and the song import works perfectly. Note to self to check for corrupt folders prior to downloading lazer haha.
