### ISSUE TITLE
Unable to access game settings

### ISSUE THREAD

**Issue by Kgym-Hina** [ppy/osu#21271]
### Type

Game behaviour

### Bug description

1. Fresh install osu!lazer on Mac(arm64)
2. Get an error when doing first time run settings.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/22652631/202399377-1cd008bd-8d79-4c3b-95ce-73f44d7f5060.png)
![image](https://user-images.githubusercontent.com/22652631/202399430-509a4b08-9a02-4f80-ade5-b107b8b92448.png)

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10029505/database.log)
[input.log](https://github.com/ppy/osu/files/10029506/input.log)
[network.log](https://github.com/ppy/osu/files/10029507/network.log)
[performance.log](https://github.com/ppy/osu/files/10029508/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10029509/runtime.log)

**Comment by peppy** [comment]
Relevant log content:

```csharp

2022-11-17 08:47:44 [error]: An unhandled error has occurred.
2022-11-17 08:47:44 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
2022-11-17 08:47:44 [error]: at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
2022-11-17 08:47:44 [error]: at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
2022-11-17 08:47:44 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.addDropdownItem(LocalisableString text, T value)
2022-11-17 08:47:44 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.setItems(IEnumerable`1 items)
2022-11-17 08:47:44 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.set_Items(IEnumerable`1 value)
2022-11-17 08:47:44 [error]: at osu.Game.Overlays.Settings.SettingsDropdown`1.set_Items(IEnumerable`1 value) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/SettingsDropdown.cs:line 22
2022-11-17 08:47:44 [error]: at osu.Game.Overlays.Settings.Sections.Audio.AudioDevicesSettings.updateItems() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/Sections/Audio/AudioDevicesSettings.cs:line 62
2022-11-17 08:47:44 [error]: at osu.Game.Overlays.Settings.Sections.Audio.AudioDevicesSettings.load() in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/Sections/Audio/
```

It looks like you have a weird audio setup, or potentially no audio device. Can you describe what audio devices you have connected in more detail?

**Comment by Kgym-Hina** [comment]
![image](https://user-images.githubusercontent.com/22652631/202400829-9234fdbd-5c8b-415f-b627-40f8acac00c1.png)
I've attached a headset on mac. There is also a built in speaker.

**Comment by Kgym-Hina** [comment]
There is a path in the log `/usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Game/Overlays/Settings/`

I cannot find this in my file system. Will that be a reason?

**Comment by peppy** [comment]
I think the issue here is that one of your output devices has no name. This will likely require a fix from our end.
