### ISSUE TITLE
Game closes if you hold the object in the editor and exit the editor

### ISSUE THREAD

**Issue by Maks1mio** [ppy/osu#21294]
### Type

Game behaviour

### Bug description

holding the circle or slider, it is still tied to hold, when I exit the editor, the game closes (check video)

### Screenshots or videos

https://user-images.githubusercontent.com/44835662/202660113-b84e3155-166c-46e0-97ae-16db7ebba5ae.mp4

https://user-images.githubusercontent.com/44835662/202660124-7ae70a63-9d7a-4023-850c-2f6a0929c846.mp4

https://user-images.githubusercontent.com/44835662/202660127-e3649796-6ce4-45be-be37-6ffdde5d7664.mp4

https://user-images.githubusercontent.com/44835662/202660128-c44615cc-07d8-43fe-9d48-deb1a2100fb0.mp4

https://user-images.githubusercontent.com/44835662/202660134-0230254c-7d11-49ce-b31d-e238a0341aec.mp4

### Version

2022.1117.0

### Logs

[network.log](https://github.com/ppy/osu/files/10039672/network.log)
[performance.log](https://github.com/ppy/osu/files/10039673/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10039674/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10039675/updater.log)
[database.log](https://github.com/ppy/osu/files/10039676/database.log)

**Comment by peppy** [comment]
The attached logs don't contain the actual error that caused a crash here, did anyone manage to reproduce?

**Comment by Maks1mio** [comment]
Bug:
After moving object in editor, it closes editor or crashes game

Expected behavior:
Editor object lost selection and changes it's position

Actual behavior:
Map editor is going to close

Steps to reproduce:
1. Select object in editor
2. Move it
3. Press ESC during moving object

On press ESC map editor checks if there were any changes in map and immediately closes itself if no.
But mouse click was not released, so object is still in moving state and after closing editor window it lost it's parent, idk how to explain it better 

https://user-images.githubusercontent.com/44835662/203531363-86086f43-02ce-44ff-93fa-aaf35d7ab419.mp4


https://user-images.githubusercontent.com/44835662/203531369-28614c84-9f79-48c5-b158-6c5b31bdb1b0.mp4

**Comment by peppy** [comment]
I'm still hoping for an *error log*.

**Comment by Alan72104** [comment]
Here is the stack trace
[runtime.log](https://github.com/ppy/osu/files/10087708/runtime.log)

**Comment by Maks1mio** [comment]
> The attached logs don't contain the actual error that caused a crash here, did anyone manage to reproduce?

I apologize. For throwing the old osu logs files out of appdata, when I moved the osu folder to another drive the logs were saved to it. 🤦‍♂️

**Comment by peppy** [comment]
Thanks.

Relevant portion of log:

```csharp
2022-11-24 23:55:45 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-11-24 23:55:45 [error]: at osu.Game.Extensions.DrawableExtensions.ScreenSpaceDeltaToParentSpace(Drawable drawable, Vector2 delta)
2022-11-24 23:55:45 [error]: at osu.Game.Rulesets.Osu.Edit.OsuSelectionHandler.HandleMovement(MoveSelectionEvent`1 moveEvent)
2022-11-24 23:55:45 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.ApplySnapResult(SelectionBlueprint`1[] blueprints, SnapResult result)
2022-11-24 23:55:45 [error]: at osu.Game.Screens.Edit.Compose.Components.EditorBlueprintContainer.ApplySnapResult(SelectionBlueprint`1[] blueprints, SnapResult result)
2022-11-24 23:55:45 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.moveCurrentSelection(DragEvent e)
2022-11-24 23:55:45 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.OnDrag(DragEvent e)
2022-11-24 23:55:45 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2022-11-24 23:55:45 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
```

This... looks like something we may want to investigate at a framework level. I don't think `OnDrag` should be fired on a drawable after it has been removed from its parent.

**Comment by peppy** [comment]
I've made an initial effort to investigate this framework-side:

https://github.com/ppy/osu-framework/compare/master...peppy:osu-framework:drag-after-drawable-removed?expand=1

Seems like we'd somehow want to trigger a drag end on parent invalidation?
