### ISSUE TITLE
lazer not launching 

### ISSUE THREAD

**Issue by SadPersonn** [ppy/osu#21649]
### Type

Crash to desktop

### Bug description

linux 6.0.12.arch1-1

lazer crashes after launch

### Screenshots or videos

![image](https://user-images.githubusercontent.com/74460065/207883825-fe7f4159-2a34-445c-a052-d9f76f077b08.png)

### Version

osu-lazer-git 2022.1117.0.r218.224bf85e4a-1

### Logs

[network.log](https://github.com/ppy/osu/files/10237732/network.log)
[runtime.log](https://github.com/ppy/osu/files/10237733/runtime.log)
[database.log](https://github.com/ppy/osu/files/10237734/database.log)
[performance.log](https://github.com/ppy/osu/files/10237735/performance.log)
[input.log](https://github.com/ppy/osu/files/10237736/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10237737/legacy-ipc.log)

**Comment by bdach** [comment]
The `osu-lazer-git` package is not maintained by anyone here. The only official form of distribution for Linux is the appimage.

Please try reproducing with the appimage first. If it happens again the we will reopen.

**Comment by bentokage** [comment]
Not sure if this is the same thing, happened to me starting today too (was working before the last update) and the error looks similar but not exact.

[runtime.log](https://github.com/ppy/osu/files/10242465/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10242466/updater.log)
[network.log](https://github.com/ppy/osu/files/10242467/network.log)
[performance.log](https://github.com/ppy/osu/files/10242468/performance.log)

```2022-12-16 03:33:47 [error]: An unhandled error has occurred.
2022-12-16 03:33:47 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
2022-12-16 03:33:47 [error]: at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2022-12-16 03:33:47 [error]: at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found)
2022-12-16 03:33:47 [error]: at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
2022-12-16 03:33:47 [error]: at osu.Game.Online.Notifications.NotificationsClient.HandleMessages(List`1 messages)
2022-12-16 03:33:47 [error]: at osu.Game.Online.Notifications.NotificationsClient.<CreateFetchMessagesRequest>b__8_0(GetUpdatesResponse updates)
2022-12-16 03:33:47 [error]: at osu.Game.Online.API.APIRequest`1.<.ctor>b__8_0()
2022-12-16 03:33:47 [error]: at osu.Game.Online.API.APIRequest.<TriggerSuccess>b__24_0()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-12-16 03:33:47 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2022-12-16 03:33:47 [verbose]: Current channel changed to MadiMooMew
2022-12-16 03:33:47 [error]: An unhandled error has occurred.
2022-12-16 03:33:47 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
2022-12-16 03:33:47 [error]: at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2022-12-16 03:33:47 [error]: at osu.Game.Online.Chat.ChannelManager.addMessages(List`1 messages)
2022-12-16 03:33:47 [error]: at osu.Game.Online.Chat.ChannelManager.<>c__DisplayClass24_2.<load>b__7()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.Scheduler.Update()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-12-16 03:33:47 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-12-16 03:33:47 [error]: at osu.Framework.Threading.GameThread.processFrame()
2022-12-16 03:33:47 [verbose]: Unhandled exception has been denied .
2022-12-16 03:33:47 [verbose]: Requesting catch-up from 7176369
2022-12-16 03:33:47 [verbose]: Requesting any changes since last known queue id 7176369
2022-12-16 03:33:47 [verbose]: Requesting catch-up from 7176419
2022-12-16 03:33:47 [verbose]: Requesting any changes since last known queue id 7176419
2022-12-16 03:33:47 [verbose]: Requesting catch-up from 7176469
2022-12-16 03:33:47 [verbose]: Requesting any changes since last known queue id 7176469
2022-12-16 03:33:47 [verbose]: Requesting catch-up from 7176519
2022-12-16 03:33:47 [verbose]: Requesting any changes since last known queue id 7176519
2022-12-16 03:33:49 [verbose]: Host execution state changed to Stopping
2022-12-16 03:33:49 [verbose]: Requesting catch-up from 7176569
2022-12-16 03:33:49 [verbose]: Requesting any changes since last known queue id 7176569
2022-12-16 03:33:49 [verbose]: Host execution state changed to Stopped```

**Comment by peppy** [comment]
@bentokage is there a reason you'r not on the latest release?

**Comment by bentokage** [comment]
Well, I feel silly now. I think I assumed the game would have tried to update automatically but it probably wasn't able to since it couldn't open. Re-installing using the launcher fixed the problem, so I'll let people know about that, since a few other people I know started having this issue too. Sorry about that!

**Comment by peppy** [comment]
Yeah, that's a bit unfortunate, and also on us (there should be an automatic recovery to make it update if it crashes).

I've tracked down the underlying issue to an `osu-web` side deploy. Have rolled it back and alerted the team for now.
