### ISSUE TITLE
Editor crashes when creating a reverse arrow slider while creating a slider

### ISSUE THREAD

**Issue by timesnewrman** [ppy/osu#22643]
### Type

Crash to desktop

### Bug description

works only on 0-tick sliders

### Screenshots or videos

https://user-images.githubusercontent.com/118610205/218853855-2108161e-8a3e-4425-a1ee-14ad304472c9.mp4

### Version

2023.207.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10736605/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10736606/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10736607/updater.log)
[database.log](https://github.com/ppy/osu/files/10736608/database.log)
[input.log](https://github.com/ppy/osu/files/10736609/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10736610/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10736611/network.log)

**Comment by bdach** [comment]
Can reproduce. Not sure why the attached log has no crash trace, but for me it dies with

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at osu.Game.Rulesets.Objects.Types.HasRepeatsExtensions.GetNodeSamples[T](T obj, Int32 nodeIndex) in /home/dachb/Documents/opensource/osu/osu.Game/Rulesets/Objects/Types/IHasRepeats.cs:line 49
   at osu.Game.Rulesets.Osu.Objects.Slider.UpdateNestedSamples() in /home/dachb/Documents/opensource/osu/osu.Game.Rulesets.Osu/Objects/Slider.cs:line 256
   at osu.Game.Rulesets.Osu.Objects.Slider.CreateNestedHitObjects(CancellationToken cancellationToken) in /home/dachb/Documents/opensource/osu/osu.Game.Rulesets.Osu/Objects/Slider.cs:line 222
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken) in /home/dachb/Documents/opensource/osu/osu.Game/Rulesets/Objects/HitObject.cs:line 129
   at osu.Game.Screens.Edit.EditorBeatmap.processHitObject(HitObject hitObject) in /home/dachb/Documents/opensource/osu/osu.Game/Screens/Edit/EditorBeatmap.cs:line 379
   at osu.Game.Screens.Edit.EditorBeatmap.UpdateState() in /home/dachb/Documents/opensource/osu/osu.Game/Screens/Edit/EditorBeatmap.cs:line 349
   at osu.Game.Screens.Edit.EditorBeatmap.Update() in /home/dachb/Documents/opensource/osu/osu.Game/Screens/Edit/EditorBeatmap.cs:line 335
```

The timeline blueprint should not be interactable while a placement is in progress.
