### ISSUE TITLE
No beatmaps loading after unsuccessful search

### ISSUE THREAD

**Issue by Pifferro** [ppy/osu#2275]
Beatmap selection empty after an unsuccessful search, even after clearing the search bar.
Going to the main menu and back does not fix it.

**Found workaround:**
Skipping to the next song via MusicController while in song selection.
Does not fix it when executed in the main menu.

**runtime.log:**
21.03.2018 22:16:42: Could not load beatmap sucessfully!
21.03.2018 22:16:42: System.NotImplementedException: The method or operation is not implemented.
21.03.2018 22:16:42: at osu.Game.Beatmaps.DummyWorkingBeatmap.DummyRulesetInfo.DummyRuleset.CreateRulesetContainerWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset)
21.03.2018 22:16:42: at osu.Game.Screens.Play.Player.load(AudioManager audio, APIAccess api, OsuConfigManager config)
21.03.2018 22:16:47: Focus contention triggered by MusicController (0,40) 400x130.

**Comment by Pifferro** [comment]
I've just seen a thread with the same issue, sorry.
