### ISSUE TITLE
phantom rooms

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#22791]
### Type

Game behaviour

### Bug description

there are 3 phantom rooms that you cannot join; it displays an error. 

the bottom one has been there for many days, the one above that one only 1-2 days, and the top one very recently. 

restarting game persists. 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/78441708/222941566-3a668eba-f7d7-4a26-a979-b8c48052e5f9.png)
![image](https://user-images.githubusercontent.com/78441708/222941574-c76a28ee-9c36-4aa0-928a-0b2ec70929e8.png)

### Version

2022.301.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10890778/runtime.log)
[network.log](https://github.com/ppy/osu/files/10890779/network.log)
[database.log](https://github.com/ppy/osu/files/10890780/database.log)
[performance.log](https://github.com/ppy/osu/files/10890781/performance.log)
[input.log](https://github.com/ppy/osu/files/10890782/input.log)

**Comment by bdach** [comment]
Relevant error:

```
2023-03-05 04:21:34 [error]: Failed to join multiplayer room.
2023-03-05 04:21:34 [error]: System.AggregateException: One or more errors occurred. (One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Non-host is attempting to join match before host))
2023-03-05 04:21:34 [error]: ---> System.AggregateException: One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Non-host is attempting to join match before host)
2023-03-05 04:21:34 [error]: ---> Microsoft.AspNetCore.SignalR.HubException: An unexpected error occurred invoking 'JoinRoomWithPassword' on the server. InvalidStateException: Non-host is attempting to join match before host
2023-03-05 04:21:34 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2023-03-05 04:21:34 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2023-03-05 04:21:34 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
2023-03-05 04:21:34 [error]: at osu.Game.Online.Multiplayer.OnlineMultiplayerClient.JoinRoom(Int64 roomId, String password) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/Multiplayer/OnlineMultiplayerClient.cs:line 83
2023-03-05 04:21:34 [error]: at osu.Game.Online.Multiplayer.OnlineMultiplayerClient.JoinRoom(Int64 roomId, String password) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/Multiplayer/OnlineMultiplayerClient.cs:line 95
2023-03-05 04:21:34 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass69_0.<<JoinRoom>b__0>d.MoveNext() in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/Multiplayer/MultiplayerClient.cs:line 182
2023-03-05 04:21:34 [error]: --- End of inner exception stack trace ---
2023-03-05 04:21:34 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.JoinRoom(Room room, String password) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/Multiplayer/MultiplayerClient.cs:line 177
2023-03-05 04:21:34 [error]: --- End of inner exception stack trace ---
```

Likely going to require server logs to diagnose.

**Comment by Axilotl17** [comment]
If possible, if not at to fix this issue please delete the current broken lobbies, because the people who host those phantom lobbies are currently unable to join any new rooms @peppy

**Comment by peppy** [comment]
I've fixed the stuck rooms once more. Still need to investigate the root cause of this.

**Comment by hashelq** [comment]
AFAIK The rooms are created by the REST request and requires a real host to join them. The room can exist without the host user client in, so, maybe there is no real host in the room.
