### ISSUE TITLE
Osu Lazer fails to launch on Apple Silicon (macOS 13)

### ISSUE THREAD

**Issue by starcraft66** [ppy/osu#22830]
### Type

Crash to desktop

### Bug description

Osu crashes on launch. See error log when run from the CLI.

### Version

Can't open the game to check, latest Apple Silicon ZIP at the time of writing

CPU/GPU: Apple M1 Pro
macOS Version: 13.1

### Logs

```
/Applications/osu\!.app/Contents/MacOS/osu\!
2023-03-10 12:00:01.441 osu![94396:7715213] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2023-03-10 12:00:01.441 osu![94396:7715213] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2023-03-10 12:00:01.441 osu![94396:7715213] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
Unhandled exception. System.InvalidOperationException: Failed to create an SDL2 GL context (Failed creating OpenGL context)
   at osu.Framework.Platform.SDL2.SDL2GraphicsSurface.initialiseOpenGL()
   at osu.Framework.Platform.SDL2.SDL2GraphicsSurface.Initialise()
   at osu.Framework.Platform.SDL2DesktopWindow.Create()
   at osu.Framework.Platform.MacOS.MacOSWindow.Create()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Desktop/Program.cs:line 120
zsh: abort      /Applications/osu!.app/Contents/MacOS/osu!
```

**Comment by peppy** [comment]
Unsure how this can be a thing, but I'm going to close this issue for now as we are getting very close to rolling out proper metal support, which will definitely resolve this issue.

**Comment by starcraft66** [comment]
This actually fixed itself on its own, presumably after I rebooted my computer!
