### ISSUE TITLE
Lazer Scores Not Submiting.

### ISSUE THREAD

**Issue by VEERT00X** [ppy/osu#22923]
### Type

Game behaviour

### Bug description

I had gotten a score ranking me second in the leaderboard of [Connect (TV Size)](https://lazer.ppy.sh/beatmapsets/24565#osu/85212) its confirmed by [This Play](https://lazer.ppy.sh/scores/2250215702) but its not showing up on the global lazer leaderboard.
This issue happend twice in the same beatmap.

### Screenshots or videos

![osu_2023-03-20_23-16-30](https://user-images.githubusercontent.com/72668825/226477483-db10b9cb-9f45-43a7-ad9b-b00df4dab878.jpg)
![osu_2023-03-20_23-16-55](https://user-images.githubusercontent.com/72668825/226477540-0e52415a-1f7c-4614-a1a0-b18897c7605d.jpg)
[Replay.zip](https://github.com/ppy/osu/files/11023468/Replay.zip)

### Version

2023.305.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11023473/database.log)
[input.log](https://github.com/ppy/osu/files/11023474/input.log)
[network.log](https://github.com/ppy/osu/files/11023476/network.log)
[performance.log](https://github.com/ppy/osu/files/11023477/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11023478/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11023479/updater.log)

**Comment by peppy** [comment]
Should be resolved now, thanks for pointing this out.

Relevant to devs following along:

```csharp
Error processing ScoreItem ScoreId: 2249906095:                                                                              Re-queueing for attempt 1 / 3
stats: queue:332 inflight:5501 dequeued:7094148 processed:7088640 errors:7
Error processing ScoreItem ScoreId: 2161730057:
Re-queueing for attempt 1 / 3                                                                                                StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET osu-queue:score-index:schema ** possibl
e thread-theft indicated; see https://stackexchange.github.io/StackExchange.Redis/ThreadTheft ** , inst: 1, qu: 0, qs: 2, aw:
 False, rs: CompletePendingMessageSync, ws: Idle, in: 7, in-pipe: 21, out-pipe: 0, serverEndpoint: redis:6379, mc: 1/1/0, mgr
: 8 of 10 available, clientName: es-scores-new, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=6,Free=32761,Min=8,Max
=32767), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: http
s://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoi
nt server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2886
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_
/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDataba
se.cs:line 2432
   at osu.ElasticIndexer.Redis.GetSchemaVersion() in /app/Redis.cs:line 33
   at osu.ElasticIndexer.SoloScoreIndexer.checkSchema() in /app/SoloScoreIndexer.cs:line 74
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state
)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), active: GET osu-queue:score-index:schema, next: G
ET osu-queue:score-index:schema ** possible thread-theft indicated; see https://stackexchange.github.io/StackExchange.Redis/T
hreadTheft ** , inst: 0, qu: 0, qs: 2, aw: False, rs: CompletePendingMessageSync, ws: Idle, in: 0, in-pipe: 21, out-pipe: 0,
serverEndpoint: redis:6379, mc: 1/1/0, mgr: 8 of 10 available, clientName: es-scores-new, IOCP: (Busy=0,Free=1000,Min=8,Max=1
000), WORKER: (Busy=6,Free=32761,Min=8,Max=32767), v: 2.2.88.56325 (Please take a look at this article for some common client
-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoi
nt server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2886
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_
/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDataba
se.cs:line 2432
```
