### ISSUE TITLE
Vulkan failed to initialise. liblibdl: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by taep96** [ppy/osu#22956]
### Type

Game behaviour

### Bug description

Game fails to initialize the Vulkan renderer. In `runtime.log`:
```
   6   │ 2023-03-26 16:18:52 [verbose]: 🖼️ Configuration renderer choice: Vulkan
   7   │ 2023-03-26 16:18:52 [verbose]: 🖼️ Renderer fallback order: [ Vulkan, OpenGL (Legacy), OpenGL ]
   8   │ 2023-03-26 16:18:52 [verbose]: 🖼️ Initialising "Veldrid" renderer with "Vulkan" surface
   9   │ 2023-03-26 16:18:53 [verbose]: Updated display mode to desktop resolution: 1920x1080@60, SDL_PIXELFORMAT_RGB888
  10   │ 2023-03-26 16:18:53 [verbose]: 🖼️ Renderer initialisation failed with:
  11   │ 2023-03-26 16:18:53 [verbose]: System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception.
  12   │ 2023-03-26 16:18:53 [verbose]: ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
  13   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.Libdl.dlerror()
  14   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary.LoadLibrary(String libraryName)
  15   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.NativeLibrary..ctor(String libraryName)
  16   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary..ctor(String libraryName)
  17   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.NativeLibrary.Load(String libraryName)
  18   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.VulkanNative.LoadNativeLibrary()
  19   │ 2023-03-26 16:18:53 [verbose]: at Vulkan.VulkanNative..cctor()
  20   │ 2023-03-26 16:18:53 [verbose]: --- End of inner exception stack trace ---
  21   │ 2023-03-26 16:18:53 [verbose]: at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers()
  22   │ 2023-03-26 16:18:53 [verbose]: at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug, VulkanDeviceOptions options)
  23   │ 2023-03-26 16:18:53 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions)
  24   │ 2023-03-26 16:18:53 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
  25   │ 2023-03-26 16:18:53 [verbose]: at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
  26   │ 2023-03-26 16:18:53 [verbose]: at osu.Framework.Graphics.Veldrid.VeldridRenderer.Initialise(IGraphicsSurface graphicsSurface)
  27   │ 2023-03-26 16:18:53 [verbose]: at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.Initialise(IGraphicsSurface graphicsSurface)
  28   │ 2023-03-26 16:18:53 [verbose]: at osu.Framework.Platform.GameHost.SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType surfaceType)
  29   │ 2023-03-26 16:18:53 [important]: The selected renderer (Vulkan) failed to initialise. Renderer selection has been reverted to automatic.
  30   │ 2023-03-26 16:18:53 [verbose]: 🖼️ Initialising "GL" renderer with "OpenGL" surface
```

Seems like there's a typo of some sort at line 12: `liblibdl: cannot open shared object file: No such file or directory`.

`libdl.so.2` is present on my system:

![image](https://user-images.githubusercontent.com/64481039/227790296-7dac6345-e91c-410e-848e-7b3dd78b4aba.png)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/64481039/227789747-94088036-32a0-46da-9f47-9da14dbc5801.png)

### Version

2023.326.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11072235/database.log)
[input.log](https://github.com/ppy/osu/files/11072236/input.log)
[network.log](https://github.com/ppy/osu/files/11072237/network.log)
[performance.log](https://github.com/ppy/osu/files/11072238/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11072239/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11072240/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11072241/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11072242/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11072243/runtime.log)

**Comment by bdach** [comment]
Relevant upstream issue: https://github.com/mellinoe/veldrid/issues/143#issuecomment-446096640

We're aware that vulkan is not 100% there yet. The suggested workaround for now is to symlink the `libdl.so.2` shared object as described in the aforementioned comment.

**Comment by adryzz** [comment]
by the way, i opened an [issue upstream](https://github.com/mellinoe/veldrid/issues/461) about this a while ago, that got then closed and appeared to have been fixed by the last message, but apparently it did not

**Comment by bdach** [comment]
Vulkan is going to be pulled as a choice on all platforms for now until it is stabilised (#22961).

**Comment by Hitsounds** [comment]
Since glibc 2.24 the functions provided by libdl.so are instead provided by libc.so, however the [vk](https://github.com/mellinoe/vk) library used by osu through [veldrid](https://github.com/mellinoe/veldrid) still tries to pull in libdl.so.

A temporary solution is to `ln -s /usr/lib/libc.so /usr/lib/libdl.so`

**Comment by Skaldebane** [comment]
Hi! When could Vulkan be back?

**Comment by bdach** [comment]
when it's ready, no ETA.

**Comment by pikaphase** [comment]
This error still happens on 2024.412.1 which has added Vulkan render option.
```
----------------------------------------------------------
runtime Log for tux (LogLevel: Verbose)
Running osu 2024.412.1.0 on .NET 8.0.4
Environment: Linux (Unix 6.8.4.1), 12 cores 
----------------------------------------------------------
2024-04-13 10:34:41 [verbose]: Starting legacy IPC provider...
2024-04-13 10:34:41 [verbose]: 🖼️ Configuration renderer choice: Deferred_Vulkan
2024-04-13 10:34:41 [verbose]: 🖼️ Renderer fallback order: [ Vulkan (Experimental), OpenGL, OpenGL (Experimental) ]
2024-04-13 10:34:41 [verbose]: 🖼️ Initialising "Deferred" renderer with "Vulkan" surface
2024-04-13 10:34:42 [verbose]: Updated display mode to desktop resolution: 1920x1080@144, SDL_PIXELFORMAT_RGB888
2024-04-13 10:34:42 [verbose]: 🖼️ Renderer initialisation failed with:
2024-04-13 10:34:42 [verbose]: System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception.
2024-04-13 10:34:42 [verbose]: ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
2024-04-13 10:34:42 [verbose]: /tmp/.mount_gearlefPB46h/usr/bin/libdl.so: cannot open shared object file: No such file or directory
2024-04-13 10:34:42 [verbose]: /tmp/.mount_gearlefPB46h/usr/bin/liblibdl.so: cannot open shared object file: No such file or directory
2024-04-13 10:34:42 [verbose]: /tmp/.mount_gearlefPB46h/usr/bin/libdl: cannot open shared object file: No such file or directory
2024-04-13 10:34:42 [verbose]: /tmp/.mount_gearlefPB46h/usr/bin/liblibdl: cannot open shared object file: No such file or directory
2024-04-13 10:34:42 [verbose]: 
2024-04-13 10:34:42 [verbose]: at Vulkan.Libdl.dlerror()
2024-04-13 10:34:42 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary.LoadLibrary(String libraryName)
2024-04-13 10:34:42 [verbose]: at Vulkan.NativeLibrary..ctor(String libraryName)
2024-04-13 10:34:42 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary..ctor(String libraryName)
2024-04-13 10:34:42 [verbose]: at Vulkan.NativeLibrary.Load(String libraryName)
2024-04-13 10:34:42 [verbose]: at Vulkan.VulkanNative.LoadNativeLibrary()
2024-04-13 10:34:42 [verbose]: at Vulkan.VulkanNative..cctor()
2024-04-13 10:34:42 [verbose]: --- End of inner exception stack trace ---
2024-04-13 10:34:42 [verbose]: at Vulkan.VulkanNative.vkEnumerateInstanceLayerProperties(UInt32& pPropertyCount, VkLayerProperties* pProperties)
2024-04-13 10:34:42 [verbose]: at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers()
2024-04-13 10:34:42 [verbose]: at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug, VulkanDeviceOptions options)
2024-04-13 10:34:42 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions)
2024-04-13 10:34:42 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
2024-04-13 10:34:42 [verbose]: at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
2024-04-13 10:34:42 [verbose]: at osu.Framework.Graphics.Veldrid.VeldridDevice..ctor(IGraphicsSurface graphicsSurface)
2024-04-13 10:34:42 [verbose]: at osu.Framework.Graphics.Rendering.Deferred.DeferredRenderer.Initialise(IGraphicsSurface graphicsSurface)
2024-04-13 10:34:42 [verbose]: at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.Initialise(IGraphicsSurface graphicsSurface)
2024-04-13 10:34:42 [verbose]: at osu.Framework.Platform.GameHost.SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType surfaceType)
2024-04-13 10:34:42 [important]: The selected renderer (Vulkan (Experimental)) failed to initialise. Renderer selection has been reverted to automatic.
2024-04-13 10:34:42 [verbose]: 🖼️ Initialising "GL" renderer with "OpenGL" surface
...
```

**Comment by smoogipoo** [comment]
See: https://github.com/ppy/osu/discussions/27659#discussioncomment-9101677

**Comment by Skaldebane** [comment]
@smoogipoo This doesn't work with the Flatpak version, any solution here?

From the logs, it seems to be looking for `libdl.so` at `/app/bin/` (which is inside the Flatpak sandbox afaik).

**Comment by pikaphase** [comment]
@Skaldebane try modifying filesystem permissions of osu! flatpak using flatseal so it can access system libraries?

**Comment by smoogipoo** [comment]
Will be fixed by https://github.com/ppy/vk/pull/1
