### ISSUE TITLE
Can't Use OpenGL Renderer on iGPU Any More

### ISSUE THREAD

**Issue by tuhanayim** [ppy/osu#22966]
### Type

Other

### Bug description

Can't switch the renderer to OpenGL on my iGPU. Old versions which use OpenGL are perfectly fine.

### Version

2023.326.0

### Logs

[network.log](https://github.com/ppy/osu/files/11072403/network.log)
[performance.log](https://github.com/ppy/osu/files/11072404/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11072405/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11072406/updater.log)

**Comment by bdach** [comment]
Whatever this is, it's equal parts funny and sad:

```
2023-03-26 17:14:31 [verbose]: SDL error log [debug]: Could not create GL context: The operation completed successfully.
2023-03-26 17:14:31 [verbose]: 🖼️ Renderer initialisation failed with:
2023-03-26 17:14:31 [verbose]: System.InvalidOperationException: Failed to create an SDL2 GL context (Could not create GL context: The operation completed successfully.)
2023-03-26 17:14:31 [verbose]: at osu.Framework.Platform.SDL2.SDL2GraphicsSurface.initialiseOpenGL()
2023-03-26 17:14:31 [verbose]: at osu.Framework.Platform.SDL2.SDL2GraphicsSurface.Initialise()
2023-03-26 17:14:31 [verbose]: at osu.Framework.Platform.SDL2Window.Create()
2023-03-26 17:14:31 [verbose]: at osu.Framework.Platform.Windows.WindowsWindow.Create()
2023-03-26 17:14:31 [verbose]: at osu.Framework.Platform.GameHost.SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType surfaceType)
```

**Comment by longnguyen2004** [comment]
Do the obvious and try to update the graphics driver first, maybe it can help with something

**Comment by tuhanayim** [comment]
> Do the obvious and try to update the graphics driver first, maybe it can help with something

Everything is on latest version on my side, also note that it started to happen after switch to Veldrid. I think it's related to it rather than driver.

**Comment by peppy** [comment]
The only possible cause of this looks to be the GL core profile being set, which wasn't the case previously. It's failing inside of SDL when attempting to do the lower level init of GL

https://github.com/ppy/osu-framework/blob/e3776ad92df65739c5c48f81f8aeb960ccd856ef/osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs#L101-L105

Failing in SDL either [here](https://github.com/letoram/SDL2/blob/master/src/video/windows/SDL_windowsopengl.c#L714) or [here](https://github.com/letoram/SDL2/blob/master/src/video/windows/SDL_windowsopengl.c#L783).

cc @smoogipoo

**Comment by longnguyen2004** [comment]
Intel HD Graphics 3000 only supports up to [OpenGL 3.1 on Windows](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#:~:text=8%2B%0AFL10_1-,3.1Windows,-3.3macOS%5B25), while osu! is initializing OpenGL 3.2. This might be the problem we're facing?

**Comment by smoogipoo** [comment]
3.2 is required for the core profile on macOS, but it seems like we may be able to go back to 3.0 on other platforms...

**Comment by smoogipoo** [comment]
Unfortunately we don't seem to be able to go back to OpenGL < 3.2 because it falls back to the 2.1 compatibility context and shader compilation fails.

Your best bet is to use Direct3D for now.
