### ISSUE TITLE
osu! on ios crashes when set to OpenGL

### ISSUE THREAD

**Issue by distrair** [ppy/osu#22978]
### Type

Other

### Bug description

When rendering set to OpenGL on iOS and restart the game, the game wont launch

### Screenshots or videos

https://user-images.githubusercontent.com/78724291/227796860-ba55133b-6a43-4055-9d75-9e9255b59e25.mp4

### Version

2023.326.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11072679/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11072680/performance.log)
[input.log](https://github.com/ppy/osu/files/11072681/input.log)
[database.log](https://github.com/ppy/osu/files/11072682/database.log)

**Comment by bdach** [comment]
Relevant portions

```
2023-03-26 18:41:39 [error]: Veldrid.VeldridException: Unable to compile shader code for shader [] of type VertexShader: ERROR: 0:1: '' :  version '330' is not supported
2023-03-26 18:41:39 [error]: ERROR: 0:3: 'layout' : syntax error: syntax error
2023-03-26 18:41:39 [error]: 
2023-03-26 18:41:39 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.InitializeResource(OpenGLDeferredResource deferredResource)
2023-03-26 18:41:39 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.EnsureResourceInitialized(OpenGLDeferredResource deferredResource)
2023-03-26 18:41:39 [error]: at Veldrid.OpenGL.OpenGLResourceFactory.CreateShaderCore(ShaderDescription& description)
```

```
2023-03-26 18:41:40 [error]: System.NullReferenceException: Arg_NullReferenceException
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.VeldridExtensions.Clone(GraphicsPipelineDescription pipeline)
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.VeldridRenderer.getPipelineInstance()
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.VeldridRenderer.DrawVertices(PrimitiveTopology type, Int32 indexStart, Int32 indicesCount)
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.Buffers.VeldridVertexBuffer`1[[osu.Framework.Graphics.Rendering.Vertices.TexturedVertex2D, osu.Framework, Version=2023.327.0.0, Culture=neutral, PublicKeyToken=null]].DrawRange(Int32 startIndex, Int32 endIndex)
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.Batches.VeldridVertexBatch`1[[osu.Framework.Graphics.Rendering.Vertices.TexturedVertex2D, osu.Framework, Version=2023.327.0.0, Culture=neutral, PublicKeyToken=null]].Draw()
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Rendering.Renderer.FlushCurrentBatch(Nullable`1 source)
2023-03-26 18:41:40 [error]: at osu.Framework.Graphics.Veldrid.Buffers.VeldridUniformBuffer`1[[osu.Game.Graphics.Backgrounds.TriangleBorderData, osu.Game, Version=2023.326.1.0, Culture=neutral, PublicKeyToken=null]].set_Data(TriangleBorderData value)
```

**Comment by KingRainbow44** [comment]
Potentially related: when launching osu! on my iPhone 7 (13.5.1) after installing the renderer update, the game behaves in a similar manner. (game crashes on startup) No settings were changed. Reinstalling the app does not help. Related to #22978 if OpenGL is set as the default renderer on older devices.

will send logs if requested!

**Comment by KingRainbow44** [comment]
Additionally, this issue doesn’t appear to occur when setting the renderer to `OpenGL (Legacy)`.

**Comment by Minorsonek** [comment]
This is still happening on latest april version on Mac M1 Max

How can I change it back to Metal because game is literally broken right now

**Comment by bdach** [comment]
@Minorsonek this issue is about iOS specifically. open a new one if you're having trouble with macOS.
