### ISSUE TITLE
Crash on MacOS 11.7.3 (20G1116)

### ISSUE THREAD

**Issue by Dovermore** [ppy/osu#23164]
### Type

Crash to desktop

### Bug description

OSU crashes upon launching on MacOS 11.7.3 (20G1116) (intel). No graphic is displayed at all.

I have attached the crash log here. Looks like its trying to access `/usr/lib/libRosetta.dylib /usr/lib/libstdc++.6.dylib` which doesn't exist on my machine?

[osu!_2023-04-09-005104_pepega-mbp.txt](https://github.com/ppy/osu/files/11183553/osu._2023-04-09-005104_pepega-mbp.txt)

(Original extension is `.crash` not `.txt`, changed for compatibility with github)

### Version

2023.403.1.0 on .NET 6.0.13

### Logs

[runtime.log](https://github.com/ppy/osu/files/11183563/runtime.log)
[input.log](https://github.com/ppy/osu/files/11183564/input.log)

**Comment by Relavien** [comment]
Same problem on macOS 11.7.6 Big Sur (Intel-based).

**Comment by peppy** [comment]
Your version of macOS is probably too old.

**Comment by PYUDNG** [comment]
Same problem on macOS 11.7.6 Catalina (Intel-based).

**Comment by Relavien** [comment]
> Your version of macOS is probably too old.

Unfortunately I cannot update any further as Apple discontinued support for my version of Macbook with Big Sur. The previous versions of osu!lazer worked fine, just fyi.

**Comment by Dovermore** [comment]
> Update: I went through all of the most recent versions and the latest one which works fine for me is 2023.305.0

Going back to a version as early as 2022.127.0 does not help on my Machine.

**Comment by laol12** [comment]
Same issue here, last version that works with my mid-2012 MacBook Pro on 10.15.7 is 2023.305.0. I wonder what's crashing the game in the newer versions. Maybe it's finally time to use Opencore.

**Comment by peppy** [comment]
Your macOS version is still too old. Please update it.

**Comment by peppy** [comment]
For visibility, related reports suggest we may have regressed this in recent times:

https://github.com/ppy/osu/discussions/23181#discussioncomment-5776923
https://github.com/ppy/osu/discussions/23035

Maybe warrants further investigation.

**Comment by Relavien** [comment]
Replying here because of an related update:

> > Your version of macOS is probably too old.
> 
> Unfortunately I cannot update any further as Apple discontinued support for my version of Macbook with Big Sur. The previous versions of osu!lazer worked fine, just fyi. Update: I went through all of the most recent versions and the latest one which works fine for me is 2023.305.0

I updated my MacBook to the newest version (Ventura 13.3.1) via OpenCore and the issue still persists. I don't exactly know if it is the same issue, but the result is the same.
[osucrash.log](https://github.com/ppy/osu/files/11372236/osucrash.log)

 I also tried opening the executable directly via the terminal and its output was:

> 2023-05-02 12:32:34.546 osu![3074:74101] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2023-05-02 12:32:34.546 osu![3074:74101] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2023-05-02 12:32:34.547 osu![3074:74101] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
Unhandled exception. System.Exception: Shader compilation failed: program_source:2:10: fatal error: 'simd/simd.h' file not found
#include <simd/simd.h>
         ^~~~~~~~~~~~~
   at Veldrid.MetalBindings.MTLDevice.newLibraryWithSource(String source, MTLCompileOptions options)
   at Veldrid.MTL.MTLShader..ctor(ShaderDescription& description, MTLGraphicsDevice gd)
   at Veldrid.MTL.MTLResourceFactory.CreateShaderCore(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description)
   at osu.Framework.Graphics.Veldrid.Shaders.VeldridShader.loadToGpu()
   at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Graphics.Veldrid.Shaders.VeldridShader.EnsureShaderInitialised()
   at osu.Framework.Graphics.Veldrid.Shaders.VeldridShader.Bind()
   at osu.Framework.Graphics.Veldrid.Textures.VeldridTexture.Upload()
   at osu.Framework.Graphics.Rendering.Renderer.BeginFrame(Vector2 windowSize)
   at osu.Framework.Graphics.Veldrid.VeldridRenderer.BeginFrame(Vector2 windowSize)
   at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.BeginFrame(Vector2 windowSize)
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.processFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass138_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.RunSingleFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2Window.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos/ppy/osu/osu.Desktop/Program.cs:line 120
zsh: abort      /Users/vivu/Downloads/osu!.app/Contents/MacOS/osu!

After some testing on my end, the latest osu! version which works normally is still 2023.305.0
I hope this report helps!

**Comment by peppy** [comment]
Is anyone in this thread actually using apple hardware? If not, we cannot support your system.

**Comment by Relavien** [comment]
> Is anyone in this thread actually using apple hardware? If not, we cannot support your system.

I am, yes (MacBook Pro mid-2014). I had to update to Ventura via an unofficial method (OpenCore), since you said that my macOS version is too old and I thought maybe that'd fix it.

**Comment by peppy** [comment]
I see.

While the team you mention may think that, there's clearly an issue as some files that we presume are always included as part of the OS are missing. It's quite possible that your macbook is missing compatibility support for newer metal based applications.

**Comment by laol12** [comment]
I am using apple hardware, yes. MacBook Pro, mid-2012. It's a metal-compatible computer since it officially supports Mojave and Catalina, which require metal-compatible GPUs to run.

**Comment by SherlockWh0** [comment]
Hi there, just got a tidbit of information:

This webpage: [https://forum.freecad.org/viewtopic.php?p=520135](url) says that somebody's FreeCAD was acting up because their libRosetta.dylib was missing. But the thing is (i'm not great with system files), why would a Mac from 2012 need Rosetta?

**Comment by Joehuu** [comment]
After installing Big Sur on my M1, I installed the release and it had the same `libRosetta.dylib` people were talking about in the logs.

Until I compiled and ran the code and it resulted in a similar error to https://github.com/ppy/osu/issues/23010 and https://github.com/ppy/osu/issues/23198.

I have a fix which is to change https://github.com/ppy/veldrid-spirv/blob/c5e84982530e0b07de61949b23034c1985baac0c/.github/workflows/build.yml#L38 to `macos-11`, but https://github.com/ppy/osu#running-osu would need to be bumped as it is currently `macos 10.15+` ([github removed the image](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/)

Even if the github actions can be changed to work with 10.15 on a higher image, I can't really test it as macOS 11 is the minimum supported on an M1 and I don't want to go the Hackintosh route. At least we can fix users on macOS 11 and 12 for now?

**Comment by laol12** [comment]
Tested 2023.511.0. Seems to be fine on 10.15.7 now. Thanks all!
