### ISSUE TITLE
If the parent folder contains a #, osu will not start.

### ISSUE THREAD

**Issue by mallgrab** [ppy/osu#2319]
It also seems like within a hierarchy of folders if one of them contains a # which osu's folder is apart of, it will also not start.

https://github.com/ppy/osu-framework/blob/b59149e1cebe28675dcd2ebd014e5793d9626c09/osu.Framework/Game.cs#L103

Throws an exception right after this.

**Comment by peppy** [comment]
What's the exception? Also what operating system?

**Comment by mallgrab** [comment]
Happens on both windows 7 and linux.

```
[runtime:important] System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\user\Google Drive\Projects\osu.Framework.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at osu.Framework.IO.Stores.DllResourceStore..ctor(String dllName) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\IO\Stores\DllResourceStore.cs:line 16
   at osu.Framework.Game.load(FrameworkConfigManager config) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Game.cs:line 103

An unhandled exception of type 'osu.Framework.Allocation.RecursiveLoadException' occurred in mscorlib.dll

Unhandled Exception: osu.Framework.Allocation.RecursiveLoadException: Could not load file or assembly 'file:///C:\Users\user\Google Drive\Projects\osu.Framework.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at osu.Framework.Extensions.ExceptionExtensions.ExceptionExtensions.Rethrow(Exception exception) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Extensions\ExceptionExtensions\ExceptionExtensions.cs:line 19
   at osu.Framework.Allocation.DependencyContainer.<>c__DisplayClass6_1.<register>b__5(Object instance) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:line 92
   at osu.Framework.Allocation.DependencyContainer.<>c__DisplayClass6_3.<register>b__8(Action`1 init) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:line 105
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at osu.Framework.Allocation.DependencyContainer.<>c__DisplayClass6_2.<register>b__7(DependencyContainer container, Object instance) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:line 105
   at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance, Boolean autoRegister, Boolean lazy) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Allocation\DependencyContainer.cs:line 193
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Graphics\Drawable.cs:line 207
   at osu.Framework.Platform.GameHost.bootstrapSceneGraph(Game game) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 486
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\Users\user\Google Drive\Projects\C#\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 395
   at osu.Desktop.Program.Main(String[] args) in C:\Users\user\Google Drive\Projects\C#\osu\osu.Desktop\Program.cs:line 47
The program '[6916] osu!.exe' has exited with code 0 (0x0).
```
