### ISSUE TITLE
Maps not loading

### ISSUE THREAD

**Issue by Dr-Small** [ppy/osu#23378]
### Bug description

I tried to open maps but they take an infinite amount of time to load.

### Version

2023.419.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11377835/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11377836/updater.log)
[database.log](https://github.com/ppy/osu/files/11377837/database.log)
[input.log](https://github.com/ppy/osu/files/11377838/input.log)
[network.log](https://github.com/ppy/osu/files/11377839/network.log)
[performance.log](https://github.com/ppy/osu/files/11377840/performance.log)

**Comment by peppy** [comment]
Please reinstall your game, somehow you are missing files.

Relevant logs:

```csharp
2023-05-02 21:06:53 [error]: An unhandled error has occurred.
2023-05-02 21:06:53 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'FFmpeg.AutoGen, Version=4.3.0.1, Culture=neutral, PublicKeyToken=9b7632533a381715'. The system cannot find the file specified.
2023-05-02 21:06:53 [error]: File name: 'FFmpeg.AutoGen, Version=4.3.0.1, Culture=neutral, PublicKeyToken=9b7632533a381715'
2023-05-02 21:06:53 [error]: at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
2023-05-02 21:06:53 [error]: at System.Reflection.RtFieldInfo.InitializeFieldType()
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Drawable.<>c.<getUnbindAction>b__18_1(FieldInfo f)
2023-05-02 21:06:53 [error]: at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
2023-05-02 21:06:53 [error]: at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Drawable.<getUnbindAction>g__cacheUnbindAction|18_0(Type ourType)
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Drawable.getUnbindAction()
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2023-05-02 21:06:53 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
```
