### ISSUE TITLE
Editor crashes if song is selected after elements being placed

### ISSUE THREAD

**Issue by CamiKaseM7** [ppy/osu#23725]
### Type

Crash to desktop

### Bug description

It's not a common situation but if you create a new beatmap, place an object, then select the audio and change back to compose the games crashes.

### Screenshots or videos

https://github.com/ppy/osu/assets/20014462/7c7c58fd-2b40-4fe0-99c4-de1481a9dba2

### Version

Development build

### Logs

[database.log](https://github.com/ppy/osu/files/11628746/database.log)
[input.log](https://github.com/ppy/osu/files/11628747/input.log)
[performance.log](https://github.com/ppy/osu/files/11628748/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11628749/runtime.log)

**Comment by bdach** [comment]
That is a debug build-specific assertion tripping.

```
2023-06-01 19:19:29 [error]: NUnit.Framework.AssertionException: Timeline is rendering many ticks (520):
2023-06-01 19:19:29 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2)
2023-06-01 19:19:29 [error]: at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
2023-06-01 19:19:29 [error]: at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
2023-06-01 19:19:29 [error]: at System.Diagnostics.Debug.Fail(String message, String detailMessage)
2023-06-01 19:19:29 [error]: at System.Diagnostics.Debug.Fail(String message)
2023-06-01 19:19:29 [error]: at osu.Game.Screens.Edit.Compose.Components.Timeline.TimelineTickDisplay.createTicks() in /home/camilo/Repos/osu/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineTickDisplay.cs:line 163
2023-06-01 19:19:29 [error]: at osu.Game.Screens.Edit.Compose.Components.Timeline.TimelineTickDisplay.Update() in /home/camilo/Repos/osu/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineTickDisplay.cs:line 98
2023-06-01 19:19:29 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

Does this happen for you with any track or just a specific one? Because it did not happen to me when I tried it on a random mp3 on my machine.

**Comment by CamiKaseM7** [comment]
> That is a debug build-specific assertion tripping.

Yeah, just tested and if I compile the project with the `-c Release` flag it works as intended, but if I don't it breaks.
> Does this happen for you with any track or just a specific one?

I thought it was on any track, I tried with two different files and both made the game crash, just tried with a third one and nothing happened.
This one made it crash [Reflect Eurobeat Remix (w@tiannya).zip](https://github.com/ppy/osu/files/11630857/Reflect.Eurobeat.Remix.w%40tiannya.zip) (Can't send it as mp3)

**Comment by Charlese2** [comment]
When you go from the default 10 second "track" to that 4 minute track it is long enough to have more than 512 timeline ticks in total (at 60 BPM with 1/4 dividers) because `DrawWidth` isn't updated until the ticks are already created.

https://github.com/ppy/osu/assets/1207515/9e4d78cc-9370-48e5-a2bd-30dc9deb308c

![image](https://github.com/ppy/osu/assets/1207515/8c1a3a22-5905-464b-9196-a850004b7804)

https://github.com/ppy/osu/blob/51149343fba8f38cfe6a4954bec324cbe8234aa6/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineTickDisplay.cs#L84-L86

With a small `DrawWidth` from starting with a short "track" the `newRange/visibleRange` ends up being most of the song.

**Comment by peppy** [comment]
This may be able to be resolved by changing the application of zoom to happen before the timeline is reconstructed for the new track.

Or making the `TimelineTickDisplay` aware of the beatmap track changing and handling it gracefully.
