### ISSUE TITLE
Invalid mod for ruleset SY (osu!)

### ISSUE THREAD

**Issue by zeankundev** [ppy/osu#23980]
### Type

Game behaviour

### Bug description

Playing any beatmap with the recently added mod (Synesthesia) directly can't submit scores (any beatmap rank). 

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/58360911/8fb3e292-46a8-4c5b-8df1-4ab2624717a8)

### Version

2023.621.0-lazer

### Logs

2023-06-21 07:10:34 [verbose]: ----------------------------------------------------------
2023-06-21 07:10:34 [verbose]: runtime Log for zeanf (LogLevel: Verbose)
2023-06-21 07:10:34 [verbose]: Running osu 2023.621.0.0 on .NET 6.0.18
2023-06-21 07:10:34 [verbose]: Environment: Windows (Microsoft Windows NT 10.0.19045.0), 4 cores
2023-06-21 07:10:34 [verbose]: ----------------------------------------------------------
2023-06-21 07:10:34 [verbose]: 🖼️ Configuration renderer choice: Direct3D11
2023-06-21 07:10:34 [verbose]: 🖼️ Renderer fallback order: [ Direct3D 11, OpenGL (Legacy), OpenGL, Vulkan ]
2023-06-21 07:10:34 [verbose]: 🖼️ Initialising "Veldrid" renderer with "Direct3D11" surface
2023-06-21 07:10:35 [verbose]: Updated display mode to desktop resolution: 1366x768@50, SDL_PIXELFORMAT_RGB888
2023-06-21 07:10:35 [verbose]: Direct3D 11 Initialized
2023-06-21 07:10:35 [verbose]: Direct3D 11 Feature Level:           11.0
2023-06-21 07:10:35 [verbose]: Direct3D 11 Adapter:                 Intel(R) HD Graphics 4000
2023-06-21 07:10:35 [verbose]: Direct3D 11 Dedicated Video Memory:  32 MB
2023-06-21 07:10:35 [verbose]: Direct3D 11 Dedicated System Memory: 0 MB
2023-06-21 07:10:35 [verbose]: Direct3D 11 Shared System Memory:    1760 MB
2023-06-21 07:10:35 [verbose]: 🖼️ Renderer initialised!
2023-06-21 07:10:35 [verbose]: Host execution state changed to Running
2023-06-21 07:10:35 [verbose]: Execution mode changed to MultiThreaded
2023-06-21 07:10:35 [verbose]: 🔈 BASS initialised
2023-06-21 07:10:35 [verbose]: BASS version:           2.4.16.7
2023-06-21 07:10:35 [verbose]: BASS FX version:        2.4.12.6
2023-06-21 07:10:35 [verbose]: BASS MIX version:       2.4.11.1
2023-06-21 07:10:35 [verbose]: Device:                 No sound
2023-06-21 07:10:35 [verbose]: Driver:
2023-06-21 07:10:35 [verbose]: Update period:          5 ms
2023-06-21 07:10:35 [verbose]: Device buffer length:   10 ms
2023-06-21 07:10:35 [verbose]: Playback buffer length: 100 ms
2023-06-21 07:10:35 [verbose]: 🔈 BASS initialised
2023-06-21 07:10:35 [verbose]: BASS version:           2.4.16.7
2023-06-21 07:10:35 [verbose]: BASS FX version:        2.4.12.6
2023-06-21 07:10:35 [verbose]: BASS MIX version:       2.4.11.1
2023-06-21 07:10:35 [verbose]: Device:                 Default
2023-06-21 07:10:35 [verbose]: Driver:
2023-06-21 07:10:35 [verbose]: Update period:          5 ms
2023-06-21 07:10:35 [verbose]: Device buffer length:   10 ms
2023-06-21 07:10:35 [verbose]: Playback buffer length: 100 ms
2023-06-21 07:10:35 [verbose]: Beginning realm file store cleanup
2023-06-21 07:10:35 [verbose]: Finished realm file store cleanup (0 of 1871 deleted)
2023-06-21 07:10:36 [verbose]: Opened realm "C:\Users\zeanf\AppData\Roaming\osu\client.realm" at version 30
2023-06-21 07:10:37 [verbose]: 🖍️ Shader Texture2D/Texture compiled!
2023-06-21 07:10:38 [verbose]: 🖍️ Shader Texture2D/CircularProgress compiled!
2023-06-21 07:10:38 [verbose]: Updated display mode to fullscreen resolution: 1366x768@50, SDL_PIXELFORMAT_RGB888
2023-06-21 07:10:39 [verbose]: Loading FPSCounter...
2023-06-21 07:10:40 [verbose]: Loaded FPSCounter!
2023-06-21 07:10:40 [verbose]: Loading VersionManager...
2023-06-21 07:10:40 [verbose]: Loaded VersionManager!
2023-06-21 07:10:40 [verbose]: Loading OsuLogo...
2023-06-21 07:10:40 [verbose]: 🖍️ Shader Texture2D/TriangleBorder compiled!
2023-06-21 07:10:40 [verbose]: Loaded OsuLogo!
2023-06-21 07:10:40 [verbose]: Loading Toolbar...
2023-06-21 07:10:40 [verbose]: 📺 OsuScreenStack#567(depth:1) loading Loader#451
2023-06-21 07:10:40 [verbose]: 📺 OsuScreenStack#567(depth:1) entered Loader#451
2023-06-21 07:10:41 [verbose]: Loaded Toolbar!
2023-06-21 07:10:41 [verbose]: Loading VolumeOverlay...
2023-06-21 07:10:41 [verbose]: 🖍️ Shader Texture2D/Blur compiled!
2023-06-21 07:10:41 [verbose]: 🖍️ Shader Texture2D/Blur compiled!
2023-06-21 07:10:41 [verbose]: Loaded VolumeOverlay!
2023-06-21 07:10:41 [verbose]: Loading OnScreenDisplay...
2023-06-21 07:10:41 [verbose]: Loaded OnScreenDisplay!
2023-06-21 07:10:41 [verbose]: Loading NotificationOverlay...
2023-06-21 07:10:41 [verbose]: Loaded NotificationOverlay!
2023-06-21 07:10:41 [verbose]: Loading LegacyImportManager...
2023-06-21 07:10:41 [verbose]: Loaded LegacyImportManager!
2023-06-21 07:10:41 [verbose]: Loading ScreenshotManager...
2023-06-21 07:10:41 [verbose]: Loaded ScreenshotManager!
2023-06-21 07:10:41 [verbose]: Loading SquirrelUpdateManager...
2023-06-21 07:10:41 [verbose]: Loaded SquirrelUpdateManager!
2023-06-21 07:10:41 [verbose]: Loading FirstRunSetupOverlay...
2023-06-21 07:10:41 [verbose]: Loaded FirstRunSetupOverlay!
2023-06-21 07:10:41 [verbose]: Loading ManageCollectionsDialog...
2023-06-21 07:10:41 [verbose]: Loaded ManageCollectionsDialog!
2023-06-21 07:10:41 [verbose]: Loading BeatmapListingOverlay...
2023-06-21 07:10:41 [verbose]: Requesting catch-up from 7640975
2023-06-21 07:10:41 [verbose]: Requesting any changes since last known queue id 7640975
2023-06-21 07:10:42 [verbose]: Catch-up complete at 7640975
2023-06-21 07:10:42 [verbose]: Loaded BeatmapListingOverlay!
2023-06-21 07:10:42 [verbose]: Loading DashboardOverlay...
2023-06-21 07:10:42 [verbose]: Loaded DashboardOverlay!
2023-06-21 07:10:42 [verbose]: Loading NewsOverlay...
2023-06-21 07:10:42 [verbose]: Loaded NewsOverlay!
2023-06-21 07:10:42 [verbose]: Loading RankingsOverlay...
2023-06-21 07:10:42 [verbose]: Loaded RankingsOverlay!
2023-06-21 07:10:42 [verbose]: Loading ChannelManager...
2023-06-21 07:10:42 [verbose]: Loaded ChannelManager!
2023-06-21 07:10:42 [verbose]: Loading ChatOverlay...
2023-06-21 07:10:42 [verbose]: Loaded ChatOverlay!
2023-06-21 07:10:42 [verbose]: Loading MessageNotifier...
2023-06-21 07:10:42 [verbose]: Loaded MessageNotifier!
2023-06-21 07:10:42 [verbose]: Loading SettingsOverlay...
2023-06-21 07:10:42 [verbose]: 🖍️ Shader CursorTrail/Texture compiled!
2023-06-21 07:10:42 [verbose]: Loaded SettingsOverlay!
2023-06-21 07:10:42 [verbose]: Loading ChangelogOverlay...
2023-06-21 07:10:42 [verbose]: Loaded ChangelogOverlay!
2023-06-21 07:10:42 [verbose]: Loading UserProfileOverlay...
2023-06-21 07:10:42 [verbose]: Loaded UserProfileOverlay!
2023-06-21 07:10:42 [verbose]: Loading BeatmapSetOverlay...
2023-06-21 07:10:42 [verbose]: Loaded BeatmapSetOverlay!
2023-06-21 07:10:42 [verbose]: Loading WikiOverlay...
2023-06-21 07:10:42 [verbose]: Loaded WikiOverlay!
2023-06-21 07:10:42 [verbose]: Loading SkinEditorOverlay...
2023-06-21 07:10:42 [verbose]: Loaded SkinEditorOverlay!
2023-06-21 07:10:42 [verbose]: Loading LoginOverlay...
2023-06-21 07:10:42 [verbose]: Loaded LoginOverlay!
2023-06-21 07:10:42 [verbose]: Loading NowPlayingOverlay...
2023-06-21 07:10:42 [verbose]: Loaded NowPlayingOverlay!
2023-06-21 07:10:42 [verbose]: Loading AccountCreationOverlay...
2023-06-21 07:10:42 [verbose]: 📺 ScreenStack#679(depth:1) scheduling push ScreenWelcome#171
2023-06-21 07:10:42 [verbose]: Loaded AccountCreationOverlay!
2023-06-21 07:10:42 [verbose]: Loading DialogOverlay...
2023-06-21 07:10:42 [verbose]: Loaded DialogOverlay!
2023-06-21 07:10:42 [verbose]: Loading HighPerformanceSession...
2023-06-21 07:10:42 [verbose]: Loaded HighPerformanceSession!
2023-06-21 07:10:42 [verbose]: Loading BackgroundBeatmapProcessor...
2023-06-21 07:10:42 [verbose]: Loaded BackgroundBeatmapProcessor!
2023-06-21 07:10:42 [verbose]: Beginning background beatmap processing..
2023-06-21 07:10:42 [verbose]: Querying for beatmap sets to reprocess...
2023-06-21 07:10:43 [verbose]: Found 0 beatmap sets which require reprocessing.
2023-06-21 07:10:43 [verbose]: Querying for scores to reprocess...
2023-06-21 07:10:43 [verbose]: Found 0 scores which require reprocessing.
2023-06-21 07:10:43 [verbose]: Finished background beatmap processing!
2023-06-21 07:10:43 [verbose]: 🖍️ Shader Texture3D/Texture compiled!
2023-06-21 07:10:43 [verbose]: 📺 OsuScreenStack#567(depth:1) suspended Loader#451 (waiting on Disclaimer#549)
2023-06-21 07:10:43 [verbose]: 📺 OsuScreenStack#567(depth:2) entered Disclaimer#549
2023-06-21 07:10:44 [verbose]: Current channel changed to #osu
2023-06-21 07:10:50 [verbose]: 📺 OsuScreenStack#567(depth:2) suspended Disclaimer#549 (waiting on IntroTriangles#431)
2023-06-21 07:10:50 [verbose]: 📺 OsuScreenStack#567(depth:3) entered IntroTriangles#431
2023-06-21 07:10:50 [verbose]: 📺 BackgroundScreenStack#630(depth:1) loading BackgroundScreenDefault#270
2023-06-21 07:10:50 [verbose]: Game-wide working beatmap updated to cYsmix - triangles (peppy) [peppy]
2023-06-21 07:10:50 [verbose]: 🌅 Background change queued
2023-06-21 07:10:50 [verbose]: 📺 BackgroundScreenStack#630(depth:1) entered BackgroundScreenDefault#270
2023-06-21 07:10:50 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2023-06-21 07:10:50 [verbose]: 🖍️ Shader LogoAnimation/LogoAnimation compiled!
2023-06-21 07:10:50 [verbose]: 🌅 Background change queued
2023-06-21 07:10:54 [verbose]: 📺 OsuScreenStack#567(depth:3) suspended IntroTriangles#431 (waiting on MainMenu#263)
2023-06-21 07:10:54 [verbose]: 📺 OsuScreenStack#567(depth:4) entered MainMenu#263
2023-06-21 07:10:54 [verbose]: ⚠️ You are now running osu! 2023.621.0-lazer.
2023-06-21 07:10:54 [verbose]: Click to see what's new!
2023-06-21 07:10:55 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2023-06-21 07:11:01 [verbose]: ButtonSystem's state changed from TopLevel to Play
2023-06-21 07:11:02 [verbose]: 📺 OsuScreenStack#567(depth:4) suspended MainMenu#263 (waiting on PlaySongSelect#494)
2023-06-21 07:11:02 [verbose]: ButtonSystem's state changed from Play to EnteringMode
2023-06-21 07:11:02 [verbose]: 📺 OsuScreenStack#567(depth:5) entered PlaySongSelect#494
2023-06-21 07:11:02 [verbose]: 📺 BackgroundScreenStack#630(depth:2) loading BackgroundScreenBeatmap#431
2023-06-21 07:11:02 [verbose]: 📺 BackgroundScreenStack#630(depth:2) suspended BackgroundScreenDefault#270 (waiting on BackgroundScreenBeatmap#431)
2023-06-21 07:11:02 [verbose]: 📺 BackgroundScreenStack#630(depth:2) entered BackgroundScreenBeatmap#431
2023-06-21 07:11:02 [verbose]: Song select updating selection with beatmap:70b47854-6bc4-42fa-9037-ba2d6cebff7e ruleset:osu
2023-06-21 07:11:02 [verbose]: Song select changing beatmap from "cYsmix - triangles (peppy) [peppy]" to "HyuN - Illusion of Inflict (schoolboy) [Easy]"
2023-06-21 07:11:02 [verbose]: Game-wide working beatmap updated to HyuN - Illusion of Inflict (schoolboy) [Easy]
2023-06-21 07:11:02 [verbose]: Song select working beatmap updated to HyuN - Illusion of Inflict (schoolboy) [Easy]
2023-06-21 07:11:02 [verbose]: Song select decided to ensurePlayingSelected
2023-06-21 07:11:02 [verbose]: 🌅 Background change queued
2023-06-21 07:11:04 [verbose]: Focus contention triggered by SongSelect+SoloModSelectOverlay.
2023-06-21 07:11:17 [verbose]: Song select updating selection with beatmap:e1b357a7-3f40-49fa-8782-3aa083703ab9 ruleset:osu
2023-06-21 07:11:17 [verbose]: Song select changing beatmap from "HyuN - Illusion of Inflict (schoolboy) [Easy]" to "Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Smiling Easy]"
2023-06-21 07:11:17 [verbose]: Game-wide working beatmap updated to Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Smiling Easy]
2023-06-21 07:11:17 [verbose]: Song select working beatmap updated to Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Smiling Easy]
2023-06-21 07:11:17 [verbose]: Song select decided to ensurePlayingSelected
2023-06-21 07:11:18 [verbose]: Song select updating selection with beatmap:591ab66b-5177-49d1-add2-78100264aebe ruleset:osu
2023-06-21 07:11:18 [verbose]: Song select changing beatmap from "Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Smiling Easy]" to "Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Sister Advanced Collab]"
2023-06-21 07:11:18 [verbose]: Game-wide working beatmap updated to Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Sister Advanced Collab]
2023-06-21 07:11:18 [verbose]: Song select working beatmap updated to Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Sister Advanced Collab]
2023-06-21 07:11:18 [verbose]: Received beatmap updates 1 updates with last id 7640976
2023-06-21 07:11:18 [verbose]: 📺 OsuScreenStack#567(depth:5) suspended PlaySongSelect#494 (waiting on PlayerLoader#181)
2023-06-21 07:11:19 [verbose]: 📺 OsuScreenStack#567(depth:6) loading PlayerLoader#181
2023-06-21 07:11:19 [verbose]: 📺 OsuScreenStack#567(depth:6) entered PlayerLoader#181
2023-06-21 07:11:21 [verbose]: Score submission token retrieved (105552244)
2023-06-21 07:11:21 [verbose]: 📺 OsuScreenStack#567(depth:6) suspended PlayerLoader#181 (waiting on SoloPlayer#196)
2023-06-21 07:11:21 [verbose]: 📺 OsuScreenStack#567(depth:7) entered SoloPlayer#196
2023-06-21 07:11:21 [verbose]: GameplayClockContainer seeking to -1362
2023-06-21 07:11:23 [verbose]: Received beatmap updates 1 updates with last id 7640977
2023-06-21 07:12:54 [error]: Failed to submit score (invalid mod for ruleset: SY)
2023-06-21 07:12:54 [error]: osu.Game.Online.API.APIException: invalid mod for ruleset: SY
2023-06-21 07:12:54 [error]: ---> System.Net.WebException: UnprocessableEntity
2023-06-21 07:12:54 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2023-06-21 07:12:54 [error]: at osu.Framework.IO.Network.WebRequest.beginResponse(CancellationToken cancellationToken)
2023-06-21 07:12:54 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken)
2023-06-21 07:12:54 [error]: --- End of inner exception stack trace ---
2023-06-21 07:12:55 [verbose]: 📺 OsuScreenStack#567(depth:7) suspended SoloPlayer#196 (waiting on SoloResultsScreen#184)
2023-06-21 07:12:55 [verbose]: 📺 OsuScreenStack#567(depth:8) loading SoloResultsScreen#184
2023-06-21 07:12:55 [verbose]: 📺 OsuScreenStack#567(depth:8) entered SoloResultsScreen#184
2023-06-21 07:12:55 [verbose]: ⚠️ Failed to submit score (invalid mod for ruleset: SY)
2023-06-21 07:12:55 [verbose]: 
2023-06-21 07:12:55 [verbose]: This error has been automatically reported to the devs.
2023-06-21 07:13:28 [verbose]: Received beatmap updates 1 updates with last id 7640978
2023-06-21 07:13:34 [verbose]: Received beatmap updates 2 updates with last id 7640980
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:7) exit from SoloResultsScreen#184
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:7) resume to SoloPlayer#196
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:6) exit from SoloPlayer#196
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:6) resume to PlayerLoader#181
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:5) exit from PlayerLoader#181
2023-06-21 07:14:15 [verbose]: 📺 OsuScreenStack#567(depth:5) resume to PlaySongSelect#494
2023-06-21 07:14:15 [verbose]: Song select working beatmap updated to Blend A - Bon Appetit S (TV Size ver.) (Nekoraw) [Sister Advanced Collab]
2023-06-21 07:14:15 [verbose]: Song select updating selection with beatmap:591ab66b-5177-49d1-add2-78100264aebe ruleset:osu
2023-06-21 07:14:15 [verbose]: Focus contention triggered by SongSelect+SoloModSelectOverlay.
2023-06-21 07:14:18 [verbose]: Received beatmap updates 1 updates with last id 7640981
2023-06-21 07:14:23 [verbose]: Focus contention triggered by NowPlayingOverlay.
2023-06-21 07:15:18 [verbose]: Received beatmap updates 1 updates with last id 7640982
2023-06-21 07:15:23 [verbose]: Focus contention triggered by SettingsOverlay.
2023-06-21 07:15:23 [verbose]: Received beatmap updates 2 updates with last id 7640984
2023-06-21 07:15:27 [verbose]: Scrolling to DebugSection..
2023-06-21 07:15:27 [verbose]: Reattempting scroll to DebugSection due to change in position
2023-06-21 07:15:27 [verbose]: Scrolling to DebugSection..
2023-06-21 07:15:28 [verbose]: Scroll operation interrupted by user scroll
2023-06-21 07:15:29 [verbose]: Focus contention triggered by ChangelogOverlay.
2023-06-21 07:15:29 [verbose]: Focus contention triggered by ChangelogOverlay.
2023-06-21 07:15:32 [verbose]: Focus contention triggered by ChangelogOverlay.
2023-06-21 07:15:43 [verbose]: Focus contention triggered by SettingsOverlay.
2023-06-21 07:15:53 [verbose]: Scrolling to GeneralSection..
2023-06-21 07:15:54 [verbose]: Finished scrolling to GeneralSection!

**Comment by peppy** [comment]
Should now be resolved, thanks for pointing this out.
