### ISSUE TITLE
Switching screen mode causes crash on lazer

### ISSUE THREAD

**Issue by MidKnightXI** [ppy/osu#24012]
### Type

Crash to desktop

### Bug description

I'm currently having a lot of screen tearing/really low fps (even if apparently the game is running at 150+ fps so I decided to change from fullscreen to borderless.

When changing I heard a weird noise in my headset and the game absolutely froze for 10 seconds until it crashed.

Also the bug happens for every screenmode chosen.

I can't provide videos because my internet is too slow, sorry about that.

### Version

2023.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/11847223/database.log)
[network.log](https://github.com/ppy/osu/files/11847225/network.log)
[performance.log](https://github.com/ppy/osu/files/11847226/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11847227/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11847229/updater.log)

**Comment by bdach** [comment]
Well...

```
2023-06-23 10:00:13 [error]: An unhandled error has occurred.
2023-06-23 10:00:13 [error]: SharpGen.Runtime.SharpGenException: HRESULT: [0x80070005], Module: [General], ApiCode: [E_ACCESSDENIED/General access denied error], Message: [Access is denied.
2023-06-23 10:00:13 [error]: ]
2023-06-23 10:00:13 [error]: at SharpGen.Runtime.Result.ThrowFailureException()
2023-06-23 10:00:13 [error]: at Vortice.DXGI.IDXGIFactory.CreateSwapChain(IUnknown device, SwapChainDescription desc)
2023-06-23 10:00:13 [error]: at Veldrid.D3D11.D3D11Swapchain.recreateSwapchain()
2023-06-23 10:00:13 [error]: at osu.Framework.Platform.GameHost.DrawFrame()
2023-06-23 10:00:13 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

Not sure what to do about _that_. Driver error perhaps?

@MidKnightXI can you try checking for graphics driver updates? Alternatively, you could try using the "OpenGL (Legacy)" renderer in settings and see whether that works any better?

**Comment by MidKnightXI** [comment]
I updated my drivers and still same problems for D11

Using OpenGL works properly (not the legacy one).

Using a legacy won't fix the problem with Direct11 on your side if I have this problem I guess many other people will have it too.

**Comment by MidKnightXI** [comment]
Also, I don't know if it can be useful for you but here is my config:

Win11
R7 3800X
GeForce 1070 8Gb
16Gb RAM

**Comment by bdach** [comment]
> Using a legacy feature won't fix the problem with Direct11 on your side if I have this problem I guess many other people will have it too.

The d3d renderer has been available for months now and this is the first I'm seeing this type of error. So I'm not sure where you're getting that from.

> Using OpenGL works properly (not the legacy one).

I said to use the legacy one for now since if anything it's _more_ battle-tested than the non-legacy one for the time being, and it's not going anywhere in the near future. But if non-legacy works for you then sure why not.

**Comment by bdach** [comment]
Also, any overlays running? Weird game add-ons? Anything out of the ordinary?

**Comment by MidKnightXI** [comment]
I didn't have anything opened but maybe I'm thinking about maybe the Armory Crate or AI Suite 3 softwares from Asus or Vanguard that may have cause the problem maybe?

**Comment by MidKnightXI** [comment]
Also I've WSL installed on my computer, I don't think it can be related to that but as it is out of the ordinary for the everyday gamer I prefered to mention it.

**Comment by bdach** [comment]
> I didn't have anything opened but maybe I'm thinking about maybe the Armory Crate or AI Suite 3 softwares from Asus or Vanguard that may have cause the problem maybe?

That's not impossible. You could try turning off some of that and seeing if anything helps.

**Comment by MidKnightXI** [comment]
Just tried to switch back to D11 without Vanguard or any Asus utilities and still the same problem happen

crash on window type change, stutters and screen tearing

**Comment by Glasses-are-90-me** [comment]
Can replicate changing output modes crashing game, it plays sound while the game screen freezes, before exiting entirely
Not ann issue for me for me because I don't change modes
NVIDIA GeForce GTX 1070 Ti
Also have asus 
[runtime.log](https://github.com/ppy/osu/files/12343242/runtime.log)
