### ISSUE TITLE
Guard against data loss in editor

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24031]
To avoid user error, we should probably disallow saving when a beatmap goes from having objects to having no object.

Alternative would be to offer a save history per beatmap (ie. last x saves or similar).

Adding a confirm on exit should be easy, but will require special attention for the `confirmExitWithSave` scenario.

### Discussed in https://github.com/ppy/osu/discussions/24020

<div type='discussions-op-text'>

<sup>Originally posted by **whatwillweget** June 24, 2023</sup>
Today, I was mapping an beatmap in osu!lazer (2023.621.0) and suddenly the beatmap was corrupted after saving, lost all data for one difficulty and reverted data for an another difficulty, which costs hours of work.

~~To fix this issue, auto-backups can save the data lost if the beatmap has been corrupted.
Auto-backups are also useful to revert the beatmap back to the old version when a mapper is unsatisfied with the beatmap.~~</div>

**Comment by whatwillweget** [comment]
For example, saving a beatmap while loading the editor can cause the issue like this, but the issue caused in the discussion was another case when saving after exiting the editor.

```
13:55:03 [verbose]: Song select changing beatmap from "MORE MORE JUMP! × Hatsune Miku - IF (get2day) [Perfect Premonition]" to "MORE MORE JUMP! × Hatsune Miku - IF (get2day) [Perfect Premonition]"
2023-06-25 13:55:03 [error]: An unhandled error has occurred.
2023-06-25 13:55:03 [error]: System.InvalidOperationException: Can not set value to "MORE MORE JUMP! × Hatsune Miku - IF (get2day) [Perfect Premonition]" as bindable is disabled.
2023-06-25 13:55:03 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2023-06-25 13:55:03 [error]: at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass102_0.<performUpdateSelected>g__run|0()
2023-06-25 13:55:03 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2023-06-25 13:55:03 [error]: at osu.Framework.Threading.Scheduler.Update()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-06-25 13:55:03 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-06-25 13:55:03 [error]: at osu.Framework.Threading.GameThread.processFrame()
2023-06-25 13:55:03 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2023-06-25 13:55:03 [verbose]: ⚠️ An unhandled error has occurred.
2023-06-25 13:55:03 [verbose]: 
2023-06-25 13:55:03 [verbose]: This error has been automatically reported to the devs.
```

**Comment by whatwillweget** [comment]
For some reason, I was lucky enough to experience on only my local beatmap, but in #24034 was terribly worse, which I remembered that the error was similar to mine.

**Comment by peppy** [comment]
We should also probably confirm if scores are going to be deleted due to a save operation (see https://github.com/ppy/osu/discussions/24047).

**Comment by cihe13375** [comment]
Two additional features that I feel would be helpful on this topic:

1) create auto backups of the beatmap every X minutes/operations, and the user may recover from those backups when they want
2) try to create a backup before exit when osu! knows it will crash (unhandled exceptions). I don't know if this is possible though.

The reason is that even if osu! itself may be designed with stability in mind, it cannot prevent accidental crash due to external factors like hardware or OS issues (In my own experience, it's mostly about the GPU watchdog timeout caused by some Folding@Home work units; it does not affect normal use or FAH itself, but is likely a reason for osu! crashing on my PC, both on lazer and stable)

**Comment by bdach** [comment]
> it cannot prevent accidental crash due to external factors like hardware or OS issues (In my own experience, it's mostly about the GPU watchdog timeout caused by some Folding@Home work units; it does not affect normal use or FAH itself, but is likely a reason for osu! crashing on my PC, both on lazer and stable)

If anything of this sort is going on then trying to anticipate it and save just-in-time-before-crash is a fool's errand, I'd say. Auto-backups are possibly okay, though, although that's probably not in the scope of this issue.
