### ISSUE TITLE
Random crashes on iOS

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24242]
I've seen this on sentry already but no idea why this would be happening. Seems new.

### Discussed in https://github.com/ppy/osu/discussions/24240

<div type='discussions-op-text'>

<sup>Originally posted by **GSculerlor** July 16, 2023</sup>
happens randomly (at least crashed at launch, song select, and during gameplay on my iPad)

running on latest release (2023.716.0) on my iPad pro 4th gen (M2) OS version 16.5.1

logs:
```
2023-07-16 12:34:56 [verbose]: GameplayClockContainer seeking to -574
2023-07-16 12:36:01 [verbose]: ⚠️ An unhandled error has occurred.
2023-07-16 12:36:01 [verbose]: 
2023-07-16 12:36:01 [verbose]: This error has been automatically reported to the devs.
2023-07-16 12:36:01 [error]: An unhandled error has occurred.
2023-07-16 12:36:01 [error]: System.InvalidOperationException: InvalidOperation_EmptyStack
2023-07-16 12:36:01 [error]: at System.Collections.Generic.Stack`1[[osu.Framework.Statistics.PerformanceCollectionType, osu.Framework, Version=2023.715.0.0, Culture=neutral, PublicKeyToken=null]].ThrowForEmptyStack()
2023-07-16 12:36:01 [error]: at System.Collections.Generic.Stack`1[[osu.Framework.Statistics.PerformanceCollectionType, osu.Framework, Version=2023.715.0.0, Culture=neutral, PublicKeyToken=null]].Peek()
2023-07-16 12:36:01 [error]: at osu.Framework.Statistics.PerformanceMonitor.BeginCollecting(PerformanceCollectionType type)
2023-07-16 12:36:01 [error]: at osu.Framework.Platform.GameHost.windowUpdate()
2023-07-16 12:36:01 [error]: at osu.Framework.Platform.SDL2Window.RunFrame()
2023-07-16 12:36:01 [error]: at osu.Framework.iOS.IOSWindow.runFrame(IntPtr userdata)
2023-07-16 12:36:01 [error]: at osu.Framework.iOS.GameApplication.Main(Game target)
2023-07-16 12:36:01 [error]: at osu.iOS.Application.Main(String[] args)
2023-07-16 12:36:01 [error]: --- End of stack trace from previous location ---
2023-07-16 12:36:01 [error]: at osu.Framework.iOS.GameApplication.Main(Game target)
2023-07-16 12:36:01 [error]: at osu.iOS.Application.Main(String[] args)
2023-07-16 12:36:01 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
```</div>

**Comment by mktwos** [comment]
Happens to me as well, using iPad pro 6th gen M2. Game is unplayable until they fix it.

**Comment by bdach** [comment]
Looks likely to be a regression from https://github.com/ppy/osu-framework/pull/5898
