### ISSUE TITLE
Crash in bubbles mod

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24444]
Happened during spectating multiplayer. Have not investigate how this can happen yet (likely `HitObject` being `null`).

```csharp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Game.Rulesets.Osu.Mods.OsuModBubbles.BubbleDrawable.getPosition(DrawableOsuHitObject drawableObject) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModBubbles.cs:line 201
   at osu.Game.Rulesets.Osu.Mods.OsuModBubbles.BubbleDrawable.PrepareForUse() in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModBubbles.cs:line 162
   at osu.Framework.Graphics.Pooling.PoolableDrawable.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

**Comment by LianSheng197** [comment]
This can also happen on solo mode. (Although I think this is edge case)

In [this beatmap](https://osu.ppy.sh/beatmapsets/1221391#osu/2540736), once the bubbles mod is enabled, and try to play, it will crash directly in version 2023.812.0.
`Segmentation fault      (core dumped)`

If on version 2023.815.0, there will be an error during the loading phase, and then I cannot enter the game. (but I can return the song list)

Here is logs: [logs.zip](https://github.com/ppy/osu/files/12386042/logs.zip) (version 2023.815.0)

**Comment by Fabiano1337** [comment]
Should be fixed now
