### ISSUE TITLE
Can not set value to "osu.Game.Rulesets.RulesetInfo"

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu#2451]
- Play a song and **stay on scorescreen**.
- Open osu!direct and click on the Catch The Beat icon:  
![image of osudirect](https://i.gyazo.com/af288e75d3e50095bbdd9dcd03a0e1dc.png)
It will make osu!lazer unresponsive with this exception caught:
![image of visual studio](https://i.gyazo.com/4edd89c064e8c80b34804994bcd4351f.png)

**Comment by Frontear** [comment]
Considering it throws when the bindable is disabled, this is intended as of now.

**Comment by UselessToucan** [comment]
You did not even provide the stacktrace :-(

**Comment by GrilledCheeese** [comment]
Is this what you're looking for? @UselessToucan   
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.&amp;lt;Run&amp;gt;b__98_1(Object &amp;lt;p0&amp;gt;, FrameEventArgs &amp;lt;p1&amp;gt;)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double&amp;amp; timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
Can not set value to "osu.Game.Rulesets.RulesetInfo" as bindable is disabled.
![image of something else that maybe you also want?](https://i.gyazo.com/1d534a7c6ba35b593ab673fbc5d8dee7.png)
