### ISSUE TITLE
OpenGL crash when entering song select

### ISSUE THREAD

**Issue by tybug** [ppy/osu#24651]
### Type

Crash to desktop

### Bug description

crash when opening song select. I'm on macos but was temporarily using OpenGL due to #23970.  Crash does not occur with metal renderer.

```
2023-08-25 04:50:52 [verbose]: 🌅 Global background change queued
2023-08-25 04:50:53 [error]: An unhandled error has occurred.
2023-08-25 04:50:53 [error]: Veldrid.VeldridException: Error(s) were encountered during the execution of OpenGL commands. See InnerException for more information.
2023-08-25 04:50:53 [error]: ---> Veldrid.VeldridException: Error linking GL program: WARNING: Could not find vertex shader attribute 'm_TexturePosition' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_TextureRect' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_maskingIndex' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_backbufferDrawDepth' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: ERROR: Input of fragment shader 'vdspv_fsin0' not written by vertex shader
2023-08-25 04:50:53 [error]: 
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLPipeline.CreateGraphicsGLResources()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLPipeline.CreateGLResources()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLCommandExecutor.ActivateGraphicsPipeline()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLCommandExecutor.SetPipeline(Pipeline pipeline)
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.NoAllocEntryList.OpenGLNoAllocCommandEntryList.ExecuteAll(OpenGLCommandExecutor executor)
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.ExecuteWorkItem(ExecutionThreadWorkItem workItem)
2023-08-25 04:50:53 [error]: --- End of inner exception stack trace ---
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.CheckExceptions()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.WaitForIdle()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.SwapBuffersCore(Swapchain swapchain)
2023-08-25 04:50:53 [error]: at osu.Framework.Platform.GameHost.Swap()
2023-08-25 04:50:53 [error]: at osu.Framework.Platform.MacOS.MacOSGameHost.Swap()
2023-08-25 04:50:53 [error]: at osu.Framework.Platform.GameHost.DrawFrame()
2023-08-25 04:50:53 [error]: at osu.Framework.Threading.GameThread.processFrame()
2023-08-25 04:50:53 [error]: An unhandled error has occurred. (inner)
2023-08-25 04:50:53 [error]: Veldrid.VeldridException: Error linking GL program: WARNING: Could not find vertex shader attribute 'm_TexturePosition' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_TextureRect' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_maskingIndex' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: WARNING: Could not find vertex shader attribute 'm_backbufferDrawDepth' to match BindAttributeLocation request.
2023-08-25 04:50:53 [error]: ERROR: Input of fragment shader 'vdspv_fsin0' not written by vertex shader
2023-08-25 04:50:53 [error]: 
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLPipeline.CreateGraphicsGLResources()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLPipeline.CreateGLResources()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLCommandExecutor.ActivateGraphicsPipeline()
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLCommandExecutor.SetPipeline(Pipeline pipeline)
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.NoAllocEntryList.OpenGLNoAllocCommandEntryList.ExecuteAll(OpenGLCommandExecutor executor)
2023-08-25 04:50:53 [error]: at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.ExecuteWorkItem(ExecutionThreadWorkItem workItem)
2023-08-25 04:50:53 [verbose]: ⚠️ An unhandled error has occurred.
2023-08-25 04:50:53 [verbose]: Unhandled exception has been denied .
```

### Version

current master

### Logs

[runtime.log](https://github.com/ppy/osu/files/12436001/runtime.log)

**Comment by peppy** [comment]
Probably very low priority.

**Comment by amadeuskarlsson** [comment]
It seems like there is an issue with the OpenGL program linking. It could be caused by missing vertex shader attribute bindings to match the Binder request, or a fragment shader input that was not written by the vertex shader. The error message includes multiple warnings and an error relating to missing shader attributes, which may be the cause of the program linking failure.
