### ISSUE TITLE
build error on net471 and startup crash on netcoreapp2.0

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2474]
distribution: ubuntu 18.04 LTS

I'm using VScode. When selecting `osu! (Debug, net471)` I get this build error:
```/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu.Game/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu.Game/osu.Game.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu-framework/osu.Framework/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu-framework/osu.Framework/osu.Framework.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu-resources/osu.Game.Resources/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu-resources/osu.Game.Resources/osu.Game.Resources.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu.Game.Rulesets.Osu/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu.Game.Rulesets.Catch/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu.Game.Rulesets.Taiko/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj]
/usr/share/dotnet/sdk/2.1.105/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '/home/lastexceed/dev/osu/osu.Game.Rulesets.Mania/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. [/home/lastexceed/dev/osu/osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj]
```
So I tried `osu! (Debug, netcoreapp2.0)` instead (since on windows that works just as good as net471 for me) and it builds successfully (0 errors, 0 warnings). Instead I get this exception on startup: 
```Exception has occurred: CLR/System.TypeInitializationException
An unhandled exception of type 'System.TypeInitializationException' occurred in OpenTK.dll: 'The type initializer for 'OpenTK.DisplayDevice' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.DllNotFoundException : Unable to load DLL 'gbm': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OpenTK.Platform.Linux.Gbm.CreateDevice(Int32 fd)
   at OpenTK.Platform.Linux.LinuxFactory.SetupDisplay(String gpu, IntPtr& gbm_device, IntPtr& egl_display)
   at OpenTK.Platform.Linux.LinuxFactory.CreateDisplay(IntPtr& gbm_device, IntPtr& egl_display)
   at OpenTK.Platform.Linux.LinuxFactory.get_gpu_fd()
   at OpenTK.Platform.Linux.LinuxFactory.CreateDisplayDeviceDriver()
   at OpenTK.DisplayDevice..cctor()
```

Which log files do you need and where do I find them? Anything else I should provide?

**Comment by peppy** [comment]
First error is you not having the .net 4.7.1 sdk installed. second is opentk not being able to get a graphic context from your linux. you're going to have to figure out why that is the case yourself.

**Comment by 999eagle** [comment]
I'm also on Ubuntu 18.04 LTS and had the same exception on startup. This solved it: `sudo apt install libgbm1`

**Comment by peppy** [comment]
@LastExceed could you please try this solution and close the issue if it resolves it?

**Comment by VPeruS** [comment]
@LastExceed You cannot  build net471 target on linux(not yet at least).  To make .dll need to explicitly set target like this `dotnet build osu.Desktop -f netcoreapp2.0`.

**Comment by Looooong** [comment]
This is because the project `osu.Framework` uses the package `ppy.OpenTK.NS20` which is forked from original one. I tried to switch to the package `OpenTK.NETCore` but it raised many errors about ambiguous reference between `osu.Framework.Graphics.Primitives.RectangleF` and `OpenTK.RectangleF`, `OpenTK.Point` and `System.Drawing.Point`, etc.

**Comment by peppy** [comment]
That is an invalid explanation.

**Comment by Looooong** [comment]
The solution `sudo apt install libgbm1` doesn't work for me either (it is already installed). Also, Ubuntu 18.04 LTS.

**Comment by peppy** [comment]
Then you are likely getting a different error from the one above, which is specifically about missing 'gbm'.

**Comment by Looooong** [comment]
I also got missing `gbm` with `libgbm1` already installed. Reinstall does not work.

**Comment by peppy** [comment]
You may want to figure out how to fix this then. Or use windows or another more friendly operating system where you do not need to manage your dependencies.

I'm closing this issue as the original issue has a proposed solution.

**Comment by Alex4386** [comment]
try `sudo apt install libgbm-dev` then.
