### ISSUE TITLE
Cannot import lazer score which export by stable

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#24899]
### Type

Crash to desktop

### Bug description

Recently when I import replay from stable into lazer, I noticed that some replay would have import errors.
but there can play normal in stable.

these replay are which I used to export from lazer to stable. 

[errorReplay.zip](https://github.com/ppy/osu/files/12707813/errorReplay.zip)
these replays are which I found cannot to import

after debug, these replays all failed with `System.IO.EndOfStreamException: Unable to read beyond the end of the stream.` at https://github.com/ppy/osu/blob/d18bd2d2acdc32f77ce5cc03d089ed329e91ca17/osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs#L111

if I add a try catch on this line, lazer can correctly import and play scores
```C#
try
{
    if (version >= 30000001)
        compressedScoreInfo = sr.ReadByteArray();
}
catch
{
}
```

Reproduction process from scratch:
1. export a lazer-play replay.
2. import to stable
3. export from stable
4. import score which export from stable

### Screenshots or videos

https://github.com/ppy/osu/assets/34775378/0699caf0-bf6e-42fa-8c26-692634b36a17

https://osu.ppy.sh/b/2840229
[replay.zip](https://github.com/ppy/osu/files/12707861/replay.zip)

### Version

d18bd2d2acdc32f77ce5cc03d089ed329e91ca17

### Logs

I'm doing batch import and have long log, so I copied part of the exception specifically

```
2023-09-24 04:03:40 [error]: [?????] Model creation of 050c3a53d2176c5e6ab759ed43d95f70-133176610002659888.osr failed.
2023-09-24 04:03:40 [error]: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
2023-09-24 04:03:40 [error]: at System.IO.BinaryReader.InternalRead(Int32 numBytes)
2023-09-24 04:03:40 [error]: at System.IO.BinaryReader.ReadInt32()
2023-09-24 04:03:40 [error]: at osu.Game.IO.Legacy.SerializationReader.ReadByteArray() in E:\github\osu\osu.Game\IO\Legacy\SerializationReader.cs:line 41
2023-09-24 04:03:40 [error]: at osu.Game.Scoring.Legacy.LegacyScoreDecoder.Parse(Stream stream) in E:\github\osu\osu.Game\Scoring\Legacy\LegacyScoreDecoder.cs:line 138
2023-09-24 04:03:40 [error]: at osu.Game.Scoring.ScoreImporter.CreateModel(ArchiveReader archive) in E:\github\osu\osu.Game\Scoring\ScoreImporter.cs:line 66
2023-09-24 04:03:40 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.importFromArchive(ArchiveReader archive, ImportParameters parameters, CancellationToken cancellationToken) in E:\github\osu\osu.Game\Database\RealmArchiveModelImporter.cs:line 253
```
[database.log](https://github.com/ppy/osu/files/12707868/database.log)

**Comment by peppy** [comment]
Hmm, this is roughly to be expected. I think the best solution will be to special case stable to reset the version to a stable version number when exporting (or importing?) lazer replays, if we actually want to support this.

Not sure we need to though, it's a very very edge case that most people will not see.

**Comment by peppy** [comment]
This will be "fixed" in the next stable release to the best of our ability. The error won't appear, but the replay may be missing some data that stable cannot reconstruct.
