### ISSUE TITLE
Installer doesn't do anything

### ISSUE THREAD

**Issue by ravener** [ppy/osu#25184]
### Type

Crash to desktop

### Bug description

I opened install.exe and i get the osu! cookie with a loading bar, after it's done it's closed and nothing happens, but apparently osu! is shown on my Windows' list of programs but no desktop/start menu shortcut, so I tried to go into the directory and manually run the exe and see what happens and this is what I get
```
Ravener@Aster MINGW64 ~/AppData/Local/osulazer
$ ./osu\!.exe
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Squirrel.SemanticVersion.TryParse(String version, SemanticVersion& value)
   at Squirrel.SemanticVersion.Parse(String version) in ./NuGet/SemanticVersion.cs:line 151
   at Squirrel.SemanticVersion..ctor(String version) in ./NuGet/SemanticVersion.cs:line 22
   at Squirrel.UpdateManager.CurrentlyInstalledVersion(String executable) in ./UpdateManager.cs:line 214
   at Squirrel.SquirrelAwareApp.HandleEvents(SquirrelHook onInitialInstall, SquirrelHook onAppUpdate, SquirrelHook onAppObsoleted, SquirrelHook onAppUninstall, SquirrelRunHook onEveryRun, String[] arguments) in ./SquirrelAwareApp.cs:line 96
   at osu.Desktop.Program.setupSquirrel()
   at osu.Desktop.Program.Main(String[] args)

```
My first idea after seeing this was to see if updating .NET fixes it so I went and installed the latest .NET 6.0.23 Desktop Runtime from the .NET website, but that didn't change anything.

Any ideas what else I can troubleshoot?

### Version

2023.1008.1

### Logs

N/A, The game doesn't start to the point of emitting logs, the installer just extracted it and it still feels like it's not actually installed? There is still an unextracted .nupkg file in there, overall sounds like something is wrong with the .NET runtime even though I didn't do anything and even updated to latest.

**Comment by longnguyen2004** [comment]
Can you run outside of MSYS2 shell?

**Comment by ravener** [comment]
> Can you run outside of MSYS2 shell? (i.e. cmd/PowerShell)

For some reason cmd.exe/Powershell both do not show any error but it still doesn't launch so they somehow hide the error when the same thing is probably happening. The issue is not with the cmd/powershell/bash issue though since the error is clearly visible in the Windows Event Viewer even when just double clicking from Explorer
