### ISSUE TITLE
Error when attempting to save beatmap while export is in progress

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25426]
Relevant logs:

```
2023-11-14 03:28:02 [error]: An unobserved error has occurred.
2023-11-14 03:28:02 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2023-11-14 03:28:02 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2023-11-14 03:28:02 [error]: at osu.Game.Database.LegacyArchiveExporter`1.ExportToStream(TModel model, Stream outputStream, ProgressNotification notification, CancellationToken cancellationToken)
2023-11-14 03:28:02 [error]: at osu.Game.Database.LegacyExporter`1.<>c__DisplayClass12_0.<ExportToStreamAsync>b__1(TModel s)
2023-11-14 03:28:02 [error]: at osu.Game.Database.RealmLive`1.PerformRead(Action`1 perform)
2023-11-14 03:28:02 [error]: at osu.Game.Database.LegacyExporter`1.<>c__DisplayClass12_0.<ExportToStreamAsync>b__0()
2023-11-14 03:28:02 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-11-14 03:28:02 [error]: --- End of stack trace from previous location ---
2023-11-14 03:28:02 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-11-14 03:28:02 [error]: --- End of stack trace from previous location ---
2023-11-14 03:28:02 [error]: at osu.Game.Database.LegacyExporter`1.ExportAsync(Live`1 model, CancellationToken cancellationToken)
2023-11-14 03:28:02 [verbose]: Invalidating working beatmap cache for Jakarta Funk Brothers - FANTASTIC THREE (Erasome) [weeeeeeeeeee]
2023-11-14 03:28:02 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.
2023-11-14 03:28:08 [error]: An unobserved error has occurred.
2023-11-14 03:28:08 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2023-11-14 03:28:08 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
2023-11-14 03:28:08 [error]: at osu.Game.Database.LegacyArchiveExporter`1.ExportToStream(TModel model, Stream outputStream, ProgressNotification notification, CancellationToken cancellationToken)
2023-11-14 03:28:08 [error]: at osu.Game.Database.LegacyExporter`1.<>c__DisplayClass12_0.<ExportToStreamAsync>b__1(TModel s)
2023-11-14 03:28:08 [error]: at osu.Game.Database.RealmLive`1.PerformRead(Action`1 perform)
2023-11-14 03:28:08 [error]: at osu.Game.Database.LegacyExporter`1.<>c__DisplayClass12_0.<ExportToStreamAsync>b__0()
2023-11-14 03:28:08 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-11-14 03:28:08 [error]: --- End of stack trace from previous location ---
2023-11-14 03:28:08 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-11-14 03:28:08 [error]: --- End of stack trace from previous location ---
2023-11-14 03:28:08 [error]: at osu.Game.Database.LegacyExporter`1.ExportAsync(Live`1 model, CancellationToken cancellationToken)
```

### Discussed in https://github.com/ppy/osu/discussions/25425

<div type='discussions-op-text'>

<sup>Originally posted by **hwabis** November 14, 2023</sup>
[runtime.log](https://github.com/ppy/osu/files/13344191/runtime.log)

https://github.com/ppy/osu/assets/62194990/42eed7e9-24df-4dfd-be63-064f2e4c4a7a

</div>

**Comment by The-Grace-God** [comment]
My guess is that this is from lazer trying to do multiple processes at once that require writhing to the drive saving your changes the only way i see to fix this (though there is probably a better method) is to pause the skin export and then save the beatmap then resume the progress on the skin export
