### ISSUE TITLE
`osu://edit/` editor timestamp links with hit objects crash chat

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#25614]
### Type

Crash to desktop

### Bug description

First reported in https://discord.com/channels/188630481301012481/1097318920991559880/1179770517994078248.

Repro branch https://github.com/ppy/osu/compare/master...Susko3:fix-chat-editor-timestamps?expand=1, failing test commit: https://github.com/ppy/osu/commit/8d02745b00b8e94111fdfd419ed93c3527626f42

This commit adds the following test string which will generate two overlapping `OpenEditorTimestamp` links.

```
osu://edit/00:12:345 (1,2) - Test?
^------------------^		first OpenEditorTimestamp
           ^-------------^	second OpenEditorTimestamp
```

The overlapping links break the logic here: (this tries to add the text in between the links – text of negative length)

https://github.com/ppy/osu/blob/40dbf098d2d31730ddecf38032da48a8d2461910/osu.Game/Graphics/Containers/LinkFlowContainer.cs#L50

---

I'm not sure what's the expected outcome when the parser is given the string `osu://edit/00:12:345 (1,2)`. Possible outcomes:

| Parsed text with link | OpenEditorTimestamp argument | Notes |
|--------|--------|--------|
| [osu://edit/00:12:345 (1,2)]() | 00:12:345 (1,2) | Makes the most sense, except spaces in the URL |
| osu://edit/[00:12:345 (1,2)]() | 00:12:345 (1,2) | |
| [osu://edit/00:12:345]() (1,2) | 00:12:345 | |

Keep in mind that `osu://edit/00:12:345%20(1,2)` in chat only partially works, it'll move to the requested timestamp, but won't select any objects.

### Screenshots or videos

The parsed links in the failing test:

![image](https://github.com/ppy/osu/assets/16479013/de9adb6b-e997-4a06-ab11-c2e1688e01a1)

### Version

b2e1a63cd7d964cf8f4bca2839f9f00b4cf65db7

### Logs

```cs
2023-11-30 14:06:57 [error]: An unhandled error has occurred.
2023-11-30 14:06:57 [error]: System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
2023-11-30 14:06:57 [error]: at System.String.Substring(Int32 startIndex, Int32 length)
2023-11-30 14:06:57 [error]: at osu.Game.Graphics.Containers.LinkFlowContainer.AddLinks(String text, List`1 links) in C:\...\osu\osu.Game\Graphics\Containers\LinkFlowContainer.cs:line 50
2023-11-30 14:06:57 [error]: at osu.Game.Overlays.Chat.ChatLine.updateMessageContent() in C:\...\osu\osu.Game\Overlays\Chat\ChatLine.cs:line 215
2023-11-30 14:06:57 [error]: at osu.Game.Overlays.Chat.ChatLine.LoadComplete() in C:\...\osu\osu.Game\Overlays\Chat\ChatLine.cs:line 155
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Drawable.loadComplete()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Testing.TestBrowser.ErrorCatchingDelayedLoadWrapper.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-11-30 14:06:57 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-11-30 14:06:57 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by Loreos7** [comment]
For me the game is being crashed by posting timestamp link in chat:
[network.log](https://github.com/ppy/osu/files/13514510/network.log)
[runtime.log](https://github.com/ppy/osu/files/13514512/runtime.log)
[performance.log](https://github.com/ppy/osu/files/13514513/performance.log)
[updater.log](https://github.com/ppy/osu/files/13514515/updater.log)

**Comment by RatinFX** [comment]
It also happens when you type `osu://xx:yy:zzz`

>  ![image](https://github.com/ppy/osu/assets/38523955/287d14fa-87e2-407b-88fe-57426a0cf6d9)

 Unless it's used somewhere, I would expect the parser to just ignore anything `osu://` when it was said in the in-game chat

**Comment by Susko3** [comment]
using `osu://` urls in chat is tested, so I assume it's important

https://github.com/ppy/osu/blob/b2e1a63cd7d964cf8f4bca2839f9f00b4cf65db7/osu.Game.Tests/Visual/Online/TestSceneChatLink.cs#L92-L94
