### ISSUE TITLE
can't migrate game files to other drive

### ISSUE THREAD

**Issue by alzughbikarim** [ppy/osu#25815]
### Type

Crash to desktop

### Bug description

Game crashes when I try to migrate the files to another drive (both are NTFS)

### Screenshots or videos

![vlc_cKOlmU8UDL](https://github.com/ppy/osu/assets/126119825/5b2badfe-37d9-4698-93ee-51911fcf96d8)

https://github.com/ppy/osu/assets/126119825/db53163d-a6bd-47d2-8230-14d2ecf21f2e

### Version

2023.1218.0

### Logs

[1702881148.performance.log](https://github.com/ppy/osu/files/13700436/1702881148.performance.log)
[1702881148.updater.log](https://github.com/ppy/osu/files/13700437/1702881148.updater.log)
[1702881148.input.log](https://github.com/ppy/osu/files/13700438/1702881148.input.log)
[1702881148.runtime.log](https://github.com/ppy/osu/files/13700439/1702881148.runtime.log)
[1702881148.database.log](https://github.com/ppy/osu/files/13700440/1702881148.database.log)

**Comment by peppy** [comment]
Looks like the beatmap collection dropdown is fucked:

```csharp
2023-12-18 06:32:49 [error]: An unhandled error has occurred.
2023-12-18 06:32:49 [error]: System.ArgumentException: The item osu.Game.Collections.AllBeatmapsCollectionFilterMenuItem already exists in this Dropdown.
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.addDropdownItem(T value, Nullable`1 position)
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.collectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
2023-12-18 06:32:49 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, HashSet`1 appliedInstances)
2023-12-18 06:32:49 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, HashSet`1 appliedInstances)
2023-12-18 06:32:49 [error]: at osu.Game.Collections.CollectionDropdown.collectionsChanged(IRealmCollection`1 collections, ChangeSet changes)
2023-12-18 06:32:49 [error]: at osu.Game.Database.RealmAccess.<>c__DisplayClass36_0`1.<RegisterForNotifications>b__1()
2023-12-18 06:32:49 [error]: at osu.Game.Database.RealmAccess.<>c__DisplayClass47_0.<BlockAllOperations>b__1(Object _)
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.GameThreadSynchronizationContext.<>c__DisplayClass4_0.<Send>b__0()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.Scheduler.Update()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.GameThreadSynchronizationContext.Send(SendOrPostCallback callback, Object state)
2023-12-18 06:32:49 [error]: at osu.Game.Database.RealmAccess.BlockAllOperations(String reason)
2023-12-18 06:32:49 [error]: at osu.Game.OsuGameBase.<>c__DisplayClass130_0.<Migrate>b__0()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.Scheduler.Update()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-12-18 06:32:49 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-12-18 06:32:49 [error]: at osu.Framework.Threading.GameThread.processFrame()
```
