### ISSUE TITLE
Osu!Lazer not opening?

### ISSUE THREAD

**Issue by K1nzy** [ppy/osu#2604]
I was just opening osu!lazer, and it seems like it won't open.
I have even checked the Task Manager to see if the process was opened but not showing.
6 Months ago Osu!Lazer was opening, so i don't know why it is not opening now.
I have tried reinstalling it, and still nothing happens.

So i hope you guys can fix this.

**Comment by Aergwyn** [comment]
Do you have a runtime.log in `%appdata%/osu/logs` with timestamps from the most recent crash/failed startup? It may contain clues to what's going on.
With just a description of nothing happening we're most likely unable to help out.

**Comment by K1nzy** [comment]
@Aergwyn Pretty sure you meant in the osu!lazer folder, but here is my logs in the `runtime.log` file.
`5/21/2018 9:08:07 AM: ----------------------------------------------------------
5/21/2018 9:08:07 AM: Runtime Log for Mine laru
5/21/2018 9:08:07 AM: osu! version b20161205.1cuttingedge
5/21/2018 9:08:07 AM: Running on Microsoft Windows NT 6.3.9600.0, 2 cores
5/21/2018 9:08:07 AM: ----------------------------------------------------------
5/21/2018 9:08:07 AM: GL Initialized
5/21/2018 9:08:07 AM: GL Version:                 4.0.0 - Build 10.18.10.4358
5/21/2018 9:08:07 AM: GL Renderer:                Intel(R) HD Graphics
5/21/2018 9:08:07 AM: GL Shader Language version: 4.00 - Build 10.18.10.4358
5/21/2018 9:08:07 AM: GL Vendor:                  Intel
5/21/2018 9:08:07 AM: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_ARB_conservative_depth GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_SUN_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_ARB_texture_swizzle GL_EXT_texture_swizzle GL_ARB_texture_gather GL_ARB_sync GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_ARB_transform_feedback2 GL_ARB_draw_indirect GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_ARB_framebuffer_no_attachments GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_ARB_texture_buffer_range GL_EXT_texture_buffer GL_EXT_texture_snorm GL_ARB_blend_func_extended GL_INTEL_performance_queries GL_INTEL_performance_query GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_geometry_shader4 GL_EXT_geometry_shader4 GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_ARB_instanced_arrays GL_ARB_base_instance GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_texture_multisample GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_timer_query GL_ARB_tessellation_shader GL_ARB_vertex_array_object GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_texture_cube_map_array GL_EXT_gpu_shader4 GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_shader_subroutine GL_ARB_transform_feedback3 GL_ARB_get_program_binary GL_ARB_separate_shader_objects GL_ARB_shader_precision GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_ARB_transform_feedback_instanced GL_ARB_compressed_texture_pixel_storage GL_ARB_shader_atomic_counters GL_ARB_shading_language_packing GL_ARB_shading_language_420pack GL_ARB_texture_storage GL_EXT_texture_storage GL_ARB_vertex_attrib_binding GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_texture_storage_multisample GL_ARB_buffer_storage GL_ARB_debug_output GL_KHR_debug GL_ARB_arrays_of_arrays GL_INTEL_map_texture GL_ARB_texture_compression_bptc GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_robustness GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_EXT_shader_integer_mix GL_ARB_stencil_texturing
5/21/2018 9:08:07 AM: GL Context:                 Index: 7, Color: 32 (8888), Depth: 16, Stencil: 0, Samples: 0, Accum: 64 (16161616), Buffers: 2, Stereo: False
5/21/2018 9:08:08 AM: Loading Skin C:\Users\inky\AppData\Local\osu!\Skins\Cookiezi 24 2017-08-17 greencurs\skin.ini
5/21/2018 9:08:08 AM: Finished loading Skin
5/21/2018 9:08:11 AM: ChangedFolders: 0
5/21/2018 9:08:11 AM: ChangedPackages: 0
5/21/2018 9:08:14 AM: Notification: Welcome to Enjuu!
5/21/2018 9:08:15 AM: Notification: Welcome to Enjuu!
5/21/2018 9:08:50 AM: Notification: Joining Game...
5/21/2018 9:08:56 AM: Notification: Looking up beatmap...
5/21/2018 9:08:57 AM: Downloading Summer Triangle
5/21/2018 9:08:58 AM: Notification: Downloading Summer Triangle
5/21/2018 9:09:04 AM: Notification: New beatmap detected.  Hit F5 to refresh.
5/21/2018 9:09:04 AM: Notification: Finished downloading Summer Triangle
5/21/2018 9:09:05 AM: ChangedFolders: 2
5/21/2018 9:09:05 AM: ChangedPackages: 0
5/21/2018 9:09:15 AM: Notification: Mouse buttons are currently disabled. Hit F10 to enable them again.
5/21/2018 9:09:21 AM: Notification: Waiting for players...
5/21/2018 9:09:33 AM: Notification: You have failed, but you can keep playing!
5/21/2018 9:09:38 AM: Notification: Hit 'Escape' once more to exit this multiplayer match.
5/21/2018 9:09:48 AM: Performing background save..
5/21/2018 9:09:48 AM: Done!
5/21/2018 9:17:11 AM: Notification: Saved Beatmap
5/21/2018 9:17:13 AM: Notification: Autoplay mod enabled
5/21/2018 9:18:46 AM: Performing background save..
5/21/2018 9:18:46 AM: Done!
5/21/2018 9:19:47 AM: Performing background save..
5/21/2018 9:19:47 AM: Done!
5/21/2018 9:20:27 AM: Notification: This map is in a qualified state.
5/21/2018 9:20:27 AM: No performance points will be awarded.
5/21/2018 9:20:27 AM: All scores will be deleted when it is ranked.
5/21/2018 9:23:08 AM: Performing background save..
5/21/2018 9:23:08 AM: Done!
5/21/2018 9:23:28 AM: Notification: This map is in a qualified state.
5/21/2018 9:23:28 AM: No performance points will be awarded.
5/21/2018 9:23:28 AM: All scores will be deleted when it is ranked.
5/21/2018 9:24:33 AM: Performing background save..
5/21/2018 9:24:33 AM: Done!
5/21/2018 9:24:48 AM: Notification: This map is in a qualified state.
5/21/2018 9:24:48 AM: No performance points will be awarded.
5/21/2018 9:24:48 AM: All scores will be deleted when it is ranked.
5/21/2018 9:25:23 AM: Notification: This map is in a qualified state.
5/21/2018 9:25:23 AM: No performance points will be awarded.
5/21/2018 9:25:23 AM: All scores will be deleted when it is ranked.
5/21/2018 9:25:55 AM: Notification: This map is in a qualified state.
5/21/2018 9:25:55 AM: No performance points will be awarded.
5/21/2018 9:25:55 AM: All scores will be deleted when it is ranked.
5/21/2018 9:26:48 AM: Notification: Joining Game...
5/21/2018 9:26:49 AM: Performing background save..
5/21/2018 9:26:49 AM: Done!
5/21/2018 9:29:46 AM: Performing background save..
5/21/2018 9:29:46 AM: Done!
5/21/2018 9:37:49 AM: Performing background save..
5/21/2018 9:37:50 AM: Performing background save..
5/21/2018 9:37:50 AM: Done!
5/21/2018 9:37:53 AM: Done!
5/21/2018 9:38:53 AM: Notification: Joining Game...
5/21/2018 9:39:13 AM: Notification: Looking up beatmap...
5/21/2018 9:39:14 AM: Downloading I Love Poland (Extended Dirty Mix)
5/21/2018 9:39:14 AM: Notification: Downloading I Love Poland (Extended Dirty Mix)
5/21/2018 9:39:27 AM: Notification: New beatmap detected.  Hit F5 to refresh.
5/21/2018 9:39:27 AM: Notification: Finished downloading I Love Poland (Extended Dirty Mix)
5/21/2018 9:39:28 AM: ChangedFolders: 2
5/21/2018 9:39:28 AM: ChangedPackages: 0
5/21/2018 9:40:33 AM: Notification: Looking up beatmap...
5/21/2018 9:40:34 AM: Downloading Shoot ten Dozy
5/21/2018 9:40:36 AM: Notification: Downloading Shoot ten Dozy
5/21/2018 9:40:43 AM: Notification: New beatmap detected.  Hit F5 to refresh.
5/21/2018 9:40:43 AM: Notification: Finished downloading Shoot ten Dozy
5/21/2018 9:40:43 AM: ChangedFolders: 2
5/21/2018 9:40:43 AM: ChangedPackages: 0
5/21/2018 9:40:52 AM: Performing background save..
5/21/2018 9:40:54 AM: Performing background save..
5/21/2018 9:40:54 AM: Done!
5/21/2018 9:40:57 AM: Done!
5/21/2018 9:41:13 AM: Notification: Waiting for players...
5/21/2018 9:41:16 AM: Notification: You have failed, but you can keep playing!
5/21/2018 9:41:29 AM: Notification: Hit 'Escape' once more to exit this multiplayer match.
5/21/2018 9:41:50 AM: Notification: Joining Game...
5/21/2018 9:41:57 AM: Notification: Hit 'Escape' once more to leave this match.
5/21/2018 9:41:59 AM: Done!
5/21/2018 9:41:59 AM: Performing background save..
5/21/2018 9:58:09 AM: Performing background save..
5/21/2018 9:58:14 AM: Done!
`

**Comment by K1nzy** [comment]
@Aergwyn Waiting for your response.

**Comment by K1nzy** [comment]
@smoogipoo how come i'm trying to run osu!stable tho? because i'm clicking on `osu!lazer.exe`

**Comment by smoogipoo** [comment]
Take a screenshot of the folder where you're running it from.

**Comment by K1nzy** [comment]
![2018-05-22_04-38-18](https://user-images.githubusercontent.com/24857552/40354677-6f9dca18-5d82-11e8-96ab-d35f2bf28e9a.png) @smoogipoo Here you go.

**Comment by K1nzy** [comment]
I have tried installing the latest version of the .NET Framework and restarted my PC but it still wont open,

**Comment by Aergwyn** [comment]
Can you also screenshot the folder you posted the log from? I'm quite curious if I mislead you by accident (I should refresh my memory) or if it actually tries to start cutting edge from lazer. o.O

**Comment by K1nzy** [comment]
@smoogipoo This was the folder you told me to give you the logs from.
![2018-05-22_04-53-57](https://user-images.githubusercontent.com/24857552/40355513-9cf443f0-5d84-11e8-8427-a8fe04326564.png)

**Comment by Aergwyn** [comment]
I'm sorry for the misunderstanding but could you please try again?
`%appdata%/osu` refers to `.../AppData/Roaming/osu` which should be the crucial difference to stable. That location is the storage for the database, files and also logs for lazer.

**Comment by K1nzy** [comment]
@Aergwyn here you go.
`
5/22/2018 9:18:11 AM: ----------------------------------------------------------
5/22/2018 9:18:11 AM: Runtime Log for inky
5/22/2018 9:18:11 AM: osu version unknown
5/22/2018 9:18:11 AM: Running on Microsoft Windows NT 10.0.16299.0, 2 cores
5/22/2018 9:18:11 AM: ----------------------------------------------------------
5/22/2018 9:18:11 AM: GL Initialized
5/22/2018 9:18:11 AM: GL Version:                 4.0.0 - Build 10.18.10.4358
5/22/2018 9:18:11 AM: GL Renderer:                Intel(R) HD Graphics
5/22/2018 9:18:11 AM: GL Shader Language version: 4.00 - Build 10.18.10.4358
5/22/2018 9:18:11 AM: GL Vendor:                  Intel
5/22/2018 9:18:11 AM: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_ARB_conservative_depth GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_SUN_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_ARB_texture_swizzle GL_EXT_texture_swizzle GL_ARB_texture_gather GL_ARB_sync GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_ARB_transform_feedback2 GL_ARB_draw_indirect GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_ARB_framebuffer_no_attachments GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_ARB_texture_buffer_range GL_EXT_texture_buffer GL_EXT_texture_snorm GL_ARB_blend_func_extended GL_INTEL_performance_queries GL_INTEL_performance_query GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_geometry_shader4 GL_EXT_geometry_shader4 GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_ARB_instanced_arrays GL_ARB_base_instance GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_texture_multisample GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_timer_query GL_ARB_tessellation_shader GL_ARB_vertex_array_object GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_texture_cube_map_array GL_EXT_gpu_shader4 GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_shader_subroutine GL_ARB_transform_feedback3 GL_ARB_get_program_binary GL_ARB_separate_shader_objects GL_ARB_shader_precision GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_ARB_transform_feedback_instanced GL_ARB_compressed_texture_pixel_storage GL_ARB_shader_atomic_counters GL_ARB_shading_language_packing GL_ARB_shading_language_420pack GL_ARB_texture_storage GL_EXT_texture_storage GL_ARB_vertex_attrib_binding GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_texture_storage_multisample GL_ARB_buffer_storage GL_ARB_debug_output GL_KHR_debug GL_ARB_arrays_of_arrays GL_INTEL_map_texture GL_ARB_texture_compression_bptc GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_robustness GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_EXT_shader_integer_mix GL_ARB_stencil_texturing
5/22/2018 9:18:42 AM: fatal error:
5/22/2018 9:18:42 AM: osu.Game.Database.MigrationFailedException: sqlite-net migration failed
5/22/2018 9:18:42 AM: at osu.Game.Database.OsuDbContext.Migrate()
5/22/2018 9:18:42 AM: at osu.Game.OsuGameBase.runMigrations()
5/22/2018 9:18:42 AM: at osu.Game.OsuGameBase.load()
5/22/2018 9:18:42 AM: 
5/22/2018 9:18:42 AM: 
`
![chrome_2018-05-22_05-08-28](https://user-images.githubusercontent.com/24857552/40356300-a260bda8-5d86-11e8-8b92-ae123125de9a.png)

**Comment by Aergwyn** [comment]
I'd like to see the `database.log` to check if the exact error shows up but otherwise my suggestion would be the same as in #2571 
>I'm a bit guessing here but if it's just failing the migrations because it's too old you can try deleting the lazer database and see if you can play again. Just be aware that you need to reimport from stable again.

**Comment by K1nzy** [comment]
@Aergwyn About to try that but here you go.
`
5/22/2018 9:18:41 AM: ----------------------------------------------------------
5/22/2018 9:18:41 AM: Database Log for inky
5/22/2018 9:18:41 AM: osu version unknown
5/22/2018 9:18:41 AM: Running on Microsoft Windows NT 10.0.16299.0, 2 cores
5/22/2018 9:18:41 AM: ----------------------------------------------------------
5/22/2018 9:18:41 AM: Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
5/22/2018 9:18:41 AM: CREATE TABLE "BeatmapDifficulty" (
5/22/2018 9:18:41 AM: "ID" INTEGER NOT NULL CONSTRAINT "PK_BeatmapDifficulty" PRIMARY KEY AUTOINCREMENT,
5/22/2018 9:18:41 AM: "ApproachRate" REAL NOT NULL,
5/22/2018 9:18:41 AM: "CircleSize" REAL NOT NULL,
5/22/2018 9:18:41 AM: "DrainRate" REAL NOT NULL,
5/22/2018 9:18:41 AM: "OverallDifficulty" REAL NOT NULL,
5/22/2018 9:18:41 AM: "SliderMultiplier" REAL NOT NULL,
5/22/2018 9:18:41 AM: "SliderTickRate" REAL NOT NULL
5/22/2018 9:18:41 AM: );
5/22/2018 9:18:41 AM: Migration failed! We'll be starting with a fresh database.
5/22/2018 9:18:41 AM: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "BeatmapDifficulty" already exists'.
5/22/2018 9:18:41 AM: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
5/22/2018 9:18:41 AM: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
5/22/2018 9:18:41 AM: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
5/22/2018 9:18:41 AM: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
5/22/2018 9:18:41 AM: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
5/22/2018 9:18:41 AM: at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
5/22/2018 9:18:41 AM: at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
5/22/2018 9:18:41 AM: at osu.Game.Database.OsuDbContext.Migrate()
5/22/2018 9:18:41 AM: Database purged successfully.
5/22/2018 9:18:41 AM: Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='10']
5/22/2018 9:18:41 AM: CREATE TABLE "BeatmapDifficulty" (
5/22/2018 9:18:41 AM: "ID" INTEGER NOT NULL CONSTRAINT "PK_BeatmapDifficulty" PRIMARY KEY AUTOINCREMENT,
5/22/2018 9:18:41 AM: "ApproachRate" REAL NOT NULL,
5/22/2018 9:18:41 AM: "CircleSize" REAL NOT NULL,
5/22/2018 9:18:41 AM: "DrainRate" REAL NOT NULL,
5/22/2018 9:18:41 AM: "OverallDifficulty" REAL NOT NULL,
5/22/2018 9:18:41 AM: "SliderMultiplier" REAL NOT NULL,
5/22/2018 9:18:41 AM: "SliderTickRate" REAL NOT NULL
5/22/2018 9:18:41 AM: );

`

**Comment by Aergwyn** [comment]
You can just drag & drop files so they remain readable, especially in case of logs.
