### ISSUE TITLE
D3D11 renderer dying on `DXGI_ERROR_DEVICE_REMOVED` in unclear circumstances

### ISSUE THREAD

**Issue by bdach** [ppy/osu#26400]
Relevant stack trace:

```
2024-01-05 04:30:24 [error]: An unhandled error has occurred.
2024-01-05 04:30:24 [error]: SharpGen.Runtime.SharpGenException: HRESULT: [0x887A0005], Module: [Vortice.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: [The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
2024-01-05 04:30:24 [error]: ]
2024-01-05 04:30:24 [error]: at SharpGen.Runtime.Result.ThrowFailureException()
2024-01-05 04:30:24 [error]: at Veldrid.D3D11.D3D11Buffer..ctor(ID3D11Device device, UInt32 sizeInBytes, BufferUsage usage, UInt32 structureByteStride, Boolean rawBuffer)
2024-01-05 04:30:24 [error]: at Veldrid.D3D11.D3D11ResourceFactory.CreateBufferCore(BufferDescription& description)
```

Not sure why this is happening, but probably worth looking into eventually.

### Discussed in https://github.com/ppy/osu/discussions/26397

<div type='discussions-op-text'>

<sup>Originally posted by **SuPeRDuDe5898** January  5, 2024</sup>
I, for some reason, crash during a song by freezing with no error message, and then just closing. The weird part is, I don't even know what caused the crashing, so I don't know how I can fix it myself.
I've also been looking around the other discussions on the official website but none of them seemed to help.</div>

**Comment by m1ntleaf** [comment]
still having the same issue, a fix would be appreciated since OpenGL causes other issues on my PC

**Comment by Sartorra** [comment]
I had this exact same error occur in the middle of a play. I checked event viewer and even windows and found this error around the time of the crash.

> The description for Event ID 153 from source nvlddmkm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

Perhaps this is an NVIDIA driver issue? (Ver 11.0.7.247, RTX 5070)

**Comment by gagahpangeran** [comment]
Another case occurred : https://osu.ppy.sh/community/forums/topics/2209956

**Comment by m1ntleaf** [comment]
> I had this exact same error occur in the middle of a play. I checked event viewer and even windows and found this error around the time of the crash.
> 
> > The description for Event ID 153 from source nvlddmkm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> Perhaps this is an NVIDIA driver issue? (Ver 11.0.7.247, RTX 5070)

I'm on an ARM PC running Qualcomm, so I doubt it
