### ISSUE TITLE
Issues with old scores not upgrading to the new scoring algorythm

### ISSUE THREAD

**Issue by hazelcode** [ppy/osu#26406]
### Type

Game behaviour

### Bug description

The system was updating my scores (to the new algorithm), when finishing, it suddenly stopped and flagged an error that such a number of scores could not be updated. I don't know why and what it is due to.

### Screenshots or videos

![osu_2024-01-05_15-40-24](https://github.com/ppy/osu/assets/84425557/7ac43ebe-6465-443e-8fc3-db0faa6e70bd)

### Version

2023.1231.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13846889/compressed-logs.zip)

**Comment by bdach** [comment]
```
2024-01-05 21:20:46 [verbose]: Upgrading scores to new scoring algorithm (200 of 3764)
2024-01-05 21:20:47 [verbose]: Failed to convert total score for 4d200aea-5179-4376-8617-4e796755751c: osu.Game.Rulesets.RulesetLoadException: Ruleset could not be loaded (Ruleset not available)
2024-01-05 21:20:47 [verbose]: at osu.Game.Rulesets.RulesetInfo.CreateInstance()
2024-01-05 21:20:47 [verbose]: at osu.Game.Database.StandardisedScoreMigrationTools.ComputeAccuracy(ScoreInfo scoreInfo)
2024-01-05 21:20:47 [verbose]: at osu.Game.Database.StandardisedScoreMigrationTools.UpdateFromLegacy(ScoreInfo score, BeatmapManager beatmaps)
2024-01-05 21:20:47 [verbose]: at osu.Game.BackgroundDataStoreProcessor.<>c__DisplayClass43_0.<convertLegacyTotalScoreToStandardised>b__3(Realm r)
2024-01-05 21:20:47 [verbose]: at osu.Game.Database.RealmExtensions.Write(Realm realm, Action`1 function)
2024-01-05 21:20:47 [verbose]: at osu.Game.Database.RealmAccess.Write(Action`1 action)
2024-01-05 21:20:47 [verbose]: at osu.Game.BackgroundDataStoreProcessor.convertLegacyTotalScoreToStandardised()
```

You appear to have leftover scores from a ruleset that has been since removed. Please upload `client.db` to determine which ones.

We should probably be handling this better (just keep going rather than stop on these).
