### ISSUE TITLE
osu! logo disappear after go to skin editor then go to multiplayer

### ISSUE THREAD

**Issue by michioxd** [ppy/osu#26500]
### Type

Crash to desktop

### Bug description

(from home screen) click edit > skin editor > return (inside skin editor) > osu! > multi
then the osu! logo disappear and another button cannot click until go to solo then go back

### Screenshots or videos

![osu!_GqibFqFzMC](https://github.com/ppy/osu/assets/80969068/562b2896-d814-47db-ad4a-6077854a9b6e)

https://github.com/ppy/osu/assets/80969068/cbf0175a-0c3e-44bf-b066-2a20af2d3600

[alternative (IPFS)](https://bafybeiepu5cpudivsnwmeelxkyi6jyq7you2sxuqow7xeicfg23czo34vm.ipfs.cf-ipfs.com/)

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13928085/compressed-logs.zip)

**Comment by peppy** [comment]
```
layer#544)
2024-01-13 13:05:04 [verbose]: ButtonSystem's state changed from Play to EnteringMode
2024-01-13 13:05:04 [verbose]: 📺 OsuScreenStack#157(depth:4) loading Multiplayer#544
2024-01-13 13:05:04 [error]: An unhandled error has occurred.
2024-01-13 13:05:04 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2024-01-13 13:05:04 [error]: at osu.Game.PerformFromMenuRunner.checkForDialog(IScreen current)
2024-01-13 13:05:04 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete()
2024-01-13 13:05:04 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-01-13 13:05:04 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-01-13 13:05:04 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-01-13 13:05:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-01-13 13:05:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-01-13 13:05:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-01-13 13:05:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```
