### ISSUE TITLE
osu!mania editor crashes when adding a note

### ISSUE THREAD

**Issue by xdi1** [ppy/osu#26519]
### Type

Crash to desktop

### Bug description

Mania editor crashes when adding a note. Can share the same cause with https://github.com/ppy/osu/issues/26493#issue-2080160403. Not happening in every maps. I attach a map I used that produced this issue. Just change the extension to osz.
[unknown artist - Fateful Confrontation.zip](https://github.com/ppy/osu/files/13930219/unknown.artist.-.Fateful.Confrontation.zip)

### Version

2024.113.0

### Logs

[1705203058.runtime.log](https://github.com/ppy/osu/files/13930214/1705203058.runtime.log)

**Comment by peppy** [comment]
Three cascading failures from the logs:

```
2024-01-14 03:31:18 [error]: System.Collections.Generic.KeyNotFoundException: The given key 'osu.Game.Rulesets.Mania.Objects.BarLine' was not present in the dictionary.
2024-01-14 03:31:18 [error]: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2024-01-14 03:31:18 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer`1.GetBlueprintFor(T item)
2024-01-14 03:31:18 [error]: at osu.Game.Screens.Edit.Compose.Components.ComposeBlueprintContainer.TransferBlueprintFor(HitObject hitObject, DrawableHitObject drawableObject)
2024-01-14 03:31:18 [error]: at osu.Game.Screens.Edit.Compose.HitObjectUsageEventBuffer.onHitObjectUsageBegan(HitObject hitObject)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.UI.Playfield.<.ctor>b__31_2(HitObject o)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.UI.Scrolling.ScrollingHitObjectContainer.AddDrawable(HitObjectLifetimeEntry entry, DrawableHitObject drawable)
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.updateChildEntry(LifetimeEntry entry, Double startTime, Double endTime, Boolean isNewEntry, Boolean mutateActiveEntries)
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.Update(Double startTime, Double endTime)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.Objects.Pooling.PooledDrawableWithLifetimeContainer`2.CheckChildrenLife()
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
```

```
2024-01-14 03:31:18 [error]: An unhandled error has occurred.
2024-01-14 03:31:18 [error]: System.InvalidOperationException: Sequence contains more than one matching element
2024-01-14 03:31:18 [error]: at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
2024-01-14 03:31:18 [error]: at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2024-01-14 03:31:18 [error]: at osu.Game.Screens.Edit.Compose.HitObjectUsageEventBuffer.onHitObjectUsageBegan(HitObject hitObject)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.UI.Playfield.<.ctor>b__31_2(HitObject o)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.UI.Scrolling.ScrollingHitObjectContainer.AddDrawable(HitObjectLifetimeEntry entry, DrawableHitObject drawable)
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.updateChildEntry(LifetimeEntry entry, Double startTime, Double endTime, Boolean isNewEntry, Boolean mutateActiveEntries)
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Performance.LifetimeEntryManager.Update(Double startTime, Double endTime)
2024-01-14 03:31:18 [error]: at osu.Game.Rulesets.Objects.Pooling.PooledDrawableWithLifetimeContainer`2.CheckChildrenLife()
2024-01-14 03:31:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
```

```
2024-01-14 03:31:18 [verbose]: This error has been automatically reported to the devs.
2024-01-14 03:31:19 [verbose]: Host execution state changed to Stopping
2024-01-14 03:31:19 [verbose]: Host execution state changed to Stopped
2024-01-14 03:31:19 [error]: Failed to unbind a local bindable in EditorLoader
2024-01-14 03:31:19 [error]: osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the InternalChildren on a Ready Drawable while not on the load or update threads. Consider using Schedule to schedule the mutation operation.
2024-01-14 03:31:19 [error]: at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String action)
2024-01-14 03:31:19 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
2024-01-14 03:31:19 [error]: at osu.Game.Screens.Play.HUD.ModDisplay.updateDisplay(ValueChangedEvent`1 mods)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.LeasedBindable`1.set_Value(T value)
2024-01-14 03:31:19 [error]: at osu.Framework.Bindables.LeasedBindable`1.UnbindAllInternal()
2024-01-14 03:31:19 [error]: at osu.Framework.Graphics.Drawable.<>c__DisplayClass16_0.<getUnbindAction>b__4(Object target)
```
