### ISSUE TITLE
Importing skins from stable results in errors.

### ISSUE THREAD

**Issue by Toasterly** [ppy/osu#26812]
### Type

Import failing

### Bug description

When I deleted all skins from Lazer and re-imported them from stable it gave me errors saying many cannot be imported.

### Screenshots or videos

![osu_2024-01-30_08-12-51](https://github.com/ppy/osu/assets/37195727/5d7dd921-677f-44b2-ae95-c2d11fbb0699)

### Version

2024.130.2

### Logs

[1706623399.database.log](https://github.com/ppy/osu/files/14099465/1706623399.database.log)

**Comment by bdach** [comment]
```
2024-01-30 14:08:44 [error]: Could not import (-         《CK》 Bacon boi nameless mix)
2024-01-30 14:08:44 [error]: System.UnauthorizedAccessException: Access to the path 'D:\osu!\Skins\-         《CK》 Bacon boi nameless mix\skin.ini' is denied.
2024-01-30 14:08:44 [error]: at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
2024-01-30 14:08:44 [error]: at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024-01-30 14:08:44 [error]: at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024-01-30 14:08:44 [error]: at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2024-01-30 14:08:44 [error]: at System.IO.File.OpenRead(String path)
```

It's either something broken with file permissions or something else is holding the files open.

Did you have any program open that could be using the old skins at the time when you were importing?

**Comment by Toasterly** [comment]
This is a brand new PC. The only programs running were discord, chrome, and Lazer. 

It is weird that file permissions would be the issue as about 13 skins from the same directory were imported without issue.

**Comment by Toasterly** [comment]
[1706625620.runtime.log](https://github.com/ppy/osu/files/14099915/1706625620.runtime.log)

After restarting Lazer to try again I am now getting even more errors on startup. Unsure if related but here are the logs.

![osu_2024-01-30_08-41-34](https://github.com/ppy/osu/assets/37195727/7245c232-9842-4fdd-bd11-e56bb72e06a3)

**Comment by bdach** [comment]
Yeah no that looks like even more permissions breakage.

Did you ever run the game as admin or something like that?

**Comment by Toasterly** [comment]
Running as admin fixes the problem, but attempting to run as a normal user afterwards results in errors again.

Running as admin also allows me to import skins from stable.

Any suggestions as to how to fix this without needing admin?

**Comment by Toasterly** [comment]
Updating r/w permissions on my D: drive to see if that fixes it when running outside of Admin. Will reply back when finished.
