### ISSUE TITLE
"An error occurred while sending the request" when trying to login to Osu account

### ISSUE THREAD

**Issue by 14okeeffel** [ppy/osu#26927]
### Type

Other

### Bug description

It happens every time I try to login to osu. The game just doesn't let me login no matter how much I update the game, restart my pc, or change my network connection. I also find that if I try to make a new account I get an error message that just says "something happened... but we don't know what". 

### Screenshots or videos

![image_2024-02-01_162804027](https://github.com/ppy/osu/assets/158496681/913355ac-795c-40af-aa4b-0ffd927685ea)
![image](https://github.com/ppy/osu/assets/158496681/c4926814-d62a-416b-896a-ca929860a624)

### Version

all recent versions of Lazer (i dont use the old version of the game anymore but i remember it doing this aswell)

### Logs

network log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.1&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxkns5
legacy-ipc.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.2&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxknq4
updater.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.3&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxkmx1
input.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.4&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxkno3
database.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.5&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxknl2
performance.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.6&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxknt6
runtime.log:
https://mail.google.com/mail/u/0?ui=2&ik=6119be5858&attid=0.7&permmsgid=msg-a:r-36214762875383631&th=18c6d5b90229bbdd&view=att&disp=safe&realattid=f_lq6kxknu7

**Comment by bdach** [comment]
I'm not sure why you're hosting the logs on _gmail_ of all places but nobody other than yourself will be access to them. So please just upload them normally by dragging a zip into the input box on github itself.

**Comment by bdach** [comment]
Uhh....

```
2023-12-15 11:58:25 [verbose]: Request to https://assets.ppy.sh/client-resources/online.db.bz2?20231215 failed with System.Net.Http.HttpRequestException: An error occurred while sending the request.
2023-12-15 11:58:25 [verbose]: ---> System.IO.IOException: The read operation failed, see inner exception.
2023-12-15 11:58:25 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
2023-12-15 11:58:25 [verbose]: ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
2023-12-15 11:58:25 [verbose]: --- End of inner exception stack trace ---
2023-12-15 11:58:25 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2023-12-15 11:58:25 [verbose]: at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
2023-12-15 11:58:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2023-12-15 11:58:25 [verbose]: --- End of inner exception stack trace ---
2023-12-15 11:58:25 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2023-12-15 11:58:25 [verbose]: at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
2023-12-15 11:58:25 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
```

This is not... typical. Do you have a non-standard networking setup? Using a proxy, VPN, something of the sort? I'd even go as far as to go and check if your PC isn't compromised because the above looks... _very_ fishy.
