### ISSUE TITLE
Unhandled exception on launching

### ISSUE THREAD

**Issue by distilledx** [ppy/osu#27244]
### Type

Crash to desktop

### Bug description

Unhandled exception on trying to run appimage 

```
~> ./osu.AppImage
touch: cannot touch '/home/esad/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
   at osu.Framework.Platform.NativeStorage.ExistsDirectory(String path)
   at .(GameHost )
   at ..ctor(GameHost , OsuGameBase )
   at ..ctor(GameHost , OsuGameBase )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at .(Object )
   at .(Object )
   at .( )
   at .( ,  )
   at .()
   at .(Boolean )
   at .(Object )
   at .(Object )
   at .()
   at .(Object , UInt32 )
   at .(Boolean )
   at .(Object[] , Type[] , Type[] , Object[])
   at .(Stream , String , Object[] , Type[], Type[] , Object[] )
   at .(Stream , String , Object[] )
   at .(Stream , String , Object[] )
   at osu.Game.Auth.Loader.()
   at osu.Game.Auth.Loader..ctor(GameHost host, OsuGameBase game)
   at osu.Desktop.Program.Main(String[] args) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Desktop/Program.cs:line 140
[1]    293611 IOT instruction (core dumped)  ./osu.AppImage
```

Running on archlinux kernel 6.6.16-1-lts

### Version

2024.219.0

### Logs

No logs cus no directory even created

**Comment by smoogipoo** [comment]
May be fixed in the next release.
