### ISSUE TITLE
osu won't start

### ISSUE THREAD

**Issue by Misa123131** [ppy/osu#27294]
### Type

Other

### Bug description

Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
   at osu.Framework.Platform.NativeStorage.ExistsDirectory(String path)
   at .(GameHost )
   at ..ctor(GameHost , OsuGameBase )
   at ..ctor(GameHost , OsuGameBase )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at .(Object )
   at .(Object )
   at .( )
   at .( ,  )
   at .()
   at .(Boolean )
   at .(Object )
   at .(Object )
   at .()
   at .(Object , UInt32 )
   at .(Boolean )
   at .(Object[] , Type[] , Type[] , Object[])
   at .(Stream , String , Object[] , Type[], Type[] , Object[] )
   at .(Stream , String , Object[] )
   at .(Stream , String , Object[] )
   at osu.Game.Auth.Loader.()
   at osu.Game.Auth.Loader..ctor(GameHost host, OsuGameBase game)
   at osu.Desktop.Program.Main(String[] args) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Desktop/Program.cs:line 140
Aborted (core dumped)

### Version

2024.219.0

### Logs

Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
   at osu.Framework.Platform.NativeStorage.ExistsDirectory(String path)
   at .(GameHost )
   at ..ctor(GameHost , OsuGameBase )
   at ..ctor(GameHost , OsuGameBase )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at .(Object )
   at .(Object )
   at .( )
   at .( ,  )
   at .()
   at .(Boolean )
   at .(Object )
   at .(Object )
   at .()
   at .(Object , UInt32 )
   at .(Boolean )
   at .(Object[] , Type[] , Type[] , Object[])
   at .(Stream , String , Object[] , Type[], Type[] , Object[] )
   at .(Stream , String , Object[] )
   at .(Stream , String , Object[] )
   at osu.Game.Auth.Loader.()
   at osu.Game.Auth.Loader..ctor(GameHost host, OsuGameBase game)
   at osu.Desktop.Program.Main(String[] args) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Desktop/Program.cs:line 140
Aborted (core dumped)

**Comment by ilyfairy** [comment]
latest version:

$ yay osu
17 aur/osu-lazer-git latest-1 (+42 0.21) (installed: 2024.221.0.r73.d544b4dbf1-1)
    A free-to-win rhythm game. Rhythm is just a *click* away!

Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
   at osu.Framework.Platform.NativeStorage.ExistsDirectory(String path)
   at osu.Framework.Platform.GameHost.GetDefaultGameStorage()
   at osu.Framework.Platform.DesktopGameHost.GetDefaultGameStorage()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/user/.cache/yay/osu-lazer-git/src/osu/osu.Desktop/Program.cs:line 137
[1]    30072 IOT instruction (core dumped)  osu-lazer

**Comment by smoogipoo** [comment]
@ilyfairy Does the directory `~/.local/share` exist for you?

**Comment by ilyfairy** [comment]
> @ilyfairy Does the directory `~/.local/share` exist for you?

`~/.local/share` directory exists

**Comment by ilyfairy** [comment]
There is an empty string.

![image](https://github.com/ppy/osu/assets/52264192/eed477e5-83e5-42a3-aed0-ef5af4dd5b10)

**Comment by ilyfairy** [comment]
Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) return string.Empty

**Comment by bdach** [comment]
We don't use `SpecialFolder.MyDocuments` I believe? It's `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` that would matter here if anything.

**Comment by ilyfairy** [comment]
Maybe it needs to be like this:
```cs
foreach (string userStoragePath in base.UserStoragePaths)
{
     if (userStoragePath == string.Empty)
         continue;
     yield return userStoragePath;
}
```

**Comment by bdach** [comment]
Does `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` also return empty string?

**Comment by ilyfairy** [comment]
> Does `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` also return empty string?

Everything is fine with UserProfile

**Comment by bdach** [comment]
Then I don't understand, why were you talking about `Documents` if we don't use it?

The error suggests that the empty string is falling out of [here](https://github.com/ppy/osu-framework/blob/781db0a67c84faae736579d0ef3e9722714880d4/osu.Framework/Platform/Linux/LinuxGameHost.cs#L38-L52). But I can't see how this is possible.

**Comment by ilyfairy** [comment]
`MyDocument` environment variable not set in some cases
After I set it up, everything ran fine
`export MyDocuments=Documents`

**Comment by smoogipoo** [comment]
Do you have an `XDG_DATA_HOME` environment variable? What's the value of it?

**Comment by ilyfairy** [comment]
> Do you have an `XDG_DATA_HOME` environment variable? What's the value of it?

I don't have the `XDG_DATA_HOME` environment variable, It is empty.

**Comment by smoogipoo** [comment]
So... 

You mentioned `MyDocuments` is empty, the reason why that could cause the failures, even though we're not using it directly, is that `Personal == MyDocuments` so `Personal` would also be empty in that case.

But the above is only relevant as long as the path defined by `{Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)}/.local/share` doesn't exist.

On my PC, `UserProfile` points to `$HOME`, but you said that `~/.local/share` exists, so I'm not sure what's happening here.

Can you give, exactly the result of `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`?

**Comment by smoogipoo** [comment]
Nevermind, I've figured out what's happening.

`UserStoragePaths` is an enumeration containing, on linux:
```
{XDG_DATA_DIR}
{UserProfile}/.local/share
{Personal}
```

On your system, `XDG_DATA_DIR` is empty, and `Personal` is also empty (== `MyDocuments`). This is because the [breaking change in .NET 8](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix) means it's now equivalent to `$HOME/Documents`.

So the enumeration becomes:
```
"$HOME/.local/share"
""
```

Then, osu!framework [iterates through all of those](https://github.com/ppy/osu-framework/blob/781db0a67c84faae736579d0ef3e9722714880d4/osu.Framework/Platform/GameHost.cs#L1030-L1056) first checking whether `./osu` exists in any one.

In the process of doing this, it checks if `./osu` exists in the `""` directory. This is where the crash occurs.

Only after osu!framework doesn't find `./osu` does it go to create a directory.

**Comment by ilyfairy** [comment]
```cs
protected virtual Storage GetDefaultGameStorage()
{
    foreach (string userStoragePath in UserStoragePaths)
    {
        Storage storage = GetStorage(userStoragePath);
        if (storage.ExistsDirectory(Name)) // maybe is `~/.local/share/osu-development` or `~/.local/share/osu`, At the beginning, this directory does not exist, so it will traverse to the next directory, which is string.Empty
        {
            return storage.GetStorageForDirectory(Name);
        }
    }
    ...
}
```

**Comment by its0ka** [comment]
arch users install "xdg-utils" and reboot and it will be fixed

**Comment by bdach** [comment]
> arch users install "xdg-utils" and reboot and it will be fixed

That's a dodgy solution at best. We have a fix ready, it will be out next release.
