### ISSUE TITLE
All Osu! files and settings deleted.

### ISSUE THREAD

**Issue by Synchronocitys** [ppy/osu#27302]
### Type

Other

### Bug description

Problem details:
If Osu! is closed and I open any downloaded Osu! files from the internet it will open Osu! followed by the report below.
Upon reopening I will see that all my beatmaps, skins and settings have been deleted I don't know if im alone with this issue but please fix immediately.

osu! version: Lazer 2024.219.0- 19 Feburary 2024 running on Macbook Air M1 2020

### Screenshots or videos

<img width="1440" alt="Screenshot 2024-02-21 at 11 33 46 pm" src="https://github.com/ppy/osu/assets/143809805/81dec513-4e93-48fa-bd5c-dd1a36a0103f">
<img width="1440" alt="Screenshot 2024-02-21 at 11 34 44 pm" src="https://github.com/ppy/osu/assets/143809805/97a2200d-57ab-449c-a5d0-204894f2de08">
<img width="1440" alt="Screenshot 2024-02-21 at 11 34 44 pm 3" src="https://github.com/ppy/osu/assets/143809805/d047109c-9bbf-44d2-a205-deb1292a2124">

### Version

osu! version: Lazer 2024.219.0- 19 Feburary 2024 running on Macbook Air M1 2020

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14366105/compressed-logs.zip)

**Comment by bdach** [comment]
Um...

```
2024-02-21 13:34:11 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2024-02-21 13:34:11 [error]: System.UnauthorizedAccessException: Access to the path '/Library/Application Support/JamfAppInstallers/com.google.Chrome/tmp' is denied.
2024-02-21 13:34:11 [error]: ---> System.IO.IOException: Permission denied
2024-02-21 13:34:11 [error]: --- End of inner exception stack trace ---
2024-02-21 13:34:11 [error]: at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
2024-02-21 13:34:11 [error]: at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
2024-02-21 13:34:11 [error]: at System.IO.Directory.CreateDirectory(String path)
2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.getConfiguration(String filename) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 724
2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.getRealmInstance() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 701
2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 314
```

What on earth is that supposed to be?

Are you using this "jamf" thing to install the game or something?

**Comment by Synchronocitys** [comment]
> Um...
> 
> ```
> 2024-02-21 13:34:11 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
> 2024-02-21 13:34:11 [error]: System.UnauthorizedAccessException: Access to the path '/Library/Application Support/JamfAppInstallers/com.google.Chrome/tmp' is denied.
> 2024-02-21 13:34:11 [error]: ---> System.IO.IOException: Permission denied
> 2024-02-21 13:34:11 [error]: --- End of inner exception stack trace ---
> 2024-02-21 13:34:11 [error]: at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
> 2024-02-21 13:34:11 [error]: at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
> 2024-02-21 13:34:11 [error]: at System.IO.Directory.CreateDirectory(String path)
> 2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.getConfiguration(String filename) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 724
> 2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.getRealmInstance() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 701
> 2024-02-21 13:34:11 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Database/RealmAccess.cs:line 314
> ```
> 
> What on earth is that supposed to be?
> 
> Are you using this "jamf" thing to install the game or something? It seems like it's hijacking `Path.GetTempPath()` by putting `/tmp` somewhere else and just wrecking everything in the process. I'd probably recommend uninstalling it because that looks terminally broken.
> 
> Case in point: [microsoft/vscode-remote-release#9074](https://github.com/microsoft/vscode-remote-release/issues/9074)

Ive reinstalled it multiple times off the official osu website and its still not working

**Comment by bdach** [comment]
Are you using a school- or work-provided device?

**Comment by Synchronocitys** [comment]
no this is my personal device

**Comment by bdach** [comment]
Okay well, again, the presence of the "JamfAppInstallers" is interfering with the correct operation of the game. If this is your personal device then I presume you have the capability to disable it, or report this as a bug to the makers of _that_ software since it's doing clearly dodgy things. It should not be presuming that it can take over `/tmp` willy nilly.

**Comment by Synchronocitys** [comment]
ok thanks
