### ISSUE TITLE
Your score will not be submitted: Not Found

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#27399]
### Type

Other

### Bug description

I get this error sometimes I play the beatmap, and It fixes by relaunching.

### Screenshots or videos

![osu_2024-02-27_14-10-20](https://github.com/ppy/osu/assets/89677246/8e9f81bf-37ed-45e6-834b-e4e414931f0b)
![osu_2024-02-27_14-10-08](https://github.com/ppy/osu/assets/89677246/1a114175-e8c5-4cfa-8d22-a1c60ae137bc)

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14418245/compressed-logs.zip)

**Comment by bdach** [comment]
Something is deeply wrong with your network connection.

```
2024-02-27 09:48:18 [verbose]: OnlineMultiplayerClient connect attempt failed: The SSL connection could not be established, see inner exception.. Next attempt in 3 seconds.
2024-02-27 09:48:18 [verbose]: Request to https://osu.ppy.sh/api/v2/notifications failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2024-02-27 09:48:18 [verbose]: ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
2024-02-27 09:48:18 [verbose]: at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
2024-02-27 09:48:18 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
```

```
2024-02-27 10:30:51 [verbose]: Performing request osu.Game.Online.API.Requests.GetScoresRequest
2024-02-27 10:30:51 [verbose]: Request to https://a.ppy.sh/30826746?1707384794.jpeg.png failed with System.Net.WebException: NotFound.
2024-02-27 10:30:51 [verbose]: Response was: <!DOCTYPE html>
2024-02-27 10:30:51 [verbose]: <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
2024-02-27 10:30:51 [verbose]: <!--[if IE 7]> <html class="no-js ie7 oldie" lang="en"> <![endif]-->
2024-02-27 10:30:51 [verbose]: <!--[if IE 8]> <html class="no-js ie8 oldie" lang="en"> <![endif]-->
2024-02-27 10:30:51 [verbose]: <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
2024-02-27 10:30:51 [verbose]: <head>
2024-02-27 10:30:51 [verbose]: <meta charset="UTF-8">
2024-02-27 10:30:51 [verbose]: <title>Create an Ecommerce Website and Sell Online! Ecommerce Software by Shopify</title>
2024-02-27 10:30:51 [verbose]: <meta name="description" content="Shopify provides a reliable Ecommerce platform so you focus on selling online! Integrated hosting, shopping cart and Ecommerce payment solution all in one!">
```

I would run an antivirus scan because it appears your PC may be compromised.

**Comment by aL1NaZ4R** [comment]
> Something is deeply wrong with your network connection.
> 
> ```
> 2024-02-27 09:48:18 [verbose]: OnlineMultiplayerClient connect attempt failed: The SSL connection could not be established, see inner exception.. Next attempt in 3 seconds.
> 2024-02-27 09:48:18 [verbose]: Request to https://osu.ppy.sh/api/v2/notifications failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
> 2024-02-27 09:48:18 [verbose]: ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
> 2024-02-27 09:48:18 [verbose]: at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
> 2024-02-27 09:48:18 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
> ```
> 
> ```
> 2024-02-27 10:30:51 [verbose]: Performing request osu.Game.Online.API.Requests.GetScoresRequest
> 2024-02-27 10:30:51 [verbose]: Request to https://a.ppy.sh/30826746?1707384794.jpeg.png failed with System.Net.WebException: NotFound.
> 2024-02-27 10:30:51 [verbose]: Response was: <!DOCTYPE html>
> 2024-02-27 10:30:51 [verbose]: 
> 2024-02-27 10:30:51 [verbose]: 
> 2024-02-27 10:30:51 [verbose]: 
> 2024-02-27 10:30:51 [verbose]:  <html class="no-js" lang="en"> 
> 2024-02-27 10:30:51 [verbose]: <head>
> 2024-02-27 10:30:51 [verbose]: <meta charset="UTF-8">
> 2024-02-27 10:30:51 [verbose]: <title>Create an Ecommerce Website and Sell Online! Ecommerce Software by Shopify</title>
> 2024-02-27 10:30:51 [verbose]: <meta name="description" content="Shopify provides a reliable Ecommerce platform so you focus on selling online! Integrated hosting, shopping cart and Ecommerce payment solution all in one!">
> ```
> 
> I would run an antivirus scan because it appears your PC may be compromised.

So shouldn't the message displays connection problem instead of "Not found" ?

**Comment by bdach** [comment]
It's not a "connection problem", it's a "something is hijacking `a.ppy.sh` requests to instead serve some shopify nonsense" problem. We're not adding special cases for that.
