### ISSUE TITLE
osu! crashes when running AIMod on certain beatmaps

### ISSUE THREAD

**Issue by 64ArthurAraujo** [ppy/osu#27588]
### Type

Crash to desktop

### Bug description

I could not pinpoint why but running AIMod on some beatmaps causes the game to crash

beatmaps that trigger this error:
https://osu.ppy.sh/beatmapsets/1495935
https://osu.ppy.sh/beatmapsets/1236927#osu/2573166 (Water)
https://osu.ppy.sh/beatmapsets/499953#osu/1063867

Console output: 
```sh
Unhandled exception. System.AggregateException: One or more errors occurred. (Attempted to divide by zero.)
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at osu.Framework.Audio.Track.Waveform.<>c__DisplayClass13_0.<.ctor>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at osu.Framework.Audio.Track.Waveform.GetPointsAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at osu.Framework.Audio.Track.Waveform.GetPoints()
   at osu.Game.Rulesets.Edit.Checks.CheckDelayedHitsounds.Run(BeatmapVerifierContext context)+MoveNext() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Rulesets/Edit/Checks/CheckDelayedHitsounds.cs:line 57
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at osu.Game.Screens.Edit.Verify.IssueTable.set_Issues(IEnumerable`1 value) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Screens/Edit/Verify/IssueTable.cs:line 42
   at osu.Game.Screens.Edit.Verify.IssueList.Refresh() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Screens/Edit/Verify/IssueList.cs:line 104
   at osu.Game.Screens.Edit.Verify.IssueList.LoadComplete() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Screens/Edit/Verify/IssueList.cs:line 92
   at osu.Framework.Graphics.Drawable.loadComplete()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass141_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.SDL2Window.RunMainLoop()
   at osu.Framework.Platform.SDL2Window.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Desktop/Program.cs:line 143

```

### Version

2024.312.1

### Logs

Since the game crashed i just compressed my logs folder
[logs.zip](https://github.com/ppy/osu/files/14576422/logs.zip)

**Comment by 64ArthurAraujo** [comment]
Just found out what happened, all of the beatmaps i've listed have custom mute hitsounds.

in osu.Game/Rulesets/Edit/Checks/CheckDelayedHitsounds.cs
```C# 
using Waveform waveform = new Waveform(stream);

var points = waveform.GetPoints();

// Skip muted samples
if (points.Length == 0 || points.Sum(getAverageAmplitude) <= silence_threshold)
        continue;
```
They have something that makes them crash before even being checked by the game if they are mute, so it will probably need a framework fix.

**Comment by bdach** [comment]
First two cases are indeed due to hitsound, the third is due to the _video_.
