### ISSUE TITLE
Crash when clicking the import completed notification. 

### ISSUE THREAD

**Issue by NGB-Was-Taken** [ppy/osu#27736]
### Type

Crash to desktop

### Bug description

I downloaded a zip file containing 581 beatmap files, extracted it into a folder and dragged all the files into the osu window. Everything goes on as normal except that the beatmaps don't show up in the map selection screen and clicking the notification crashes the game.

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14775271/compressed-logs.zip)

**Comment by tybug** [comment]
cc @ppy/team-client. Relevant log file is `1711549216.runtime.log`.

Stacktrace:

```
2024-03-27 14:37:46 [verbose]: Beginning PresentBeatmap with beatmap unknown artist - unknown title
2024-03-27 14:37:49 [error]: An unhandled error has occurred.
2024-03-27 14:37:49 [error]: System.InvalidOperationException: Sequence contains no elements
2024-03-27 14:37:49 [error]: at System.Linq.ThrowHelper.ThrowNoElementsException()
2024-03-27 14:37:49 [error]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
2024-03-27 14:37:49 [error]: at osu.Game.OsuGame.<>c__DisplayClass100_0.<PresentBeatmap>b__3(IScreen screen) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 648
2024-03-27 14:37:49 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-03-27 14:37:49 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-03-27 14:37:49 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-03-27 14:37:49 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-03-27 14:37:49 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-03-27 14:37:49 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

This looks relevant as well:
```
2024-03-27 14:36:33 [verbose]: Song select updating selection with beatmap:null ruleset:osu
2024-03-27 14:36:33 [verbose]: Song select changing beatmap from "Silent Siren - Hachigatsu no Yoru (Cut Ver.) (Log Off Now) [Hard]" to "null"
2024-03-27 14:36:33 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2024-03-27 14:36:33 [verbose]: Song select decided to ensurePlayingSelected
```

@NGB-Was-Taken, it may be helpful if you can upload the zip file of the maps you tried to import.

**Comment by NGB-Was-Taken** [comment]
[Here](https://drive.google.com/file/d/1C-Lqz86MsnFW6jqKIjlf68cO_8Oadyb4/view) is a link to google drive containing zip of all 589* maps (4.9 GB in size).

**Comment by 64ArthurAraujo** [comment]
Reproduced this in development and got more verbose logs, for every beatmap it says "no content found in beatmap file (beatmap).osu" another detail is that i could not extract the zip from my file manager, it said "Unsupported zip compression method (9: deflation-64-bit)" but im not sure if its related to this.

```
database] 2024-03-28 15:34:52 [verbose]: [cc2d8] Beginning import from 1461145 NIWASHI - Sapphire On Fire.osz...
[database] 2024-03-28 15:34:52 [verbose]: [cc2d8] No content found in beatmap file niwashi - sapphire on fire (deviouspanda) [normal].osu.
[database] 2024-03-28 15:34:52 [verbose]: [cc2d8] No content found in beatmap file niwashi - sapphire on fire (deviouspanda) [extravaganza].osu.
[database] 2024-03-28 15:34:52 [verbose]: [cc2d8] Import successfully completed!
[database] 2024-03-28 15:34:52 [verbose]: [cd2f4] Beginning import from 1525158 Shooting star - Space Carnival.osz...
[database] 2024-03-28 15:34:53 [verbose]: [cd2f4] No content found in beatmap file shooting star - space carnival (digitalhypno) [#2839].osu.
[database] 2024-03-28 15:34:53 [verbose]: [cd2f4] Import successfully completed!
[database] 2024-03-28 15:34:53 [verbose]: [acffa] Beginning import from 1525160 Omodoka - Yosawya san (JAKAZiD's Yosawyamen Bootleg Edit).osz...
[database] 2024-03-28 15:34:53 [verbose]: [acffa] No content found in beatmap file omodoka - yosawya san (jakazid's yosawyamen bootleg edit) (digitalhypno) [#2839].osu.
[database] 2024-03-28 15:34:53 [verbose]: [acffa] Import successfully completed!
[database] 2024-03-28 15:34:53 [verbose]: [f4abc] Beginning import from 1525162 Kikuo - Gangu Kyou Sou Kyoku -Shuuen-.osz...
[database] 2024-03-28 15:34:53 [verbose]: [f4abc] No content found in beatmap file kikuo - gangu kyou sou kyoku -shuuen- (digitalhypno) [#2839].osu.
[database] 2024-03-28 15:34:53 [verbose]: [f4abc] Import successfully completed!
[database] 2024-03-28 15:34:53 [verbose]: [ee220] Beginning import from 1529362 Ado - Odo.osz...
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [Dailycare's Normal].
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [Dance].
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [Flake's Hard].
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [Wanpachi's Hyper].
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [moph's Extra].
[database] 2024-03-28 15:34:53 [verbose]: [ee220] [LocalCachedBeatmapMetadataSource] Cached local retrieval for Ado - Odo (Heilia) [ponbot's Insane].
[runtime] 2024-03-28 15:34:53 [verbose]: Invalidating working beatmap cache for Ado - Odo (Heilia) [moph's Extra]
[runtime] 2024-03-28 15:34:53 [verbose]: Invalidating working beatmap cache for Ado - Odo (Heilia) [ponbot's Insane]
[database] 2024-03-28 15:34:53 [verbose]: [ee220] Import successfully completed!
[runtime] 2024-03-28 15:34:53 [verbose]: ⚠️ Imported 589 beatmaps! Click to view.
[runtime] 2024-03-28 15:34:54 [debug]: MouseDownEvent(Left) handled by NotificationOverlay.
[runtime] 2024-03-28 15:34:55 [verbose]: Beginning PresentBeatmap with beatmap unknown artist - unknown title
[runtime] 2024-03-28 15:34:55 [debug]: ClickEvent(Left) handled by ProgressCompletionNotification.
[runtime] 2024-03-28 15:34:55 [debug]: Focus changed from FilterControl+FilterControlTextBox to nothing.
[runtime] 2024-03-28 15:34:55 [debug]: MouseClick handled by ProgressCompletionNotification.
[runtime] 2024-03-28 15:34:55 [debug]: Focus changed from nothing to FilterControl+FilterControlTextBox.
[runtime] 2024-03-28 15:34:55 [error]: An unhandled error has occurred.
[runtime] 2024-03-28 15:34:55 [error]: System.InvalidOperationException: Sequence contains no elements
```

**Comment by Stedoss** [comment]
For a simpler reproduction, import [this](https://github.com/ppy/osu/files/14796077/18.Scatman.John.-.Scatman.zip) beatmap (rename to `.osz`) that was included in the linked pack, then click on the imported notification. This will crash the game in the same way (and not show the imported beatmap in the carousel - it will be imported as unknown). Reason for the crash on notification activation is that there is [no beatmap to be selected (import count is 0).](https://github.com/ppy/osu/blob/21201e616d5a67b0868651a913b93ae9b5fb1077/osu.Game/OsuGame.cs#L647-L650)

I don't know why it's failing to read the `.osu` content, maybe weird/corrupt compression? Seems to happen on a bunch of the beatmaps from the posted pack.

**Comment by NGB-Was-Taken** [comment]
> I don't know why it's failing to read the `.osu` content, maybe weird/corrupt compression? Seems to happen on a bunch of the beatmaps from the posted pack.

Ok, so I tried importing one by one, it successfully imported around 5-6 maps. Then i moved to 5 at a time and imported 15 maps. Then I selected 20 maps and it didn't import a single one. But then I imported the same 20 maps 2-3 maps at a time and all imported.

> another detail is that i could not extract the zip from my file manager, it said "Unsupported zip compression method (9: deflation-64-bit)" and it might be related to this.

`zipinfo` shows method `d64N` and version 2.1 for most beatmaps while 4.5 for a few. Tried importing a couple of beatmaps with both 2.1 and 4.5 and they successfully imported.

**Comment by 64ArthurAraujo** [comment]
> For a simpler reproduction, import [this](https://github.com/ppy/osu/files/14796077/18.Scatman.John.-.Scatman.zip) beatmap (rename to `.osz`) that was included in the linked pack

I found something, go to BeatmapImporter.cs and add a breakpoint to line 354 debug it with the zip given as a example by @Stedoss, you will see that it will fall into the if condition `lineReader.PeekLine() == null`. Now unzip it and edit the first .osu file line, just remove everything and type again `osu file format v3` (manually), compress it and import again, you will see  that now its succesfully importing but causing another error: 

![image](https://github.com/ppy/osu/assets/90941580/7b7f6e44-027d-4d20-95f5-b09f9ee2cfcf)

![image](https://github.com/ppy/osu/assets/90941580/51949c4f-e1d4-4ea2-9338-8e0011e0e19a)


this error happens because all the beatmap's file names are lower cased and the .osu file looks for the audio with the original case. I that pretty much confirms that this compression is corrupted/messed up, but **of course osu! should not crash in those situations.**

**Comment by NGB-Was-Taken** [comment]
> I think that pretty much confirms that this compression is corrupted/messed up

Only the name seems to be messed up? The md5 hash of the audio is the same as mentioned in the `.osu` file.
![image](https://github.com/ppy/osu/assets/76197326/ee19c12a-8682-4aca-907c-5e85f93d72b2)
![image](https://github.com/ppy/osu/assets/76197326/4b5cfab9-3de5-4a2b-bf7e-aed4ed421930)

Also, can compressing a zip file mess up with the contents inside the zip?

When importing everything at once, nothing gets imported but a lot of beatmaps can be imported when going one by one. Shouldn't it import what it can and report failure on rest?
