### ISSUE TITLE
`libdl` not included in Linux version of the release 2024.412.1

### ISSUE THREAD

**Issue by SysError99** [ppy/osu#27910]
### Type

Game behaviour

### Bug description

`libdl` that seems to be crucial in order to enable Vulkan renderer is missing from Linux (AppImage) version of the release 2024.412.1, causes the game to not be able to initialise the renderer with Vulkan.

Here's the log of what happened during runtime:
```
----------------------------------------------------------
runtime Log for nate (LogLevel: Verbose)
Running osu 2024.412.1.0 on .NET 8.0.4
Environment: Linux (Unix 6.1.85.1), 8 cores 
----------------------------------------------------------
2024-04-17 08:50:52 [verbose]: Starting legacy IPC provider...
2024-04-17 08:50:53 [verbose]: 🖼️ Configuration renderer choice: Deferred_Vulkan
2024-04-17 08:50:53 [verbose]: 🖼️ Renderer fallback order: [ Vulkan (Experimental), OpenGL, OpenGL (Experimental) ]
2024-04-17 08:50:53 [verbose]: 🖼️ Initialising "Deferred" renderer with "Vulkan" surface
2024-04-17 08:50:53 [verbose]: Updated display mode to desktop resolution: 1920x1080@75, SDL_PIXELFORMAT_RGB888
2024-04-17 08:50:53 [verbose]: 🖼️ Renderer initialisation failed with:
2024-04-17 08:50:54 [verbose]: System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception.
2024-04-17 08:50:54 [verbose]: ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
2024-04-17 08:50:54 [verbose]: /tmp/.mount_osu.Ap0LK9ji/usr/bin/libdl.so: cannot open shared object file: No such file or directory
2024-04-17 08:50:54 [verbose]: /tmp/.mount_osu.Ap0LK9ji/usr/bin/liblibdl.so: cannot open shared object file: No such file or directory
2024-04-17 08:50:54 [verbose]: /tmp/.mount_osu.Ap0LK9ji/usr/bin/libdl: cannot open shared object file: No such file or directory
2024-04-17 08:50:54 [verbose]: /tmp/.mount_osu.Ap0LK9ji/usr/bin/liblibdl: cannot open shared object file: No such file or directory
2024-04-17 08:50:54 [verbose]: 
2024-04-17 08:50:54 [verbose]: at Vulkan.Libdl.dlerror()
2024-04-17 08:50:54 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary.LoadLibrary(String libraryName)
2024-04-17 08:50:54 [verbose]: at Vulkan.NativeLibrary..ctor(String libraryName)
2024-04-17 08:50:54 [verbose]: at Vulkan.NativeLibrary.UnixNativeLibrary..ctor(String libraryName)
2024-04-17 08:50:54 [verbose]: at Vulkan.NativeLibrary.Load(String libraryName)
2024-04-17 08:50:54 [verbose]: at Vulkan.VulkanNative.LoadNativeLibrary()
2024-04-17 08:50:54 [verbose]: at Vulkan.VulkanNative..cctor()
2024-04-17 08:50:54 [verbose]: --- End of inner exception stack trace ---
2024-04-17 08:50:54 [verbose]: at Vulkan.VulkanNative.vkEnumerateInstanceLayerProperties(UInt32& pPropertyCount, VkLayerProperties* pProperties)
2024-04-17 08:50:54 [verbose]: at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers()
2024-04-17 08:50:54 [verbose]: at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug, VulkanDeviceOptions options)
2024-04-17 08:50:54 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions)
2024-04-17 08:50:54 [verbose]: at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
2024-04-17 08:50:54 [verbose]: at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
2024-04-17 08:50:54 [verbose]: at osu.Framework.Graphics.Veldrid.VeldridDevice..ctor(IGraphicsSurface graphicsSurface)
2024-04-17 08:50:54 [verbose]: at osu.Framework.Graphics.Rendering.Deferred.DeferredRenderer.Initialise(IGraphicsSurface graphicsSurface)
2024-04-17 08:50:54 [verbose]: at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.Initialise(IGraphicsSurface graphicsSurface)
2024-04-17 08:50:54 [verbose]: at osu.Framework.Platform.GameHost.SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType surfaceType)
2024-04-17 08:50:54 [important]: The selected renderer (Vulkan (Experimental)) failed to initialise. Renderer selection has been reverted to automatic.
2024-04-17 08:50:54 [verbose]: 🖼️ Initialising "GL" renderer with "OpenGL" surface
```

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15008576/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Don't use Vulkan or symlink it to `libdl.so.2`. Will be fixed in next release.
