### ISSUE TITLE
No beatmaps found after Vulkan related crash

### ISSUE THREAD

**Issue by EdmundDong** [ppy/osu#28018]
### Type

Other

### Bug description

I was testing out the new experimental renderers and was running into crashes similar to #22960. In my case, the game usually crashes after a differing number of beatmap restarts rather than whenever I started a beatmap.

I tried updating my graphics card drivers to see if that would fix the crashing. After updating the driver, the game crashed but my screen had flickering stripes instead of just freezing as it did before the driver update. I opened the game and my beatmap library is gone. My library consisted of imports from stable, files downloaded in client, and files downloaded and opened into lazer.

The first-time setup allows me to import maps from stable but I'm not sure if there's a way to rescan the beatmaps in the lazer files. I obviously can download the beatmaps again, but I'm not sure if that would clobber any of the lazer replays.

### Screenshots or videos

![osu_2024-04-27_22-15-23](https://github.com/ppy/osu/assets/12579441/da126fe7-1b4b-4f53-821a-4ac03bbe9da1)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15140843/compressed-logs.zip)

**Comment by peppy** [comment]
```
2024-04-28 04:46:28 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 9 more times...
2024-04-28 04:46:28 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 8 more times...
2024-04-28 04:46:29 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 7 more times...
2024-04-28 04:46:29 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 6 more times...
2024-04-28 04:46:29 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 5 more times...
2024-04-28 04:46:29 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 4 more times...
2024-04-28 04:46:30 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 3 more times...
2024-04-28 04:46:30 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 2 more times...
2024-04-28 04:46:30 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 1 more times...
2024-04-28 04:46:30 [verbose]: Operation failed (Access to the path 'C:\Users\edong\AppData\Roaming\osu\AuthNative.dll' is denied.). Retrying 0 more times...


2024-04-28 04:46:32 [verbose]: Execution mode changed to MultiThreaded
2024-04-28 04:46:33 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2024-04-28 04:46:33 [error]: Realms.Exceptions.RealmException: SetEndOfFile() failed: unknown error (1224)
2024-04-28 04:46:33 [error]: at Realms.NativeException.ThrowIfNecessary()
2024-04-28 04:46:33 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
2024-04-28 04:46:33 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
2024-04-28 04:46:33 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2024-04-28 04:46:33 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2024-04-28 04:46:33 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2024-04-28 04:46:33 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()

2024-04-28 04:46:33 [verbose]: Creating full realm database backup at client_1714279593_corrupt.realm


```

Another case of "access denied" (probably due to antivirus or files still open) causing realm "corrupt database" triggering. I think I'll look into fixing this, it's not the first time.

@EdmundDong you can recover your database by deleting `client.realm` and renaming `client_1714279593_corrupt.realm` to `client.realm` while osu! is not running.

**Comment by EdmundDong** [comment]
I'm not sure why but `client_1714279593_corrupt.realm` did not exist, but the earlier backup `client_1714279540_corrupt.realm` did and I was able to recover the database from there.

Thanks for the quick support.
