### ISSUE TITLE
Crashing on startup: System.DllNotFoundException: bass

### ISSUE THREAD

**Issue by kot83** [ppy/osu#2809]
When starting `osu-lazer`, it crashes with a fatal error:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: bass
  at (wrapper managed-to-native) ManagedBass.Bass.GetDeviceInfo(int,ManagedBass.DeviceInfo&)
  at ManagedBass.Bass.get_DeviceCount () [0x00002] in <936a2c37f562472c9811ed7141f6f26b>:0 
  at osu.Framework.Audio.AudioManager.getAllDevices () [0x00000] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices () [0x0000d] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Audio.AudioManager.setAudioDevice (System.String preferredDevice) [0x00006] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Audio.AudioManager+<>c__DisplayClass28_0.<onDeviceChanged>b__0 () [0x00011] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Threading.Scheduler.Update () [0x001f8] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Threading.GameThread.ProcessFrame () [0x00043] in <506100d3b11146f084c4f5dc734b2137>:0 
  at osu.Framework.Threading.GameThread.runWork () [0x0002a] in <506100d3b11146f084c4f5dc734b2137>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <1050938ab6ed42698bde160668e4367c>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <1050938ab6ed42698bde160668e4367c>:0 
```
I am using the `osu-lazer-git` package on the Arch Linux AUR.

**Comment by LittleEndu** [comment]
osu-lazer-git is not officially supported. Please compile the game yourself

**Comment by FreezyLemon** [comment]
See #2785, not the exact same error but it's not unlikely that you can fix the issue by just compiling the game yourself.

**Comment by kot83** [comment]
Same error:
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.setAudioDevice(String preferredDevice)
   at osu.Framework.Audio.AudioManager.<>c__DisplayClass28_0.<onDeviceChanged>b__0()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by FreezyLemon** [comment]
Duplicate of #2386

**Comment by kot83** [comment]
I don't know if I should've commented here or on 2386, but I figured it out. I had to install the `libbass` package. It worked after that.
