### ISSUE TITLE
osu! keeps crashing in multi lobbies

### ISSUE THREAD

**Issue by Sargeanthost** [ppy/osu#28199]
### Type

Crash to desktop

### Bug description

This has been happening randomly for a while (at least a month, perhaps longer, I always chucked it up to being something I was doing), but every so often osu! will crash when alt-tabbing. It has been going on for at least a couple of versions, not sure starting when. I recently just thought of checking event viewer, and that's where this error report was. I also really only remember this happening in multi lobbies.

```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   at System.Net.FixedSizeReader.ReadPacket(Byte[], Int32, Int32)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.StartReading(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.TlsStream.Read(Byte[], Int32, Int32)
   at System.Net.PooledStream.Read(Byte[], Int32, Int32)
   at System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean)
   at System.Net.ConnectStream.ProcessWriteCallDone(System.Net.ConnectionReturnResult)
   at System.Net.HttpWebRequest.CheckDeferredCallDone(System.Net.ConnectStream)
   at System.Net.HttpWebRequest.GetResponse()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zUVukhpwbF1ln()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zOdHQ8GMejSJd()
   at A.B.Z1(System.Object)
   at A.B.H1(System.Object)
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zc9AScD8=()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zQErXNwwwLBjc()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=znM$vleK0bLWVf_vDWG_Xgtmchj2gjV0QFI5iLb4=(System.Reflection.MethodBase, System.Object, System.Object[])
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zVwoxKf$xdXY5y2y4MiXUdpY=(System.Reflection.MethodBase, System.Object, System.Object[], Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z9Z0rByNnvSa83$ahc9BGwiA1oBv9elCT3mvsUoU=(System.Reflection.MethodBase, Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zngV3waz1s84NF4H5apHEyEA=(#=qbuhFeljqqKxdHimbCy7ReAtz2ovZdZt$0$SRc4J2ODc=)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=za5jyoQ2SUWlOMvS9dNNSU$Q48JrL(#=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=, #=qbuhFeljqqKxdHimbCy7ReAtz2ovZdZt$0$SRc4J2ODc=)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z_g2bLyvlwzpV1J7UN$8s7Uk=()
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=z9v6SU6BJ8S$q6TpwtG3ZX$4=(Boolean)
   at #=qk3gqvYha2Ji0raS3NtCa_6fEF9bz9Wgkao$n5wqmlM4=.#=zwbpACt$T3THoHbwyBXoblk$ArjuPASZgTPuLPWI=(System.Object[], System.Type[], System.Type[], System.Object[])
   at #=zMP3zBd1mUO9GahpnJ$C0$s0ipKI_toDeBIYdSUA=.#=zHdKR5SSGhzbB(System.Object, System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(System.Object)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr, System.Object[], System.Object, System.Object[] ByRef)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessageSink)
   at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.DoAsyncCall()
   at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.ThreadPoolCallBack(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

This error was from earlier in the day when I also had another crash:

```
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Net.UnsafeNclNativeMethods+OSSOCK.recv(IntPtr, Byte*, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef)
   at System.Net.Sockets.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[], Int32, Int32)
   at System.Net.FixedSizeReader.ReadPacket(Byte[], Int32, Int32)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.StartReading(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.TlsStream.Read(Byte[], Int32, Int32)
   at System.Net.PooledStream.Read(Byte[], Int32, Int32)
   at System.Net.Connection.SyncRead(System.Net.HttpWebRequest, Boolean, Boolean)
   at System.Net.ConnectStream.ProcessWriteCallDone(System.Net.ConnectionReturnResult)
   at System.Net.HttpWebRequest.CheckDeferredCallDone(System.Net.ConnectStream)
   at System.Net.HttpWebRequest.GetResponse()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zUVukhpwbF1ln()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zOdHQ8GMejSJd()
   at A.B.Z1(System.Object)
   at A.B.H1(System.Object)
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zc9AScD8=()
   at #=zGuaKTsTgabjwytkz5Pfh_es=.#=zQErXNwwwLBjc()
   at #=zcfYyoBe8EckczyEekP0Ba18=.#=zbzPF50A=(Boolean)
   at #=zcfYyoBe8EckczyEekP0Ba18=.#=z3JbHjCk=()
   at #=zfhjrwbOJApcpofg2Mg==+#=zkSz_Rs6a59wk6hWRc_eB6Ug=.#=z2hiXcuqqLm$GiJbeCw8NFPI=()
   at #=zgfRPpNH4DVouVPcew_6nKViriDp4+#=z9m5LMsoXUiDokt1JpDPEFvk=.#=zEHdfO5Em7_NMlEkuWg==(System.Object)
   at #=z0As3f94NGz3iUzJ5Uz9uwPU=.#=z0iCbFCHEYIxi()
   at #=z0As3f94NGz3iUzJ5Uz9uwPU=.#=z0Ns5mZs=()
   at #=zVpSSamIGON7UpICsMgioHtA=.#=z0iCbFCHEYIxi(#=z0As3f94NGz3iUzJ5Uz9uwPU=)
   at #=zVpSSamIGON7UpICsMgioHtA=.#=zwIETPO7J8hXy()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

Windows 11 laptop, nvidia 3050ti, ryzen cpu

I'll also add that I don't ever recall osu crashing while I'm *in* the game, always either tabbing out of the game or tabbing into the game.

Ok, here are the dates for when osu has crashed for this security violation, not sure if it will help:

4/15 4/19 4/19 4/23 4/28 5/1 5/1 5/16 5/17 5/17 

### Version

20240513.1

### Logs

[update_success.log](https://github.com/ppy/osu/files/15359976/update_success.log)
[session.log](https://github.com/ppy/osu/files/15359977/session.log)
[osu!auth.log](https://github.com/ppy/osu/files/15359978/osu.auth.log)
[runtime.log](https://github.com/ppy/osu/files/15359979/runtime.log)

**Comment by bdach** [comment]
This belongs in https://github.com/ppy/osu-stable-issues
