### ISSUE TITLE
Realm startup unrecoverable error: osu.Game.Rulesets.RulesetLoadException: Ruleset could not be loaded (Type lookup failure)

### ISSUE THREAD

**Issue by DGCK81LNN** [ppy/osu#28209]
### Type

Other

### Bug description

Perhaps my third party rulesets aren't loading properly, but it should not prevent me from playing the original rulesets. Now all my beatmaps and scores won't load.

After removing all third party rulesets, I made the client retry database migration by renaming `client_xxxxx_corrupt.realm` to overwrite `client.realm` and it still errors.

~~~
2024-05-19 06:58:30 [verbose]: Running realm migration to version 41...
2024-05-19 06:58:30 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2024-05-19 06:58:30 [error]: System.AggregateException: Exception occurred in a Realm.MigrationCallback callback. (Ruleset could not be loaded (Type lookup failure))
2024-05-19 06:58:30 [error]: ---> osu.Game.Rulesets.RulesetLoadException: Ruleset could not be loaded (Type lookup failure)
2024-05-19 06:58:30 [error]: at osu.Game.Rulesets.RulesetInfo.CreateInstance()
2024-05-19 06:58:30 [error]: at osu.Game.Scoring.ScoreInfo.<get_Mods>b__155_0(APIMod m)
2024-05-19 06:58:30 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
2024-05-19 06:58:30 [error]: at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
2024-05-19 06:58:30 [error]: at osu.Game.Scoring.ScoreInfo.get_Mods()
2024-05-19 06:58:30 [error]: at osu.Game.Scoring.Legacy.LegacyScoreDecoder.PopulateTotalScoreWithoutMods(ScoreInfo score)
2024-05-19 06:58:30 [error]: at osu.Game.Database.RealmAccess.applyMigrationsForVersion(Migration migration, UInt64 targetVersion)
2024-05-19 06:58:30 [error]: at osu.Game.Database.RealmAccess.onMigration(Migration migration, UInt64 lastSchemaVersion)
2024-05-19 06:58:30 [error]: at Realms.SharedRealmHandle.OnMigration(IntPtr oldRealmPtr, IntPtr newRealmPtr, IntPtr migrationSchema, Schema oldSchema, UInt64 schemaVersion, IntPtr managedConfigHandle)
2024-05-19 06:58:30 [error]: --- End of inner exception stack trace ---
2024-05-19 06:58:30 [error]: at Realms.NativeException.ThrowIfNecessary()
2024-05-19 06:58:30 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
2024-05-19 06:58:30 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
2024-05-19 06:58:30 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2024-05-19 06:58:30 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2024-05-19 06:58:30 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2024-05-19 06:58:30 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()
~~~

### Version

2024.519.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/15368464/logs.zip)

**Comment by DGCK81LNN** [comment]
I downgraded to the previous version, re-enabled my custom rulesets and deleted all Yoso beatmaps, and then removed the custom rulesets again and updated to the latest version again but the error is still there. [logs.zip](https://github.com/ppy/osu/files/15368553/logs.zip)

And I hate the fact you can't stop an outdated client from updating itself (with an "Automatically install updates" setting or something), which made the above procedure difficult as hell.

**Comment by bdach** [comment]
we'll fix this properly. please cease for now.

**Comment by bdach** [comment]
@DGCK81LNN @Litttlefish this has been hotfixed in 2024.513.1. To go back to how things were please *first* upgrade the game to that version and *then* restore `client.realm` from backup.

**Comment by Litttlefish** [comment]
> @DGCK81LNN @Litttlefish this has been hotfixed in 2024.513.1. To go back to how things were please _first_ upgrade the game to that version and _then_ restore `client.realm` from backup.

Fixed, thanks!

**Comment by DGCK81LNN** [comment]
Sorry if I sounded a bit resentful; I didn't mean that. Thanks for all the hard work.
