### ISSUE TITLE
Android version crashes instantly to home screen

### ISSUE THREAD

**Issue by Jinkkuu** [ppy/osu#28225]
### Type

Crash to desktop

### Bug description

Crashes instantly just by opening osu!
Device:
Samsung Galaxy Tab S8
Android 14

### Version

2024.519.1 

### Logs

[1716118709.runtime.log](https://github.com/ppy/osu/files/15369171/1716118709.runtime.log)
[1716118709.network.log](https://github.com/ppy/osu/files/15369172/1716118709.network.log)
[1716118709.input.log](https://github.com/ppy/osu/files/15369173/1716118709.input.log)
[1716118709.database.log](https://github.com/ppy/osu/files/15369174/1716118709.database.log)
[1716118709.auth.log](https://github.com/ppy/osu/files/15369175/1716118709.auth.log)

**Comment by bdach** [comment]
```
2024-05-19 11:38:30 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2024-05-19 11:38:30 [error]: Realms.Exceptions.RealmException: fstat() failed: Permission denied: Permission denied (13)
2024-05-19 11:38:30 [error]: at Realms.NativeException.ThrowIfNecessary()
2024-05-19 11:38:30 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
2024-05-19 11:38:30 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
2024-05-19 11:38:30 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2024-05-19 11:38:30 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2024-05-19 11:38:30 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2024-05-19 11:38:30 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()
```

No idea how this happens.

**Comment by Jinkkuu** [comment]
> ```
> 2024-05-19 11:38:30 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
> 2024-05-19 11:38:30 [error]: Realms.Exceptions.RealmException: fstat() failed: Permission denied: Permission denied (13)
> 2024-05-19 11:38:30 [error]: at Realms.NativeException.ThrowIfNecessary()
> 2024-05-19 11:38:30 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
> 2024-05-19 11:38:30 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
> 2024-05-19 11:38:30 [error]: at Realms.RealmConfigurationBase.CreateRealm()
> 2024-05-19 11:38:30 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
> 2024-05-19 11:38:30 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
> 2024-05-19 11:38:30 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()
> ```
> 
> No idea how this happens. Both my test devices did not have something like this transpire.

Tried reinstalling osu! but no avail. it started at 2024.412.0 so i don't why this is happening

**Comment by shiumano** [comment]
If you can use ADB, you might try running `adb shell ls -alh /sdcard/Android/data/sh.ppy.osulazer/files`.
Might not help.

**Comment by Sakura-QwQ** [comment]
I have the same problem.I tried the older version but it's not work,too.But Last week it was able to run normally.
My device is Redmi K60 Pro,Android 13.
[1716261723.auth.log](https://github.com/ppy/osu/files/15384138/1716261723.auth.log)
[1716261723.database.log](https://github.com/ppy/osu/files/15384139/1716261723.database.log)
[1716261723.input.log](https://github.com/ppy/osu/files/15384140/1716261723.input.log)
[1716261723.network.log](https://github.com/ppy/osu/files/15384141/1716261723.network.log)
[1716261723.runtime.log](https://github.com/ppy/osu/files/15384143/1716261723.runtime.log)
![Screenshot_2024-05-20-17-59-20-320_com miui bugreport](https://github.com/ppy/osu/assets/62683680/033344e1-bdd0-4d3d-bce9-005645a5d6b2)

**Comment by Jinkkuu** [comment]
> If you can use ADB, you might try running `adb shell ls -alh /sdcard/Android/data/sh.ppy.osulazer/files`. Might not help.

What does that do?

**Comment by peppy** [comment]
Does the new release work any better (2024.521.2)?

**Comment by bdach** [comment]
As per

> it started at 2024.412.0 so i don't why this is happening

I'd think that the answer is "no" but worth a try I guess.

**Comment by Sakura-QwQ** [comment]
> Does the new release work any better (2024.521.2)?

No,it still has the same problem.
[1716286390.auth.log](https://github.com/ppy/osu/files/15388356/1716286390.auth.log)
[1716286390.database.log](https://github.com/ppy/osu/files/15388360/1716286390.database.log)
[1716286390.network.log](https://github.com/ppy/osu/files/15388362/1716286390.network.log)
[1716286390.runtime.log](https://github.com/ppy/osu/files/15388363/1716286390.runtime.log)

**Comment by Jinkkuu** [comment]
> Does the new release work any better (2024.521.2)?

Nope still the same problem I'm gonna see if downgrading realm fixes this

**Comment by peppy** [comment]
If you mean the realm package, we didn't upgrade it.
