### ISSUE TITLE
Game hard locking up/crashing on attempting to play any beatmap

### ISSUE THREAD

**Issue by whamer100** [ppy/osu#28697]
### Type

Crash to desktop

### Bug description

All I remember doing was listening to the song with daycore in the background for a while, and then turned off the mod and pressed play. Since the first crash it's happening for me every time I try loading **any** beatmap.

(1st attached image is where the game crashes, and 2nd attached image is when i attempted to take a screenshot)

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/10352720/186de546-8162-4a58-855a-597375d3a488)
![osu_2024-07-01_15-19-02](https://github.com/ppy/osu/assets/10352720/7800194d-7b22-4d14-a143-ec28f2a1e646)

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16059570/compressed-logs.zip)

**Comment by whamer100** [comment]
Additional info from event viewer:
```
Application: osu!.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Veldrid.Vk.VkDeviceMemoryManager+ChunkAllocator..ctor(Vulkan.VkDevice, UInt32, Boolean)
   at Veldrid.Vk.VkDeviceMemoryManager+ChunkAllocatorSet.Allocate(UInt64, UInt64, Veldrid.Vk.VkMemoryBlock ByRef)
   at Veldrid.Vk.VkDeviceMemoryManager.Allocate(Vulkan.VkPhysicalDeviceMemoryProperties, UInt32, Vulkan.VkMemoryPropertyFlags, Boolean, UInt64, UInt64, Boolean, Vulkan.VkImage, Vulkan.VkBuffer)
   at Veldrid.Vk.VkBuffer..ctor(Veldrid.Vk.VkGraphicsDevice, UInt32, Veldrid.BufferUsage, System.String)
   at Veldrid.ResourceFactory.CreateBuffer(Veldrid.BufferDescription ByRef)
   at osu.Framework.Graphics.Rendering.Deferred.Allocation.DeviceBufferPool+PooledDeviceBuffer..ctor(osu.Framework.Graphics.Veldrid.Pipelines.GraphicsPipeline, UInt32, Veldrid.BufferUsage)
   at osu.Framework.Graphics.Rendering.Deferred.Allocation.DeviceBufferPool.Get()
   at osu.Framework.Graphics.Rendering.Deferred.Allocation.VertexManager.Write[[osu.Framework.Graphics.Rendering.Vertices.TexturedVertex2D, osu.Framework, Version=2024.625.0.0, Culture=neutral, PublicKeyToken=null]](osu.Framework.Graphics.Rendering.Deferred.Allocation.MemoryReference ByRef)
   at osu.Framework.Graphics.Rendering.Deferred.EventProcessor.processUploads()
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.<createThread>g__runWork|66_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

**Comment by whamer100** [comment]
After testing every other renderer, its only happening with Vulkan.

**Comment by IceBlossom** [comment]
I'd like to add that the game is still fully interactable when rendering freezes.

https://github.com/ppy/osu/assets/78196119/17d8d145-b023-4272-95d6-e65d082ebb32

**Comment by smoogipoo** [comment]
Vulkan is unstable right now. Don't use it.
