### ISSUE TITLE
The game crashes upon launch (Android )

### ISSUE THREAD

**Issue by adExera** [ppy/osu#28822]
### Type

Crash to desktop

### Bug description

 Once I start the game,It just crashed. 

It was working fine before I updated the system, but after the update it won't work anymore

Phone: REDMAGIC 8 Pro
Model: NX729J
CPU: 8 gen2
GPU: Adreno 740
System:  RedmagicOS9.0.13MR (Android 14 api34)

### Screenshots or videos

 

https://github.com/ppy/osu/assets/166110258/a89a577d-2a31-43c9-b395-115eb51d850c

### Version

osu  lazer  Android ver 2024.625.2

### Logs

[logs.zip](https://github.com/user-attachments/files/16173597/logs.zip)

**Comment by bdach** [comment]
```
2024-07-10 11:00:57 [error]: Realm startup failed with unrecoverable error; starting with a fresh database. A backup of your database has been made.
2024-07-10 11:00:57 [error]: Realms.Exceptions.RealmException: flock() failed: Function not implemented (38)
2024-07-10 11:00:57 [error]: at Realms.NativeException.ThrowIfNecessary()
2024-07-10 11:00:57 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
2024-07-10 11:00:57 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
2024-07-10 11:00:57 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2024-07-10 11:00:57 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2024-07-10 11:00:57 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2024-07-10 11:00:57 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()
```

The upstream thread for this is https://github.com/realm/realm-core/issues/7037. Not much we can do ourselves. Some users in that thread are saying further security updates apparently "fix" this. Your vendor may be lagging behind which is why this is an issue for you only now.
