### ISSUE TITLE
Crash on entering and leaving daily challenge quickly

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#28875]
### Type

Crash to desktop

### Bug description

This was done in debug mode.
Just opened the game and joined/left the daily challenge screen once or twice.

### Version

https://github.com/ppy/osu/commit/c854dfd6fb70f29964a62a453b1f39ce2902ec1b

### Logs

[1721053672.network.log](https://github.com/user-attachments/files/16236073/1721053672.network.log)
[1721053672.performance.log](https://github.com/user-attachments/files/16236074/1721053672.performance.log)
[1721053672.runtime.log](https://github.com/user-attachments/files/16236075/1721053672.runtime.log)
[1721053672.input.log](https://github.com/user-attachments/files/16236076/1721053672.input.log)

**Comment by peppy** [comment]
```
2024-07-15 14:28:16 [error]: An unhandled error has occurred.
2024-07-15 14:28:16 [error]: System.ObjectDisposedException: Cannot access a disposed object.
2024-07-15 14:28:16 [error]: Object name: 'osu.Game.Screens.OnlinePlay.DailyChallenge.DailyChallengeLeaderboard'.
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.LoadComponentsAsync[TLoadable](IEnumerable`1 components, Action`1 onLoaded, CancellationToken cancellation, Scheduler scheduler)
2024-07-15 14:28:16 [error]: at osu.Game.Screens.OnlinePlay.DailyChallenge.DailyChallengeLeaderboard.<RefetchScores>b__30_0(IndexedMultiplayerScores req) in C:\Users\Elia\Documents\GitHub\osu\osu.Game\Screens\OnlinePlay\DailyChallenge\DailyChallengeLeaderboard.cs:line 141
2024-07-15 14:28:16 [error]: at osu.Game.Online.API.APIRequest`1.<.ctor>b__8_0() in C:\Users\Elia\Documents\GitHub\osu\osu.Game\Online\API\APIRequest.cs:line 40
2024-07-15 14:28:16 [error]: at osu.Game.Online.API.APIRequest.<TriggerSuccess>b__24_0() in C:\Users\Elia\Documents\GitHub\osu\osu.Game\Online\API\APIRequest.cs:line 167
2024-07-15 14:28:16 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-15 14:28:16 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-15 14:28:16 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-15 14:28:16 [error]: at osu.Framework.Threading.GameThread.processFrame()
```
