### ISSUE TITLE
Crash when adding mania notes right after changing timing point 

### ISSUE THREAD

**Issue by gresial101** [ppy/osu#28938]
### Type

Crash to desktop

### Bug description

It happens if you try to chart right after editing a bpm point or inherit point in the timing menu. i cant say if it happens on any other game mode besides mania editor. Before the most recent update it would give you a warning that something was going wrong and that it automaticly got reported to the devs but now it just straight up crashes which is far more annoying so i feel the need to report this. i have to assume the issue has to do with placeing objects after the divisor lines change distance from the new timing point or inherit point. either way its super annoying that Osu! lazer crashes like this.

### Screenshots or videos

![osu_2024-07-18_19-46-14](https://github.com/user-attachments/assets/198c6a4d-c780-438a-af2b-0bef5b604dc1)

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16299161/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Relevant log excerpt:
```
2024-07-19 00:46:12 [error]: An unhandled error has occurred.
2024-07-19 00:46:12 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2024-07-19 00:46:12 [error]: at osu.Game.Rulesets.Edit.PlacementBlueprint.UpdateTimeAndPosition(SnapResult result)
2024-07-19 00:46:12 [error]: at osu.Game.Rulesets.Mania.Edit.Blueprints.NotePlacementBlueprint.UpdateTimeAndPosition(SnapResult result)
2024-07-19 00:46:12 [error]: at osu.Game.Screens.Edit.Compose.Components.ComposeBlueprintContainer.updatePlacementPosition()
2024-07-19 00:46:12 [error]: at osu.Game.Screens.Edit.Compose.Components.ComposeBlueprintContainer.ensurePlacementCreated()
2024-07-19 00:46:12 [error]: at osu.Game.Screens.Edit.Compose.Components.ComposeBlueprintContainer.refreshTool()
2024-07-19 00:46:12 [error]: at osu.Game.Screens.Edit.Compose.Components.ComposeBlueprintContainer.hitObjectAdded(HitObject obj)
```
