### ISSUE TITLE
Game crashes when presenting a replay from multiplayer results screen

### ISSUE THREAD

**Issue by ggliv** [ppy/osu#29152]
### Type

Crash to desktop

### Bug description

Probably caused/exacerbated by #29097, if I had to guess.

Repro:
1. Play a multi game to completion
2. From the results screen, download and watch someone's replay
3. Crash

### Version

2024.727.0

### Logs

<details>
<summary>Relevant snippet</summary>
<pre><code>2024-07-28 00:18:58 [verbose]: 📺 OsuScreenStack#570(depth:7) entered MultiplayerResultsScreen#442
2024-07-28 00:19:00 [verbose]: ⚠️ Downloading Elliot G boy playing Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]
2024-07-28 00:19:01 [verbose]: ⚠️ Imported Elliot G boy playing Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]! Click to view.
2024-07-28 00:19:02 [verbose]: Beginning PresentScore with score Elliot G boy playing Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:6) exit from MultiplayerResultsScreen#442
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:6) resume to MultiplayerPlayer#143
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:5) exit from MultiplayerPlayer#143
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:5) resume to MultiplayerPlayerLoader#214
2024-07-28 00:19:02 [verbose]: High performance session finished (10 others remain)
2024-07-28 00:19:02 [verbose]: 📺 BackgroundScreenStack#280(depth:1) exit from BackgroundScreenBeatmap#266
2024-07-28 00:19:02 [verbose]: 📺 BackgroundScreenStack#280(depth:1) resume to BackgroundScreenDefault#210
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:4) exit from MultiplayerPlayerLoader#214
2024-07-28 00:19:02 [verbose]: 📺 OsuScreenStack#570(depth:4) resume to Multiplayer#309
2024-07-28 00:19:02 [verbose]: Game-wide working beatmap updated to please load a beatmap! - no beatmaps available!
2024-07-28 00:19:02 [verbose]: 🌅 Global background change queued
2024-07-28 00:19:02 [verbose]: PresentScore updating beatmap (Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]) and ruleset (osu!) to match score
2024-07-28 00:19:02 [error]: An unhandled error has occurred.
2024-07-28 00:19:02 [error]: System.InvalidOperationException: Can not set value to "Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]" as bindable is disabled.
2024-07-28 00:19:02 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 00:19:02 [error]: at osu.Framework.Bindables.NonNullableBindable`1.set_Value(T value)
2024-07-28 00:19:02 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 00:19:02 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 00:19:02 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 00:19:02 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions.
2024-07-28 00:19:02 [verbose]: ⚠️ An unhandled error has occurred.
2024-07-28 00:19:02 [verbose]: 
2024-07-28 00:19:02 [verbose]: This error has been automatically reported to the devs.
2024-07-28 00:19:02 [verbose]: PresentScore updating beatmap (Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]) and ruleset (osu!) to match score
2024-07-28 00:19:02 [error]: An unhandled error has occurred.
2024-07-28 00:19:02 [error]: System.InvalidOperationException: Can not set value to "Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]" as bindable is disabled.
2024-07-28 00:19:02 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 00:19:02 [error]: at osu.Framework.Bindables.NonNullableBindable`1.set_Value(T value)
2024-07-28 00:19:02 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 00:19:02 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 00:19:02 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:02 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 00:19:02 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 00:19:02 [verbose]: Too many unhandled exceptions, crashing out.
2024-07-28 00:19:02 [verbose]: ⚠️ An unhandled error has occurred.
2024-07-28 00:19:02 [verbose]: 
2024-07-28 00:19:02 [verbose]: This error has been automatically reported to the devs.
2024-07-28 00:19:03 [verbose]: 🌅 Global background loading
2024-07-28 00:19:03 [verbose]: PresentScore updating beatmap (Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]) and ruleset (osu!) to match score
2024-07-28 00:19:03 [error]: An unhandled error has occurred.
2024-07-28 00:19:03 [error]: System.InvalidOperationException: Can not set value to "Alex Pizzuti - I Don't Wanna Go To School feat. Shibui (Nightcore Mix) (Andrea) [Gero & Mekki's Hard]" as bindable is disabled.
2024-07-28 00:19:03 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 00:19:03 [error]: at osu.Framework.Bindables.NonNullableBindable`1.set_Value(T value)
2024-07-28 00:19:03 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 00:19:03 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 00:19:03 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 00:19:03 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 00:19:03 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 00:19:03 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 00:19:03 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 00:19:03 [verbose]: Too many unhandled exceptions, crashing out.</code></pre>
</details>

**Comment by bdach** [comment]
Please post full logs. The snippet is not enough.

**Comment by frenzibyte** [comment]
Also noticed this while playing on multiplayer:
```
2024-07-28 19:55:20 [verbose]: ⚠️ Downloading Reyyo playing Pegboard Nerds - Try This (Marmowka) [Insane]
2024-07-28 19:55:21 [verbose]: ⚠️ Imported Reyyo playing Pegboard Nerds - Try This (Marmowka) [Insane]! Click to view.
2024-07-28 19:55:22 [verbose]: Beginning PresentScore with score Reyyo playing Pegboard Nerds - Try This (Marmowka) [Insane]
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:6) exit from MultiplayerResultsScreen#180
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:6) resume to MultiplayerPlayer#404
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:5) exit from MultiplayerPlayer#404
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:5) resume to MultiplayerPlayerLoader#492
2024-07-28 19:55:22 [verbose]: Ending high performance session
2024-07-28 19:55:22 [verbose]: 📺 BackgroundScreenStack#391(depth:1) exit from BackgroundScreenBeatmap#581
2024-07-28 19:55:22 [verbose]: 📺 BackgroundScreenStack#391(depth:1) resume to BackgroundScreenDefault#275
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:4) exit from MultiplayerPlayerLoader#492
2024-07-28 19:55:22 [verbose]: 📺 OsuScreenStack#403(depth:4) resume to Multiplayer#218
2024-07-28 19:55:22 [verbose]: Game-wide working beatmap updated to S3RL - Pika Girl (Nightcore & Cut Ver.) (Sotarks) [Reform's Extra]
2024-07-28 19:55:22 [verbose]: MusicController starting playback to EnsurePlayingSomething
2024-07-28 19:55:22 [verbose]: 🌅 Global background change queued
2024-07-28 19:55:22 [verbose]: PresentScore updating beatmap (Pegboard Nerds - Try This (Marmowka) [Insane]) and ruleset (osu!) to match score
2024-07-28 19:55:22 [error]: An unhandled error has occurred.
2024-07-28 19:55:22 [error]: System.InvalidOperationException: Can not set value to "Pegboard Nerds - Try This (Marmowka) [Insane]" as bindable is disabled.
2024-07-28 19:55:22 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 19:55:22 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 19:55:22 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions.
2024-07-28 19:55:22 [verbose]: ⚠️ An unhandled error has occurred.
2024-07-28 19:55:22 [verbose]:
2024-07-28 19:55:22 [verbose]: This error has been automatically reported to the devs.
2024-07-28 19:55:22 [verbose]: PresentScore updating beatmap (Pegboard Nerds - Try This (Marmowka) [Insane]) and ruleset (osu!) to match score
2024-07-28 19:55:22 [error]: An unhandled error has occurred.
2024-07-28 19:55:22 [error]: System.InvalidOperationException: Can not set value to "Pegboard Nerds - Try This (Marmowka) [Insane]" as bindable is disabled.
2024-07-28 19:55:22 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 19:55:22 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 19:55:22 [verbose]: Too many unhandled exceptions, crashing out.
2024-07-28 19:55:22 [verbose]: ⚠️ An unhandled error has occurred.
2024-07-28 19:55:22 [verbose]:
2024-07-28 19:55:22 [verbose]: This error has been automatically reported to the devs.
2024-07-28 19:55:22 [verbose]: 🌅 Global background loading
2024-07-28 19:55:22 [verbose]: PresentScore updating beatmap (Pegboard Nerds - Try This (Marmowka) [Insane]) and ruleset (osu!) to match score
2024-07-28 19:55:22 [error]: An unhandled error has occurred.
2024-07-28 19:55:22 [error]: System.InvalidOperationException: Can not set value to "Pegboard Nerds - Try This (Marmowka) [Insane]" as bindable is disabled.
2024-07-28 19:55:22 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2024-07-28 19:55:22 [error]: at osu.Game.OsuGame.<>c__DisplayClass105_0.<PresentScore>b__1(IScreen screen) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/OsuGame.cs:line 781
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.findValidTarget(IScreen current) in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 96
2024-07-28 19:55:22 [error]: at osu.Game.PerformFromMenuRunner.checkCanComplete() in /Users/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/PerformFromMenuRunner.cs:line 82
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-07-28 19:55:22 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-07-28 19:55:22 [error]: at osu.Framework.Threading.GameThread.processFrame()
2024-07-28 19:55:22 [verbose]: Too many unhandled exceptions, crashing out.
```

Raising to `priority:0`.

**Comment by frenzibyte** [comment]
[logs.zip](https://github.com/user-attachments/files/16405231/logs.zip)
