### ISSUE TITLE
Game stuck in main menu screen after opening from editor link

### ISSUE THREAD

**Issue by Hydria** [ppy/osu#29975]
### Type

Game behaviour

### Bug description

clicked osu://edit/00:18:277 (18277|0,18277|1,18384|2,18384|1) which ended up opening lazer, and after reaching the main menu, I noticed the osu circle wasn't coloured in, the top bar was missing, and clicking the cookie resulted in no behaviour. The shortcut commands still worked, though the music could not be paused either.

1727109241.runtime.log should have the corresponding error related to this issue.

Opening the game a second time this way did not have the same issue, so this appears to be a one-off issue.

### Screenshots or videos

https://github.com/user-attachments/assets/b3558a19-72d8-4b6c-9bba-8bac1042d115

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17101200/compressed-logs.zip)

**Comment by bdach** [comment]
I guess there's this:

```
2024-09-23 16:34:05 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2024-09-23 16:34:05 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNext()
2024-09-23 16:34:05 [error]: at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character)
2024-09-23 16:34:05 [error]: at osu.Framework.Graphics.Sprites.SpriteIcon.updateTexture()
2024-09-23 16:34:05 [error]: at osu.Framework.Graphics.Sprites.SpriteIcon.load(FontStore store, ShaderManager shaders)
2024-09-23 16:34:05 [error]: at osu.Framework.Graphics.Sprites.SpriteIcon.<>c.<RegisterForDependencyActivation>b__27_0(Object t, IReadOnlyDependencyContainer d)
2024-09-23 16:34:05 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-09-23 16:34:05 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-09-23 16:34:05 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[T](T instance)
```

but I wouldn'r expect this to have the effect shown on the video necessarily...?

**Comment by peppy** [comment]
I've confirmed the above exception cannot happen in our official codebase. This is due to a custom ruleset doing weird font loading.

`2024-09-23 16:34:05 [verbose]: Cached font load for Fonts/tauFont`

We could guard against this but I'm not sure it's our responsibility to do so. Maybe it is because `Game.AddFont` can be called at any point (but shouldn't be, in its current form). @ppy/team-client thoughts on fixing this framework side?

**Comment by bdach** [comment]
> Maybe it is because `Game.AddFont` can be called at any point (but shouldn't be, in its current form)

If it can be made safe then sure. Exception to tell people off that they shouldn't be doing that is also fine I guess.
