### ISSUE TITLE
Failed to join multiplayer room

### ISSUE THREAD

**Issue by inawwwah** [ppy/osu#30221]
### Type

Other

### Bug description

I entered a multiplayer room but suddenly it crashed and exited the room. I tried to join several multiplayer rooms afterward but failed after restarting osu. It's not my internet issue. Working on Macbook Air M1 with system version 12.4.

Note: I joined rooms without passwords.

### Screenshots or videos

<img width="1440" alt="Screen Shot 2024-10-11 at 23 32 53" src="https://github.com/user-attachments/assets/698b8350-7b06-4ac4-80d9-7221008c2380">
e.g. I failed to join the open room selected and any other open rooms.

### Version

2024.1009.1

### Logs

2024-10-11 15:22:27 [verbose]: 🌅 Global background change queued
2024-10-11 15:22:28 [verbose]: 🌅 Global background loading
2024-10-11 15:22:43 [verbose]: ⚠️ Failed to join multiplayer room.
2024-10-11 15:22:43 [verbose]: 
2024-10-11 15:22:43 [verbose]: This error has been automatically reported to the devs.
2024-10-11 15:22:43 [error]: Failed to join multiplayer room.
2024-10-11 15:22:43 [error]: System.AggregateException: One or more errors occurred. (One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server.))
2024-10-11 15:22:43 [error]: ---> System.AggregateException: One or more errors occurred. (An unexpected error occurred invoking 'JoinRoomWithPassword' on the server.)
2024-10-11 15:22:43 [error]: ---> Microsoft.AspNetCore.SignalR.HubException: An unexpected error occurred invoking 'JoinRoomWithPassword' on the server.
2024-10-11 15:22:43 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2024-10-11 15:22:43 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
2024-10-11 15:22:43 [error]: at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
2024-10-11 15:22:43 [error]: at osu.Game.Online.Multiplayer.OnlineMultiplayerClient.JoinRoom(Int64 roomId, String password)
2024-10-11 15:22:43 [error]: at osu.Game.Online.Multiplayer.OnlineMultiplayerClient.JoinRoom(Int64 roomId, String password)
2024-10-11 15:22:43 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.<>c__DisplayClass76_0.<<JoinRoom>b__0>d.MoveNext()
2024-10-11 15:22:43 [error]: --- End of inner exception stack trace ---
2024-10-11 15:22:43 [error]: at osu.Game.Online.Multiplayer.MultiplayerClient.JoinRoom(Room room, String password)
2024-10-11 15:22:43 [error]: --- End of inner exception stack trace ---

**Comment by peppy** [comment]
The server had an issue. You won't be able to join older rooms. Please join newer rooms.
