### ISSUE TITLE
Can't submit scores warning appear in a weird time

### ISSUE THREAD

**Issue by necocat0918** [ppy/osu#30323]
### Type

Other

### Bug description

Even with the latest lazer version, osu doesn't seem like it want to submit your score, may be a server issue

I checked updates and ini files, it is the latest

### Screenshots or videos

https://streamable.com/r8vb0u

video expire in 2 days (sorry for that)

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17411770/compressed-logs.zip)

**Comment by necocat0918** [comment]
issue was fully fixed in the next restart

**Comment by bdach** [comment]
You had this happening for whatever reason for a while:

```
2024-10-17 11:36:18 [verbose]: Request to https://osu.ppy.sh/api/v2/seasonal-backgrounds failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2024-10-17 11:36:18 [verbose]: ---> System.IO.IOException: Unable to read data from the transport connection: 遠端主機已強制關閉一個現存的連線。.
2024-10-17 11:36:18 [verbose]: ---> System.Net.Sockets.SocketException (10054): 遠端主機已強制關閉一個現存的連線。
2024-10-17 11:36:18 [verbose]: --- End of inner exception stack trace ---
2024-10-17 11:36:18 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-10-17 11:36:18 [verbose]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
2024-10-17 11:36:18 [verbose]: at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
2024-10-17 11:36:18 [verbose]: at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-10-17 11:36:18 [verbose]: at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
2024-10-17 11:36:18 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
2024-10-17 11:36:18 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
```

and the same reason caused auth to fail to update, which caused submission to stop working. Not really seeing anything actionable here, seems to just be network issue.
