### ISSUE TITLE
Crash when resetting offset

### ISSUE THREAD

**Issue by ssz7-ch2** [ppy/osu#30573]
### Type

Crash to desktop

### Bug description

Was trying to reset the offset for a beatmap when the game crashed.
Tried to reproduce but I have no idea what I specifically did to cause the crash.

### Version

2024.1009.1.0

### Logs

[1731189581.runtime.log](https://github.com/user-attachments/files/17689846/1731189581.runtime.log)

**Comment by frenzibyte** [comment]
Relevant excerpt:
```
2024-11-10 01:14:52 [error]: System.ArgumentException: newValue must be finite, but is NaN. (Parameter 'newValue')
2024-11-10 01:14:52 [error]: at osu.Framework.Graphics.TransformableExtensions.PopulateTransform[TValue,TEasing,TThis](TThis t, Transform`3 transform, TValue newValue, Double duration, TEasing& easing)
2024-11-10 01:14:52 [error]: at osu.Game.Screens.Ranking.Statistics.HitEventTimingDistributionGraph.Bar.updateMetrics(Boolean animate)
2024-11-10 01:14:52 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-11-10 01:14:52 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-11-10 01:14:52 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

For cases like this I wonder if it's worth the effort to investigate and find out the direct reason why this happened instead of just adding a guard around https://github.com/ppy/osu/blob/53509453405f8256fd66b05dabf84c65c5f2b0b2/osu.Game/Screens/Ranking/Statistics/HitEventTimingDistributionGraph.cs#L351 and call it a day (assuming it is where the NaN came from, which it likely is).

**Comment by bdach** [comment]
NaNs are usually proof of `0f / 0f` division. So that'd be the obvious first direction to explore, if you can get that to happen.

**Comment by frenzibyte** [comment]
I'm not sure how to reproduce this myself, and on a bit of scouting I wasn't able to find anything wrong, so that's why I'm asking here if it's worth the effort rather than just guarding against faulty calculations.

**Comment by bdach** [comment]
I don't think blindly guarding against unexpected data we do. Not without understanding where the unexpected data is coming from beforehand, and in looking at this a bit, it would appear the NaNs come from `HitEvent`s themselves since I see no other avenues of possibility, which would be *very* worrying.

**Comment by peppy** [comment]
> I'm not sure how to reproduce this myself, and on a bit of scouting I wasn't able to find anything wrong, so that's why I'm asking here if it's worth the effort rather than just guarding against faulty calculations.

Did you try the obvious case of no results to display? Because it took me 2 minutes to make a test covering this failure it was so obvious 😅 .
