### ISSUE TITLE
osu! crashes with no output

### ISSUE THREAD

**Issue by LollipopFt** [ppy/osu#30717]
### Type

Crash to desktop

### Bug description

In the latest version [2024.1115.3](https://github.com/ppy/osu/releases/tag/2024.1115.3), osu crashes immediately: window does not appear, with no helpful output in the console:
```
[ball@pyramid ~]$ osu.AppImage 
cp: cannot create regular file '/home/ball/.cache/thumbnails/normal/a6a2f50d1e3433418de2cc8b94d70b1c.png': No such file or directory
cp: cannot create regular file '/home/ball/.cache/thumbnails/large/a6a2f50d1e3433418de2cc8b94d70b1c.png': No such file or directory
[ball@pyramid ~]$ 
```

whereas in [2024.1115.2](https://github.com/ppy/osu/releases/tag/2024.1115.2), osu crashes with errors:
```
[ball@pyramid ~]$ osu.AppImage 
cp: cannot create regular file '/home/ball/.cache/thumbnails/normal/a6a2f50d1e3433418de2cc8b94d70b1c.png': No such file or directory
cp: cannot create regular file '/home/ball/.cache/thumbnails/large/a6a2f50d1e3433418de2cc8b94d70b1c.png': No such file or directory
/tmp/.mount_osu.ApZzxWvh/usr/bin/UpdateNix: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Unhandled exception. System.Exception: Update.exe process exited too soon (127).
   at Velopack.UpdateExe.Apply(IVelopackLocator locator, VelopackAsset toApply, Boolean silent, Boolean restart, String[] restartArgs, ILogger logger)
   at Velopack.VelopackApp.Run(ILogger logger)
   at osu.Desktop.Program.setupVelopack()
   at osu.Desktop.Program.Main(String[] args)
Aborted (core dumped)
[ball@pyramid ~]$ 
```

### Version

2024.1115.3

### Logs

unable to get output: game crashes immediately

**Comment by hwsmm** [comment]
What distro are you using? and does `OSU_EXTERNAL_UPDATE_PROVIDER=1 ./osu.AppImage` help?

**Comment by LollipopFt** [comment]
i should close this, decided to "fix" it by clearing out the .local files and start from scratch.

**Comment by developedby** [comment]
For anyone reading this in the future, simply downloading the latest appimage should be enough, no need to nuke your install.
