### ISSUE TITLE
Beatmap comment embeddings not displaying correctly in in-game beatmap listing

### ISSUE THREAD

**Issue by jojohnathon** [ppy/osu#30791]
### Type

Game behaviour

### Bug description

Open in-game beatmap listing --> go to a beatmap comment w/ image or gif

[Beatmap ](https://osu.ppy.sh/beatmapsets/2264468#osu/4820866)in my example

### Screenshots or videos

![image](https://github.com/user-attachments/assets/5ec9df90-55bf-40fa-ae8f-4341e25bda0c)

![image](https://github.com/user-attachments/assets/6a598e98-052f-4ed7-91dc-49cda0cba4f8)

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17827833/compressed-logs.zip)

**Comment by bdach** [comment]
Both of these shown on the screenshot are gifs.

Support for gif display [has been considered out of scope](https://github.com/ppy/osu/issues/14417#issuecomment-902912900) previously. Not sure if anything changed.

**Comment by jojohnathon** [comment]
![image](https://github.com/user-attachments/assets/e6fa950d-e323-445c-896d-1c19f11b3f5e)
![image](https://github.com/user-attachments/assets/67d2f2a5-7812-428a-b6f2-d2f15d0f889c)

Here's an [example ](https://osu.ppy.sh/comments/2537181)with images. 


Another [one](https://osu.ppy.sh/comments/3276232).
![image](https://github.com/user-attachments/assets/69a9b0ec-bb57-4df9-95ee-8f1f0ea0a397)
![image](https://github.com/user-attachments/assets/f5131383-67b5-4a20-9350-f87b301696d1)


Somewhat related are the [emojis](https://osu.ppy.sh/comments/2537065).
![image](https://github.com/user-attachments/assets/6513b947-f664-4f5f-8506-1a3d20600485)
![image](https://github.com/user-attachments/assets/e7e1c26c-b745-4cb8-ad76-de97ee2ea4f8)

**Comment by frenzibyte** [comment]
Both of the examples you attached above contain images hosted on the s-ul.eu domain. Those fail the SSL handshake, therefore not loading in the game:
```
[network] 2024-11-24 08:38:13 [verbose]: Request to https://prdec.s-ul.eu/eiU27EFf.jpg failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
[network] 2024-11-24 08:38:13 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
[network] 2024-11-24 08:38:13 [verbose]: ---> Interop+AppleCrypto+SslException: handshake failure
[network] 2024-11-24 08:38:13 [verbose]: --- End of inner exception stack trace ---
[network] 2024-11-24 08:38:13 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
[network] 2024-11-24 08:38:13 [verbose]: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
```

This can also be confirmed in the logs you have attached:
```
2024-11-20 08:52:59 [verbose]: Request to https://ashi.s-ul.eu/A8lGZMuj failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2024-11-20 08:52:59 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
2024-11-20 08:52:59 [verbose]: ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
2024-11-20 08:52:59 [verbose]: --- End of inner exception stack trace ---
```

may need @ppy/team-client attention since s-ul.eu is commonly used by the osu! community as far my quick google and discord searches go, although I'm not quite sure what can be done from our side to fix this (other than to figure out how it still loads on osu-web and in browsers in general).

**Comment by nanaya** [comment]
oh yeah, markdown images are proxied on web during parsing phase which for comments happens on frontend (proxied url is obtained through `/beatmapsets/discussions/media-url?url=...`)

**Comment by peppy** [comment]
Hmm, right. We need to be doing that in the client then 💦

**Comment by bdach** [comment]
there's a PR fixing this already, no counsel required
