### ISSUE TITLE
Applying a filter while entering song select and loading a map directly after that crashes the game

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#3105]
This is a bit tricky to reproduce, you really have to mash keys while entering song select (just hit "asdf" and Enter at the same time).

```
System.InvalidOperationException: Can not set value to "osu.Game.Beatmaps.DummyWorkingBeatmap" as bindable is disabled.
   at osu.Framework.Configuration.Bindable`1.set_Value(T value)
   at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass30_0.<updateSelectedBeatmap>g__performLoad|0() in D:\DEV\osu\osu.Game\Screens\Select\SongSelect.cs:line 322
   at osu.Game.Screens.Select.SongSelect.updateSelectedBeatmap(BeatmapInfo beatmap) in D:\DEV\osu\osu.Game\Screens\Select\SongSelect.cs:line 339
   at osu.Game.Screens.Select.BeatmapCarousel.updateItems() in D:\DEV\osu\osu.Game\Screens\Select\BeatmapCarousel.cs:line 586
   at osu.Game.Screens.Select.BeatmapCarousel.Update() in D:\DEV\osu\osu.Game\Screens\Select\BeatmapCarousel.cs:line 415
```

[Video](https://youtu.be/7CgJyWa0IX8)

**Comment by peppy** [comment]
I think this will be fixed by the changes I'm working on for song select.

**Comment by peppy** [comment]
This should be fixed already.
