### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [ppy/osu#3215]

**Comment by H1ROYUKII** [comment]
howd that happen

**Comment by peppy** [comment]
Are you running on linux? Could be a similar issue to #3118.

**Comment by WithoutKnock** [comment]
No I'm running it on Windows. 

My PC Specs: 

CPU: Intel Core i5 750
GPU: GeForce GT 230
RAM: 12GB 
OS: Windows Server 2016 Standard Evaluation (My CPU is a Server/Enterprise CPU)

**Comment by WithoutKnock** [comment]
I still have the Visual Bug. I thought this is fixed now....

**Comment by peppy** [comment]
You will need to recompile.

**Comment by peppy** [comment]
Oh, you are on windows? That's an interesting one then. Can you please ensure you are on 2018.906.0?

**Comment by WithoutKnock** [comment]
ok wait

**Comment by WithoutKnock** [comment]
![screenshot 44](https://user-images.githubusercontent.com/41303944/45164888-d562ee80-b1f3-11e8-9fb9-15a64668f987.png)

**Comment by peppy** [comment]
Are you on the latest nvidia drivers?

**Comment by WithoutKnock** [comment]
let me check

**Comment by WithoutKnock** [comment]
I need to redownload experience sry for that ._.

**Comment by WithoutKnock** [comment]
I'm on the latest one

**Comment by WithoutKnock** [comment]
Version 342.01

**Comment by peppy** [comment]
This is not a chat room. Please combine your outgoing text into a single message and refrain from posting "let me check" or similar.

**Comment by WithoutKnock** [comment]
ok sry for that

**Comment by WithoutKnock** [comment]
https://youtu.be/a5Kt3-vS3OQ

If you need something like this there you go

**Comment by WithoutKnock** [comment]
Ok this is very weird right now. I just let the auto bot play big black and the bot just misses and in the video you can see many visual bugs.

https://youtu.be/iaYB4pS8GQ0

runtime.log:

06.09.2018 16:17:28: ----------------------------------------------------------
06.09.2018 16:17:28: Runtime Log for Administrator (LogLevel: Verbose)
06.09.2018 16:17:28: osu 2018.906.0.0
06.09.2018 16:17:28: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
06.09.2018 16:17:28: ----------------------------------------------------------
06.09.2018 16:17:28: GL Initialized
06.09.2018 16:17:28: GL Version:                 3.3.0
06.09.2018 16:17:28: GL Renderer:                GeForce GT 230/PCIe/SSE2
06.09.2018 16:17:28: GL Shader Language version: 3.30 NVIDIA via Cg compiler
06.09.2018 16:17:28: GL Vendor:                  NVIDIA Corporation
06.09.2018 16:17:28: GL Extensions:              GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_clear_buffer_object GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_debug GL_KTX_buffer_region GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_ES1_1_compatibility GL_NV_explicit_multisample GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_buffer_load GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_expand_normal GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control
06.09.2018 16:17:28: BASS Initialized
06.09.2018 16:17:28: BASS Version:               2.4.12.15
06.09.2018 16:17:28: BASS FX Version:            2.4.11.1
06.09.2018 16:17:28: Device:                     Lautsprecher (High Definition Audio-Gerät)
06.09.2018 16:17:28: Drive:                      {0.0.0.00000000}.{a8ecd6bc-0f0a-4d49-b08c-c55489d61e77}
06.09.2018 16:17:33: Screen changed → Disclaimer
06.09.2018 16:17:39: Screen changed → Intro
06.09.2018 16:17:42: Screen changed → MainMenu
06.09.2018 16:18:21: ButtonSystem's state changed from Initial to TopLevel
06.09.2018 16:18:23: ButtonSystem's state changed from TopLevel to Play
06.09.2018 16:18:24: ButtonSystem's state changed from Play to EnteringMode
06.09.2018 16:18:24: Screen changed → PlaySongSelect
06.09.2018 16:18:24: updating selection with beatmap:161 ruleset:0
06.09.2018 16:18:24: beatmap changed from "nekodex - circles! (peppy) []" to "Akaza Akari(CV:Mikami Shiori) - Watashi, Shuyaku no Akaza Akari desu (Setz) [kakifly's Hard]"
06.09.2018 16:18:24: working beatmap updated to Akaza Akari(CV:Mikami Shiori) - Watashi, Shuyaku no Akaza Akari desu (Setz) [kakifly's Hard]
06.09.2018 16:18:28: updating selection with beatmap:420 ruleset:0
06.09.2018 16:18:28: beatmap changed from "Akaza Akari(CV:Mikami Shiori) - Watashi, Shuyaku no Akaza Akari desu (Setz) [kakifly's Hard]" to "RADWIMPS - Zen Zen Zense (movie ver.) (Monstrata) [Battle's Easy]"
06.09.2018 16:18:28: working beatmap updated to RADWIMPS - Zen Zen Zense (movie ver.) (Monstrata) [Battle's Easy]
06.09.2018 16:18:29: updating selection with beatmap:303 ruleset:0
06.09.2018 16:18:29: beatmap changed from "RADWIMPS - Zen Zen Zense (movie ver.) (Monstrata) [Battle's Easy]" to "The Quick Brown Fox - The Big Black (Blue Dragon) [WHO'S AFRAID OF THE BIG BLACK]"
06.09.2018 16:18:29: working beatmap updated to The Quick Brown Fox - The Big Black (Blue Dragon) [WHO'S AFRAID OF THE BIG BLACK]
06.09.2018 16:18:31: Focus contention triggered by ModSelectOverlay (0,0) 1 365x510.
06.09.2018 16:18:34: Screen changed → PlayerLoader
06.09.2018 16:18:37: Screen changed → Player
06.09.2018 16:20:57: Screen changed → Results
06.09.2018 16:21:04: Screen changed ← Player (0,0) 1 365x728
06.09.2018 16:21:04: Screen changed ← PlayerLoader (0,0) 1 365x728
06.09.2018 16:21:04: Screen changed ← PlaySongSelect (0,0) 1 365x728
06.09.2018 16:21:04: working beatmap updated to The Quick Brown Fox - The Big Black (Blue Dragon) [WHO'S AFRAID OF THE BIG BLACK]
06.09.2018 16:21:06: Focus contention triggered by ModSelectOverlay (0,0) 1 365x510.
06.09.2018 16:21:11: Screen changed ← MainMenu (0,0) 1 365x728
06.09.2018 16:21:11: ButtonSystem's state changed from EnteringMode to TopLevel
06.09.2018 16:21:16: ButtonSystem's state changed from TopLevel to Exit
06.09.2018 16:21:16: Screen changed ← Intro (0,0) 1 365x728
06.09.2018 16:21:16: Screen changed ← Disclaimer (0,0) 1 365x766
06.09.2018 16:21:16: Screen changed ← Loader (0,0) 1 365x766
06.09.2018 16:21:16: Screen changed ←
06.09.2018 16:21:16: Unhandled exception has been allowed with 0 more allowable exceptions .
06.09.2018 16:21:17: An unhandled error has occurred.
06.09.2018 16:21:17: System.InvalidOperationException: Attempting to access a TextureWithRefCount's underlying texture after all references are lost.
06.09.2018 16:21:17: at osu.Framework.Graphics.Textures.TextureWithRefCount.get_TextureGL()
06.09.2018 16:21:17: at osu.Framework.Graphics.Sprites.SpriteDrawNode.Draw(Action`1 vertexAction)
06.09.2018 16:21:17: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction)
06.09.2018 16:21:17: at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.drawChildren(Action`1 vertexAction, Vector2 frameBufferSize)
06.09.2018 16:21:17: at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.Draw(Action`1 vertexAction)
06.09.2018 16:21:17: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction)
06.09.2018 16:21:17: at osu.Framework.Platform.GameHost.DrawFrame()
06.09.2018 16:21:17: at osu.Framework.Threading.GameThread.ProcessFrame()
06.09.2018 16:21:17: at osu.Framework.Threading.GameThread.runWork()

**Comment by WithoutKnock** [comment]
I just found out If I'm in windowed mode the Visual Bugs are gone ;D (In Fullscreen and Borderless still there).

windowed resolution: 1280x720
monitor max. resolution 1920x1080 (only have one monitor)

logs:
[debug.log](https://github.com/ppy/osu/files/2359759/debug.log)
[performance.log](https://github.com/ppy/osu/files/2359760/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2359761/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2359762/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2359763/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2359764/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2359765/runtime.log)

**Comment by marcan** [comment]
If I had to guess that might actually be a divide by zero or corner case vertex alignment issue. It seems to happen when the notes are dead vertical/horizontal, right in the middle.

**Comment by marcan** [comment]
Looking at the same shader as in #1865, I see `v_BlendRange.x` is checked for zero in several places, but not in [this](https://github.com/ppy/osu-framework/blob/f9cb6c89a328f179c5121bc77cd0f711576ef17f/osu.Framework/Resources/Shaders/sh_TextureRounded.fs#L73) line. That's a varying, so if the pixels line up right I could see it being exactly 0 in the middle of an object if it's perfectly horizontal or vertical, causing a divide by zero. Long shot maybe, but worth looking into?

**Comment by marcan** [comment]
Potential bug [here](https://github.com/ppy/osu-framework/blob/f9cb6c89a328f179c5121bc77cd0f711576ef17f/osu.Framework/Graphics/Lines/PathDrawNode.cs#L139). `Texture.Width` is an integer, so the integer division truncates. The texture is set to clamp mode, so it should still render pixels there, but that might be subtly broken on this GPU or driver or something. It's also possible it only breaks for NPOT textures and then only for the right/bottom side, if they are internally padded or clamping only works on POT boundaries, which sounds like the kind of stupid bug some drivers/GPUs could have.

I see more hits for the same pattern. I'm sending in ppy/osu-framework#1881 to fix it.

**Comment by TPGPL** [comment]
Is this issue still relevant?

**Comment by WithoutKnock** [comment]
Yes it is

**Comment by peppy** [comment]
@WithoutKnock have you tested on the latest build? A second fix has been merged since then.

**Comment by WithoutKnock** [comment]
![screenshot 48](https://user-images.githubusercontent.com/41303944/45586928-a426a480-b8fe-11e8-89e2-c5764885722b.png)

**Comment by WithoutKnock** [comment]
[performance.log](https://github.com/ppy/osu/files/2385753/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2385754/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2385755/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2385756/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2385757/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2385758/runtime.log)
[debug.log](https://github.com/ppy/osu/files/2385759/debug.log)

**Comment by WithoutKnock** [comment]
The Video should explain everything.

https://streamable.com/23ihy

[database.log](https://github.com/ppy/osu/files/3612547/database.log)
[network.log](https://github.com/ppy/osu/files/3612548/network.log)
[performance.log](https://github.com/ppy/osu/files/3612549/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3612550/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3612551/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3612552/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3612553/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3612554/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3612555/updater.log)

**Comment by peppy** [comment]
On a quick check from @Tom94, the remaining issue may be related to the removal of the epsilon subtraction at https://github.com/marcan/osu-framework/commit/7170c492df1a09438e2b3efcd143ed79e4e67dc0#diff-6ab15dd22923474140a29e6deef5f30cR76. Adding this back in some form may resolve.

**Comment by peppy** [comment]
Please do not rename or close issues without reason.

**Comment by smoogipoo** [comment]
From https://github.com/ppy/osu/discussions/19238
[runtime.log](https://github.com/ppy/osu/files/9141538/runtime.log)

---

I've ordered a 9800GT to try to reproduce this on.
