### ISSUE TITLE
osu!mania beatmap conversion failures

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#3236]
Post any osu!mania beatmap conversion failures here.

```
08/16/2018 04:45:47: beatmap changed from "baker - For a Dead Girl+ (handsome) [Collab Extra]" to "baker - For a Dead Girl+ (handsome) [Collab Extra]"
08/16/2018 04:45:47: working beatmap updated to baker - For a Dead Girl+ (handsome) [Collab Extra]
08/16/2018 04:45:47: Allowable iterations (20) exceeded:
08/16/2018 04:45:47: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.PatternGenerator.RunWhile(Func`1 condition, Action action)
08/16/2018 04:45:47: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.HitObjectPatternGenerator.generateRandomPatternWithMirrored(Double centreProbability, Double p2, Double p3)
```

(Marking as 👍 when issues are resolved)

**Comment by Morilli** [comment]
https://osu.ppy.sh/b/933228
```
16.08.2018 16:54:37: beatmap changed from "Memme - BSPower Explosion (AngelHoney) [Normal]" to "NOMA - Brain Power Long Version (Skystar) [Overdrive]"
16.08.2018 16:54:37: working beatmap updated to NOMA - Brain Power Long Version (Skystar) [Overdrive]
16.08.2018 16:54:37: Conversion encountered errors. The beatmap may not be correctly converted.
16.08.2018 16:54:37: ExceededAllowedIterationsException: Exception of type 'osu.Game.Rulesets.Mania.Beatmaps.Patterns.PatternGenerator+ExceededAllowedIterationsException' was thrown.
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.PatternGenerator.RunWhile(Func`1 condition, Action action)
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.generateRandomHoldNotes(Double startTime, Int32 noteCount)
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.generateNRandomNotes(Double startTime, Double p2, Double p3, Double p4)
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.generate()
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.Generate()+MoveNext()
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.ManiaBeatmapConverter.generateConverted(HitObject original, IBeatmap originalBeatmap)+MoveNext()
16.08.2018 16:54:37: at osu.Game.Rulesets.Mania.Beatmaps.ManiaBeatmapConverter.ConvertHitObject(HitObject original, IBeatmap beatmap)+MoveNext()
16.08.2018 16:54:37: at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
16.08.2018 16:54:37: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
16.08.2018 16:54:37: at osu.Game.Beatmaps.BeatmapConverter`1.convert(HitObject original, IBeatmap beatmap)+MoveNext()
16.08.2018 16:54:37: at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
16.08.2018 16:54:37: at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
16.08.2018 16:54:37: at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
16.08.2018 16:54:37: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
16.08.2018 16:54:37: at osu.Game.Beatmaps.BeatmapConverter`1.ConvertBeatmap(IBeatmap original)
16.08.2018 16:54:37: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset)
16.08.2018 16:54:37: at osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.getInfoLabels()
16.08.2018 16:54:37: at osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.load(LocalisationEngine localisation)
16.08.2018 16:54:37: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
16.08.2018 16:54:37: at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
16.08.2018 16:54:37: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_1.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
16.08.2018 16:54:37: at System.Collections.Generic.List`1.ForEach(Action`1 action)
16.08.2018 16:54:37: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
16.08.2018 16:54:37: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
16.08.2018 16:54:37: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
16.08.2018 16:54:37: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by smoogipoo** [comment]
https://osu.ppy.sh/beatmapsets/158023#osu/555797

```
08/17/2018 04:43:36: working beatmap updated to UNDEAD CORPORATION - Everything will freeze (Ekoro) [Hard]
08/17/2018 04:43:36: Conversion encountered errors. The beatmap may not be correctly converted.
08/17/2018 04:43:36: ExceededAllowedIterationsException: Exception of type 'osu.Game.Rulesets.Mania.Beatmaps.Patterns.PatternGenerator+ExceededAllowedIterationsException' was thrown.
08/17/2018 04:43:36: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.PatternGenerator.RunWhile(Func`1 condition, Action action)
08/17/2018 04:43:36: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.generateRandomHoldNotes(Double startTime, Int32 noteCount)
08/17/2018 04:43:36: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.DistanceObjectPatternGenerator.generateNRandomNotes(Double startTime, Double p2, Double p3, Double p4)
```

**Comment by Morilli** [comment]
https://osu.ppy.sh/s/106063
```
17.08.2018 15:26:31: working beatmap updated to Infected Mushroom - Where Do I Belong (HanzeR) [Hard]
17.08.2018 15:26:31: Unhandled exception has been allowed with {allowableExceptions} more allowable exceptions .
17.08.2018 15:26:31: An unhandled error has occurred.
17.08.2018 15:26:31: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
17.08.2018 15:26:31: Parameter name: previousTime
17.08.2018 15:26:31: at osu.Game.Rulesets.Mania.Beatmaps.Patterns.Legacy.HitObjectPatternGenerator..ctor(FastRandom random, HitObject hitObject, ManiaBeatmap beatmap, Pattern previousPattern, Double previousTime, Vector2 previousPosition, Double density, PatternType lastStair, IBeatmap originalBeatmap)
17.08.2018 15:26:31: at osu.Game.Rulesets.Mania.Beatmaps.ManiaBeatmapConverter.generateConverted(HitObject original, IBeatmap originalBeatmap)+MoveNext()
17.08.2018 15:26:31: at osu.Game.Rulesets.Mania.Beatmaps.ManiaBeatmapConverter.ConvertHitObject(HitObject original, IBeatmap beatmap)+MoveNext()
17.08.2018 15:26:31: at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
17.08.2018 15:26:31: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
17.08.2018 15:26:31: at osu.Game.Beatmaps.BeatmapConverter`1.convert(HitObject original, IBeatmap beatmap)+MoveNext()
17.08.2018 15:26:31: at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
17.08.2018 15:26:31: at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
17.08.2018 15:26:31: at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
17.08.2018 15:26:31: at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
17.08.2018 15:26:31: at osu.Game.Beatmaps.BeatmapConverter`1.ConvertBeatmap(IBeatmap original)
17.08.2018 15:26:31: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset)
17.08.2018 15:26:31: at osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.getInfoLabels()
17.08.2018 15:26:31: at osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.load(LocalisationEngine localisation)
17.08.2018 15:26:31: --- End of stack trace from previous location where exception was thrown ---
17.08.2018 15:26:31: at osu.Framework.Platform.GameHost.UpdateFrame()
17.08.2018 15:26:31: at osu.Framework.Threading.GameThread.ProcessFrame()
17.08.2018 15:26:31: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by Morilli** [comment]
Since #3312 I haven't seen a single failing map, so yeah, this should be fixed.
