### ISSUE TITLE
Crash after scrolling through song select

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3316]
I was going through each map I had one by one cause reasons, and eventually lazer crashed. I also noticed while doing it lazers cpu usage was constantly at >60%, even though I wasn't actually playing a map, but just scrolling through song select.
Here's the console output from the error:
```
[runtime:verbose] 25.08.2018 12:47:42: Unhandled exception has been denied .

Unhandled Exception: [runtime:error] 25.08.2018 12:47:42: An unhandled error has occurred.
[runtime:error] 25.08.2018 12:47:42: Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Failure loading DAC: CreateDacInstance failed 0x8007000e
[runtime:error] 25.08.2018 12:47:42: at Microsoft.Diagnostics.Runtime.DacLibrary..ctor(DataTargetImpl dataTarget, String dacDll)
[runtime:error] 25.08.2018 12:47:42: at Microsoft.Diagnostics.Runtime.ClrInfo.ConstructRuntime(String dac)
[runtime:error] 25.08.2018 12:47:42: at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime()
[runtime:error] 25.08.2018 12:47:42: at osu.Framework.Statistics.BackgroundStackTraceCollector.getStackTrace(Thread targetThread)
[runtime:error] 25.08.2018 12:47:42: at osu.Framework.Statistics.BackgroundStackTraceCollector.<>c__DisplayClass8_0.<.ctor>b__0()
[runtime:error] 25.08.2018 12:47:42: at osu.Framework.Threading.GameThread.ProcessFrame()
[runtime:error] 25.08.2018 12:47:42: at osu.Framework.Threading.GameThread.runWork()
[runtime:error] 25.08.2018 12:47:42: at System.Threading.Thread.ThreadMain_ThreadStart()
[runtime:error] 25.08.2018 12:47:42: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[runtime:error] 25.08.2018 12:47:42: --- End of stack trace from previous location where exception was thrown ---
[runtime:error] 25.08.2018 12:47:42: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Unhandled Exception: Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Failure loading DAC: CreateDacInstance failed 0x8007000e
   at Microsoft.Diagnostics.Runtime.DacLibrary..ctor(DataTargetImpl dataTarget, String dacDll)
   at Microsoft.Diagnostics.Runtime.ClrInfo.ConstructRuntime(String dac)
   at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime()
   at osu.Framework.Statistics.BackgroundStackTraceCollector.getStackTrace(Thread targetThread)
   at osu.Framework.Statistics.BackgroundStackTraceCollector.<>c__DisplayClass8_0.<.ctor>b__0()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass102_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in C:\Users\Moritz\osu\osu.Desktop\Program.cs:line 46
Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: Failure loading DAC: CreateDacInstance failed 0x8007000e
   at Microsoft.Diagnostics.Runtime.DacLibrary..ctor(DataTargetImpl dataTarget, String dacDll)
   at Microsoft.Diagnostics.Runtime.ClrInfo.ConstructRuntime(String dac)
   at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime()
   at osu.Framework.Statistics.BackgroundStackTraceCollector.getStackTrace(Thread targetThread)
   at osu.Framework.Statistics.BackgroundStackTraceCollector.<>c__DisplayClass8_0.<.ctor>b__0()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass102_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in C:\Users\Moritz\osu\osu.Desktop\Program.cs:line 46
```
Important notes: I reproduced it on local debug as well as on 2018.824.0. osu!mania has to be the selected mode, else it doesn't work. Relevant log files from the session: [logs.zip](https://github.com/ppy/osu/files/2320636/logs.zip).
Could be related to the current osu!mania conversion problems, if so this might only be a temporary issue.

**Comment by peppy** [comment]
This looks to be a result of you having "performance logging" turned on. Please turn it off (at the far bottom of settings).

**Comment by Morilli** [comment]
Not sure I understand why this is a non-issue. I believe "performance logging" turned on should not make certain actions crash the game. Please correct me if I'm wrong though.

**Comment by peppy** [comment]
probably, but it’s a debug tool and should not be used while playing. for now, disabling is a fine aolution.
