### ISSUE TITLE
Osu Lazer Crashes

### ISSUE THREAD

**Issue by 3DDI3LU** [ppy/osu#3349]
when i open osu lazer it just crashes

Log Name:      Application
Source:        .NET Runtime
Date:          2/9/2018 3:32:51 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Asrock
Description:
Application: osu!.exe
CoreCLR Version: 4.6.26725.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass102_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-09-02T07:32:51.000000000Z" />
    <EventRecordID>252098</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Asrock</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 4.6.26725.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo&amp; Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.&lt;&gt;c__DisplayClass26_0.&lt;.ctor&gt;b__3()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.&lt;&gt;c__DisplayClass102_0.&lt;Run&gt;b__1(Object &lt;p0&gt;, FrameEventArgs &lt;p1&gt;)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double&amp; timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          2/9/2018 3:32:51 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Asrock
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5b58a311
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18938, time stamp: 0x5a7ddf0a
Exception code: 0xe0434352
Fault offset: 0x0000000000008eac
Faulting process ID: 0x7f0
Faulting application start time: 0x01d4428f25b754c7
Faulting application path: C:\Users\User\AppData\Local\osulazer\app-2018.901.0\osu!.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report ID: 656174a1-ae82-11e8-846a-d050992a88b7
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-09-02T07:32:51.000000000Z" />
    <EventRecordID>252099</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Asrock</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5b58a311</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.18938</Data>
    <Data>5a7ddf0a</Data>
    <Data>e0434352</Data>
    <Data>0000000000008eac</Data>
    <Data>7f0</Data>
    <Data>01d4428f25b754c7</Data>
    <Data>C:\Users\User\AppData\Local\osulazer\app-2018.901.0\osu!.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>656174a1-ae82-11e8-846a-d050992a88b7</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by peppy** [comment]
Are you running from the installed copy (using `install.exe` from the releases page)?

What operating system are you running on?

**Comment by 3DDI3LU** [comment]
yes i used install.exe and i'm running it on windows 8.1

**Comment by 3DDI3LU** [comment]
it would still crash after all these updates

**Comment by peppy** [comment]
Can you confirm your operating system is 64 bit?

**Comment by 3DDI3LU** [comment]
@peppy please look into this issue

**Comment by peppy** [comment]
Could you please try again using the latest isntaller?

**Comment by 3DDI3LU** [comment]
i uninstalled the old version and installed it again and this pops out
![image](https://user-images.githubusercontent.com/42906196/50585603-c2fe7600-0eb0-11e9-85fc-bee6ec8b3329.png)

**Comment by 3DDI3LU** [comment]
heres the log

`Log Name:      Application
Source:        .NET Runtime
Date:          2/1/2019 5:05:00 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Asrock
Description:
Application: osu!.exe
CoreCLR Version: 4.6.27110.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass99_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-01-02T09:05:00.000000000Z" />
    <EventRecordID>296023</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Asrock</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 4.6.27110.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo&amp; Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.&lt;&gt;c__DisplayClass26_0.&lt;.ctor&gt;b__3()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.&lt;&gt;c__DisplayClass99_0.&lt;Run&gt;b__1(Object &lt;p0&gt;, FrameEventArgs &lt;p1&gt;)
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double&amp; timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)
</Data>
  </EventData>
</Event>`

**Comment by peppy** [comment]
I have no idea how this can happen. You seem to be missing DLLs. Are you able to check for the presence of bass.dll in `AppData/Local/osu/x64`?

**Comment by 3DDI3LU** [comment]
it would seem that i don't have a file named osu in Local just osu!lazer

**Comment by bdach** [comment]
Closing due to inactivity. Please reopen if this still occurs on newer builds.

**Comment by ZhenyaStudio** [comment]
> it would seem that i don't have a file named osu in Local just osu!lazer



> when i open osu lazer it just crashes
> 
> Log Name: Application Source: .NET Runtime Date: 2/9/2018 3:32:51 PM Event ID: 1026 Task Category: None Level: Error Keywords: Classic User: N/A Computer: Asrock Description: Application: osu!.exe CoreCLR Version: 4.6.26725.6 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info) at ManagedBass.Bass.get_DeviceCount() at osu.Framework.Audio.AudioManager.getAllDevices() at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3() at osu.Framework.Threading.ScheduledDelegate.RunTask() at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.ProcessFrame() at osu.Framework.Threading.GameThread.runWork() --- End of stack trace from previous location where exception was thrown --- at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.ProcessFrame() at osu.Framework.Platform.GameHost.<>c__DisplayClass102_0.b__1(Object , FrameEventArgs ) at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp) at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch) at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) at osu.Framework.Platform.GameHost.Run(Game game) at osu.Desktop.Program.Main(String[] args)
> 
> Event Xml: 1026 2 0 0x80000000000000 252098 Application Asrock Application: osu!.exe CoreCLR Version: 4.6.26725.6 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info) at ManagedBass.Bass.get_DeviceCount() at osu.Framework.Audio.AudioManager.getAllDevices() at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3() at osu.Framework.Threading.ScheduledDelegate.RunTask() at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.ProcessFrame() at osu.Framework.Threading.GameThread.runWork() --- End of stack trace from previous location where exception was thrown --- at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.ProcessFrame() at osu.Framework.Platform.GameHost.<>c__DisplayClass102_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>) at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp) at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch) at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) at osu.Framework.Platform.GameHost.Run(Game game) at osu.Desktop.Program.Main(String[] args)
> 
> Log Name: Application Source: Application Error Date: 2/9/2018 3:32:51 PM Event ID: 1000 Task Category: (100) Level: Error Keywords: Classic User: N/A Computer: Asrock Description: Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5b58a311 Faulting module name: KERNELBASE.dll, version: 6.3.9600.18938, time stamp: 0x5a7ddf0a Exception code: 0xe0434352 Fault offset: 0x0000000000008eac Faulting process ID: 0x7f0 Faulting application start time: 0x01d4428f25b754c7 Faulting application path: C:\Users\User\AppData\Local\osulazer\app-2018.901.0\osu!.exe Faulting module path: C:\Windows\system32\KERNELBASE.dll Report ID: 656174a1-ae82-11e8-846a-d050992a88b7 Faulting package full name: Faulting package-relative application ID: Event Xml: 1000 2 100 0x80000000000000 252099 Application Asrock osu!.exe 0.0.0.0 5b58a311 KERNELBASE.dll 6.3.9600.18938 5a7ddf0a e0434352 0000000000008eac 7f0 01d4428f25b754c7 C:\Users\User\AppData\Local\osulazer\app-2018.901.0\osu!.exe C:\Windows\system32\KERNELBASE.dll 656174a1-ae82-11e8-846a-d050992a88b7

your processor is good?
your processor is new?
try update windows 8.1
your memory pc is good?
