### ISSUE TITLE
Exception when importing beatmaps with game minimized

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3510]
I was importing beatmaps as normal (this time with Lazer minimized and with the song list section) when suddenly, I got this error on _runtime.log_:
```
30/09/2018 12:51:14: Unhandled exception has been allowed with 0 more allowable exceptions .
30/09/2018 12:51:18: An unhandled error has occurred.
30/09/2018 12:51:18: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
30/09/2018 12:51:18: Parameter name: index
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.checkChildrenLife()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.FlowContainer`1.UpdateChildrenLife()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30/09/2018 12:51:18: at osu.Framework.Platform.GameHost.UpdateFrame()
30/09/2018 12:51:18: at osu.Framework.Threading.GameThread.ProcessFrame()
30/09/2018 12:51:18: at osu.Framework.Threading.GameThread.runWork()
30/09/2018 12:51:19: Focus contention triggered by NotificationOverlay.
```

and this on the _performance-gamethread.update.log_:
```
30/09/2018 12:51:19: | Slow frame on thread "GameThread.Update"
30/09/2018 12:51:19: |
30/09/2018 12:51:19: | * Thread time  : 251.349ms
30/09/2018 12:51:19: | * Frame length : 4.448ms (allowable: 135ms)
30/09/2018 12:51:19: |
30/09/2018 12:51:19: | Stack trace:
30/09/2018 12:51:19: |- InlinedCallFrame
30/09/2018 12:51:19: |- InlinedCallFrame
30/09/2018 12:51:19: |- DomainBoundILStubClass.IL_STUB_PInvoke(Byte*, Int32)
30/09/2018 12:51:19: |- System.IO.Compression.ZLibNative+ZLibStreamHandle.Inflate(FlushCode)
30/09/2018 12:51:19: |- System.IO.Compression.Inflater.Inflate(FlushCode)
30/09/2018 12:51:19: |- System.IO.Compression.Inflater.ReadInflateOutput(Byte*, Int32, FlushCode, Int32 ByRef)
30/09/2018 12:51:19: |- System.IO.Compression.Inflater.InflateVerified(Byte*, Int32)
30/09/2018 12:51:19: |- System.IO.Compression.DeflateStream.ReadCore(System.Span`1<Byte>)
30/09/2018 12:51:19: |- System.IO.Compression.DeflateStream.Read(Byte[], Int32, Int32)
30/09/2018 12:51:19: |- SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp]](System.IO.Stream, SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32>)
30/09/2018 12:51:19: |- SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp]](System.IO.Stream)
30/09/2018 12:51:19: |- DebuggerU2MCatchHandlerFrame
30/09/2018 12:51:19: |- HelperMethodFrame_PROTECTOBJ
30/09/2018 12:51:19: |- System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
30/09/2018 12:51:19: |- osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_1.<CreateActivator>b__4(System.Object, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(osu.Framework.Graphics.Drawable)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.load(osu.Framework.Graphics.Shaders.ShaderManager, System.Nullable`1<System.Threading.CancellationToken>)
30/09/2018 12:51:19: |- DebuggerU2MCatchHandlerFrame
30/09/2018 12:51:19: |- ProtectValueClassFrame
30/09/2018 12:51:19: |- HelperMethodFrame_PROTECTOBJ
30/09/2018 12:51:19: |- System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
30/09/2018 12:51:19: |- osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_1.<CreateActivator>b__4(System.Object, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(osu.Framework.Graphics.Drawable)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.load(osu.Framework.Graphics.Shaders.ShaderManager, System.Nullable`1<System.Threading.CancellationToken>)
30/09/2018 12:51:19: |- DebuggerU2MCatchHandlerFrame
30/09/2018 12:51:19: |- ProtectValueClassFrame
30/09/2018 12:51:19: |- HelperMethodFrame_PROTECTOBJ
30/09/2018 12:51:19: |- System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
30/09/2018 12:51:19: |- osu.Framework.Allocation.BackgroundDependencyLoaderAttribute+<>c__DisplayClass6_1.<CreateActivator>b__4(System.Object, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Allocation.DependencyActivator.activate(System.Object, osu.Framework.Allocation.DependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(osu.Framework.Graphics.Drawable)
30/09/2018 12:51:19: |- osu.Framework.Graphics.Containers.CompositeDrawable.load(osu.Framework.Graphics.Shaders.ShaderManager, System.Nullable`1<System.Threading.CancellationToken>)
30/09/2018 12:51:19: |- DebuggerU2MCatchHandlerFrame
30/09/2018 12:51:19: |- ProtectValueClassFrame
30/09/2018 12:51:19: |- HelperMethodFrame_PROTECTOBJ
30/09/2018 12:51:19: |- System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
30/09/2018 12:51:19: |- Unknown Frame
30/09/2018 12:51:19: 
```

and, to be sure, I paste what happened on _performance-gamethread.draw.log_:
```
30/09/2018 12:51:19: | Slow frame on thread "GameThread.Draw"
30/09/2018 12:51:19: |
30/09/2018 12:51:19: | * Thread time  : 251.526ms
30/09/2018 12:51:19: | * Frame length : 4.470ms (allowable: 216ms)
30/09/2018 12:51:19: |
30/09/2018 12:51:19: | Stack trace:
30/09/2018 12:51:19: |- HelperMethodFrame
30/09/2018 12:51:19: |- osu.Framework.Platform.GameHost.DrawFrame()
30/09/2018 12:51:19: |- osu.Framework.Threading.GameThread.ProcessFrame()
30/09/2018 12:51:19: |- osu.Framework.Threading.GameThread.runWork()
30/09/2018 12:51:19: |- System.Threading.Thread.ThreadMain_ThreadStart()
30/09/2018 12:51:19: |- System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
30/09/2018 12:51:19: |- GCFrame
30/09/2018 12:51:19: |- DebuggerU2MCatchHandlerFrame
30/09/2018 12:51:19: 
```

Nothing strange on other logs, but if you need more information just ask.

**Comment by smoogipoo** [comment]
This was just a threading issue which has since been fixed (or at least we have exceptions in-place now to catch these cases). Feel free to open a new PR if something similar comes up again.
