### ISSUE TITLE
Crash when activating "Bypass caching" option

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu#3517]
When enabling the "Bypass caching" option in the debug settings, the game instantly crashes to desktop.

```
01.10.2018 22:40:34: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
01.10.2018 22:40:34: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
01.10.2018 22:40:34: at osu.Framework.Graphics.Sprites.SpriteText.computeScreenSpaceCharacters()
01.10.2018 22:40:34: at osu.Framework.Graphics.Sprites.SpriteText.ApplyDrawNode(DrawNode node)
01.10.2018 22:40:34: at osu.Framework.Graphics.Drawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
01.10.2018 22:40:34: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
01.10.2018 22:40:34: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
01.10.2018 22:40:34: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
01.10.2018 22:40:34: at ... and so on
01.10.2018 22:40:34: at osu.Framework.Graphics.Containers.CompositeDrawable.addFromComposite(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode, Int32& j, CompositeDrawable parentComposite, List`1 target)
01.10.2018 22:40:34: at osu.Framework.Graphics.Containers.CompositeDrawable.GenerateDrawNodeSubtree(UInt64 frame, Int32 treeIndex, Boolean forceNewDrawNode)
01.10.2018 22:40:34: at osu.Framework.Platform.GameHost.UpdateFrame()
01.10.2018 22:40:34: at osu.Framework.Threading.GameThread.ProcessFrame()
01.10.2018 22:40:34: at osu.Framework.Threading.GameThread.runWork()
```
full log: https://pastebin.com/j8aVjbEW

**Comment by smoogipoo** [comment]
I'm not sure if this is even a candidate for fixing, but removing the debug setting altogether. There have been 0 cases to-date where it has been useful to us.

**Comment by peppy** [comment]
We have used in the past to check whether caching has been the root cause of issues (that's the reason this exists). Not sure if such cases come up as much now that the framework is approaching stability.

Arguable.

**Comment by smoogipoo** [comment]
I can't remember a single case where we have done so. Also considering that _framework visual tests_ runs at <0.5ms with this setting turned, it is next to unusable in general.
