### ISSUE TITLE
Clicking the (disabled) gamemode switch buttons in score select crashes the game

### ISSUE THREAD

**Issue by WRMSRwasTaken** [ppy/osu#3548]
Using 2018.1004.1, clicking one of the gamemode switches (after completing a osu! map, and clicking osu!taiko for example), brings an error, clicking it 2 times more will actually crash the game.

![2018-10-05_12-47-47](https://user-images.githubusercontent.com/4244869/46531358-3b976b80-c89d-11e8-900c-ce51a7c7cb8d.gif)

**Comment by peppy** [comment]
Does this only happen at the results screen?

**Comment by WRMSRwasTaken** [comment]
It works on the main menu, song select & multiplayer lobby.

**Comment by peppy** [comment]
"works" as in "crashes"?

**Comment by plankp** [comment]
I reproduced it: Here is the extract of the log:

```

10/05/2018 10:55:24: An unhandled error has occurred.
10/05/2018 10:55:24: System.InvalidOperationException: Can not set value to "osu!catch (fruits) ID: 2" as bindable is disabled.
10/05/2018 10:55:24: at osu.Framework.Configuration.Bindable`1.set_Value(T value)
10/05/2018 10:55:24: at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
10/05/2018 10:55:24: at osu.Game.Overlays.Toolbar.ToolbarButton.OnClick(ClickEvent e) in /Users/dean/Projects/osu/osu.Game/Overlays/Toolbar/ToolbarButton.cs:line 151
10/05/2018 10:55:24: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
10/05/2018 10:55:24: at osu.Framework.Input.MouseButtonEventManager.PropagateMouseButtonEvent(IEnumerable`1 drawables, MouseButtonEvent e)
10/05/2018 10:55:24: at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state)
10/05/2018 10:55:24: at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime)
10/05/2018 10:55:24: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
10/05/2018 10:55:24: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
10/05/2018 10:55:24: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
10/05/2018 10:55:24: at osu.Framework.Input.InputManager.Update()
10/05/2018 10:55:24: at osu.Framework.Input.PassThroughInputManager.Update()
10/05/2018 10:55:24: at osu.Framework.Graphics.Drawable.UpdateSubTree()
10/05/2018 10:55:24: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
10/05/2018 10:55:24: at osu.Framework.Platform.GameHost.UpdateFrame()
10/05/2018 10:55:24: at osu.Framework.Threading.GameThread.ProcessFrame()
10/05/2018 10:55:24: at osu.Framework.Threading.GameThread.runWork()
10/05/2018 10:55:24: Focus contention triggered by NotificationOverlay.
```

**Comment by WRMSRwasTaken** [comment]
Nope, sorry. It does not crash the game in those cases. It just crashes on the ending screen.
