### ISSUE TITLE
Launch game with Wifi off crashes the game

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3572]
On mac (taken from network.log):

```
10/10/2018 00:32:53: Performing request osu.Game.Online.API.Requests.GetUserRequest
10/10/2018 00:32:54: Request to https://osu.ppy.sh/api/v2/me failed with System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
10/10/2018 00:32:54: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
10/10/2018 00:32:54: --- End of inner exception stack trace ---
10/10/2018 00:32:54: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
10/10/2018 00:32:54: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:54: at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:54: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:54: at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
10/10/2018 00:32:54: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:54: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
10/10/2018 00:32:54: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:54: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:54: at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
10/10/2018 00:32:54: at osu.Framework.IO.Network.WebRequest.internalPerform().
10/10/2018 00:32:54: Processing response from https://osu.ppy.sh/api/v2/me failed with System.ArgumentNullException: Value cannot be null.
10/10/2018 00:32:54: Parameter name: value
10/10/2018 00:32:54: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
10/10/2018 00:32:54: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
10/10/2018 00:32:54: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
10/10/2018 00:32:54: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
10/10/2018 00:32:55: Request to https://api.github.com/repos/ppy/osu/releases/latest failed with System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
10/10/2018 00:32:55: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
10/10/2018 00:32:55: --- End of inner exception stack trace ---
10/10/2018 00:32:55: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
10/10/2018 00:32:55: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:55: at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:55: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:55: at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
10/10/2018 00:32:55: at System.Threading.Tasks.ValueTask`1.get_Result()
10/10/2018 00:32:55: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
10/10/2018 00:32:55: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:55: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
10/10/2018 00:32:55: at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
10/10/2018 00:32:55: at osu.Framework.IO.Network.WebRequest.internalPerform().
10/10/2018 00:32:55: Processing response from https://api.github.com/repos/ppy/osu/releases/latest failed with System.ArgumentNullException: Value cannot be null.
10/10/2018 00:32:55: Parameter name: value
10/10/2018 00:32:55: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
10/10/2018 00:32:55: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
10/10/2018 00:32:55: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
10/10/2018 00:32:55: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
```

**Comment by peppy** [comment]
Can you confirm you're on the latest release?

**Comment by plankp** [comment]
Just tested with 2018.1004.1 with wifi being the only network connection. Turning wifi off then launching osu crashes it and generates the same exception in network.log.
