### ISSUE TITLE
Unable to startup osu! on ubuntu 18.04 desktop

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#3584]
I think it's related to libbass, which is this issue: #2809.

Here is the error trace back. The window will flash then disappear.
> Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices()
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
   at osu.Framework.Audio.AudioManager.setAudioDevice(String preferredDevice)
   at osu.Framework.Audio.AudioManager.<>c__DisplayClass28_0.<onDeviceChanged>b__0()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass98_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/hexiaoling/Software/osu/osu.Desktop/Program.cs:line 46

**Comment by plankp** [comment]
Similar to #3349 but on different OS?

**Comment by LovelyA72** [comment]
I tried the way from #3257,and it works for me. But maybe we can have a way in the future to automatically install these libs.
