### ISSUE TITLE
Since today, osu!lazer crashes on start - Dotnet Core - Ubuntu

### ISSUE THREAD

**Issue by Alexmitter** [ppy/osu#3590]
Since today, a clean reclone and build. osu!lazer crashes at start.

Error Msg from dotnet core listed here. Rest of the output is in the osu.log file.
The Window appears for a second, Welcome Sound is playing.

`Unhandled Exception: System.InvalidOperationException: Attempted to update dropdown to a value which wasn't contained as an item ({Width=1366, Height=768}).
   at osu.Framework.Graphics.UserInterface.Dropdown`1.selectionChanged(T newSelection)
   at osu.Framework.Configuration.Bindable`1.set_Value(T value)
   at osu.Framework.Configuration.Bindable`1.BindTo(Bindable`1 them)
   at osu.Game.Overlays.Settings.SettingsItem`1.set_Bindable(Bindable`1 value) in /home/alexmitter/git/osu-lazer-linux-installer/scripts/osu/osu.Game/Overlays/Settings/SettingsItem.cs:line 66
   at osu.Game.Overlays.Settings.Sections.Graphics.LayoutSettings.load(FrameworkConfigManager config, OsuGameBase game) in /home/alexmitter/git/osu-lazer-linux-installer/scripts/osu/osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass98_0.<Run>b__1(Object <p0>, FrameEventArgs <p1>)
   at OpenTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/alexmitter/git/osu-lazer-linux-installer/scripts/osu/osu.Desktop/Program.cs:line 46`

[osu.log](https://github.com/ppy/osu/files/2475875/osu.log)

**Comment by AtomCrafty** [comment]
Duplicate of #3474, a fix is currently waiting for review.
Until then, delete `%appdata%\osu\framework.ini`, that should fix the startup crash.

**Comment by Alexmitter** [comment]
@AtomCrafty maybe mentioning for others that they can find framework.ini under ~/.local/share/osu
But i can confirm it is working again
Also just to mention it, hovering over the big osu! button in the main menu makes a snare sound for every beat.

**Comment by AtomCrafty** [comment]
Sorry, I missed the "Ubuntu" in your description ^^
And I believe the beat sound is intended.

**Comment by Alexmitter** [comment]
@AtomCrafty No Problem, i just wanted to add it because i by myself forgot it is under .local so i had to search for minutes and i want to protect others from the struggle. About the Beat Sound, just wasn't sure, didn't noticed it before.
