### ISSUE TITLE
ChannelManager requests cause crash with 100% packet loss

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#3867]
Reproduction steps:
1. Open chat
2. Condition 100% packet loss
3. Open a new public channel

```
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at osu.Game.Online.Chat.ChannelManager.<>c__DisplayClass27_0.<Poll>b__1(Exception _) in /Users/smoogipoo/Repos/osu/osu.Game/Online/Chat/ChannelManager.cs:line 408
   at osu.Game.Online.API.APIRequest.<>c__DisplayClass23_0.<Fail>b__0() in /Users/smoogipoo/Repos/osu/osu.Game/Online/API/APIRequest.cs:line 112
```

Happens before + after https://github.com/ppy/osu/pull/3865

**Comment by smoogipoo** [comment]
Fixed.
