### ISSUE TITLE
ChannelTabControl adds tabs on background thread

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#3891]
```
[runtime:error] 12/21/2018 04:17:10: osu.Framework.Graphics.Containers.CompositeDrawable+InvalidThreadForChildMutationException: Cannot mutate the children of a Loaded CompositeDrawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.Containers.CompositeDrawable.ensureChildMutationAllowed() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 546
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 454
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/Container.cs:line 199
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.Containers.FlowContainer`1.AddInternal(Drawable drawable) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/FlowContainer.cs:line 84
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.Containers.Container`1.Add(T drawable) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/Container.cs:line 179
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.Menu.Add(MenuItem item) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/Menu.cs:line 260
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.Dropdown`1.AddDropdownItem(String text, T value) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/Dropdown.cs:line 84
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.Dropdown`1.AddDropdownItem(T value) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/Dropdown.cs:line 64
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.TabControl`1.AddTabItem(TabItem`1 tab, Boolean addToDropdown) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/TabControl.cs:line 212
[runtime:error] 12/21/2018 04:17:10: at osu.Game.Overlays.Chat.Tabs.ChannelTabControl.AddTabItem(TabItem`1 item, Boolean addToDropdown) in /Users/smoogipoo/Repos/osu/osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs:line 52
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.TabControl`1.addTab(T value, Boolean addToDropdown) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/TabControl.cs:line 186
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Graphics.UserInterface.TabControl`1.AddItem(T item) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/UserInterface/TabControl.cs:line 166
[runtime:error] 12/21/2018 04:17:10: at osu.Game.Overlays.Chat.Tabs.ChannelTabControl.AddChannel(Channel channel) in /Users/smoogipoo/Repos/osu/osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs:line 74
[runtime:error] 12/21/2018 04:17:10: at osu.Game.Overlays.ChatOverlay.onChannelAddedToJoinedChannels(IEnumerable`1 channels) in /Users/smoogipoo/Repos/osu/osu.Game/Overlays/ChatOverlay.cs:line 324
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Configuration.BindableCollection`1.add(T item, BindableCollection`1 caller) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Configuration/BindableCollection.cs:line 73
[runtime:error] 12/21/2018 04:17:10: at osu.Framework.Configuration.BindableCollection`1.Add(T item) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Configuration/BindableCollection.cs:line 56
[runtime:error] 12/21/2018 04:17:10: at osu.Game.Online.Chat.ChannelManager.getChannel(Channel lookup, Boolean addToAvailable, Boolean addToJoined) in /Users/smoogipoo/Repos/osu/osu.Game/Online/Chat/ChannelManager.cs:line 306
[runtime:error] 12/21/2018 04:17:10: at osu.Game.Online.Chat.ChannelManager.JoinChannel(Channel channel, Boolean alreadyJoined) in /Users/smoogipoo/Repos/osu/osu.Game/Online/Chat/ChannelManager.cs:line 322
```

**Comment by smoogipoo** [comment]
Locally, I've fixed this by placing the `JoinChannel` call in `LoadComplete()` rather than `load()`, but we should probably make sure that it's scheduled internally anyway.

**Comment by peppy** [comment]
After further discussion we've decided to leave this as-is. We generally don't guarantee thread safety for methods like this and it'd be weird to start doing it (where do we draw the line?).
