### ISSUE TITLE
Application will not open win7 64 at all

### ISSUE THREAD

**Issue by Riince** [ppy/osu#4047]
When I run the osu! exe in the osulazer folder, nothing happens, the exe file can be seen in my processes for a fraction of a second and closes at 500-700kb of ram usage, no error log is created either in the osulazer folder or in my osu! installation folder (which is located on another hard drive). Nothing is added to my event viewer either so I haven't a clue what's happening. I see the little hourglass next to my cursor for a couple of frames whenever i click it only. I tried running and installing as administrator, restarting, etc.

https://i.imgur.com/zdTyW0C.png (red background indicates exiting process)

 i dont know the version, i tried both the installer from 2019.111.0 and 2018.1228.0 releases, neither worked. The updater also opens a command prompt for a fraction of a second which closes and creates a squirrelsetup.log file in the osulazer directory with nothing but "2019-01-11 15:32:41> Program: Starting Squirrel Updater:" in it.

There are no logs being written anywhere when it crashes, osu! is installed in another hard drive and I checked those logs, I even created an osu and logs folder where osu! wanted to install to by default and it didn't start creating a log of the crash then, either.

All I can offer is the installation log, maybe something went awry:

2019-01-11 15:15:14> Program: Starting Squirrel Updater: --install .
2019-01-11 15:15:14> Program: Starting install, writing to C:\Users\VekoIsMyWife\AppData\Local\SquirrelTemp
2019-01-11 15:15:14> Program: About to install to: C:\Users\VekoIsMyWife\AppData\Local\osulazer
2019-01-11 15:15:14> Program: Install path C:\Users\VekoIsMyWife\AppData\Local\osulazer already exists, burning it to the ground
2019-01-11 15:15:14> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\VekoIsMyWife\AppData\Local\osulazer\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-01-11 15:15:14> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\VekoIsMyWife\AppData\Local\osulazer\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-01-11 15:15:14> CheckForUpdateImpl: Reading RELEASES file from C:\Users\VekoIsMyWife\AppData\Local\SquirrelTemp
2019-01-11 15:15:14> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-01-11 15:15:15> ApplyReleasesImpl: Writing files to app directory: C:\Users\VekoIsMyWife\AppData\Local\osulazer\app-2019.111.0
2019-01-11 15:15:15> LogHost: Rigging execution stub for osu!_ExecutionStub.exe to C:\Users\VekoIsMyWife\AppData\Local\osulazer\osu!.exe
2019-01-11 15:15:18> ApplyReleasesImpl: Squirrel Enabled Apps: []
2019-01-11 15:15:18> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2019-01-11 15:15:18> ApplyReleasesImpl: About to create shortcuts for osu!.exe, rootAppDir C:\Users\VekoIsMyWife\AppData\Local\osulazer
2019-01-11 15:15:18> ApplyReleasesImpl: Creating shortcut for osu!.exe => C:\Users\VekoIsMyWife\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ppy Pty Ltd\osu!lazer.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: About to save shortcut: C:\Users\VekoIsMyWife\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ppy Pty Ltd\osu!lazer.lnk (target C:\Users\VekoIsMyWife\AppData\Local\osulazer\osu!.exe, workingDir C:\Users\VekoIsMyWife\AppData\Local\osulazer\app-2019.111.0, args , toastActivatorCSLID ebc39359-2a76-5ce1-8452-e9222d928c95)
2019-01-11 15:15:18> ApplyReleasesImpl: Creating shortcut for osu!.exe => C:\Users\VekoIsMyWife\Desktop\osu!lazer.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: About to save shortcut: C:\Users\VekoIsMyWife\Desktop\osu!lazer.lnk (target C:\Users\VekoIsMyWife\AppData\Local\osulazer\osu!.exe, workingDir C:\Users\VekoIsMyWife\AppData\Local\osulazer\app-2019.111.0, args , toastActivatorCSLID ebc39359-2a76-5ce1-8452-e9222d928c95)
2019-01-11 15:15:18> ApplyReleasesImpl: Examining Pin: Firefox.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-01-11 15:15:18> ApplyReleasesImpl: Examining Pin: Firefox.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2019-01-11 15:15:18> ApplyReleasesImpl: Fixing up tray icons
2019-01-11 15:15:18> ApplyReleasesImpl: cleanDeadVersions: for version 2019.111.0
2019-01-11 15:15:18> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2019.111.0

**Computer Specifications:** 
i7-4790k
gtx 960 4gb
intel hd 4600
windows 7 pro 64bit sp1 6.1.7601 build 7601
.net framework 4.7
dx11
c++ redistributables 2010 and 2015

**Comment by Trigger-b0y** [comment]
I have same problem and reported in this issue https://github.com/ppy/osu/issues/3769
Try run 2018.730.0, 2018.801.0 versions and post here your result for feedback

**Comment by smoogipoo** [comment]
Are there any log files in `%appdata%\logs`?

**Comment by Trigger-b0y** [comment]
> Are there any log files in `%appdata%\logs`?

>There are no logs being written anywhere when it crashes, osu! is installed in another hard drive and I checked those logs, I even created an osu and logs folder where osu! wanted to install to by default and it didn't start creating a log of the crash then, either.

>**There are no logs being written anywhere when it crashes**

**Comment by smoogipoo** [comment]
According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

In addition to KB2999226, make sure you also have [KB2533623](https://www.microsoft.com/en-us/download/details.aspx?id=26767) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.

**Comment by Riince** [comment]
> 
> 
> According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
> 
> In addition to KB2999226, make sure you also have [KB2533623](https://www.microsoft.com/en-us/download/details.aspx?id=26767) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:<path_to_app>\hostfxr.dll failed.

I got the same error as trigger-boy from sdk that you describe, however I was not able to install this KB. Both say they are not applicable to my computer.
