### ISSUE TITLE
Unable to login on osu!lazer

### ISSUE THREAD

**Issue by xXSparkk** [ppy/osu#4056]
I am able to login on the older version of osu, however, this one does not let me. 

Video: https://www.youtube.com/watch?v=eNZoJHXt4MQ

osu!lazer version: 2019.111.0

Logs: 2019-01-14 11:23:50 PM: ----------------------------------------------------------
2019-01-14 11:23:50 PM: Network Log for Ashley (LogLevel: Verbose)
2019-01-14 11:23:50 PM: osu 2019.111.0.0
2019-01-14 11:23:50 PM: Running on Microsoft Windows NT 6.2.9200.0, 8 cores
2019-01-14 11:23:50 PM: ----------------------------------------------------------
2019-01-14 11:23:50 PM: We just went Connecting!
2019-01-14 11:23:50 PM: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Forbidden.
2019-01-14 11:23:51 PM: Processing response from https://osu.ppy.sh/oauth/token failed with Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
2019-01-14 11:23:51 PM: at Newtonsoft.Json.JsonTextReader.ParseValue()
2019-01-14 11:23:51 PM: at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
2019-01-14 11:23:51 PM: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2019-01-14 11:23:51 PM: at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2019-01-14 11:23:51 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2019-01-14 11:23:51 PM: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2019-01-14 11:23:51 PM: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
2019-01-14 11:23:51 PM: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).
2019-01-14 11:23:51 PM: Login failed!
2019-01-14 11:23:51 PM: We just went Offline!

**Comment by xXSparkk** [comment]
Yes, neither has worked

**Comment by Slayer95** [comment]
It looks to me that the response isn't JSON but HTML, hence the character ``<`` in Path '', line 0, position 0.

**Comment by JSR-Gaming-x** [comment]
What operating system are you on? Can you type capital letters? I had to change my password to all lowercase to get it working for me.

**Comment by peppy** [comment]
@JSR-Gaming-x please refrain from commenting on issues without reading the issue history. I understand you may be trying to be helpful, but this is the opposite of that.

**Comment by Gamereily** [comment]
I have just recently had the same issue. I haven't been playing osu!lazer for very long but I know it worked in a previous version. I don't know what has changed since then for it to cause 1. a sign out and then 2. inability to log back in.

**Comment by petzku** [comment]
I'm having the same issue. `network.log` looks as follows:
```
2020-04-02 01:47:43 [verbose]: ----------------------------------------------------------
2020-04-02 01:47:43 [verbose]: network Log for Petzku (LogLevel: Verbose)
2020-04-02 01:47:43 [verbose]: osu 2020.402.0.0
2020-04-02 01:47:43 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 16 cores
2020-04-02 01:47:43 [verbose]: ----------------------------------------------------------
2020-04-02 01:47:43 [verbose]: We just went Connecting!
2020-04-02 01:47:53 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2020-04-02 01:48:03 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2020-04-02 01:48:03 [verbose]: Login failed!
2020-04-02 01:48:03 [verbose]: We just went Offline!
2020-04-02 01:49:10 [verbose]: We just went Connecting!
2020-04-02 01:49:20 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2020-04-02 01:49:30 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2020-04-02 01:49:30 [verbose]: Login failed!
2020-04-02 01:49:30 [verbose]: We just went Offline!
2020-04-02 01:51:07 [verbose]: We just went Connecting!
2020-04-02 01:51:17 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2020-04-02 01:51:27 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2020-04-02 01:51:27 [verbose]: Login failed!
2020-04-02 01:51:27 [verbose]: We just went Offline!
```

No problems logging in on the old client.

**Comment by peppy** [comment]
Going to close this for now as it's almost 100% a user-side (or ISP or other) issue.
