### ISSUE TITLE
Game either throwing error or crashing upon double click on button

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4530]
When clicking a back button or forwards button twice, second time right before it dissapears, it throws an error, if you press the button as its dissapearing 3 times (including first click) it crashes the game,

Video: https://youtu.be/ofDXgIhhUZ

Not too much of a serious bug but should be fixed anyway

**Comment by peppy** [comment]
Video unavailable and description doesn't mention where you're clicking.

**Comment by Joehuu** [comment]
To reproduce:
- Go to results screen on any play
- Click back button twice fast or spam (results' and then song select's)

It throws the error, but I can't seem to crash it anymore (had it happen before).

**Comment by peppy** [comment]
Possibly related to https://github.com/ppy/osu-framework/issues/2277.

**Comment by Hubza** [comment]
https://youtu.be/ofDXgIhhUZI seems i accidently removed a character

on a (<) Back button, or a forwards button seeable in video

**Comment by Hubza** [comment]
> 
> 
> To reproduce:
> 
>     * Go to results screen on any play
> 
>     * Click back button twice fast or spam (results' and then song select's)
> 
> 
> It throws the error, but I can't seem to crash it anymore (had it happen before).

i got it to throw the error by heading into the (rankings?) and clicking the forwards button very fast

**Comment by Hubza** [comment]
> 
> 
> > To reproduce:
> > ```
> > * Go to results screen on any play
> > 
> > * Click back button twice fast or spam (results' and then song select's)
> > ```
> > It throws the error, but I can't seem to crash it anymore (had it happen before).
> 
> i got it to throw the error by heading into the (rankings?) and clicking the forwards button very fast

it was chart sorry

**Comment by Hubza** [comment]
*but i didnt close it*

**Comment by Aergwyn** [comment]
I could reproduce it in the main menu right after starting the game. It's not 100% and seems to be related to timings. Too fast or too slow and it doesn't seem to crash.

[runtime.log](https://github.com/ppy/osu/files/3050293/runtime.log)
Log is empty which is weird.

So here is the stack from the console:
```
Unhandled Exception: [runtime:error] 2019-04-06 08:40:09: An unhandled error has occurred.
[runtime:error] 2019-04-06 08:40:09: System.NullReferenceException: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Screens.ScreenStack.Push(IScreen source, IScreen newScreen) in C:\projects\osu-framework-a4n7e\osu.Framework\Screens\ScreenStack.cs:line 90
   at osu.Framework.Screens.ScreenExtensions.<>c__DisplayClass0_0.<Push>b__0(ScreenStack stack) in C:\projects\osu-framework-a4n7e\osu.Framework\Screens\IScreen.cs:line 55
   at osu.Framework.Screens.ScreenExtensions.runOnRoot(IDrawable current, Action`1 onRoot, Action onFail) in C:\projects\osu-framework-a4n7e\osu.Framework\Screens\IScreen.cs:line 98
   at osu.Framework.Screens.ScreenExtensions.runOnRoot(IDrawable current, Action`1 onRoot, Action onFail) in C:\projects\osu-framework-a4n7e\osu.Framework\Screens\IScreen.cs:line 101
   at osu.Framework.Screens.ScreenExtensions.Push(IScreen screen, IScreen newScreen) in C:\projects\osu-framework-a4n7e\osu.Framework\Screens\IScreen.cs:line 55
   at osu.Game.Screens.Menu.MainMenu.onSolo() in C:\Users\Aergwyn\Desktop\osu\osu.Game\Screens\Menu\MainMenu.cs:line 106
   at osu.Game.Screens.Menu.ButtonSystem.<load>b__34_0() in C:\Users\Aergwyn\Desktop\osu\osu.Game\Screens\Menu\ButtonSystem.cs:line 109
   at osu.Game.Screens.Menu.Button.trigger() in C:\Users\Aergwyn\Desktop\osu\osu.Game\Screens\Menu\Button.cs:line 225
   at osu.Game.Screens.Menu.Button.OnClick(ClickEvent e) in C:\Users\Aergwyn\Desktop\osu\osu.Game\Screens\Menu\Button.cs:line 203
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Drawable.cs:line 1849
   at osu.Framework.Input.MouseButtonEventManager.<>c__DisplayClass38_0.<PropagateMouseButtonEvent>b__0(Drawable target) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\MouseButtonEventManager.cs:line 268
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.MouseButtonEventManager.PropagateMouseButtonEvent(IEnumerable`1 drawables, MouseButtonEvent e) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\MouseButtonEventManager.cs:line 268
   at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\MouseButtonEventManager.cs:line 196
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\MouseButtonEventManager.cs:line 1
53
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\InputManager.cs:line 473
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\InputManager.cs:line 437
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\UserInputManager.cs:line 45
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler) in C:\projects\osu-framework-a4n7e\osu.Framework\Input\StateChanges\ButtonInput.cs:line 73
   at osu.Framework.Input.InputManager.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Input\InputManager.cs:line 237
   at osu.Framework.Input.PassThroughInputManager.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Input\PassThroughInputManager.cs:line 129
   at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Drawable.cs:line 424
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 786
   at osu.Framework.Platform.GameHost.UpdateFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 287
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 140
   at osu.Framework.Threading.GameThread.runWork() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass83_0.<handleException>b__0() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 221
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 292
   at osu.Framework.Threading.Scheduler.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 157
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 137
   at osu.Framework.Threading.InputThread.RunUpdate() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\InputThread.cs:line 28
   at osu.Framework.Platform.GameHost.<Run>b__104_1(Object <p0>, FrameEventArgs <p1>) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 520
   at osuTK.GameWindow.OnUpdateFrame(FrameEventArgs e)
   at osuTK.GameWindow.OnUpdateFrameInternal(FrameEventArgs e)
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameWindow.cs:line 259
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 531
   at osu.Desktop.Program.Main(String[] args) in C:\Users\Aergwyn\Desktop\osu\osu.Desktop\Program.cs:line 46[runtime:error] 2019-04-06 08:40:09: at osu.Framework.Screens.ScreenStack.Push(IScreen source, IScreen newScreen) in C:\
projects\osu-framework-a4n7e\osu.Framework\Screens\ScreenStack.cs:line 90
```
And a video just to be sure: [Youtube (0:23)](https://youtu.be/_2hoPm2Bu3w)

**Comment by peppy** [comment]
Should be touched on by https://github.com/ppy/osu-framework/issues/2277.
