### ISSUE TITLE
Viewing the Beatmap page while downloading crashes the game

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4588]
**Describe the crash:** 
When you download a map and click on the beatmap so it shows the page,
The game does crash. I could only reproduce this on Taiko and CTB 
**Screenshots or videos showing encountered issue:** 
https://streamable.com/40rif

**osu!lazer version:** Latest commit 224c8d0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3041546/database.log)
[runtime.log](https://github.com/ppy/osu/files/3041547/runtime.log)

**Computer Specifications:** i3 6100 GTX 1050ti 8GB RAM Windows 10 x64 1809

**Comment by Lolihunter1337** [comment]
Now that i looked a bit closer i noticed the taiko and ctb leaderboards on the beatmap page dont load in the client. maybe related?

**Comment by peppy** [comment]
for reference:

```log
2019-04-04 02:59:11: System.Collections.Generic.KeyNotFoundException: The given key 'Meh' was not present in the dictionary.
2019-04-04 02:59:11: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2019-04-04 02:59:11: at osu.Game.Overlays.BeatmapSet.Scores.DrawableTopScore.set_Score(ScoreInfo value) in E:\Spiele\osu!\osu\osu.Game\Overlays\BeatmapSet\Scores\DrawableTopScore.cs:line 63
2019-04-04 02:59:11: at osu.Game.Overlays.BeatmapSet.Scores.ScoresContainer.updateDisplay() in E:\Spiele\osu!\osu\osu.Game\Overlays\BeatmapSet\Scores\ScoresContainer.cs:line 83
2019-04-04 02:59:11: at osu.Game.Overlays.BeatmapSet.Scores.ScoresContainer.set_Scores(IEnumerable`1 value) in E:\Spiele\osu!\osu\osu.Game\Overlays\BeatmapSet\Scores\ScoresContainer.cs:line 43
```

@smoogipoo is this fixed by your/evast's PR? i think it may be.

**Comment by smoogipoo** [comment]
Should be, yup
