### ISSUE TITLE
osu!direct free download and crash after that

### ISSUE THREAD

**Issue by hafizdkren** [ppy/osu#4593]
**Describe the bug:** 
I just try new version since long ago and try to go direct where I just try click direct and it's automatic download a song based on song button and search button (like search on direct and download it, and try to see info then download it like no video at all). after several download it come with crash can't go home, going alt+f4, and tada. osu!lazer can't open. right now
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.406.0
**Logs:**

**Comment by peppy** [comment]
Please actually attach logs.

**Comment by hafizdkren** [comment]
2019-04-06 12:34:16: ----------------------------------------------------------
2019-04-06 12:34:16: Runtime Log for hafiz (LogLevel: Verbose)
2019-04-06 12:34:16: osu 2019.406.0.0
2019-04-06 12:34:16: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
2019-04-06 12:34:16: ----------------------------------------------------------
2019-04-06 12:34:16: GL Initialized
2019-04-06 12:34:16: GL Version:                 4.6.0 NVIDIA 419.67
2019-04-06 12:34:16: GL Renderer:                GeForce 930MX/PCIe/SSE2
2019-04-06 12:34:16: GL Shader Language version: 4.60 NVIDIA
2019-04-06 12:34:16: GL Vendor:                  NVIDIA Corporation
2019-04-06 12:34:16: GL Extensions:              GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_win32 GL_EXT_win32_keyed_mutex GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_win32 GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_NVX_multigpu_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control
2019-04-06 12:34:18: BASS Initialized
2019-04-06 12:34:18: BASS Version:               2.4.14.0
2019-04-06 12:34:18: BASS FX Version:            2.4.12.1
2019-04-06 12:34:18: Device:                     Speakers (Conexant SmartAudio HD)
2019-04-06 12:34:18: Drive:                      {0.0.0.00000000}.{00f3114a-a077-4ea0-a97c-fad70dcddc30}
2019-04-06 12:34:22: Screen changed → Loader
2019-04-06 12:34:23: Screen changed → Disclaimer
2019-04-06 12:34:29: Screen changed → Intro
2019-04-06 12:34:32: Screen changed → MainMenu
2019-04-06 12:34:34: ButtonSystem's state changed from Initial to TopLevel
2019-04-06 12:34:39: Focus contention triggered by KeyBindingOverlay.
2019-04-06 12:35:00: ButtonSystem's state changed from TopLevel to Play
2019-04-06 12:35:01: ButtonSystem's state changed from Play to EnteringMode
2019-04-06 12:35:01: Screen changed → PlaySongSelect
2019-04-06 12:35:02: updating selection with beatmap:2 ruleset:0
2019-04-06 12:35:02: beatmap changed from "nekodex - circles! (peppy) []" to "KIRA - Circles (feat. GUMI) (Niva) [3.14]"
2019-04-06 12:35:02: working beatmap updated to KIRA - Circles (feat. GUMI) (Niva) [3.14]
2019-04-06 12:35:06: updating selection with beatmap:3 ruleset:0
2019-04-06 12:35:06: beatmap changed from "KIRA - Circles (feat. GUMI) (Niva) [3.14]" to "KIRA - Circles (feat. GUMI) (Niva) [Normal]"
2019-04-06 12:35:06: working beatmap updated to KIRA - Circles (feat. GUMI) (Niva) [Normal]
2019-04-06 12:35:07: Screen changed → PlayerLoader
2019-04-06 12:35:11: Screen changed → Player
2019-04-06 12:35:50: Screen changed ← PlayerLoader
2019-04-06 12:35:50: Screen changed ← PlaySongSelect
2019-04-06 12:35:50: working beatmap updated to KIRA - Circles (feat. GUMI) (Niva) [Normal]
2019-04-06 12:35:55: updating selection with beatmap:20 ruleset:0
2019-04-06 12:35:55: beatmap changed from "KIRA - Circles (feat. GUMI) (Niva) [Normal]" to "xi - Blue Zenith (Asphyxia) [Easy]"
2019-04-06 12:35:56: working beatmap updated to xi - Blue Zenith (Asphyxia) [Easy]
2019-04-06 12:35:57: updating selection with beatmap:13 ruleset:0
2019-04-06 12:35:57: beatmap changed from "xi - Blue Zenith (Asphyxia) [Easy]" to "xi - Blue Zenith (Asphyxia) [Akaphyxia's Normal]"
2019-04-06 12:35:57: working beatmap updated to xi - Blue Zenith (Asphyxia) [Akaphyxia's Normal]
2019-04-06 12:41:13: Screen changed → PlayerLoader
2019-04-06 12:41:15: Screen changed → Player
2019-04-06 12:45:31: Screen changed → SoloResults
2019-04-06 12:45:38: Screen changed ← Player
2019-04-06 12:45:38: Screen changed ← PlayerLoader
2019-04-06 12:45:38: Screen changed ← PlaySongSelect
2019-04-06 12:45:38: working beatmap updated to xi - Blue Zenith (Asphyxia) [Akaphyxia's Normal]
2019-04-06 12:45:49: Focus contention triggered by DirectOverlay.
2019-04-06 12:46:07: Focus contention triggered by BeatmapSetOverlay.
2019-04-06 12:46:31: Focus contention triggered by NotificationOverlay.
2019-04-06 12:46:31: Focus contention triggered by LoginOverlay.
2019-04-06 12:46:35: Focus contention triggered by UserProfileOverlay.
2019-04-06 12:46:58: updating selection with beatmap:4 ruleset:0
2019-04-06 12:46:58: beatmap changed from "xi - Blue Zenith (Asphyxia) [Akaphyxia's Normal]" to "KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]"
2019-04-06 12:46:58: working beatmap updated to KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]
2019-04-06 12:47:03: Screen changed → Editor
2019-04-06 12:47:31: ButtonSystem's state changed from EnteringMode to Initial
2019-04-06 12:52:08: Screen changed ← PlaySongSelect
2019-04-06 12:52:08: working beatmap updated to KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]
2019-04-06 12:52:11: updating selection with beatmap:3 ruleset:0
2019-04-06 12:52:11: beatmap changed from "KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]" to "KIRA - Circles (feat. GUMI) (Niva) [Normal]"
2019-04-06 12:52:11: working beatmap updated to KIRA - Circles (feat. GUMI) (Niva) [Normal]
2019-04-06 12:52:16: updating selection with beatmap:9 ruleset:0
2019-04-06 12:52:16: beatmap changed from "KIRA - Circles (feat. GUMI) (Niva) [Normal]" to "xi - Halcyon (gowww) [Beginner]"
2019-04-06 12:52:16: working beatmap updated to xi - Halcyon (gowww) [Beginner]
2019-04-06 12:52:17: updating selection with beatmap:26 ruleset:0
2019-04-06 12:52:17: beatmap changed from "xi - Halcyon (gowww) [Beginner]" to "cYsmix - Classic Pursuit (-kevincela-) [Normal]"
2019-04-06 12:52:17: working beatmap updated to cYsmix - Classic Pursuit (-kevincela-) [Normal]
2019-04-06 12:52:19: updating selection with beatmap:23 ruleset:0
2019-04-06 12:52:19: beatmap changed from "cYsmix - Classic Pursuit (-kevincela-) [Normal]" to "cYsmix - Classic Pursuit (-kevincela-) [Expert]"
2019-04-06 12:52:19: working beatmap updated to cYsmix - Classic Pursuit (-kevincela-) [Expert]
2019-04-06 12:52:21: updating selection with beatmap:null ruleset:0
2019-04-06 12:52:21: beatmap changed from "cYsmix - Classic Pursuit (-kevincela-) [Expert]" to ""
2019-04-06 12:52:21: working beatmap updated to please load a beatmap! - no beatmaps available! () []
2019-04-06 12:52:24: updating selection with beatmap:31 ruleset:0
2019-04-06 12:52:24: beatmap changed from "please load a beatmap! - no beatmaps available! () []" to "cYsmix - Moonlight Sonata (Okorin) [Intermediate]"
2019-04-06 12:52:24: working beatmap updated to cYsmix - Moonlight Sonata (Okorin) [Intermediate]
2019-04-06 12:52:27: updating selection with beatmap:null ruleset:0
2019-04-06 12:52:27: beatmap changed from "cYsmix - Moonlight Sonata (Okorin) [Intermediate]" to ""
2019-04-06 12:52:27: working beatmap updated to please load a beatmap! - no beatmaps available! () []
2019-04-06 12:52:28: updating selection with beatmap:25 ruleset:0
2019-04-06 12:52:28: beatmap changed from "please load a beatmap! - no beatmaps available! () []" to "cYsmix - Classic Pursuit (-kevincela-) [Insane]"
2019-04-06 12:52:29: working beatmap updated to cYsmix - Classic Pursuit (-kevincela-) [Insane]
2019-04-06 12:52:29: updating selection with beatmap:23 ruleset:0
2019-04-06 12:52:29: beatmap changed from "cYsmix - Classic Pursuit (-kevincela-) [Insane]" to "cYsmix - Classic Pursuit (-kevincela-) [Expert]"
2019-04-06 12:52:29: working beatmap updated to cYsmix - Classic Pursuit (-kevincela-) [Expert]
2019-04-06 12:52:30: updating selection with beatmap:9 ruleset:0
2019-04-06 12:52:30: beatmap changed from "cYsmix - Classic Pursuit (-kevincela-) [Expert]" to "xi - Halcyon (gowww) [Beginner]"
2019-04-06 12:52:30: working beatmap updated to xi - Halcyon (gowww) [Beginner]
2019-04-06 12:52:32: Focus contention triggered by ModSelectOverlay.
2019-04-06 12:52:37: updating selection with beatmap:27 ruleset:0
2019-04-06 12:52:37: beatmap changed from "xi - Halcyon (gowww) [Beginner]" to "cYsmix - Moonlight Sonata (Okorin) [Easy]"
2019-04-06 12:52:37: working beatmap updated to cYsmix - Moonlight Sonata (Okorin) [Easy]
2019-04-06 12:52:38: updating selection with beatmap:40 ruleset:0
2019-04-06 12:52:38: beatmap changed from "cYsmix - Moonlight Sonata (Okorin) [Easy]" to "ESTi - Oblivion (MoonFragrance) [Easy]"
2019-04-06 12:52:38: working beatmap updated to ESTi - Oblivion (MoonFragrance) [Easy]
2019-04-06 12:52:40: updating selection with beatmap:39 ruleset:0
2019-04-06 12:52:40: beatmap changed from "ESTi - Oblivion (MoonFragrance) [Easy]" to "ESTi - Oblivion (MoonFragrance) [Maximum]"
2019-04-06 12:52:40: working beatmap updated to ESTi - Oblivion (MoonFragrance) [Maximum]
2019-04-06 12:52:43: updating selection with beatmap:27 ruleset:0
2019-04-06 12:52:43: beatmap changed from "ESTi - Oblivion (MoonFragrance) [Maximum]" to "cYsmix - Moonlight Sonata (Okorin) [Easy]"
2019-04-06 12:52:43: working beatmap updated to cYsmix - Moonlight Sonata (Okorin) [Easy]
2019-04-06 12:52:44: updating selection with beatmap:28 ruleset:0
2019-04-06 12:52:44: beatmap changed from "cYsmix - Moonlight Sonata (Okorin) [Easy]" to "cYsmix - Moonlight Sonata (Okorin) [Expert]"
2019-04-06 12:52:44: working beatmap updated to cYsmix - Moonlight Sonata (Okorin) [Expert]
2019-04-06 12:52:48: Screen changed → PlayerLoader
2019-04-06 12:52:50: Focus contention triggered by NotificationOverlay.
2019-04-06 12:52:53: Screen changed → Player
2019-04-06 12:56:04: Screen changed → SoloResults
2019-04-06 12:56:09: Screen changed ← Player
2019-04-06 12:56:09: Screen changed ← PlayerLoader
2019-04-06 12:56:09: Screen changed ← PlaySongSelect
2019-04-06 12:56:09: working beatmap updated to cYsmix - Moonlight Sonata (Okorin) [Expert]
2019-04-06 12:56:13: Focus contention triggered by BeatmapOptionsOverlay.
2019-04-06 12:56:16: updating selection with beatmap:39 ruleset:0
2019-04-06 12:56:16: beatmap changed from "cYsmix - Moonlight Sonata (Okorin) [Expert]" to "ESTi - Oblivion (MoonFragrance) [Maximum]"
2019-04-06 12:56:16: working beatmap updated to ESTi - Oblivion (MoonFragrance) [Maximum]
2019-04-06 12:56:19: updating selection with beatmap:4 ruleset:0
2019-04-06 12:56:19: beatmap changed from "ESTi - Oblivion (MoonFragrance) [Maximum]" to "KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]"
2019-04-06 12:56:19: working beatmap updated to KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]
2019-04-06 12:56:20: updating selection with beatmap:5 ruleset:0
2019-04-06 12:56:20: beatmap changed from "KIRA - Circles (feat. GUMI) (Hafizdkren) [On Search]" to "xi - Halcyon -Long Version- (Natsu) [Deity]"
2019-04-06 12:56:20: working beatmap updated to xi - Halcyon -Long Version- (Natsu) [Deity]
2019-04-06 12:56:24: Screen changed ← MainMenu
2019-04-06 12:56:24: ButtonSystem's state changed from Initial to TopLevel
2019-04-06 12:56:25: ButtonSystem's state changed from TopLevel to Exit
2019-04-06 12:56:25: Screen changed ← Intro
2019-04-06 12:56:28: Screen changed ← Disclaimer
2019-04-06 12:56:28: Screen changed ← Loader
2019-04-06 12:56:28: Screen changed ←

**Comment by peppy** [comment]
The log is truncated before anything interesting happens. Just the actual error part should be sufficient.

**Comment by hafizdkren** [comment]
ok. let me explained. i install osu!lazer yesterday after several hour of update. install it like a normal. login. several setting. and open direct. i'm just looking kira song and accidentally download kira circle. and after try a bot, back to direct. download several song. and when going home it just can open. handler is error and able to play a song but can't goes to home screen. alt+f4, try to open it again. just blank with not respond. i forget to give a log so that's what i can get. sorry maybe the log is not the bugs log. but that what i'm experience with

**Comment by peppy** [comment]
Can you revise a video maybe?

**Comment by hafizdkren** [comment]
i'm not sure it will run like i tried yesterday. but ok

**Comment by hafizdkren** [comment]
[database.log](https://github.com/ppy/osu/files/3051350/database.log)
[network.log](https://github.com/ppy/osu/files/3051351/network.log)
[performance.log](https://github.com/ppy/osu/files/3051352/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3051353/runtime.log)
https://youtu.be/vqdlyhqyK5Y

**Comment by smoogipoo** [comment]
Still not sure what I'm looking for, your video is recorded at an extremely low framerate, and it looks like you managed to go back into menu fine + didn't experience an error/crash?

**Comment by Ishidres** [comment]
I can reproduce the issue above:
- open osu!
- login if you aren't already
- open osu!direct
- search for any beatmap
- preview the song of the beatmap by clicking on the play button (▶️)
- the game crashes after a few seconds

Screencast of what it looks like:
https://youtu.be/BTAjp8i8xlE

Logs:
[database.log](https://github.com/ppy/osu/files/3203196/database.log)
[debug.log](https://github.com/ppy/osu/files/3203197/debug.log)
[network.log](https://github.com/ppy/osu/files/3203198/network.log)
[performance.log](https://github.com/ppy/osu/files/3203199/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3203201/runtime.log)

**Comment by HoutarouOreki** [comment]
```
2019-05-21 05:04:58: Focus contention triggered by DirectOverlay.
2019-05-21 05:05:09: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-05-21 05:05:09: Focus contention triggered by NotificationOverlay.
2019-05-21 05:05:09: An unobserved error has occurred.
2019-05-21 05:05:09: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null.
2019-05-21 05:05:09: Parameter name: data) ---> System.ArgumentNullException: Value cannot be null.
2019-05-21 05:05:09: Parameter name: data
2019-05-21 05:05:09: at osu.Framework.Audio.Track.TrackBass.<>c__DisplayClass15_0.<.ctor>b__0()
2019-05-21 05:05:09: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-05-21 05:05:09: --- End of stack trace from previous location where exception was thrown ---
2019-05-21 05:05:09: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2019-05-21 05:05:09: --- End of inner exception stack trace ---
2019-05-21 05:05:09: ---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
2019-05-21 05:05:09: Parameter name: data
2019-05-21 05:05:09: at osu.Framework.Audio.Track.TrackBass.<>c__DisplayClass15_0.<.ctor>b__0()
2019-05-21 05:05:09: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-05-21 05:05:09: --- End of stack trace from previous location where exception was thrown ---
2019-05-21 05:05:09: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
2019-05-21 05:05:09: 
2019-05-21 05:05:09: An unobserved error has occurred. (inner)
2019-05-21 05:05:09: System.ArgumentNullException: Value cannot be null.
2019-05-21 05:05:09: Parameter name: data
2019-05-21 05:05:09: at osu.Framework.Audio.Track.TrackBass.<>c__DisplayClass15_0.<.ctor>b__0()
2019-05-21 05:05:09: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-05-21 05:05:09: --- End of stack trace from previous location where exception was thrown ---
2019-05-21 05:05:09: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
```
Can only reproduce with nekodex - circles
