### ISSUE TITLE
osu!lazer Crashing on Startup

### ISSUE THREAD

**Issue by Eugiv2** [ppy/osu#4615]
So I used to use osu!lazer a bit back when i had Windows 10 and it worked completely fine. But when I reverted back to Windows 8.1 the game would just crash on startup. I've been downloading the newest version of osu!lazer every couple weeks (deleting the previous one every time) and it was always the same result.

![0679808906890689](https://user-images.githubusercontent.com/49473223/55861395-a5306380-5bb9-11e9-96a6-84677092f2f2.PNG)

the current version I'm trying to use is 2019.406.0

Crash Info:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osu!.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c0ab1b7
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.19269
  Fault Module Timestamp:	5c5e079f
  Exception Code:	e0434352
  Exception Offset:	0000000000008e6c
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	3081
  Additional Information 1:	8bf1
  Additional Information 2:	8bf1ff648f0ad8f62266b176c58e1ce4
  Additional Information 3:	59a0
  Additional Information 4:	59a01316a1989d7620631962391e56ea

Processor:
Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz 2.40GHZ
System Type:
64-bit Operating System, x64 based Processor
GPU:
![0875](https://user-images.githubusercontent.com/49473223/55862656-3accf280-5bbc-11e9-8170-ec9334e6a6de.PNG)

**Comment by peppy** [comment]
Did you check https://github.com/ppy/osu#requirements?

**Comment by Eugiv2** [comment]
I've gone through all of the requirements and external links, downloading all that was recommended, and I still got the exact same result?

**Comment by peppy** [comment]
Please check our log files and event viewer for anything relevant.

**Comment by Eugiv2** [comment]
Where can I find those?

**Comment by peppy** [comment]
For event viewer please google it (will be under Application logs). For osu! logs they will be in `AppData/Roaming/osu/Logs/` (but if the crash is a startup crash these may not be so relevant.

**Comment by Eugiv2** [comment]
So I've just had a look in the logs folder for osu and I found performance and runtime logs, I have put the download link to them below. But I did find some stuff inside the logs that may be useful (I have put them in bold), I am new to this stuff so i may be wrong,

performance logs:
2019-04-11 02:57:58: ----------------------------------------------------------
2019-04-11 02:57:58: Performance Log for Declan Pears (LogLevel: Verbose)
2019-04-11 02:57:58: osu 2019.406.0.0
2019-04-11 02:57:58: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
2019-04-11 02:57:58: ----------------------------------------------------------
**2019-04-11 02:57:58: Drawable [SquirrelUpdateManager] took 344.34ms to load and was not async!**

runtime logs:
**2019-04-11 02:57:44: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-04-11 02:57:44: An unhandled error has occurred.
2019-04-11 02:57:44: System.DllNotFoundException: Unable to load DLL 'bass' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)**
2019-04-11 02:57:44: at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
2019-04-11 02:57:44: at ManagedBass.Bass.get_DeviceCount()
2019-04-11 02:57:44: at osu.Framework.Audio.AudioManager.getAllDevices()
2019-04-11 02:57:44: at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices()
2019-04-11 02:57:44: at osu.Framework.Audio.AudioManager.setAudioDevice(String preferredDevice)
2019-04-11 02:57:44: at osu.Framework.Audio.AudioManager.<>c__DisplayClass28_0.<onDeviceChanged>b__0()
2019-04-11 02:57:44: at osu.Framework.Threading.ScheduledDelegate.RunTask()
2019-04-11 02:57:44: at osu.Framework.Threading.Scheduler.Update()
2019-04-11 02:57:44: at osu.Framework.Threading.GameThread.ProcessFrame()
2019-04-11 02:57:44: at osu.Framework.Threading.GameThread.runWork()

This was repeated for nearly the whole of the 3.8 million characters, with varying dates. I also found this, the line "2019-04-11 XX:XX:XX: Unhandled exception has been allowed with 0 more allowable exceptions ." from what i could see was only repeated 3 times and was replaced overtime by "2019-04-11 XX:XX:XX: Unhandled exception has been denied ." If This was anything of use please inform me on what I can do.

Download links:
[performance.log](https://github.com/ppy/osu/files/3070933/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3070937/runtime.log)

**Comment by peppy** [comment]
Are you on a 32 bit system? We don't publish 32 bit builds yet.

**Comment by Eugiv2** [comment]
nup, definitely using a 64-bit system...

![0598234765](https://user-images.githubusercontent.com/49473223/56024354-2e2ed280-5d53-11e9-8ed3-609583cd6543.PNG)

**Comment by iiSaLMaN** [comment]
Can you check if there's a file called `bass.dll` in `%localappdata%\osulazer\app-2019.406.0\x64` and `%localappdata%\osulazer\app-2019.406.0\x86`

**Comment by Eugiv2** [comment]
I have just checked those 2 folders and `bass.dll` is present in both
`%localappdata%\osulazer\app-2019.406.0\x64`:
![0l1](https://user-images.githubusercontent.com/49473223/56353037-d93c0200-6213-11e9-82e3-abca06055767.PNG)
`%localappdata%\osulazer\app-2019.406.0\x86`:
![0l2](https://user-images.githubusercontent.com/49473223/56353039-db05c580-6213-11e9-937d-cfbbfc6a53f8.PNG)

**Comment by iiSaLMaN** [comment]
How is it not locating the DLLs then..., have you tried building osu!lazer manually?

**Comment by Eugiv2** [comment]
I have not, and I'm not sure how to...

**Comment by peppy** [comment]
It's likely an issue with platform/architecture mismatch, not a missing file.

**Comment by Goseale** [comment]
@Eugiv2 Try copying the bass file located at the x64 folder to the app folder and then start osu, it worked for me

**Comment by bdach** [comment]
Closing due to inactivity. Please reopen if this still occurs on newer builds.

**Comment by EileoOfficial** [comment]
it doesn't work

**Comment by smoogipoo** [comment]
@EileoOfficial please provide more information - logs and/or event viewer entries.

**Comment by EileoOfficial** [comment]
[performance.log](https://github.com/ppy/osu/files/5314327/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5314328/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5314329/updater.log)
[database.log](https://github.com/ppy/osu/files/5314330/database.log)
[network.log](https://github.com/ppy/osu/files/5314331/network.log)

**Comment by bdach** [comment]
@EileoOfficial your database seems to have become corrupted somehow. as a short-term workaround please backup & remove or rename the `%AppData%/Local/osu/client.db` file and try launching again. note that doing this will require you to reimport things again as the DB will start from scratch.

**Comment by EileoOfficial** [comment]
ight, let me do this

**Comment by EileoOfficial** [comment]
it worked, thanks!!!
