### ISSUE TITLE
Works on Crostini, but audio is buggy or I can't login and download beatmaps

### ISSUE THREAD

**Issue by kathelynn** [ppy/osu#4812]
**Describe the bug:** 
Audio is buggy: It feels like there's a lot of clips of osu's song being played, going back and forth and the sound played when hovering and pressing buttons are delayed.
I can't login: The email is there, and I'm sure I typed the password correctly but whenever I press Login nothing happens. It loads, then nothing.
I can't download beatmaps: Nothing shows up on the Direct. I can't drag and drop beatmaps either. 
**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1oP5jFWStk9HMM3acYjHcSseL2r2hKWWS/view?usp=sharing
For some reason, audio cannot be heard. I also can't show footage of drag and dropping beatmaps but currently, it doesn't work. Also in the video it looks very laggy, but the game is actually smooth.
**osu!lazer version:** 
No idea, just did `git clone https://github.com/ppy/osu` a few hours ago, so I believe I'm on the latest version
**Logs:**

**Comment by peppy** [comment]
You've given no logs, no system specs, no details of how you compiled (did you follow the guides to build as release?) and your issue contradicts itself (tarts by saying sound is playing, then says sound is not).

**Comment by kathelynn** [comment]
I'm sorry, I'm very new to this. I have run osu!lazer on Crostini by the following:
I installed Debian 9's dotnet Core SDK 2.2 from https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current and used `LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Debug/netcoreapp2.2" dotnet run --project osu.Desktop` to build and run lazer. I also tried `LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Release/netcoreapp2.2" dotnet run --project osu.Desktop` 

The audio issue fixed itself for no reason, but apparently, it's working right now.

**Logs**
For issues with logging in or any of the online features, I have managed to get network.log and it gives out this
```2019-05-17 03:33:14: ----------------------------------------------------------
2019-05-17 03:33:14: Network Log for kathelyn (LogLevel: Verbose)
2019-05-17 03:33:14: osu 0.0.0.0
2019-05-17 03:33:14: Running on Unix 4.19.34.4457, 4 cores
2019-05-17 03:33:14: ----------------------------------------------------------
2019-05-17 03:33:14: We just went Connecting!
2019-05-17 03:33:16: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
2019-05-17 03:33:16: at Interop.SslInitializer..cctor()
2019-05-17 03:33:16: --- End of inner exception stack trace ---
2019-05-17 03:33:16: at Interop.Ssl..cctor()
2019-05-17 03:33:16: --- End of inner exception stack trace ---
2019-05-17 03:33:16: at Interop.Ssl.SslV2_3Method()
2019-05-17 03:33:16: at Interop.Ssl.SslMethods..cctor()
2019-05-17 03:33:16: --- End of inner exception stack trace ---
2019-05-17 03:33:16: at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
2019-05-17 03:33:16: at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
2019-05-17 03:33:16: at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
2019-05-17 03:33:16: --- End of inner exception stack trace ---
2019-05-17 03:33:16: at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
2019-05-17 03:33:16: at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
2019-05-17 03:33:16: at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
2019-05-17 03:33:16: at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
2019-05-17 03:33:16: at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
2019-05-17 03:33:16: at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
2019-05-17 03:33:16: at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
2019-05-17 03:33:16: at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
2019-05-17 03:33:16: at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
2019-05-17 03:33:16: at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
2019-05-17 03:33:16: at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2019-05-17 03:33:16: --- End of inner exception stack trace ---
2019-05-17 03:33:16: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Threading.Tasks.ValueTask`1.get_Result()
2019-05-17 03:33:16: at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Threading.Tasks.ValueTask`1.get_Result()
2019-05-17 03:33:16: at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
2019-05-17 03:33:16: at System.Threading.Tasks.ValueTask`1.get_Result()
2019-05-17 03:33:16: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-05-17 03:33:16: at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-05-17 03:33:16: at osu.Framework.IO.Network.WebRequest.internalPerform() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 323.
2019-05-17 03:33:16: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
2019-05-17 03:33:16: Parameter name: value
2019-05-17 03:33:16: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2019-05-17 03:33:16: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2019-05-17 03:33:16: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\JsonWebRequest.cs:line 21
2019-05-17 03:33:16: at osu.Framework.IO.Network.WebRequest.Complete(Exception e) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 486.
2019-05-17 03:33:16: Login failed!
2019-05-17 03:33:16: We just went Offline!
```

**Specs**
![Screenshot 2019-05-17 at 11 37 45 AM](https://user-images.githubusercontent.com/50712757/57901563-4fc23300-7898-11e9-9949-0030ea068a30.png)

**Comment by kathelynn** [comment]
After updating to Chrome OS 76 and reinstalled Crostini, the issue was fixed.
