### ISSUE TITLE
Cakebuild script doesn't work

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#4969]
When i run the build script on powershell `build.ps1`, it fails to install `NVika.MSBuild` and throws this exception `NuGet.Packaging.Signing.SignatureException`
<details>
  <summary>Script output</summary>

  ```
  Preparing to run build script...
Restoring cake tools...
Running build script...
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing C:/Users/Salman Ahmed/source/repos/osu-fork/build/build.cake...
Processing build script...
Installing tools...
Missing C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1\nvika.msbuild.1.0.1.nupkg
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/nvika.msbuild/index.json
Retrieving package 'NVika.MSBuild 1.0.1' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg 891ms
Acquiring lock for the installation of NVika.MSBuild 1.0.1
Acquired lock for the installation of NVika.MSBuild 1.0.1
Installing NVika.MSBuild 1.0.1.
Install failed. Rolling back...
Executing nuget actions took 2.3 sec
Error: System.AggregateException: One or more errors occurred. () ---> NuGet.Packaging.Signing.SignatureException
   at NuGet.Packaging.PackageExtractor.VerifyPackageSignatureAsync(String source, Guid parentId, PackageIdentity package, PackageExtractionContext packageExtractionContext, ISignedPackageReader signedPackageReader, CancellationToken token)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass3_2.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Packaging.PackageExtractor.InstallFromSourceAsync(String source, PackageIdentity packageIdentity, Func`2 copyToAsync, VersionFolderPathResolver versionFolderPathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
   at NuGet.Protocol.GlobalPackagesFolderUtility.AddPackageAsync(String source, PackageIdentity packageIdentity, Stream packageStream, String globalPackagesFolder, Guid parentId, ILogger logger, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.<>c__DisplayClass3_0.<<GetDownloadResultAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.<>c__DisplayClass16_0`1.<<ProcessStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.Protocol.DownloadResourceV3.GetDownloadResourceResultAsync(PackageIdentity identity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackageDownloader.GetDownloadResourceResultAsync(SourceRepository sourceRepository, PackageIdentity packageIdentity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_1.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.EnsureResultAsync()
   at NuGet.PackageManagement.PackagePreFetcherResult.GetResultAsync()
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.NuGet.Install.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path) in C:\projects\cake\src\Cake.NuGet\Install\NuGetPackageInstaller.cs:line 147
   at Cake.Core.Scripting.ScriptProcessor.InstallPackages(IReadOnlyCollection`1 modules, DirectoryPath installPath, PackageType packageType) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 193
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 148
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
---> (Inner Exception #0) NU3000: <---
  ```
  
</details>

**Comment by miterosan** [comment]
Please try to reset your nuget cache.

You can do this using ``dotnet nuget locals all -c``


iiSaLMaN <notifications@github.com> schrieb am So., 9. Juni 2019, 09:04:

**Comment by iiSaLMaN** [comment]
That resulted in another problem
<details>
<summary>Log</summary>

```
PS C:\Users\Salman Ahmed\source\repos\osu-fork> ./build.ps1 -Verbosity  diagnostic
Preparing to run build script...
Restoring cake tools...
Running build script...
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing C:/Users/Salman Ahmed/source/repos/osu-fork/build/build.cake...
Processing build script...
Installing tools...
Missing C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1\nvika.msbuild.1.0.1.nupkg
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/nvika.msbuild/index.json
Retrieving package 'NVika.MSBuild 1.0.1' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg 1445ms
Acquiring lock for the installation of NVika.MSBuild 1.0.1
Acquired lock for the installation of NVika.MSBuild 1.0.1
Installing NVika.MSBuild 1.0.1.
Error downloading 'NVika.MSBuild.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg'.
Access to the path 'C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1' is denied.
  GET https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg 916ms
Acquiring lock for the installation of NVika.MSBuild 1.0.1
Acquired lock for the installation of NVika.MSBuild 1.0.1
Installing NVika.MSBuild 1.0.1.
Error downloading 'NVika.MSBuild.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg'.
Access to the path 'C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1' is denied.
  GET https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg 912ms
Acquiring lock for the installation of NVika.MSBuild 1.0.1
Acquired lock for the installation of NVika.MSBuild 1.0.1
Installing NVika.MSBuild 1.0.1.
Install failed. Rolling back...
Executing nuget actions took 3.51 sec
Error: System.AggregateException: One or more errors occurred. (Error downloading 'NVika.MSBuild.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg'.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Error downloading 'NVika.MSBuild.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg'. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass3_2.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Packaging.PackageExtractor.InstallFromSourceAsync(String source, PackageIdentity packageIdentity, Func`2 copyToAsync, VersionFolderPathResolver versionFolderPathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
   at NuGet.Protocol.GlobalPackagesFolderUtility.AddPackageAsync(String source, PackageIdentity packageIdentity, Stream packageStream, String globalPackagesFolder, Guid parentId, ILogger logger, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.<>c__DisplayClass3_0.<<GetDownloadResultAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.<>c__DisplayClass16_0`1.<<ProcessStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.Protocol.DownloadResourceV3.GetDownloadResourceResultAsync(PackageIdentity identity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackageDownloader.GetDownloadResourceResultAsync(SourceRepository sourceRepository, PackageIdentity packageIdentity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_1.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.EnsureResultAsync()
   at NuGet.PackageManagement.PackagePreFetcherResult.GetResultAsync()
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.NuGet.Install.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path) in C:\projects\cake\src\Cake.NuGet\Install\NuGetPackageInstaller.cs:line 147
   at Cake.Core.Scripting.ScriptProcessor.InstallPackages(IReadOnlyCollection`1 modules, DirectoryPath installPath, PackageType packageType) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 193
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 148
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Error downloading 'NVika.MSBuild.1.0.1' from 'https://api.nuget.org/v3-flatcontainer/nvika.msbuild/1.0.1/nvika.msbuild.1.0.1.nupkg'. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass3_2.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Packaging.PackageExtractor.InstallFromSourceAsync(String source, PackageIdentity packageIdentity, Func`2 copyToAsync, VersionFolderPathResolver versionFolderPathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
   at NuGet.Protocol.GlobalPackagesFolderUtility.AddPackageAsync(String source, PackageIdentity packageIdentity, Stream packageStream, String globalPackagesFolder, Guid parentId, ILogger logger, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.<>c__DisplayClass3_0.<<GetDownloadResultAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.<>c__DisplayClass16_0`1.<<ProcessStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.Protocol.DownloadResourceV3.GetDownloadResourceResultAsync(PackageIdentity identity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackageDownloader.GetDownloadResourceResultAsync(SourceRepository sourceRepository, PackageIdentity packageIdentity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_1.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.PackageManagement.PackagePreFetcherResult.EnsureResultAsync()
   at NuGet.PackageManagement.PackagePreFetcherResult.GetResultAsync()
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)<---
```
</details>

**Comment by miterosan** [comment]
"Access to the path 'C:\Users\Salman Ahmed\.nuget\packages\nvika.msbuild\1.0.1' is denied."

Can you check if you have anything open, that could lock that path?

If not: can you restart your PC just to be sure?

**Comment by iiSaLMaN** [comment]
It worked now, i guess there was a process locking that folder but anyways, thanks
