### ISSUE TITLE
Importing Beatmaps from stable Issues

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#5091]
**Issue 1.**  Button says "Import beatmaps from stable" and the notification says  "Imported X of Y beatmaps" when it is talking about beatmap **sets**.  For example, mine is saying "Imported X of 4204 beatmaps", when I have 16,000 beatmaps, but around that many beatmap sets. Might want to add " sets" for clarity.

**Issue 2.** Lazer is only attempting to import 4204 sets when I have 5330 sets.  Not sure why this is the case.

**Issue 3.** Lots of import failures on various songs, however the notification claims this is already getting logged and alerted to devs.

Importing 4204 sets
![image](https://user-images.githubusercontent.com/49334335/59889015-f1eda300-938f-11e9-8c28-665fdecb003e.png)

Final imported after failures
![image](https://user-images.githubusercontent.com/49334335/59889239-18f8a480-9391-11e9-9bc9-a528e8c32cc0.png)

Supposedly have 5330 sets on stable
![image](https://user-images.githubusercontent.com/49334335/59889032-0336af80-9390-11e9-9252-bb12788b2f9d.png)

Stable showing 16k beatmaps
![image](https://user-images.githubusercontent.com/49334335/59889119-7a6c4380-9390-11e9-98c0-7c007d8edd17.png)

Runtime log
[runtime.log](https://github.com/ppy/osu/files/3312527/runtime.log)

Network log (looks like most failures were no longer available maps)
[network.log](https://github.com/ppy/osu/files/3312534/network.log)

Database log (failures appear to be missing songs / invalid file formats)
[database.log](https://github.com/ppy/osu/files/3312537/database.log)

**Comment by iiSaLMaN** [comment]
Some beatmaps you tried to import are very old and cannot be imported
```
2019-06-20 11:52:41: [?????] Model creation of 140301 Eluveitie - A Rose for Epona failed.
2019-06-20 11:52:41: System.IO.IOException: Unknown file format (ow computerosu file format v12)
2019-06-20 11:52:41: at osu.Game.Beatmaps.Formats.Decoder.GetDecoder[T](StreamReader stream)
2019-06-20 11:52:41: at osu.Game.Beatmaps.BeatmapManager.CreateModel(ArchiveReader reader)
2019-06-20 11:52:41: at osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive, CancellationToken cancellationToken)
2019-06-20 11:52:41: Could not import (140301 Eluveitie - A Rose for Epona)
```
also, some cannot be imported because they have null file format
```
2019-06-21 12:21:23: Could not import (88180 t+pazolite - Cheatreal)
2019-06-21 12:21:23: System.IO.IOException: Unknown file format (null)
2019-06-21 12:21:23: at osu.Game.Beatmaps.Formats.Decoder.GetDecoder[T](StreamReader stream)
2019-06-21 12:21:23: at osu.Game.Beatmaps.BeatmapManager.createBeatmapDifficulties(ArchiveReader reader)
2019-06-21 12:21:23: at osu.Game.Beatmaps.BeatmapManager.Populate(BeatmapSetInfo beatmapSet, ArchiveReader archive, CancellationToken cancellationToken)
2019-06-21 12:21:23: at osu.Game.Database.ArchiveModelManager`2.<>c__DisplayClass34_0.<<Import>b__0>d.MoveNext()
2019-06-21 12:21:23: --- End of stack trace from previous location where exception was thrown ---
2019-06-21 12:21:23: at osu.Game.Database.ArchiveModelManager`2.Import(TModel item, ArchiveReader archive, CancellationToken cancellationToken)
2019-06-21 12:21:23: at osu.Game.Database.ArchiveModelManager`2.Import(String path, CancellationToken cancellationToken)
2019-06-21 12:21:23: at osu.Game.Database.ArchiveModelManager`2.<>c__DisplayClass26_0.<<Import>b__0>d.MoveNext()
```

**Comment by peppy** [comment]
5330 is the number of folders. beatmaps can have subfolders. it is not an accurate way of counting how many beatmaps you have.

As for the term "beatmap set", it is an internal term which we generally don't use in a public facing way. We've discussed removing ti from the code base in favour of `Beamaps` and `BeatmpDifficulties`.

**Comment by peppy** [comment]
Closing this one as kind of invalid, for the reasons specified in my comments.
