### ISSUE TITLE
osu!lazer for android on S9+ crashes on startup

### ISSUE THREAD

**Issue by DecayingEagle** [ppy/osu#5323]
Just wanted to make you aware of that osu! crashes on S9+ with android pie. Probably a full screen (S9+ screen is 18.5:9 aspect ratio) issue or just that I am running on pie.
Btw for a brief moment you can see the osu logo, therefore I think that it can be another problem than that.

![Screenshot_20190710-205905_One UI Home](https://user-images.githubusercontent.com/46646694/60996777-9f335580-a355-11e9-8e99-b066367f0ebf.jpg)

**Comment by TheComputerGuy96** [comment]
@DecayingEagle Logcat please

Here's how to do it: https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/

**Comment by DecayingEagle** [comment]
one sec
working on it

**Comment by DecayingEagle** [comment]
`Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.pluscubed.matlog
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2361)
        at com.android.server.pm.permission.PermissionManagerService.access$1100(PermissionManagerService.java:131)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:3240)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6401)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25686)
        at android.os.Binder.shellCommand(Binder.java:642)
        at android.os.Binder.onTransact(Binder.java:540)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3315)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4731)
        at android.os.Binder.execTransact(Binder.java:739)`

help

**Comment by DecayingEagle** [comment]
wait it's working now
