### ISSUE TITLE
Importing map throws a WebException

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5344]
**Describe the bug:** Download and import https://osu.ppy.sh/beatmapsets/137804#osu/344332. osu!lazer will seemingly import the map correctly, yet throw an error ``System.Net.WebException: NotFound``.

**osu!lazer version:** 2019.704.0

**Logs:** 
```
[f6fad] Beginning import...
[f6fad] Performing online lookups...
[f6fad] Import successfully completed!
[f6fad] Online retrieval failed for [2]
System.Net.WebException: NotFound
at osu.Framework.IO.Network.WebRequest.Complete(Exception e) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 506
at osu.Framework.IO.Network.WebRequest.beginResponse(CancellationToken cancellationToken) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 410
at osu.Framework.IO.Network.WebRequest.internalPerform() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 331

```

**Comment by EVAST9919** [comment]
Happens when you are trying to import deleted beatmap (by deleted I mean deleted from the site)

**Comment by peppy** [comment]
This is now silenced via https://github.com/ppy/osu/pull/5471 (doesn't appear in notifications).

**Comment by Morilli** [comment]
> Happens when you are trying to import deleted beatmap (by deleted I mean deleted from the site)

Not sure I understand. The beatmap I linked can be downloaded from the site, so it's certainly not deleted, or am I misunderstanding you?
