### ISSUE TITLE
Beatmap imports may fail randomly

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#5345]
**Describe the bug:** osu!lazer likes to throw database errors every once in a while after trying to import all maps from stable. It seems like this issue is thread-based, as it is *inconsistent*, which means that specifically trying to import the mentioned map will work without throwing any errors.

**osu!lazer version:** 2019.704.0 / master

**Logs:** 
```
Could not import (13022 Koji Kondo & Mahito Yokota - Egg Planet)
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing) in G:\Dokumente\GitHub\osu\osu.Game\Database\DatabaseWriteUsage.cs:line 39
at osu.Game.Database.DatabaseWriteUsage.Dispose() in G:\Dokumente\GitHub\osu\osu.Game\Database\DatabaseWriteUsage.cs:line 54
at osu.Game.Database.ArchiveModelManager`2.<>c__DisplayClass28_0.<<Import>b__0>d.MoveNext() in G:\Dokumente\GitHub\osu\osu.Game\Database\ArchiveModelManager.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
at osu.Game.Database.ArchiveModelManager`2.Import(TModel item, ArchiveReader archive, CancellationToken cancellationToken) in G:\Dokumente\GitHub\osu\osu.Game\Database\ArchiveModelManager.cs:line 265
at osu.Game.Database.ArchiveModelManager`2.Import(String path, CancellationToken cancellationToken) in G:\Dokumente\GitHub\osu\osu.Game\Database\ArchiveModelManager.cs:line 172
at osu.Game.Database.ArchiveModelManager`2.<>c__DisplayClass20_0.<<Import>b__0>d.MoveNext() in G:\Dokumente\GitHub\osu\osu.Game\Database\ArchiveModelManager.cs:line 113
```

I'm getting so many errors and stacktraces it's hard to distinguish between individual errors. If this seems incomplete I can provide a full log file.

**Comment by jai-x** [comment]
This might be related to changes made here: https://github.com/ppy/osu/pull/5269

**Comment by Morilli** [comment]
Thought so as well, but I specifically made sure it's in fact reproducable on 2019.704.0, which doesn't include this PR. The error messages look a little different though, so here you go: 
[log.txt](https://github.com/ppy/osu/files/3386711/log.txt)

**Comment by Akarinnnnn** [comment]
I've found an example: https://osu.ppy.sh/beatmapsets/1302026#osu/2702472 too.

**Comment by bdach** [comment]
@Akarinnnnn that map imported just fine for me. you may have a locally corrupted database.

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn that map imported just fine for me. you may have a locally corrupted database.

Thank you. How to fix(or reset?) my database?

**Comment by bdach** [comment]
Move away your `client.db` file in the lazer directory (`%AppData%/osu` on windows). We'll be addressing database failures at some point.

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn that map imported just fine for me. you may have a locally corrupted database.

Re-import this map caused this issue again.
Reproduce steps:
1. Edit this map with stable editor
2. Export this map
3. Fail

**Comment by peppy** [comment]
Can you confirm it fails 100% of the time? This original issue reports that if you try to import more than once it will eventually succeed, but that's not the case for you?

**Comment by Akarinnnnn** [comment]
I have retried 15 times, and it fails all the time. This is the [file](https://github.com/ppy/osu/files/6033840/AirS.-.Opening.zip) renamed "osz" to "zip".  
Later I will compile a debug version to see what's wrong happened.

**Comment by peppy** [comment]
Thanks.

**Comment by Akarinnnnn** [comment]
According my diagnose, the old, corrupted database was not really cleared, so this map can't import. Thank you for pay attention.
Would you like to provide a button that "Clear database and restart Osu!"?

**Comment by bdach** [comment]
Such a button shouldn't be a thing. It would be temporary at best. The goal is to have the database work robustly - as I have previously hinted we're in a bit of a limbo in that regard, but we're well aware of the issues.

Manually removing is the way to go for now.

**Comment by peppy** [comment]
Should be resolved with realm.
