### ISSUE TITLE
osu! crashes when playing a beatmap in the editor

### ISSUE THREAD

**Issue by jeffrypig23** [ppy/osu#5676]
**Describe the crash:** 
After selecting a beatmap in the standard single player mode, changing to the editor, waiting for the beatmap to load, and then playing the beatmap will cause osu! to crash.

I tried going straight into the editor upon loading the game, but under this circumstance it doesn't crash. This makes it seem like the crash may be related to loading approach/hit circles (maybe a framework issue?).

**Screenshots or videos showing encountered issue:** 
[Video](https://youtu.be/aGdhnobZRg8)

**osu!lazer version:** 
Local release (2019.809.0)

**Logs:** 
```
Unhandled Exception: System.ArgumentOutOfRangeException: Positive number required.
Parameter name: bytesAllocated
   at System.GC.AddMemoryPressure(Int64 bytesAllocated)
   at osu.Framework.Platform.NativeMemoryTracker.AddMemory(Object source, Int64 amount) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\NativeMemoryTracker.cs:line 27
   at osu.Framework.Graphics.OpenGL.Buffers.RenderBuffer.set_Size(Vector2 value) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\RenderBuffer.cs:line 66
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.initialise() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 73
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.Bind() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 86
   at osu.Framework.Graphics.BufferedDrawNode.BindFrameBuffer(FrameBuffer frameBuffer) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\BufferedDrawNode.cs:line 141
   at osu.Framework.Graphics.BufferedDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\BufferedDrawNode.cs:line 87
   at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawable_DrawNode.cs:line 198
   at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawable_DrawNode.cs:line 198
   at osu.Framework.Platform.GameHost.DrawFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 367
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 140
   at osu.Framework.Threading.GameThread.runWork() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 321
   at osu.Framework.Threading.Scheduler.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 160
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 136
   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 553
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 556
   at osu.Desktop.Program.Main(String[] args) in /Users/stephenogden/Documents/GitHub/osu/osu.Desktop/Program.cs:line 56
```

**Computer Specifications:** 
CPU: 2.7 GHz Intel Core i5
GPU: Intel Iris Graphics 6100 (Integrated graphics)
RAM: 8 GB DDR3
OS: macOS 10.14.6 (Mojave)

Yes, Im running osu! on a 2015 macbook pro :(

**Comment by jeffrypig23** [comment]
More logs!

```
[runtime:verbose] 2019-08-11 04:16:53: GL Initialized
[runtime:verbose] 2019-08-11 04:16:53: GL Version:                 2.1 INTEL-12.10.12
[runtime:verbose] 2019-08-11 04:16:53: GL Renderer:                Intel(R) Iris(TM) Graphics 6100
[runtime:verbose] 2019-08-11 04:16:53: GL Shader Language version: 1.20
[runtime:verbose] 2019-08-11 04:16:53: GL Vendor:                  Intel Inc.
[runtime:verbose] 2019-08-11 04:16:53: GL Extensions:              GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
[runtime:debug] 2019-08-11 04:16:54: Loading Font OpenSans...
[runtime:debug] 2019-08-11 04:16:54: Loading Font FontAwesome-Solid...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font FontAwesome-Solid!
[runtime:debug] 2019-08-11 04:16:54: Loading Font FontAwesome-Regular...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font FontAwesome-Regular!
[runtime:debug] 2019-08-11 04:16:54: Loading Font FontAwesome-Brands...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font FontAwesome-Brands!
[runtime:debug] 2019-08-11 04:16:54: Loading Font osuFont...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font osuFont!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-Medium...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font OpenSans!
[runtime:debug] 2019-08-11 04:16:54: Loading Font OpenSans-Bold...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-Medium!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-MediumItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-MediumItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Noto-Basic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font OpenSans-Bold!
[runtime:debug] 2019-08-11 04:16:54: Loading Font OpenSans-Italic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Noto-Basic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Noto-Hangul...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font OpenSans-Italic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font OpenSans-BoldItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font OpenSans-BoldItalic!
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Noto-Hangul!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Noto-CJK-Basic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Noto-CJK-Basic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Noto-CJK-Compatibility...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Noto-CJK-Compatibility!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-Regular...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-Regular!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-RegularItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-RegularItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-SemiBold...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-SemiBold!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-SemiBoldItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-SemiBoldItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-Bold...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-Bold!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-BoldItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-BoldItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-Light...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-Light!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-LightItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-LightItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-Black...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-Black!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Exo2.0-BlackItalic...
[runtime:debug] 2019-08-11 04:16:54: Loaded Font Exo2.0-BlackItalic!
[runtime:debug] 2019-08-11 04:16:54: Loading Font Venera...
Console output is being limited. Please check runtime.log for full logs.
[runtime:verbose] 2019-08-11 04:16:54: BASS Initialized
[runtime:verbose] 2019-08-11 04:16:54: BASS Version:               2.4.14.1
[runtime:verbose] 2019-08-11 04:16:54: BASS FX Version:            2.4.12.1
[runtime:verbose] 2019-08-11 04:16:54: Device:                     PH-BTH3 Headphones
[runtime:verbose] 2019-08-11 04:16:54: Drive:                      20-16-03-16-d2-5d:output
[performance:verbose] 2019-08-11 04:16:57: TextureAtlas initialised (1024x1024)
[performance:verbose] 2019-08-11 04:16:57: TextureAtlas initialised (1024x1024)
[performance:verbose] 2019-08-11 04:16:57: Drawable [Audio (FrameStatisticsDisplay)] took 52.17ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:57: Drawable [BackButton] took 52.52ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:57: Drawable [Container] took 69.58ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:57: Drawable [ScalingContainer+ScalingDrawSizePreservingFillContainer] took 69.78ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:57: Drawable [ScalingContainer+AlwaysInputContainer] took 69.85ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:57: Drawable [ScalingContainer] took 69.96ms to load and was not async!
[performance:verbose] 2019-08-11 04:16:58: Texture requested (1920x8) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
[performance:verbose] 2019-08-11 04:16:58: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
[runtime:verbose] 2019-08-11 04:16:58: Screen changed → Loader
[runtime:verbose] 2019-08-11 04:16:59: Screen changed → IntroCircles
[performance:verbose] 2019-08-11 04:16:59: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
[runtime:verbose] 2019-08-11 04:17:02: Screen changed → MainMenu
[runtime:debug] 2019-08-11 04:17:04: MouseDownEvent(Left) handled by OsuLogo.
Console output is being limited. Please check runtime.log for full logs.
[runtime:verbose] 2019-08-11 04:17:04: ButtonSystem's state changed from Initial to TopLevel
[runtime:verbose] 2019-08-11 04:17:07: ButtonSystem's state changed from TopLevel to Play
[runtime:debug] 2019-08-11 04:17:07: ClickEvent(Left) handled by Button.
[runtime:debug] 2019-08-11 04:17:07: MouseClick handled by Button.
[runtime:verbose] 2019-08-11 04:17:08: ButtonSystem's state changed from Play to EnteringMode
[runtime:verbose] 2019-08-11 04:17:08: Screen changed → PlaySongSelect
[runtime:debug] 2019-08-11 04:17:08: ClickEvent(Left) handled by Button.
[runtime:debug] 2019-08-11 04:17:08: MouseClick handled by Button.
[performance:verbose] 2019-08-11 04:17:08: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
[performance:verbose] 2019-08-11 04:17:08: Texture requested (1366x768) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
[performance:verbose] 2019-08-11 04:17:08: TextureAtlas size exceeded 3 time(s); generating new texture (1024x1024)
[runtime:debug] 2019-08-11 04:17:08: Focus changed from nothing to SearchTextBox.
[runtime:verbose] 2019-08-11 04:17:08: updating selection with beatmap:30 ruleset:0
[runtime:verbose] 2019-08-11 04:17:08: beatmap changed from "nekodex - circles! (peppy) []" to "nekodex - circles! (pishifat) [easy!]"
[runtime:verbose] 2019-08-11 04:17:08: working beatmap updated to nekodex - circles! (pishifat) [easy!]
[runtime:debug] 2019-08-11 04:17:08: Loaded SettingsOverlay!
[runtime:debug] 2019-08-11 04:17:08: Loading ChangelogOverlay...
[performance:verbose] 2019-08-11 04:17:09: Texture requested (1400x310) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
[performance:verbose] 2019-08-11 04:17:09: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
[runtime:debug] 2019-08-11 04:17:09: Loaded ChangelogOverlay!
[runtime:debug] 2019-08-11 04:17:09: Loading UserProfileOverlay...
[runtime:debug] 2019-08-11 04:17:09: Loaded UserProfileOverlay!
[runtime:debug] 2019-08-11 04:17:09: Loading BeatmapSetOverlay...
[runtime:debug] 2019-08-11 04:17:09: Loaded BeatmapSetOverlay!
[runtime:debug] 2019-08-11 04:17:09: Loading LoginOverlay...
[runtime:debug] 2019-08-11 04:17:09: Loaded LoginOverlay!
[runtime:debug] 2019-08-11 04:17:09: Loading MusicController...
[performance:verbose] 2019-08-11 04:17:10: Texture requested (1366x768) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
[runtime:debug] 2019-08-11 04:17:10: Loaded MusicController!
[runtime:debug] 2019-08-11 04:17:10: Loading AccountCreationOverlay...
[runtime:debug] 2019-08-11 04:17:10: Loaded AccountCreationOverlay!
[runtime:debug] 2019-08-11 04:17:10: Loading DialogOverlay...
[runtime:debug] 2019-08-11 04:17:10: Loaded DialogOverlay!
[runtime:debug] 2019-08-11 04:17:10: Loading ExternalLinkOpener...
[runtime:debug] 2019-08-11 04:17:10: Loaded ExternalLinkOpener!
[runtime:debug] 2019-08-11 04:17:10: Focus changed from SearchTextBox to nothing.
[runtime:verbose] 2019-08-11 04:17:10: Screen changed ← MainMenu
[runtime:debug] 2019-08-11 04:17:10: Pressed (Back) handled by BackButton.
[runtime:debug] 2019-08-11 04:17:10: KeyDownEvent(Escape, False) handled by GlobalActionContainer.
[runtime:verbose] 2019-08-11 04:17:11: ButtonSystem's state changed from EnteringMode to TopLevel
[runtime:verbose] 2019-08-11 04:17:12: ButtonSystem's state changed from TopLevel to EnteringMode
[runtime:verbose] 2019-08-11 04:17:12: Screen changed → Editor
[runtime:debug] 2019-08-11 04:17:12: ClickEvent(Left) handled by Button.
[runtime:debug] 2019-08-11 04:17:12: MouseClick handled by Button.
[runtime:debug] 2019-08-11 04:17:14: ClickEvent(Left) handled by IconButton.
[runtime:debug] 2019-08-11 04:17:14: MouseClick handled by IconButton.
[runtime:debug] 2019-08-11 04:17:15: ClickEvent(Left) handled by PlaybackControl+PlaybackTabControl+PlaybackTabItem value: 1.
[runtime:debug] 2019-08-11 04:17:15: MouseClick handled by PlaybackControl+PlaybackTabControl+PlaybackTabItem value: 1.
[runtime:verbose] 2019-08-11 04:17:17: Unhandled exception has been denied .

Unhandled Exception: System.ArgumentOutOfRangeException: Positive number required.
Parameter name: bytesAllocated
   at System.GC.AddMemoryPressure(Int64 bytesAllocated)
   at osu.Framework.Platform.NativeMemoryTracker.AddMemory(Object source, Int64 amount) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\NativeMemoryTracker.cs:line 27
   at osu.Framework.Graphics.OpenGL.Buffers.RenderBuffer.set_Size(Vector2 value) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\RenderBuffer.cs:line 66
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.initialise() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 73
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.Bind() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 86
   at osu.Framework.Graphics.BufferedDrawNode.BindFrameBuffer(FrameBuffer frameBuffer) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\BufferedDrawNode.cs:line 141
   at osu.Framework.Graphics.BufferedDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\BufferedDrawNode.cs:line 87
   at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawable_DrawNode.cs:line 198
   at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawable_DrawNode.cs:line 198
   at osu.Framework.Platform.GameHost.DrawFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 367
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 140
   at osu.Framework.Threading.GameThread.runWork() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 321
   at osu.Framework.Threading.Scheduler.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 160
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 136
   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 553
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 556
   at osu.Desktop.Program.Main(String[] args) in /Users/stephenogden/Documents/GitHub/osu/osu.Desktop/Program.cs:line 56
[runtime:error] 2019-08-11 04:17:17: An unhandled error has occurred.
[runtime:error] 2019-08-11 04:17:17: System.ArgumentOutOfRangeException: Positive number required.
[runtime:error] 2019-08-11 04:17:17: Parameter name: bytesAllocated
[runtime:error] 2019-08-11 04:17:17: at System.GC.AddMemoryPressure(Int64 bytesAllocated)
[runtime:error] 2019-08-11 04:17:17: at osu.Framework.Platform.NativeMemoryTracker.AddMemory(Object source, Int64 amount) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\NativeMemoryTracker.cs:line 27
[runtime:error] 2019-08-11 04:17:17: at osu.Framework.Graphics.OpenGL.Buffers.RenderBuffer.set_Size(Vector2 value) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\RenderBuffer.cs:line 66
[runtime:error] 2019-08-11 04:17:17: at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.initialise() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 73
[runtime:error] 2019-08-11 04:17:17: at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.Bind() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\FrameBuffer.cs:line 86
[runtime:error] 2019-08-11 04:17:17: at osu.Framework.Graphics.BufferedDrawNode.BindFrameBuffer(FrameBuffer frameBuffer) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\BufferedDrawNode.cs:line 141
```

**Comment by smoogipoo** [comment]
Thanks. It's an issue I'm aware of and have a fix for but not PRd yet.
