### ISSUE TITLE
Hard crash when changing skin during gameplay

### ISSUE THREAD

**Issue by peppy** [ppy/osu#6152]
```
Unhandled Exception: [runtime:error] 2019-09-18 11:21:22: An unhandled error has occurred.
[runtime:error] 2019-09-18 11:21:22: System.ObjectDisposedException: Can not play disposed samples.
[runtime:error] 2019-09-18 11:21:22: Object name: 'osu.Framework.Audio.Sample.SampleChannelBass'.
[runtime:error] 2019-09-18 11:21:22: at osu.Framework.Audio.Sample.SampleChannel.Play(Boolean restart) in C:\projects\osu-framework-a4n7e\osu.Framework\Audio\Sample\SampleChannel.cs:line 26
[runtime:error] 2019-09-18 11:21:22: at osu.Game.Skinning.SkinnableSound.<>c.<Play>b__11_0(SampleChannel c) in /Users/dean/Projects/osu/osu.Game/Skinning/SkinnableSound.cs:line 57
[runtime:error] 2019-09-18 11:21:22: at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action) in C:\projects\osu-framework-a4n7e\osu.Framework\Extensions\IEnumerableExtensions\EnumerableExtensions.cs:line 22
[runtime:error] 2019-09-18 11:21:22: at osu.Game.Skinning.SkinnableSound.Play() in /Users/dean/Projects/osu/osu.Game/Skinning/SkinnableSound.cs:line 57
[runtime:error] 2019-09-18 11:21:22: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.PlaySamples() in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 272
[runtime:error] 2019-09-18 11:21:22: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.updateState(ArmedState newState, Boolean force) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 188
```

**Comment by HoLLy-HaCKeR** [comment]
Related to #5798?

**Comment by peppy** [comment]
Duplicate, well spotted.
