### ISSUE TITLE
Song selection fails to load when offline

### ISSUE THREAD

**Issue by ghost** [ppy/osu#6533]
I have an iPhone 7, and I've come across a bug that when you're offline, the beatmap select screen will load, then will freeze when you select a new difficulty. If you exit out and go back in, it doesn't load the beatmap select at all. This only happens when you're off WiFi.

Here are some screenshots:
[beatmap select not recognizing difficulty](https://imgur.com/yup44yO) 
[beatmap select failing to load](https://imgur.com/Muut9wy)

[screen recording](https://imgur.com/jcEnidF)

osu!lazer version: 2019.1011.0

**Comment by swoolcock** [comment]
Sounds very odd, some extra info if you could:

1) What version of iOS?
2) Are you able to upload a screen recording?
3) Is it 100% repeatable?
4) Is it completely frozen in that second screenshot?

**Comment by trillyon** [comment]
1. 13.1, I think
2. Yes, here you go - [link](https://imgur.com/yup44yO)
3. I do not think it's repeatable on some devices
4. Sometimes the game will crash, but not 100% of the time.
5. Yes.

**Comment by bdach** [comment]
> 2. Yes, here you go - [link](https://imgur.com/yup44yO)

I don't know if by accident or not, but you've posted the *image* from the issue body again - we'd appreciate a *video* demonstrating the issue, if at all possible.

**Comment by trillyon** [comment]
[i have way too many github and imgur tabs open](https://imgur.com/jcEnidF)

**Comment by dscnnctd** [comment]
Managed to reproduce this on the same device. However, I can’t manage to reproduce this offline and then I managed to do it online instead.

**Comment by smoogipoo** [comment]
This is not an iOS specific issue, can be triggered the same way by signing out / faking 100% network drops.

**Comment by smoogipoo** [comment]
Related:

```

Unhandled exception. System.ObjectDisposedException: Attempting to load an already disposed drawable.
Object name: 'PlaySongSelect'.
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](IEnumerable`1 components, IReadOnlyDependencyContainer dependencies)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass16_2`1.<LoadComponentsAsync>b__3()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Drawab[runtime:error] 2019-10-18 11:17:31: An unhandled error has occurred.
le.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Cont[runtime:error] 2019-10-18 11:17:31: System.ObjectDisposedException: Attempting to load an already disposed drawable.
ainers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass92_0.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>)
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /Users/smoogipoo/Repos/osu/osu.Desktop/Program.cs:line 56[runtime:error] 2019-10-18 11:17:31: Object name: 'PlaySongSelect'.

[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](IEnumerable`1 components, IReadOnlyDependencyContainer dependencies)
[runtime:error] 2019-10-18 11:17:31: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[runtime:error] 2019-10-18 11:17:31: --- End of stack trace from previous location where exception was thrown ---
[runtime:error] 2019-10-18 11:17:31: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[runtime:error] 2019-10-18 11:17:31: --- End of stack trace from previous location where exception was thrown ---
[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass16_2`1.<LoadComponentsAsync>b__3()
[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Threading.ScheduledDelegate.RunTask()
[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Threading.Scheduler.Update()
[runtime:error] 2019-10-18 11:17:31: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```
