### ISSUE TITLE
Lazer crash on ChromeOS

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6573]
**Describe the bug:** I installed Lazer on ChromeOS, and opened it, but it just opened and closed without so much as the warning on start up. It just opens, black screen for about 5 seconds, then crashes

**Screenshots or videos showing encountered issue:** (Unable to get a recording)

**osu!lazer version:** 2019.1021.0

**Logs:** The log files didn't exist when I went to go get them from the log folder.

**Comment by enoslayd** [comment]
So this means that osu will work on chrome os in the future?

**Comment by bdach** [comment]
As far as I'm aware users have already been running lazer on ChromeOS already in the past (either by manually compiling from source as on Linux, or by leveraging the Android compatibility layer with the APK), albeit by the virtue of being low-end devices Chromebooks are struggling to keep up performance-wise - but as time goes on we can hopefully address performance in general on all platforms.

**Comment by peppy** [comment]
Closing this due to lack of useful information provided. Please re-open if able to debug or find system logs.

**Comment by MeguMario** [comment]
```
04-17 11:14:43.013   557   972 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:899 android.content.ContextWrapper.startActivity:401 org.chromium.arc.applauncher.IntentLauncher.startActivityWithWindowInfo:117 org.chromium.arc.applauncher.AppLauncherService.launchIntent:1235 org.chromium.arc.applauncher.AppLauncherService.launchAppWithWindowInfo:1203
04-17 11:14:43.029   760  6932 D ArcMediaControllerManager: onTaskMovedToFront: 36                                                                                                                04-17 11:14:43.029   133  2107 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (has extras)} from uid 1000
04-17 11:14:43.029   133  2107 W ActivityManager: getValidLaunchStackOnDisplay: can't launch on displayId 0
04-17 11:14:43.029   557   557 D ArcAppTaskTracker: Calculating task stack diff.
04-17 11:14:43.031   133  2107 I ActivityManagerInjector: getResolvedRootLaunchBounds called with root activity {N-resizeable 0x0, AC, PropertyRecord{mVersion=3, mDisplayId=0, mBounds=Rect(0, 0 - 0, 0), mRestoreBounds=Rect(0, 0 - 0, 0), mWindowMode=1, mWasUserResized=false, mImmersive=false, mLastWindowStateInClamShell=-1, mWindowLayoutAffinity=null}}
04-17 11:14:43.031   133  2107 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:43.031   133  2107 E WindowManagerInjectorArc: setArcAttributeWindowSizeConstraints: cannot find task: 41
04-17 11:14:43.031   133  2107 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE                                                                 04-17 11:14:43.031   133  2107 I ActivityManagerInjectorArc: updateCaptionLocked: skipping activity that isn't fully started                                                                      04-17 11:14:43.033   133  2107 I ActivityManagerInjectorArc: notifyActivityAddedToTask: added to new task. activity=ActivityRecord{98af3e0 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity t41}
04-17 11:14:43.039   133   261 D DecorView[osulazer]: Cannot get the activity to get CaptionConfiguration.                                                                                        04-17 11:14:43.040   557   972 I ArcIntentLauncher: Activity launched for #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity;i.window_session_id=24;end
04-17 11:14:43.040   557   972 I ArcAppLauncherService: Activity launched for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (has extras) }.
04-17 11:14:43.059   557   557 D ArcAppTaskTracker: Task created: 41 - ComponentInfo{sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity} .                                                     04-17 11:14:43.060   760  6932 E ArcMediaControllerManager: Could not find task with id: 36
04-17 11:14:43.061   557   557 D ArcAppTaskTracker: Active task: 41.
04-17 11:14:43.034   133  2107 I ActivityManagerInjectorArc: notifyActivityAddedToTask: added to new task. activity=ActivityRecord{98af3e0 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity t41}
04-17 11:14:43.082   133  1048 E ActivityManager: applyOptionsLocked: Unknown animationType=0
04-17 11:14:43.098   133   222 I ActivityManager: Start proc 19273:sh.ppy.osulazer/u0a79 for activity sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity
04-17 11:14:43.102    14    14 D wayland-service: Creating app window for task_id 41 from package 'sh.ppy.osulazer'
04-17 11:14:43.102    14    14 I wayland-service: Set task 41 window type 1from package 'sh.ppy.osulazer
04-17 11:14:43.102    14    14 D wayland-service: ApplyBackgroundColor for task_id 41, color=-16777216                                                                                            04-17 11:14:43.106 19273 19273 E sh.ppy.osulaze: Not starting debugger since process cannot load the jdwp agent.
04-17 11:14:43.108   133  1048 D ActivityManagerInjectorArc: taskOcclusionChanged: taskId=36 does not support PIP                                                                                 04-17 11:14:43.115   133  1048 D ActivityManagerInjectorArc: taskOcclusionChanged: taskId=41 does not support PIP
04-17 11:14:43.149 19273 19273 E LoadedApk: Unable to instantiate appComponentFactory
04-17 11:14:43.149 19273 19273 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/sh.ppy.osulazer-gUdd-pAXJRkgoUm9qntEFg==/base.apk"],nativeLibraryDirectories=[/data/app/sh.ppy.osulazer-gUdd-pAXJRkgoUm9qntEFg==/lib/x86, /data/app/sh.ppy.osulazer-gUdd-pAXJRkgoUm9qntEFg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
04-17 11:14:43.149 19273 19273 E LoadedApk:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)                                                                      04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.LoadedApk.getResources(LoadedApk.java:1032)                                                                                        04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6008)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.ActivityThread.access$1100(ActivityThread.java:201)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.os.Looper.loop(Looper.java:193)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at android.app.ActivityThread.main(ActivityThread.java:6971)                                                                                      04-17 11:14:43.149 19273 19273 E LoadedApk:     at java.lang.reflect.Method.invoke(Native Method)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-17 11:14:43.149 19273 19273 E LoadedApk:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
04-17 11:14:43.185   557   557 D ArcAppTaskTracker: Calculating task stack diff.
04-17 11:14:43.185   557   557 D ArcAppTaskTracker: Active task: 41.
04-17 11:14:43.316 19273 19273 W monodroid-gc: GREF GC Threshold: 46080
04-17 11:14:43.726 19273 19273 D OpenGLRenderer: Skia GL Pipeline
04-17 11:14:43.749   133  1048 V ActivityManagerInjectorArc: canRequestFixedOrientation returns isRoot=true isPip=false
04-17 11:14:43.749   133  1048 I ActivityManagerInjectorArc: setRequestedOrientation: TaskRecordArc{TaskRecordArc{TaskRecord{a1c723c #41 A=sh.ppy.osulazer U=0 StackId=36 sz=1}, WindowState{fullscreen restore-bounds=Rect(0, 0 - 0, 0)}} , WindowState{fullscreen restore-bounds=Rect(0, 0 - 0, 0)}}  orientation: InvalidOrientation(13)
04-17 11:14:43.750    14    61 D wayland-service: Setting orientation lock to 0 for task_id 41.
04-17 11:14:43.751   133  1048 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:43.773   133  1048 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
04-17 11:14:43.785    14    61 D wayland-service: Wayland Remote Shell Workspace Info id=0 pos=0,0 size=1366x768 insets=0,0,0,0 stable_insets=0,0,0,48 transform=WL_OUTPUT_TRANSFORM_NORMAL is_internal=1                                                                                                                                                                                           04-17 11:14:43.785    14    61 D wayland-service: Wayland Remote Shell Configure primary_id=0 size=1366x768 mm=216x121 layout=ZCR_REMOTE_SHELL_V1_LAYOUT_MODE_WINDOWED metrics_changed=1
04-17 11:14:43.786    14    61 E wayland-service: Sending display metrics
04-17 11:14:43.787   133  1048 W WindowPositioner: WindowPositioner.applyPendingWorkspaceConfig WorkspaceConfig{0:Workspace{Rect(0, 0 - 1366, 768), insets=Insets{left=0, top=0, right=0, bottom=0}, stableInsets=Insets{left=0, top=0, right=0, bottom=48}, autoHide=true}, primaryDisplayId=0, layoutMode=windowed, transform=0}
04-17 11:14:43.787   133  1048 I ActivityManagerInjectorArc: onWorkspaceChanged. displayId: 0
04-17 11:14:43.787   133  1048 I ActivityManagerInjectorArc: onWorkspaceInsetsChanged. displayId: 0 insets: Insets{left=0, top=0, right=0, bottom=0}
04-17 11:14:43.787   133  1048 E ActivityManagerInjectorArc: getPipTaskOrRemovePinnedStackIfEmpty: Pinned stack doesn't exist
04-17 11:14:43.793   133  1048 V ActivityManagerInjector: applyWorkspaceConfig - done resizing & moving windows
04-17 11:14:43.804   133   220 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:43.855 19273 19273 D vndksupport: Loading /vendor/lib/hw/gralloc.cros.so from current namespace instead of sphal namespace.
04-17 11:14:43.867 19273 19273 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-17 11:14:43.868 19273 19273 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0                                                            04-17 11:14:43.878 19273 19273 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
04-17 11:14:43.878 19273 19273 D vndksupport: Loading /vendor/lib/hw/gralloc.cros.so from current namespace instead of sphal namespace.                                                           04-17 11:14:43.946 19273 19273 V AndroidGameView: Successfully created the framebuffer
04-17 11:14:44.033 19273 19273 F libc    : Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 19273 (sh.ppy.osulazer), pid 19273 (sh.ppy.osulazer)
04-17 11:14:44.069 19308 19308 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
04-17 11:14:44.070   130   130 I /system/bin/tombstoned: received crash request for pid 19273
04-17 11:14:44.070 19308 19308 I crash_dump32: performing dump of process 19273 (target tid = 19273)
04-17 11:14:44.074 19308 19308 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-17 11:14:44.074 19308 19308 F DEBUG   : Build fingerprint: 'google/rammus/rammus_cheets:9/R100-14526.84.0/8414072:user/release-keys'
04-17 11:14:44.074 19308 19308 F DEBUG   : Revision: '0'
04-17 11:14:44.074 19308 19308 F DEBUG   : ABI: 'x86'
04-17 11:14:44.074 19308 19308 F DEBUG   : pid: 19273, tid: 19273, name: sh.ppy.osulazer  >>> sh.ppy.osulazer <<<                                                                                 04-17 11:14:44.074 19308 19308 F DEBUG   : signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
04-17 11:14:44.074 19308 19308 F DEBUG   :     eax 4e9b8956  ebx d1b20b58  ecx ffc444b4  edx c0991000
04-17 11:14:44.075 19308 19308 F DEBUG   :     edi f3568d9c  esi c0991000
04-17 11:14:44.075 19308 19308 F DEBUG   :     ebp 00000017  esp ffc4419c  eip d17e312d
04-17 11:14:44.075 19308 19308 F DEBUG   :
04-17 11:14:44.075 19308 19308 F DEBUG   : backtrace:
04-17 11:14:44.075 19308 19308 F DEBUG   :     #00 pc 0006212d  /data/app/sh.ppy.osulazer-gUdd-pAXJRkgoUm9qntEFg==/lib/x86/libmonosgen-2.0.so (mono_spill_global_vars+61)
04-17 11:14:43.807   133   220 I chatty  : uid=1000(system) ActivityManager identical 1 line
04-17 11:14:43.810   133   220 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:44.250   133   220 I OrientationSynchronizer: Setting rotation is timed out
04-17 11:14:44.258   130   130 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_04                                                                                      04-17 11:14:44.270   133 19311 W ActivityManager:   Force finishing activity sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity
04-17 11:14:44.276   133 19311 E TaskRecordArc: updateSnapshotVisibility: no activity in task record 41
04-17 11:14:44.278   133   220 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
04-17 11:14:44.278   133   220 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver                                                                                                                                  04-17 11:14:44.291    14    61 D wayland-service: Wayland Remote Shell Workspace Info id=0 pos=0,0 size=1366x768 insets=0,0,0,48 stable_insets=0,0,0,48 transform=WL_OUTPUT_TRANSFORM_NORMAL is_internal=1                                                                                                                                                                                          04-17 11:14:44.291    14    61 D wayland-service: Wayland Remote Shell Configure primary_id=0 size=1366x768 mm=216x121 layout=ZCR_REMOTE_SHELL_V1_LAYOUT_MODE_WINDOWED metrics_changed=1          04-17 11:14:44.292    14    61 E wayland-service: Sending display metrics                                                                                                                         04-17 11:14:44.295   133  2492 E ActivityManagerInjectorArc: taskOcclusionChanged: taskId not found:41
04-17 11:14:44.295   133  2492 W WindowPositioner: WindowPositioner.applyPendingWorkspaceConfig WorkspaceConfig{0:Workspace{Rect(0, 0 - 1366, 768), insets=Insets{left=0, top=0, right=0, bottom=48}, stableInsets=Insets{left=0, top=0, right=0, bottom=48}, autoHide=false}, primaryDisplayId=0, layoutMode=windowed, transform=0}
04-17 11:14:44.295   133  2492 I ActivityManagerInjectorArc: onWorkspaceChanged. displayId: 0                                                                                                     04-17 11:14:44.295   133  2492 I ActivityManagerInjectorArc: onWorkspaceInsetsChanged. displayId: 0 insets: Insets{left=0, top=0, right=0, bottom=48}
04-17 11:14:44.295   133  2492 E ActivityManagerInjectorArc: getPipTaskOrRemovePinnedStackIfEmpty: Pinned stack doesn't exist                                                                     04-17 11:14:44.309   133  2492 V ActivityManagerInjector: applyWorkspaceConfig - done resizing & moving windows
04-17 11:14:44.310   650 19313 I ArcCrashDumpStreamer: Streamed 214 B for data_app_native_crash dump.
04-17 11:14:44.315   133   220 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:44.371   557   557 D ArcAppTaskTracker: Calculating task stack diff.
04-17 11:14:44.372   557   557 D ArcAppTaskTracker: Task destroyed: 41 .
04-17 11:14:44.372   557   557 D ArcAppTaskTracker: Active task: 36.                                                                                                                              04-17 11:14:44.393   815   815 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.udc.service.START dat=chimera-action:com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
04-17 11:14:44.393   815   815 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.udc.service.START dat=chimera-action:com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
04-17 11:14:44.405   133   288 W InputDispatcher: channel '24eaf41 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-17 11:14:44.405   133   288 E InputDispatcher: channel '24eaf41 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-17 11:14:44.412   133   296 E ArcGfxMetrics: Failed to find pattern in output: 95th percentile: (\d+)ms.
04-17 11:14:44.318   133   220 V WindowPositioner: getFinalOrientation: task workspace configuration=SCREEN_ORIENTATION_LANDSCAPE
04-17 11:14:44.415   133   216 I ActivityManager: Process sh.ppy.osulazer (pid 19273) has died: vis  +99TOP
04-17 11:14:44.415   133   216 E TaskRecordArc: updateSnapshotVisibility: no activity in task record 41
04-17 11:14:44.417   133  1047 I WindowManager: WIN DEATH: Window{24eaf41 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity}
04-17 11:14:44.417   133  1047 W InputDispatcher: Attempted to unregister already unregistered input channel '24eaf41 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)'
04-17 11:14:44.418   109   109 I Zygote  : Process 19273 exited due to signal (11)
04-17 11:14:44.418   109   109 I Zygote  : Process 19273 dumped core.
04-17 11:14:44.419   133   223 W libprocessgroup: kill(-19273, 9) failed: No such process
04-17 11:14:44.419   133   223 I libprocessgroup: Successfully killed process cgroup uid 10079 pid 19273 in 0ms
04-17 11:14:44.425    14  2599 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen sh.ppy.osulazer#0
04-17 11:14:44.425    14  2599 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen sh.ppy.osulazer#0
04-17 11:14:44.427   133   261 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5618 com.android.server.wm.WindowManagerService.removeWindow:1665 com.android.server.wm.Session.remove:228
04-17 11:14:44.427   133   216 W ActivityManagerInjectorArc: anyTaskForIdLocked: no task state id = 41
04-17 11:14:44.427   133   216 W ActivityManagerInjectorArc: anyTaskForIdLocked: no task state id = 41
04-17 11:14:44.427   133   216 E ActivityManagerInjectorArc: taskDragFinished: taskId=41 has invalid operation
04-17 11:14:44.427    14    61 W wayland-service: Notified that task_id 41 was destroyed, but it is not known to us.
04-17 11:14:44.441   133   229 W ActivityManager: setHasOverlayUi called on unknown pid: 19273
04-17 11:14:44.460   133  2690 D ActivityManagerInjectorArc: taskOcclusionChanged: taskId=36 does not support PIP
04-17 11:14:45.361   815   815 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.libs.gmscorelogger.service.START dat=chimera-action:com.google.android.gms.libs.gmscorelogger.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
```
It's a few years late, I don't know if there're any interest in getting the Android build of Lazer to work on Chrome OS's Android container, but still here's the system log. Hope it's helpful somehow

Note that this was running on the older Arc++ instead of the new Arcvm (which share the same method with the Linux's container), and this installation of Chrome OS is a custom built image using Brunch to run the OS on other computer, it may have some difference compare to the official device, but it should be close enough to represent the real deal
