### ISSUE TITLE
Cancelling loading of beatmap w/ storyboard crashes the game

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#6821]
**Describe the crash:** As the title states. The following action reproduces the issue on my box:

1. On screen `PlaySongSelect`, load a beatmap with a storyboard.
2. Immediately cancel the process.

The cancelling action would result in an unhandled `System.OperationCancelledException`, causing the (possible) crash.

**osu!lazer version:** Debug build of commit `574de39`

**Logs:**
The note from Visual Studio Code upon crash:
```
An exception of type 'System.OperationCanceledException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The operation was canceled.'
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at osu.Game.Storyboards.Drawables.DrawableStoryboardLayer.load(Nullable`1 cancellationToken) in /home/mcendu/Documents/osu/osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs:line 32
```
Stack of the crashing thread at point of crash on two runs:
```
[外部代码] (Unknown Source:0)
osu.Game.dll!osu.Game.Storyboards.Drawables.DrawableStoryboardLayer.load(System.Threading.CancellationToken? cancellationToken) 行 32 (/home/mcendu/Documents/osu/osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs:32)
[外部代码] (Unknown Source:0)
osu.Game.dll!osu.Game.Storyboards.Drawables.DrawableStoryboard.load(osu.Game.IO.FileStore fileStore, osu.Game.Screens.Play.GameplayClock clock, System.Threading.CancellationToken? cancellationToken) 行 72 (/home/mcendu/Documents/osu/osu.Game/Storyboards/Drawables/DrawableStoryboard.cs:72)
[外部代码] (Unknown Source:0)
osu.Game.dll!osu.Game.Screens.Play.DimmableStoryboard.initializeStoryboard(bool async) 行 52 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/DimmableStoryboard.cs:52)
osu.Game.dll!osu.Game.Screens.Play.DimmableStoryboard.load() 行 27 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/DimmableStoryboard.cs:27)
[外部代码] (Unknown Source:0)
osu.Game.dll!osu.Game.Screens.Play.Player.addUnderlayComponents(osu.Framework.Graphics.Containers.Container target) 行 154 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/Player.cs:154)
osu.Game.dll!osu.Game.Screens.Play.Player.load(osu.Framework.Audio.AudioManager audio, osu.Game.Online.API.IAPIProvider api, osu.Game.Configuration.OsuConfigManager config) 行 134 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/Player.cs:134)
[外部代码] (Unknown Source:0)
```
```
[External Code] (Unknown Source:0)
osu.Game.dll!osu.Game.Storyboards.Drawables.DrawableStoryboardLayer.load(System.Threading.CancellationToken? cancellationToken) Line 32 (/home/mcendu/Documents/osu/osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs:32)
[External Code] (Unknown Source:0)
osu.Game.dll!osu.Game.Storyboards.Drawables.DrawableStoryboard.load(osu.Game.IO.FileStore fileStore, osu.Game.Screens.Play.GameplayClock clock, System.Threading.CancellationToken? cancellationToken) Line 72 (/home/mcendu/Documents/osu/osu.Game/Storyboards/Drawables/DrawableStoryboard.cs:72)
[External Code] (Unknown Source:0)
osu.Game.dll!osu.Game.Screens.Play.DimmableStoryboard.initializeStoryboard(bool async) Line 52 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/DimmableStoryboard.cs:52)
osu.Game.dll!osu.Game.Screens.Play.DimmableStoryboard.load() Line 27 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/DimmableStoryboard.cs:27)
[External Code] (Unknown Source:0)
osu.Game.dll!osu.Game.Screens.Play.Player.addUnderlayComponents(osu.Framework.Graphics.Containers.Container target) Line 154 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/Player.cs:154)
osu.Game.dll!osu.Game.Screens.Play.Player.load(osu.Framework.Audio.AudioManager audio, osu.Game.Online.API.IAPIProvider api, osu.Game.Configuration.OsuConfigManager config) Line 134 (/home/mcendu/Documents/osu/osu.Game/Screens/Play/Player.cs:134)
[External Code] (Unknown Source:0)
```
**Computer Specifications:** .NET Core 3.0 on Ubuntu Eoan; Game launched from Visual Studio Code

**Comment by peppy** [comment]
I can't reproduce this. Could you try launching without a debugger?
