### ISSUE TITLE
When i try to open the game it just crash

### ISSUE THREAD

**Issue by PolloBollo** [ppy/osu#6948]
**Describe the crash:** 
When i click in the icon, it shows a black screen and then it closes without any message or anything

**Screenshots or videos showing encountered issue:** 
Not Needed

**osu!lazer version:** 
201911220

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3883755/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3883756/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3883757/updater.log)
[database.log](https://github.com/ppy/osu/files/3883758/database.log)

**Computer Specifications:** 
Intel HD Graphics 6000, i5.5350U, 64 bits, 8 GB ram

**Comment by bdach** [comment]
Seemingly relevant stack trace:
```
2019-11-24 03:31:08: An unhandled error has occurred.
2019-11-24 03:31:08: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'button')
2019-11-24 03:31:08: at osuTK.Input.JoystickState.SetButton(Int32 button, Boolean value)
2019-11-24 03:31:08: at osuTK.Platform.Windows.WinRawJoystick.QueryDeviceCaps(Device stick)
2019-11-24 03:31:08: at osuTK.Platform.Windows.WinRawJoystick.RefreshDevices()
2019-11-24 03:31:08: at osuTK.Platform.Windows.WinRawJoystick..ctor(IntPtr window)
2019-11-24 03:31:08: at osuTK.Platform.Windows.WinRawInput.CreateDrivers()
2019-11-24 03:31:08: at osuTK.Platform.Windows.WinInputBase.ProcessEvents()
2019-11-24 03:31:08: at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
2019-11-24 03:31:08: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-11-24 03:31:08: --- End of stack trace from previous location where exception was thrown ---
2019-11-24 03:31:08: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-11-24 03:31:08: at System.Threading.ThreadHelper.ThreadStart()
```
What input devices are you using? I'd be especially interested in any gamepads/tablets with buttons/similar devices. Is this crash consistent?

**Comment by peppy** [comment]
Long standing bug which should be a quick fix at osuTK (https://github.com/ppy/osu-framework/issues/2272)
