### ISSUE TITLE
Subsequent logs..? (Linux on ChromeOS)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#7062]
**Describe the bug:** I don't really know how to describe this one. Idk if it's compatibility, or something else. Just when I open Lazer, I got 4 notifications as pictured in the screenshot I attached. I closed it, then went to open osu!direct, and the same 4 notifications popped up again. I didn't even try gameplay, so idk what these notifications affect.

**Screenshots or videos showing encountered issue:** 
![Screenshot 2019-12-04 at 11 06 49](https://user-images.githubusercontent.com/50627538/70159646-3ee7dc00-1687-11ea-973a-47050fb37e6a.png)

**osu!lazer version:** 2019.1128.0

**Logs:** 
[Archive.zip](https://github.com/ppy/osu/files/3922844/Archive.zip)

**Comment by X4X5** [comment]
Correction (since I used `git pull` before opening Lazer): The version is 2019.1204.0

**Comment by bdach** [comment]
Looks like there might be some issues with the newly added StbiSharp library:

```
2019-12-04 04:06:19: Texture could not be loaded via STB; falling back to ImageSharp.
2019-12-04 04:06:19: System.DllNotFoundException: Unable to load shared library 'stbi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libstbi: cannot open shared object file: No such file or directory
2019-12-04 04:06:19: at StbiSharp.Stbi.LoadFromMemory(Byte* data, Int64 len, Int32& width, Int32& height, Int32& numChannels, Int32 desiredNumChannels)
2019-12-04 04:06:19: at StbiSharp.Stbi.LoadFromMemory(ReadOnlySpan`1 data, Int32 desiredNumChannels)
2019-12-04 04:06:19: at StbiSharp.Stbi.LoadFromMemory(MemoryStream data, Int32 desiredNumChannels)
2019-12-04 04:06:19: at osu.Framework.Graphics.Textures.TextureUpload.LoadFromStream[TPixel](Stream stream)
```

Please run lazer with `LD_DEBUG=libs` or even `LD_DEBUG=all` (warning: will spew a lot of output) set and attach the command line output here. Output of `lscpu` could also be helpful.

I'm assuming this is on a chromebook?

**Comment by X4X5** [comment]
Yes. That's what I mean when I say "ChromeOS"

**Comment by X4X5** [comment]
https://docs.google.com/document/d/10bCLJWwvvjo4kxDqpeS_tDA34umMLk3rrXgLim-hNAY/edit?usp=sharing

It kinda lagged the Chromebook getting the entire printout, so idk if parts of it repeated when I copy pasted it into Google Docs.

**Comment by bdach** [comment]
Seemingly relevant part:
```
      1888:     find library=stbi.so [0]; searching
      1888:      search cache=/etc/ld.so.cache
      1888:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)
      1888:       trying file=/lib/x86_64-linux-gnu/stbi.so
      1888:       trying file=/usr/lib/x86_64-linux-gnu/stbi.so
      1888:       trying file=/lib/stbi.so
      1888:       trying file=/usr/lib/stbi.so
      1888:
      1888:     /lib/x86_64-linux-gnu/libm.so.6: error: version lookup error: version `GLIBC_2.27' not found (required by /home/jjharbin2022/osu/osu.Desktop/bin/Debug/netcoreapp3.0/runtimes/linux-x64/native/libstbi.so) (fatal)
```
Looks like the runtimes packaged in the `StbiSharp` nuget were linked against glibc 2.27 which is newer than the version on your system. What you could try doing is updating glibc:
```
$ sudo apt-get update
$ sudo apt-get install libc6
```
and seeing if this makes the errors go away.

Up in the air if we want to lower the glibc version used to link runtimes against - @Tom94, any thoughts? 2.27's release date was 2018-02-01 ([source](https://sourceware.org/glibc/wiki/Glibc%20Timeline)), we might want to drop that down a few versions if possible and deemed necessary.

**Comment by X4X5** [comment]
So... I got this line when I did that.

`libc6 is already the newest version (2.24-11+deb9u4).`

**Comment by bdach** [comment]
It means that your distribution version's package lists don't have a glibc version above 2.24. This confirms that the version is the root cause here, however when it comes to the resolution you might not be able to do anything on your side, since glibc is kind of tied to the kernel itself and it's very unlikely you'll be able to upgrade the existing version any higher.

You *might* be able to install a newer glibc *alongside* the system one and then point lazer at it using `LD_LIBRARY_PATH`, but since I haven't ever tried doing anything like that it might not work.

**Comment by X4X5** [comment]
I'm also running Linux on a Chromebook, so I wonder if it has anything to do with the fact that I'm running a virtual machine, and not running it on an actual Linux computer

**Comment by bdach** [comment]
I imagine this'll happen on any Linux distro old enough to be stuck with a <2.27 glibc version with no way to update - not that I checked, however.

**Comment by X4X5** [comment]
Is this something that can be debugged with something like VS Code, or is this something entirely different?

**Comment by peppy** [comment]
cc @Tom94 for visibility

**Comment by Tom94** [comment]
I see no downside to linking to an older glibc version as long as it's still binary-compatible with the latest. I'll check for that soonish.

**Comment by Tom94** [comment]
We probably want a static variable tracking when loading fails due to a missing shared library such that it's not attempted for every single image load.

**Comment by peppy** [comment]
Will only fail once now, thanks to https://github.com/ppy/osu-framework/pull/3079.

Underlying linking issue still need addressing.

**Comment by X4X5** [comment]
So this will be fixed once that framework pull request has been merged?

**Comment by smoogipoo** [comment]
Read the above comment again.

**Comment by Jordan-Jay** [comment]
Remove platform:linux tag as it's not specific to Linux just Chrome OS as it doesn't have an up to date glibc for the game. Other than that maybe making a separate build for Chrome OS which just has a lower version dependency for glibc which aligns with their kernel glibc update schedule?

**Comment by bdach** [comment]
> Remove platform:linux tag as it's not specific to Linux just Chrome OS as it doesn't have an up to date glibc for the game. 

Incorrect. This could happen on any linux distro with a mismatching glibc.

> Other than that maybe making a separate build for Chrome OS which just has a lower version dependency for glibc which aligns with their kernel glibc update schedule?

Not happening. The burden of support doing that would place on us is too large considering the number of users affected by this. Already having issues keeping up with mobile as is.

**Comment by Jordan-Jay** [comment]
> > Remove platform:linux tag as it's not specific to Linux just Chrome OS as it doesn't have an up to date glibc for the game.
> 
> Incorrect. This could happen on any linux distro with a mismatching glibc.
> 
> > Other than that maybe making a separate build for Chrome OS which just has a lower version dependency for glibc which aligns with their kernel glibc update schedule?
> 
> Not happening. The burden of support doing that would place on us is too large considering the number of users affected by this. Already having issues keeping up with mobile as is.

Oh yeah good catch. Re-reading it again i just noticed that Tom94 already found a fix for this anyway ;P
