### ISSUE TITLE
Unable to launch on aarch64 (arm) linux

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu#7166]
**Describe the bug:** 
Attempt to launch om aarch64 ubuntu linux does not succeed. What have failed:

- osu failed to load acodec-related libraries, as my distribution does not have `libavformat.so` (and others) symlinked to actual library, only `libavcodec.so.58` is symlinked (for a concrete ABI version). Adding symlinks fixes the issue
- after adding symlinks to avcodec-related libraries errors on video decoding appeared in the log (shown below)
- osu failed to load libsbi.so (probably due to lack of version compiled for aarch64)
- osu stalled while loading with 100% cpu load. As `runtime.log` stops at `Loading SocialOverlay...`, I guess that it does cause the issue

**Screenshots or videos showing encountered issue:** 

osu! stalls in this state:
![Screenshot from 2019-12-12 03-53-30](https://user-images.githubusercontent.com/10363282/70673622-35b4cb80-1c94-11ea-8431-2eb85c18fb21.png)

**osu!lazer version:** 

`2019.1205.0`

**Logs:** 

Video decoding errors:
```[runtime:verbose] 2019-12-12 12:53:18: VideoDecoder faulted: System.Exception: Error -1094995529 opening file or stream.
[runtime:verbose] 2019-12-12 12:53:18: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding()
[runtime:verbose] 2019-12-12 12:53:18: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding()
```

[runtime.log](https://github.com/ppy/osu/files/3953315/runtime.log)

**Comment by enoslayd** [comment]
Do you have system-wide ffmpeg installed?

**Comment by smoogipoo** [comment]
> osu failed to load libsbi.so (probably due to lack of version compiled for aarch64)

does this cause a crash for you?

**Comment by mcendu** [comment]
AArch64 is not a typo. The name is used to refer to 64-bit ARM CPUs.

**Comment by peppy** [comment]
Oh. That makes it a bit more obvious why it's crashing. We have not even considered support for that platform.

**Comment by DCNick3** [comment]
> Do you have system-wide ffmpeg installed?

Yes

> does this cause a crash for you?

No, it does not crash. It's just one of (obvious) errors found in logs. What happens is that osu! stalls at black screen with "development build" text at the bottom, eating 100% of one cpu core.

 I don't know what causes it, but, as it looks like from #7062, inability to find libstbi.so, which is a native part of StbiSharp, is not fatal. 

Most probably the problem is inside `Loading SocialOverlay...`, as it is the last thing you can see in log.

**Comment by bdach** [comment]
Does the game run if you switch from `IntroSequence = Triangles` to `IntroSequence = Circles` in `~/.local/share/osu/game.ini`?

If not this is likely that stall requires debugging with the actual hardware. We could try to get a trace from you since apparently there are ways to do so on .NET Core 3.0, but it might be easier if you just profiled on your own (if you can, that is).

**Comment by DCNick3** [comment]
Will check it after several days, thank you.

About the profiling thing - what is the idea? Should I just slap some breakpoints and see what works and what does not? Or should I check the `dotnet trace`?

**Comment by bdach** [comment]
From what I understand what you do is `dotnet trace collect -p [PID]` (see [random unchecked source](https://michaelscodingspot.com/dotnet-trace/)). Unfortunately there doesn't seem to be a way to start collecting a trace when the process spawns, so you're going to have to be quick on the draw or get a script going probably.

**Comment by DCNick3** [comment]
>Does the game run if you switch from IntroSequence = Triangles to IntroSequence = Circles in ~/.local/share/osu/game.ini?

The funny thing is that the `game.ini` is not even created, so looks like the startup fails earlier.

**Comment by DCNick3** [comment]
I've done it and, after spending some time, I can say that there probably is an audio thread lockup happening in `osu.Framework.Audio.Track.TrackBass.StartAsync`, inside the lambda, that goes into external code (that is, libbass):

![Screenshot_20191220_033100](https://user-images.githubusercontent.com/10363282/71220315-27406280-22d9-11ea-9867-613bb81fd532.png)

To further confirm it I would need to do some patched to `osu.Framework`. How could one do so and link osu! against that patched framework?

Also, I'm attaching a trace in case someone wants to dig deeper: [trace.nettrace.zip](https://github.com/ppy/osu/files/3986149/trace.nettrace.zip)

**Comment by LanTenDragon** [comment]
@DCNick3 See the framework's wiki  https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects

**Comment by DCNick3** [comment]
Thanks, will continue to investigate

**Comment by DCNick3** [comment]
By adding logging calls, I've found that the control goes to `Bass.ChannelPlay` in `osu.Framework.Audio.Track.TrackBass.startInternal` and never returns. So, this is where the lockup happens. Don't really know what should I do with it next...

**Comment by peppy** [comment]
You'd probably want to start by finding and adding the correct bass library files for your platform.

**Comment by DCNick3** [comment]
Well, I have done it at the beginning, getting them from https://www.un4seen.com/forum/?topic=13804.0

The thing is that the library does work to some extent (the linking is done fine). Also the "circles" sound is played too, but the `ChannelPlay` routine never returns (previous calls are executed successfully). I think this might be a problem with ABI, but I'm not entirely sure, as I would expect a crash or some "junk" values as a return value...

**Comment by HopeBaron** [comment]
I can confirm the same issue on my machine  with arch64 but I fixed this by changing the audio source to Pulse Audio Server which I use for my setup. Thought it's worth mentioning

**Comment by squidink7** [comment]
Sorry to necro-bump (if that's even a thing here), but I just attempted to build osu! on my Raspberry Pi 4, and thought I'd leave some notes for anyone else who wanted to undertake this challenge. Since the other comments in this issue, osu! switched to realm as the database, which requires a native `librealm-wrappers.so` library. This doesn't come built for arm64 by default, and I had to build the [realm-dotnet](https://github.com/realm/realm-dotnet) repository from source in order to get it to work. Unfortunately for whatever reason, arch Linux's version of OpenSSL didn't contain the files necessary for this to build, and that library didn't contain a prebuilt version of it to automatically download like it does x64. To avoid myself the pain of having to compile a library for compiling library for compiling this game, I just grabbed the Debian package and added the necessary files. After I got it all worked out, eventually it produced the realm-wrappers library which I added to the native libs folder along with the bass libraries mentioned above. After all this osu! now works, albeit very slowly (but that's just the power of the PI's gpu and outdated OpenGL).

**Comment by TailsFanLOL** [comment]
Yo, anyone still here?
I am trying to get osu! running on Acer Chromebook Tab 10, which is currently running PostMarketOS. This is MUSL/Linux, so I don't see how it is any different from Android (a supported platform). However, running it thru dotnet produces no logs at all. It does run in WayDroid, however only at like 17FPS in the menus, I just wanna try running it natively and see if that works.

**Comment by squidink7** [comment]
I don't currently have an arm device available to test anymore but I have helped someone recently get it to work so it can be done if you're committed. Since my previous comment, realm-dotnet includes everything necessary to work on arm, so if you add the bass libraries that should be enough to get it to compile.

**Comment by bdach** [comment]
If anything I suspect musl may be the issue here. We don't care but I believe our dependencies may generally assume glibc.

**Comment by TailsFanLOL** [comment]
> so if you add the bass libraries that should be enough to get it to compile.

It *does* compile, it just doesn't run.

**Comment by Tianming-Wu** [comment]
@squidink7  So, do you still have the compiled package? I just couldn't spend tens of hours on it, since it will probably affect my schoolwork.
Though I'm running ubuntu, and I don't know if it works.

**Comment by squidink7** [comment]
No, unfortunately. I don't have the device I tested it on anymore, though compiling it isn't too hard if you have experience building .net apps from source, and if you have matrix you can message me there and I can try to help you with any questions :)

**Comment by TailsFanLOL** [comment]
I tried again. I recall finding the logs dir and it erroring out on something GL related a few months back (apparently it doesn't stdout it, for some reason). Now the logs kinda... ...get cut off? Sometimes it says `Initializing "GL" renderer...`, sometimes it doesn't. Nothing else in there.

**Comment by JamiKettunen** [comment]
Fwiw I'm able to play the game at imo already perfect performance on a Lenovo Yoga Slim 7x (Snapdragon X Elite) with an external high(er) refresh rate monitor and peripherals [plugged into a dock](https://support.lenovo.com/us/en/accessories/acc500106-thinkpad-usb-c-dock-gen-2-overview-and-service-parts) as tested under Ubuntu 25.04:
<img src="https://github.com/user-attachments/assets/44af4842-2dc4-4e50-9095-4f04e71300c0" height="360" />

`OSU_SDL3=1 SDL_VIDEODRIVER=wayland dotnet run --configuration Release --project osu.Desktop` does the trick after putting the arm64 .so libraries of the additional [libbass](https://www.un4seen.com/files/baskees24-linux.zip), [libbass_fx](https://www.un4seen.com/files/z/0/bass_fx24-linux.zip) & [libbassmix](https://www.un4seen.com/files/bassmix24-linux.zip) dependencies under e.g. `osu.Desktop/bin/Release/net8.0/runtimes/linux-arm64/native`

The only tricky one was `libveldrid-spirv.so` which you can source from https://github.com/JamiKettunen/veldrid-spirv/actions/runs/14741844559 for now until ppy upstream is providing arm64 binaries too

**Comment by NoaHimesaka1873** [comment]
Works without any change (besides changing arch to aarch64) with AUR package https://aur.archlinux.org/packages/osu-lazer

**Comment by bdach** [comment]
> Works without any change (besides changing arch to aarch64) with AUR package https://aur.archlinux.org/packages/osu-lazer

...so long as you're fine with none of the online functionality working, which is blocked on auth builds happening as per https://github.com/ppy/osu-deploy/pull/192.

**Comment by NoaHimesaka1873** [comment]
> > Works without any change (besides changing arch to aarch64) with AUR package https://aur.archlinux.org/packages/osu-lazer
> 
> ...so long as you're fine with none of the online functionality working, which is blocked on auth builds happening as per [ppy/osu-deploy#192](https://github.com/ppy/osu-deploy/pull/192).

Yeah, at least I can download beatmaps directly still, which is enough for me now.

**Comment by mrrpmeowfurry** [comment]
> > Works without any change (besides changing arch to aarch64) with AUR package https://aur.archlinux.org/packages/osu-lazer
> 
> ...so long as you're fine with none of the online functionality working, which is blocked on auth builds happening as per [ppy/osu-deploy#192](https://github.com/ppy/osu-deploy/pull/192).

I know that this issue has been inactive for quite some time now, but I wanted to share my findings

The pull request [ppy/osu-deploy#192](https://github.com/ppy/osu-deploy/pull/192) does successfully build and produce an AppImage file. However, the binary does not run at all, no output, no logs, nothing

Build command:
```bash
dotnet run -c Release -- "" "" linux arm64
```

Build output:
```bash

  Please note that OSU! and PPY are registered trademarks and as such covered by trademark law.
  Do not distribute builds of this project publicly that make use of these.

Increment Version:     True
Signing Certificate:   
Upload to GitHub:      False

Ready to deploy version 2026.412.0-lazer on platform Linux!
0       Using working directory  /var/home/evelyn/osu-deploy...
0       Running dotnet tool restore...
198     Restoring previous build...
198     Running build...
205     Using working directory  /var/home/evelyn/osu/...
205     Running chmod +x /var/home/evelyn/osu-deploy/staging/osu!.AppDir/AppRun...
207     Using working directory  /var/home/evelyn/osu/...
207     Running dotnet publish -f net8.0 -r linux-arm64 -c Release -o "/var/home/evelyn/osu-deploy/staging/osu!.AppDir/usr/bin" -p:Version=2026.412.0-lazer --self-contained  osu.Desktop...
42447   Creating release...
42447   Using working directory  /var/home/evelyn/osu-deploy...
42447   Running dotnet vpk [linux] pack --packTitle="osu!" --packAuthors="ppy Pty Ltd" --packId="osulazer" --packVersion="2026.412.0-lazer" --runtime="linux-arm64" --outputDir="/var/home/evelyn/osu-deploy/releases" --mainExe="osu!" --packDir="/var/home/evelyn/osu-deploy/staging/osu!.AppDir" --channel="linux-arm64" --verbose  --compression gzip...
50402   Done!
```

Running the AppImage:
```bash
mrrpmeowfurry@fedora:~/$ ./osulazer-linux-arm64.AppImage
mrrpmeowfurry@fedora:~/$ lscpu | grep arch
Architecture:                            aarch64
```

The process exits immediately without any visible error or log output.

Does anyone know what might be causing this issue? Right now I'm unable to debug, since the client does not produces logs at all.

Thanks in advance.

**Comment by JamiKettunen** [comment]
forget deploy, it's pointless for you to be messing around with especially since it seems like you may also have problems either with the specific OS or possibly your drivers, `dotnet run --project osu.Desktop` from this repo still just works for me. would be nice to be able to submit scores on ARM64 hw running Linux but that's not something I can do anything about...

**Comment by mrrpmeowfurry** [comment]
> forget deploy, it's pointless for you to be messing around with especially since it seems like you may also have problems either with the specific OS or possibly your drivers, `dotnet run --project osu.Desktop` from this repo still just works for me. would be nice to be able to submit scores on ARM64 hw running Linux but that's not something I can do anything about...

I see. I was able to resolve the issue by creating an Ubuntu 24.04 container and installing SDL2. After that the game launches just fine.

Also, you can submit scores on dev.ppy.sh if you launch in debug mode
```
dotnet run --project osu.Desktop -c Debug
```

**Comment by JamiKettunen** [comment]
Here's a little something so that people don't have to keep suffering with the extremely annoying non-stop notification spam on every beatmap enter etc reminding how upstream still has no anti-cheat compiled for ARM64 outside macOS/mobile, have fun (or just do `Debug` build ig)

<img height="120" alt="Image of score submission failing" src="https://github.com/user-attachments/assets/a677863a-eb1d-4a15-a1b3-302d6b987ec5" />

<img height="120" alt="Image of limited realtime online functionality" src="https://github.com/user-attachments/assets/7fab29cb-eb27-4ce7-b1bb-f15188fa0a5e" />

```diff
--- a/osu.Game/Online/Multiplayer/MultiplayerClientExtensions.cs
+++ b/osu.Game/Online/Multiplayer/MultiplayerClientExtensions.cs
@@ -33,7 +33,6 @@ public static void FireAndForget(this Task task, Action? onSuccess = null, Actio
                     if (exception.GetHubExceptionMessage() is string message)
                     {
                         // Hub exceptions generally contain something we can show the user directly.
-                        Logger.Log(message, level: LogLevel.Important);
                         return;
                     }
 
--- a/osu.Game/Screens/Play/SubmittingPlayer.cs
+++ b/osu.Game/Screens/Play/SubmittingPlayer.cs
@@ -149,8 +149,6 @@ void handleTokenFailure(Exception exception, bool displayNotification = false)
 
                     if (string.IsNullOrEmpty(exception.Message))
                         notifications?.Post(new ScoreSubmissionFailureNotification(whatWillHappen, "Failed to retrieve a score submission token."));
-                    else
-                        notifications?.Post(new ScoreSubmissionFailureNotification(whatWillHappen, getUserFacingAPIError(exception)));
                 }
 
                 if (shouldExit)
```

**Comment by davidmc971** [comment]
Can confirm osu! running fine on my Lenovo Yoga Slim 7x (Snapdragon X Elite) on NixOS as well (just need to make sure required libraries are available) 😁 

Example `shell.nix` to run it from source:

```nix
{ pkgs ? import <nixpkgs> { } }:

pkgs.mkShell {
  packages = [ pkgs.dotnetCorePackages.sdk_8_0-bin ];

  # Native libs dlopen'd at runtime by the NuGet-bundled SDL3, Veldrid and BASS.
  # NixOS has no global ld path, so expose them via LD_LIBRARY_PATH.
  # /run/opengl-driver/lib provides the system mesa (turnip/freedreno) EGL,
  # GLX and Vulkan ICDs.
  LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath (with pkgs; [
    # SDL3 video (Wayland + X11 fallback)
    wayland
    libxkbcommon
    libdecor
    libx11
    libxcursor
    libxext
    libxfixes
    libxi
    libxrandr
    libxscrnsaver
    libxinerama
    # graphics
    libglvnd
    vulkan-loader
    # audio (BASS/SDL)
    alsa-lib
    libpulseaudio
    # misc runtime deps (video decode, input, crypto)
    ffmpeg
    udev
    openssl
    icu
  ]) + ":/run/opengl-driver/lib";
}
```

With `osu` git repo next to `shell.nix` run:

```sh
nix-shell --run "cd osu && dotnet run --project osu.Desktop -c Release"
```

And everything works!

Would love to see an official aarch64 release for one of my favorite games 🫶

**Comment by imnotpoz** [comment]
if you're on nixos you can also add this to your package list:

```nix
(pkgs.osu-lazer.overrideAttrs (old: {
  meta = old.meta // {
    platforms = old.meta.platforms ++ [ "aarch64-linux" ];
  };
}))
```

this works for me on asahi M2 pro :3c

would love to see an official release one day but this works fine for now

**Comment by trustytrojan** [comment]
> if you're on nixos you can also add this to your package list:
> 
> ```nix
> (pkgs.osu-lazer.overrideAttrs (old: {
>   meta = old.meta // {
>     platforms = old.meta.platforms ++ [ "aarch64-linux" ];
>   };
> }))
> ```
> 
> this works for me on asahi M2 pro :3c
> 
> would love to see an official release one day but this works fine for now

Can confirm this works on NixOS on my Lenovo Yoga Slim 7x (Snapdragon X Elite)! Someone should really PR [nixpkgs](https://github.com/NixOS/nixpkgs) to add `aarch64-linux` to the package's platforms.

**Comment by imnotpoz** [comment]
good idea, opened one here: https://github.com/NixOS/nixpkgs/pull/562931

feel free to like it and add a review saying it works if you wanna speed it up! :3c

**Comment by imnotpoz** [comment]
the PR was merged, use this link to track when it hits nixos-unstable https://nixpk.gs/pr-tracker.html?pr=562931

**Comment by imnotpoz** [comment]
it's in nixos-unstable!! make sure to update nixpkgs to the latest commit and you'll be able to run it straight from the `osu-lazer` package
