### ISSUE TITLE
Unable to do anything after importing my maps and skins from stable

### ISSUE THREAD

**Issue by Mashsim** [ppy/osu#7236]
I insalled lazer, after setting it the game asked me if I wanted to import all my maps and my skins from stable, I did it and after it was done, I couldn't do anything. I tried unistalling but it doesn't erase your previous settings and I don't know what's the game directory with all the files.

Video: https://youtu.be/EvuYz6aWYOA

**osu!lazer version: 2019.1216.0** 

**Logs: 
[database.log](https://github.com/ppy/osu/files/3968975/database.log)
[runtime.log](https://github.com/ppy/osu/files/3969057/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3969058/updater.log)
[performance.log](https://github.com/ppy/osu/files/3969059/performance.log)**

**Comment by l3lackShark** [comment]
@Mashsim Logs directory: %appdata%\osu\logs

**Comment by bdach** [comment]
Except for one parsing failure (most likely due to an `.osu` file being effectively empty):
```
2019-12-13 20:59:27: [?????] Model creation of 701163 RADWIMPS - Nandemo Nai ya failed.
2019-12-13 20:59:27: System.IO.IOException: Unknown file format (null)
2019-12-13 20:59:27: at osu.Game.Beatmaps.Formats.Decoder.GetDecoder[T](LineBufferedReader stream)
2019-12-13 20:59:27: at osu.Game.Beatmaps.BeatmapManager.CreateModel(ArchiveReader reader)
2019-12-13 20:59:27: at osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive, CancellationToken cancellationToken)
```
import logs are clean. Please upload the full set of logs (`runtime.log` especially) post-import.

**Comment by bdach** [comment]
Actually disregard that, I missed this one:
```
2019-12-13 23:11:38: [dd928] Database import or population failed and has been rolled back.
2019-12-13 23:11:38: Newtonsoft.Json.JsonSerializationException: Error getting value from 'AllowFail' on 'osu.Game.Rulesets.Osu.Mods.OsuModEasy'.
2019-12-13 23:11:38: ---> System.NullReferenceException: Object reference not set to an instance of an object.
2019-12-13 23:11:38: at osu.Game.Rulesets.Mods.ModEasy.get_AllowFail()
2019-12-13 23:11:38: at lambda_method(Closure , Object )
2019-12-13 23:11:38: at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
2019-12-13 23:11:38: --- End of inner exception stack trace ---
2019-12-13 23:11:38: at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
2019-12-13 23:11:38: at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
```
Likely the root cause.

**Comment by Mashsim** [comment]
> Except for one parsing failure (most likely due to an `.osu` file being effectively empty):
> 
> ```
> 2019-12-13 20:59:27: [?????] Model creation of 701163 RADWIMPS - Nandemo Nai ya failed.
> 2019-12-13 20:59:27: System.IO.IOException: Unknown file format (null)
> 2019-12-13 20:59:27: at osu.Game.Beatmaps.Formats.Decoder.GetDecoder[T](LineBufferedReader stream)
> 2019-12-13 20:59:27: at osu.Game.Beatmaps.BeatmapManager.CreateModel(ArchiveReader reader)
> 2019-12-13 20:59:27: at osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive, CancellationToken cancellationToken)
> ```
> 
> import logs are clean. Please upload the full set of logs (`runtime.log` especially) post-import.

Done.
