### ISSUE TITLE
Hard crash on x86 Android

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#7241]
Every version of Lazer since 2019.1021.0 crashes on my x86 tablet. 
Logcat from 2019.1021.0:
 
![Screenshot_2019-12-17-13-07-57](https://user-images.githubusercontent.com/20248967/70976707-7dd15500-20bd-11ea-85f5-76143b82e934.png)

**Comment by peppy** [comment]
I don't know that we can/do support android 5.

**Comment by l3lackShark** [comment]
I will install android 6 on it and will come back with results.

**Comment by huoyaoyuan** [comment]
The manifest says it supports Android 5(API Level 21) as minimal.
May be caused by some dependency not supporting it. It should be acceptable to drop such an old version.

**Comment by l3lackShark** [comment]
Android 6.0.1, still crashes
<details>
  <summary>Logcat Log</summary>
  
  12-17 14:08:36.354  2662  2662 E DEBUG   : AM write failed: Broken pipe

12-17 14:08:36.355  3011  3063 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)

12-17 14:08:36.359  3011  5444 W ActivityManager:   Force finishing activity sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity

12-17 14:08:36.405  3011  3308 W InputDispatcher: channel '2f07016 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

12-17 14:08:36.405  3011  3308 E InputDispatcher: channel '2f07016 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

12-17 14:08:36.405  3011  3058 D GraphicsStats: Buffer count: 8

12-17 14:08:36.405  2672  2672 I Zygote  : Process 5411 exited due to signal (11)

12-17 14:08:36.405  3011  3057 I WindowState: WIN DEATH: Window{2f07016 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity}

12-17 14:08:36.405  3011  3057 W InputDispatcher: Attempted to unregister already unregistered input channel '2f07016 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity (server)'

12-17 14:08:36.406  3011  3057 W WindowManager: Force-removing child win Window{ef1d823 u0 SurfaceView} from container Window{2f07016 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity}

12-17 14:08:36.416  3011  4626 W WindowManager: Failed looking up window

12-17 14:08:36.416  3011  4626 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@5d34b84 does not exist

12-17 14:08:36.416  3011  4626 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8828)

12-17 14:08:36.416  3011  4626 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8819)

12-17 14:08:36.416  3011  4626 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1219)

12-17 14:08:36.416  3011  4626 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)

12-17 14:08:36.416  3011  4626 I WindowState: WIN DEATH: null

12-17 14:08:36.465  3011  5444 W ActivityManager: Exception thrown during pause

12-17 14:08:36.465  3011  5444 W ActivityManager: android.os.DeadObjectException

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:879)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2992)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2848)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2828)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12494)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:12365)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:13081)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12586)

12-17 14:08:36.465  3011  5444 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

12-17 14:08:36.468  2467  2467 E lowmemorykiller: Error opening /proc/5411/oom_score_adj; errno=2

12-17 14:08:36.471  3011  3791 I ActivityManager: Process sh.ppy.osulazer (pid 5411) has died
  
</details>
