### ISSUE TITLE
Back button crashes game

### ISSUE THREAD

**Issue by EvilSourcerer** [ppy/osu#7277]
**Describe the crash:** 
Game crashes randomly after pressing the back button sometimes (will work on refining cause of crash)

**osu!lazer version:** 
2019.1216.0_224_g1c9b27a9c-1 (AUR osu-lazer-git)
**Logs:** 
```
Unhandled exception. System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.ValidateReadWriteArgs(Byte[] array, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at osu.Framework.Graphics.Video.VideoDecoder.readPacket(Void* opaque, Byte* bufferPtr, Int32 bufferSize)
   at osu.Framework.Graphics.Video.VideoDecoder.decodingLoop(CancellationToken cancellationToken)
Fatal error. Internal CLR error. (0x80131506)
   at osu.Framework.Graphics.Video.VideoDecoder.decodingLoop(System.Threading.CancellationToken)
   at osu.Framework.Graphics.Video.VideoDecoder.<StartDecoding>b__48_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
[1]    93579 abort (core dumped)  osu-lazer
```
**Computer Specifications:** 
Intel i7-7700HQ
Intel HD Graphics 630
Nvidia GeForce GTX 1060 Mobile
using X server
Arch btw

**Comment by peppy** [comment]
Can you confirm that you are exiting gameplay when this happens?

**Comment by EvilSourcerer** [comment]
Yes, it does happen sometimes when I exit gameplay. I don't know what exactly needs to happen to cause this crash, so i'll update this when I figure out more

**Comment by smoogipoo** [comment]
This is almost certainly going to be caused by super unsafe disposal in `VideoDecoder`, which disposes the underlying file stream before decoding is stopped: 
![image](https://user-images.githubusercontent.com/1329837/71142943-3503d280-225c-11ea-9235-77c1224faf9e.png)
