### ISSUE TITLE
Crash after install LineageOS (Android 7.1)

### ISSUE THREAD

**Issue by gr01d** [ppy/osu#7884]
**Describe the crash:** 
I downloaded the latest release of 2020.215.0 for Android then it crashed after opening the app. 
This is my first time installing osu for android.

**Screenshots or videos showing encountered issue:** 
Just a plain old `osu! has stopped`
**osu!lazer version:** 

**Logs:** 
ADB LOGCAT EXCERPT

```
02-17 22:29:39.997 23820 23820 V AndroidGameView: osuTK.Graphics.GraphicsModeException: Failed to retrieve GraphicsMode, error BAD_ATTRIBUTE
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Platform.Egl.EglGraphicsMode.SelectGraphicsMode (osuTK.Platform.Egl.SurfaceType surfaceType, System.IntPtr display, osuTK.Graphics.ColorFormat color, System.Int32 depth, System.Int32 stencil, System.Int32 samples, osuTK.Graphics.ColorFormat accum, System.Int32 buffers, System.Boolean stereo, osuTK.Platform.Egl.RenderableFlags renderableFlags) [0x000af] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Platform.Egl.EglContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000cc] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Android.AndroidGraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00000] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Android.AndroidFactory.CreateGLContext (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Boolean directRendering, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x0000e] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000c8] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00008] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osuTK.Android.AndroidGameView.CreateFrameBuffer () [0x0006c] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:39.997 23820 23820 V AndroidGameView:   at osu.Framework.Android.AndroidGameView.CreateFrameBuffer () [0x00000] in <72c226c4314a4591a41a26582d58af7c>:0 
02-17 22:29:40.019 23820 23820 I MonoDroid: UNHANDLED EXCEPTION:
02-17 22:29:40.021 23820 23820 I MonoDroid: System.InvalidOperationException: Can't load egl, aborting ---> osuTK.Graphics.GraphicsModeException: Failed to retrieve GraphicsMode, error BAD_ATTRIBUTE
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Platform.Egl.EglGraphicsMode.SelectGraphicsMode (osuTK.Platform.Egl.SurfaceType surfaceType, System.IntPtr display, osuTK.Graphics.ColorFormat color, System.Int32 depth, System.Int32 stencil, System.Int32 samples, osuTK.Graphics.ColorFormat accum, System.Int32 buffers, System.Boolean stereo, osuTK.Platform.Egl.RenderableFlags renderableFlags) [0x000af] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Platform.Egl.EglContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000cc] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Android.AndroidGraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00000] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Android.AndroidFactory.CreateGLContext (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Boolean directRendering, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x0000e] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000c8] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00008] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osuTK.Android.AndroidGameView.CreateFrameBuffer () [0x0006c] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osu.Framework.Android.AndroidGameView.CreateFrameBuffer () [0x00000] in <72c226c4314a4591a41a26582d58af7c>:0 
02-17 22:29:40.021 23820 23820 I MonoDroid:    --- End of inner exception stack trace ---
02-17 22:29:40.021 23820 23820 I MonoDroid:   at osu.Framework.Android.AndroidGameView.CreateFrameBuffer () [0x0003e] in <72c226c4314a4591a41a26582d58af7c>:0 
02-17 22:29:40.022 23820 23820 I MonoDroid:   at osuTK.Android.AndroidGameView.CreateSurface () [0x00008] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.022 23820 23820 I MonoDroid:   at osuTK.Android.AndroidGameView.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x00007] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.022 23820 23820 I MonoDroid:   at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceCreated_Landroid_view_SurfaceHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder) [0x00011] in <fc48fafcaab54aaab7baa98ebf40eb80>:0 
02-17 22:29:40.022 23820 23820 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.12(intptr,intptr,intptr)
02-17 22:29:40.040 23820 23820 W art     : JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
02-17 22:29:40.052 23820 23820 D AndroidRuntime: Shutting down VM
02-17 22:29:40.071 23820 23820 E AndroidRuntime: FATAL EXCEPTION: main
02-17 22:29:40.071 23820 23820 E AndroidRuntime: Process: sh.ppy.osulazer, PID: 23820
02-17 22:29:40.071 23820 23820 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.InvalidOperationException: Can't load egl, aborting ---> osuTK.Graphics.GraphicsModeException: Failed to retrieve GraphicsMode, error BAD_ATTRIBUTE
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Platform.Egl.EglGraphicsMode.SelectGraphicsMode (osuTK.Platform.Egl.SurfaceType surfaceType, System.IntPtr display, osuTK.Graphics.ColorFormat color, System.Int32 depth, System.Int32 stencil, System.Int32 samples, osuTK.Graphics.ColorFormat accum, System.Int32 buffers, System.Boolean stereo, osuTK.Platform.Egl.RenderableFlags renderableFlags) [0x000af] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Platform.Egl.EglContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000cc] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Android.AndroidGraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.Egl.EglWindowInfo window, osuTK.Graphics.IGraphicsContext sharedContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00000] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Android.AndroidFactory.CreateGLContext (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Boolean directRendering, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x0000e] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, osuTK.Graphics.IGraphicsContext shareContext, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x000c8] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Graphics.GraphicsContext..ctor (osuTK.Graphics.GraphicsMode mode, osuTK.Platform.IWindowInfo window, System.Int32 major, System.Int32 minor, osuTK.Graphics.GraphicsContextFlags flags) [0x00008] in <7fc41a022a574c66b9b7cf691ee2de7d>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Android.AndroidGameView.CreateFrameBuffer () [0x0006c] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osu.Framework.Android.AndroidGameView.CreateFrameBuffer () [0x00000] in <72c226c4314a4591a41a26582d58af7c>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:    --- End of inner exception stack trace ---
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osu.Framework.Android.AndroidGameView.CreateFrameBuffer () [0x0003e] in <72c226c4314a4591a41a26582d58af7c>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Android.AndroidGameView.CreateSurface () [0x00008] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at osuTK.Android.AndroidGameView.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x00007] in <7484b4753167456b82f11e78c0669d25>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at Android.Views.ISurfaceHolderCallbackInvoker.n_SurfaceCreated_Landroid_view_SurfaceHolder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder) [0x00011] in <fc48fafcaab54aaab7baa98ebf40eb80>:0 
02-17 22:29:40.071 23820 23820 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.12(intptr,intptr,intptr)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at osutk.android.AndroidGameView.n_surfaceCreated(Native Method)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at osutk.android.AndroidGameView.surfaceCreated()
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
02-17 22:29:40.071 23820 23820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
02-17 22:29:40.075  3056 15987 W ActivityManager:   Force finishing activity sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity
02-17 22:29:40.087  3056 15987 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:375 com.android.server.am.AppErrors.crashApplication:309 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13732 com.android.server.am.ActivityManagerService.handleApplicationCrash:13714 
02-17 22:29:40.153  3056  4480 I OpenGLRenderer: Initialized EGL, version 1.4
02-17 22:29:40.153  3056  4480 D OpenGLRenderer: Swap behavior 1
02-17 22:29:40.587  3056  3070 W ActivityManager: Activity pause timeout for ActivityRecord{c2ff882 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity t12670 f}
02-17 22:29:40.594  3056  3070 I Sensors : AccelerometerSensor enable: mEnabled 1, handle 0, en 0
02-17 22:29:40.596  3056  3070 I WindowManager: Failed to capture screenshot of Token{4b09b93 ActivityRecord{c2ff882 u0 sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity t12670 f}} appWin=Window{17893a u0 SurfaceView - sh.ppy.osulazer/crc64f3e94a995e5d9e96.OsuGameActivity} drawState=3
02-17 22:29:40.645   253   253 D gralloc.sc8830: fb_post fps = 23.837774
```

**Computer Specifications:** 
Samsung Tab A7 SM-T285 Lineage OS Android 7.1

**Comment by bdach** [comment]
Not familiar with LineageOS but from the attached logcat something went very wrong very deep (possibly wrong/outdated OpenGL ES version).

Since we're not currently accepting mobile issues, and the issue concerns an OS we don't really offer support for, going to go ahead and close this for the time being.
