### ISSUE TITLE
can't launch osu!

### ISSUE THREAD

**Issue by VelperK** [ppy/osu#7996]
When I try opening the executable the screen goes black for a brief moment and then returns to the desktop.

video showing the issue: https://youtu.be/-bevxvlxJmI

osu!lazer version 2020.225.0

**Logs:**

Windows Event Viewer log

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5dedc13b
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0xf96f12ee
Exception code: 0xe0434352
Fault offset: 0x000000000003a839
Faulting process id: 0x31e0
Faulting application start time: 0x01d5ec378cd62cfc
Faulting application path: C:\Users\Santiago\AppData\Local\osulazer\app-2020.225.0\osu!.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f7ab1687-aaa7-4bea-a0f7-b845781182b9
Faulting package full name: 
Faulting package-relative application ID: 

osu! log

2020-02-25 23:59:04: ----------------------------------------------------------
2020-02-25 23:59:04: database Log for Santiago (LogLevel: Verbose)
2020-02-25 23:59:04: osu 2020.225.0.0
2020-02-25 23:59:04: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
2020-02-25 23:59:04: ----------------------------------------------------------
2020-02-25 23:59:04: Failed executing DbCommand (1ms) [Parameters=[@p0='?'], CommandType='Text', CommandTimeout='10']
2020-02-25 23:59:04: DELETE FROM "BeatmapInfo"
2020-02-25 23:59:04: WHERE "ID" = @p0;
2020-02-25 23:59:04: SELECT changes();
2020-02-25 23:59:04: An exception occurred in the database while saving changes for context type 'osu.Game.Database.OsuDbContext'.
2020-02-25 23:59:04: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-02-25 23:59:04: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
2020-02-25 23:59:04: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2020-02-25 23:59:04: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2020-02-25 23:59:04: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
2020-02-25 23:59:04: at System.Data.Common.DbCommand.ExecuteReader()
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
2020-02-25 23:59:04: --- End of inner exception stack trace ---
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
2020-02-25 23:59:04: at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

**Comment by smoogipoo** [comment]
Is this a really old installation of the game that has only recently been opened? We'll need your `client.db` located in `%APPDATA%\osu` to investigate further.

**Comment by VelperK** [comment]
this is a fresh installation I did 20 minutes ago of the latest version

client.db: https://1drv.ms/u/s!AvEEWyK_QKccsMUfr8ipIiNPyyOxNg?e=bSswDq

**Comment by peppy** [comment]
Can you try deleting or renaming `client.db` and see if it works after that?

**Comment by VelperK** [comment]
that did it! thanks

still a weird crash but oh well, hope this helps in development.

**Comment by peppy** [comment]
Closing this one for now. The underlying issue is being tracked at a higher level.
