### ISSUE TITLE
Error submitting score after the 10th completed beatmap in a room

### ISSUE THREAD

**Issue by nathannino** [ppy/osu#8062]
**Describe the bug:** 
After the 10th completed beatmap in a multiplayer room, all additional beatmaps will not be able to submit scores. From what I remember, you can still improve the first 10 beatmaps you played in the room, but take that part with a grain of salt
**Screenshots or videos showing encountered issue:** 
https://youtu.be/rv97JtXnofY
**osu!lazer version:** 
2020.229.1
**Logs:**
https://drive.google.com/drive/folders/1_6iMvdKXzS0nWa2p3EsexK9jtVSyr9Nf?usp=sharing

**Comment by bdach** [comment]
Logs show a server-side error:
```
2020-03-01 01:28:21 [error]: Failed to submit score
2020-03-01 01:28:21 [error]: osu.Game.Online.API.APIException: Exception of type 'osu.Game.Online.API.APIException' was thrown.
2020-03-01 01:28:21 [error]: ---> System.Net.WebException: InternalServerError
2020-03-01 01:28:21 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2020-03-01 01:28:21 [error]: at osu.Framework.IO.Network.WebRequest.beginResponse(CancellationToken cancellationToken)
2020-03-01 01:28:21 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform()
```
Looks like something to be handled web-side.

**Comment by peppy** [comment]
This should now be resolved, via database changes.
