### ISSUE TITLE
Disposed judgements added to the draw hierarchy

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#8081]
```
[runtime:error] 2020-03-02 00:44:26: An unhandled error has occurred.
[runtime:error] 2020-03-02 00:44:26: System.ObjectDisposedException: Disposed Drawables may not have children added.
[runtime:error] 2020-03-02 00:44:26: Object name: 'Hit explosions (Container)'.
[runtime:error] 2020-03-02 00:44:26: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
[runtime:error] 2020-03-02 00:44:26: at osu.Game.Rulesets.Mania.UI.Column.OnNewResult(DrawableHitObject judgedObject, JudgementResult result) in /Users/smoogipoo/Repos/osu/osu.Game.Rulesets.Mania/UI/Column.cs:line 171
[runtime:error] 2020-03-02 00:44:26: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.<addNested>b__52_0(DrawableHitObject d, JudgementResult r) in /Users/smoogipoo/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 210
[runtime:error] 2020-03-02 00:44:26: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.ApplyResult(Action`1 application) in /Users/smoogipoo/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 451
[runtime:error] 2020-03-02 00:44:26: at osu.Game.Rulesets.Mania.Objects.Drawables.DrawableHoldNoteTail.CheckForResult(Boolean userTriggered, Double timeOffset) in /Users/smoogipoo/Repos/osu/osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNoteTail.cs:line 50
```

This is likely not mania-specific, and can occur on fail.

**Comment by peppy** [comment]
@smoogipoo do you remember exactly how this repro'd? was it during the exit of the player screen or something like that?

**Comment by smoogipoo** [comment]
I don't, unfortunately.I think it could occur while using quick-retry, though.

**Comment by peppy** [comment]
Going to close for now as non-reproducible. I've tried to figure how this could happen but cannot find a pathway.
