### ISSUE TITLE
Storyboard of handsome's Impulse crashes the game

### ISSUE THREAD

**Issue by TJYSunset** [ppy/osu#8094]
**Describe the crash:** 
Playing or watching replay of [Culprate & Au5 - Impulse](https://osu.ppy.sh/beatmapsets/705788/#osu/1492654) with storyboard crashes the game at approximately 3:01. Turning off storyboard prevents the crash.

**Screenshots or videos showing encountered issue:** 
[2020-03-03_01-59-32.zip](https://github.com/ppy/osu/files/4277088/2020-03-03_01-59-32.zip)
Blackout in this video is the game crashing, not video corruption.
(unrelated: the fast forward effect in replay scrubbing is way too slow.)

**osu!lazer version:** 
2020.229.1

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4277062/logs.zip)

**Computer Specifications:** 
Windows 10 Pro 18362.418
AMD Ryzen 7 3800X
NVIDIA GeForce GTX 1660 Ti

**Comment by bdach** [comment]
Relevant excerpt:
```
2020-03-02 17:48:58 [error]: An unhandled error has occurred.
2020-03-02 17:48:58 [error]: System.ArgumentException: X must be finite, but is NaN.
2020-03-02 17:48:58 [error]: at osu.Framework.Graphics.Drawable.set_X(Single value)
2020-03-02 17:48:58 [error]: at osu.Framework.Graphics.Transforms.Transform`2.Apply(Double time)
2020-03-02 17:48:58 [error]: at osu.Framework.Graphics.Transforms.Transformable.updateTransforms(Double time, Boolean forceRewindReprocess)
```
Closing & grouping this up with #5525 as the two probably need similar fail-safe handling.
