### ISSUE TITLE
osu!lazer won't execute

### ISSUE THREAD

**Issue by Kasumiowo** [ppy/osu#8253]
lazer won't open when installed. Nothing exist in %AppData%/osu/logs. 
osu!lazer version 2020.312.0
Processor:Intel(R) Core (TM) i5-6200U CPU @ 2.30GHz 2.40GHz
System: 64-bit Operating System, x64-based processor
SDKS version 3.1.102
installed multiple windows update

Nothing in Event Viewer

Executing in dotnet seems to encounter this error:
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\Jia Wen\AppData\Local\osulazer\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\Users\Jia Wen\AppData\Local\osulazer\osu!.runtimeconfig.json file specifying the appropriate framework.

Squirrel Log:2020-03-12 20:26:17> Program: Starting Squirrel Updater: --install .
2020-03-12 20:26:17> Program: Starting install, writing to C:\Users\Jia Wen\AppData\Local\SquirrelTemp
2020-03-12 20:26:17> Program: About to install to: C:\Users\Jia Wen\AppData\Local\osulazer
2020-03-12 20:26:17> Program: Install path C:\Users\Jia Wen\AppData\Local\osulazer already exists, burning it to the ground
2020-03-12 20:26:18> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jia Wen\AppData\Local\osulazer\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-03-12 20:26:18> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jia Wen\AppData\Local\osulazer\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-03-12 20:26:18> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Jia Wen\AppData\Local\SquirrelTemp
2020-03-12 20:26:18> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-03-12 20:26:19> ApplyReleasesImpl: Writing files to app directory: C:\Users\Jia Wen\AppData\Local\osulazer\app-2020.312.0
2020-03-12 20:26:20> LogHost: Rigging execution stub for osu!_ExecutionStub.exe to C:\Users\Jia Wen\AppData\Local\osulazer\osu!.exe
2020-03-12 20:26:24> ApplyReleasesImpl: Squirrel Enabled Apps: []
2020-03-12 20:26:24> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2020-03-12 20:26:24> ApplyReleasesImpl: About to create shortcuts for osu!.exe, rootAppDir C:\Users\Jia Wen\AppData\Local\osulazer
2020-03-12 20:26:24> ApplyReleasesImpl: Creating shortcut for osu!.exe => C:\Users\Jia Wen\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ppy Pty Ltd\osu!lazer.lnk
2020-03-12 20:26:24> ApplyReleasesImpl: About to save shortcut: C:\Users\Jia Wen\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ppy Pty Ltd\osu!lazer.lnk (target C:\Users\Jia Wen\AppData\Local\osulazer\osu!.exe, workingDir C:\Users\Jia Wen\AppData\Local\osulazer\app-2020.312.0, args , toastActivatorCSLID ebc39359-2a76-5ce1-8452-e9222d928c95)
2020-03-12 20:26:24> ApplyReleasesImpl: Creating shortcut for osu!.exe => C:\Users\Jia Wen\Desktop\osu!lazer.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: About to save shortcut: C:\Users\Jia Wen\Desktop\osu!lazer.lnk (target C:\Users\Jia Wen\AppData\Local\osulazer\osu!.exe, workingDir C:\Users\Jia Wen\AppData\Local\osulazer\app-2020.312.0, args , toastActivatorCSLID ebc39359-2a76-5ce1-8452-e9222d928c95)
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: Discord.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: File Explorer (2).lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: osu!.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: Discord.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: File Explorer (2).lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Examining Pin: osu!.lnk
2020-03-12 20:26:25> ApplyReleasesImpl: Fixing up tray icons
2020-03-12 20:26:25> ApplyReleasesImpl: cleanDeadVersions: for version 2020.312.0
2020-03-12 20:26:25> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2020.312.0

**Comment by peppy** [comment]
Are you a developer? Do you happen to have a global configuration file for dotnet in your user folder or something? It looks like properties required to start are not being read from the adjacent config.

**Comment by bdach** [comment]
Closing due to inactivity and not enough information provided to begin to solve this problem. Please reopen if you decide to provide additional info or answer the questions above.
