### ISSUE TITLE
osu! not loading (Manjaro 19.0)

### ISSUE THREAD

**Issue by uwuplant** [ppy/osu#8273]
This is probably not related to osu! itself, but still sending it here just in case.

**Describe the crash:** 
Crashing when running osu.AppImage (not loading osu!)
**Screenshots or videos showing encountered issue:** 
N/A, included crash log.
**osu!lazer version:** 
2020.312.0 (also happening on 2020.311.0)
**Logs:**
> No protocol specified
No protocol specified
Unhandled exception. System.TypeInitializationException: The type initializer for 'osuTK.DisplayDevice' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at osuTK.Platform.Linux.LinuxFactory.CreateDisplay(IntPtr& gbm_device, IntPtr& egl_display)
   at osuTK.Platform.Linux.LinuxFactory.get_gpu_fd()
   at osuTK.Platform.Linux.LinuxFactory.CreateDisplayDeviceDriver()
   at osuTK.DisplayDevice..cctor()
   --- End of inner exception stack trace ---
   at osuTK.DisplayDevice.get_Default()
   at osuTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode)
   at osu.Framework.Platform.GameWindow..ctor(Int32 width, Int32 height)
   at osu.Framework.Platform.DesktopGameWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 57
Aborted (core dumped)

**Computer Specifications:** 
i7-7700k, GTX 1060
Manjaro System Information Output:

> Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.66.0
Qt Version: 5.14.1
Kernel Version: 5.4.18-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15.6 GiB of RAM

**Comment by peppy** [comment]
looks like your gpu doesn't support something we are doing. if it runs on windows then it's a driver issue.

you can try specifying --sdl to see if that helps

**Comment by uwuplant** [comment]
thank you, will try that out

may be an issue with drivers
