### ISSUE TITLE
Crash on dual stage mod in mania ruleset

### ISSUE THREAD

**Issue by andy840119** [ppy/osu#8553]
**Describe the bug:** 
Crash on `dual stage` mod in mania ruleset if using `osu!classic` skin

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/9100368/78210392-0b0dad80-74e5-11ea-9b2f-558778d2fa2e.png)

**osu!lazer version:** 
2020.402.0

**Logs:**
```
   at osu.Game.Skinning.LegacySkin.lookupForMania[TValue](LegacyManiaSkinConfigurationLookup maniaLookup) in F:\Github\andy840119\osu\osu.Game\Skinning\LegacySkin.cs:line 185
   at osu.Game.Skinning.LegacySkin.GetConfig[TLookup,TValue](TLookup lookup) in F:\Github\andy840119\osu\osu.Game\Skinning\LegacySkin.cs:line 139
   at osu.Game.Skinning.SkinManager.GetConfig[TLookup,TValue](TLookup lookup) in F:\Github\andy840119\osu\osu.Game\Skinning\SkinManager.cs:line 134
   at osu.Game.Skinning.SkinProvidingContainer.GetConfig[TLookup,TValue](TLookup lookup) in F:\Github\andy840119\osu\osu.Game\Skinning\SkinProvidingContainer.cs:line 77
   at osu.Game.Rulesets.Mania.Skinning.ManiaLegacySkinTransformer.GetConfig[TLookup,TValue](TLookup lookup) in F:\Github\andy840119\osu\osu.Game.Rulesets.Mania\Skinning\ManiaLegacySkinTransformer.cs:line 116
   at osu.Game.Skinning.SkinProvidingContainer.GetConfig[TLookup,TValue](TLookup lookup) in F:\Github\andy840119\osu\osu.Game\Skinning\SkinProvidingContainer.cs:line 72
   at osu.Game.Rulesets.Mania.UI.ManiaStage.onSkinChanged() in F:\Github\andy840119\osu\osu.Game.Rulesets.Mania\UI\ManiaStage.cs:line 160
   at osu.Game.Rulesets.Mania.UI.ManiaStage.load(ISkinSource skin) in F:\Github\andy840119\osu\osu.Game.Rulesets.Mania\UI\ManiaStage.cs:line 151
```

**Comment by smoogipoo** [comment]
Have already resolved this in a branch, not ready for PR yet.
