### ISSUE TITLE
Enabling converted beatmaps with no beatmaps visible crashes song select

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#8957]
Enabling `Show converted beatmaps` which filtered crashes song select.

Steps to reproduce:
1. Disable `Show converted beatmaps`.
2. Enter song select.
3. Type a search filter that displays no beatmaps.
4. Enable `Show converted beatmaps`.
5. Crash.

Log:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Game.Screens.Select.Carousel.CarouselBeatmap.<>c__DisplayClass3_0.<Filter>b__0(String term) in /Users/smoogipoo/Repos/osu/osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs:line 64
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Game.Screens.Select.Carousel.CarouselBeatmap.Filter(FilterCriteria criteria) in /Users/smoogipoo/Repos/osu/osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs:line 64
   at osu.Game.Screens.Select.Carousel.CarouselGroup.<>c__DisplayClass10_0.<Filter>b__0(CarouselItem c) in /Users/smoogipoo/Repos/osu/osu.Game/Screens/Select/Carousel/CarouselGroup.cs:line 85
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at osu.Game.Screens.Select.Carousel.CarouselGroup.Filter(FilterCriteria criteria) in /Users/smoogipoo/Repos/osu/osu.Game/Screens/Select/Carousel/CarouselGroup.cs:line 85

```

**Comment by smoogipoo** [comment]
Actually this seems to occur in general when filtering to no beatmaps with `show converted beatmaps` enabled.
