### ISSUE TITLE
Occasional crash when dragging a selection in osu!mania editor

### ISSUE THREAD

**Issue by peppy** [ppy/osu#9063]
- Select some notes
- Drag around and a crash may occur

```
[runtime] 2020-05-19 09:03:46 [error]: System.InvalidOperationException: Removed a drawable (DrawableNote) whose parent was not this (ScrollingHitObjectContainer), but .
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.RemoveInternal(Drawable drawable)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Graphics.Containers.LifetimeManagementContainer.RemoveInternal(Drawable drawable)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.onStartTimeChanged(DrawableHitObject hitObject) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 59
[runtime] 2020-05-19 09:03:46 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.<>c__DisplayClass6_0.<Add>b__0(ValueChangedEvent`1 _) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 29
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Framework.Bindables.BindableNumber`1.SetValue(T value)
[runtime] 2020-05-19 09:03:46 [error]: at osu.Game.Rulesets.Objects.HitObject.set_StartTime(Double value) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/HitObject.cs:line 45
[runtime] 2020-05-19 09:03:46 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.moveCurrentSelection(DragEvent e) in /Users/dean/Projects/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 417
[runtime] 2020-05-19 09:03:46 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.OnDrag(DragEvent e) inSystem.InvalidOperationException: Removed a drawable (DrawableNote) whose parent was not this (ScrollingHitObjectContainer), but .
   at osu.Framework.Graphics.Containers.CompositeDrawable.RemoveInternal(Drawable drawable)
   at osu.Framework.Graphics.Containers.LifetimeManagementContainer.RemoveInternal(Drawable drawable)
   at osu.Game.Rulesets.UI.HitObjectContainer.onStartTimeChanged(DrawableHitObject hitObject) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 59
   at osu.Game.Rulesets.UI.HitObjectContainer.<>c__DisplayClass6_0.<Add>b__0(ValueChangedEvent`1 _) in /Users/dean/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 29
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Framework.Bindables.BindableNumber`1.SetValue(T value)
   at osu.Game.Rulesets.Objects.HitObject.set_StartTime(Double value) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/HitObject.cs:line 45
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.moveCurrentSelection(DragEvent e) in /Users/dean/Projects/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 417
   at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.OnDrag(DragEvent e) in /Users/dean/Projects/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 193
```

**Comment by peppy** [comment]
Tentatively closing as fixed by #9352 (I can't reproduce any more).
