### ISSUE TITLE
Video not working on linux

### ISSUE THREAD

**Issue by danbulant** [ppy/osu#9127]
**Describe the bug:** 
(I'm making a bug report since the implementation issue has been close quite some time ago) Opening maps with video (which, as I tested, works on other platforms like android and windows and on stable) shows just the image on linux (I clicked download with video directly from Osu!lazer).

**osu!lazer version:** 
2020.313 (I think, not sure) - 2020.515.0

**Logs:**

```
2020-05-27 13:05:04 [verbose]: ----------------------------------------------------------
2020-05-27 13:05:04 [verbose]: runtime Log for dan (LogLevel: Verbose)
2020-05-27 13:05:04 [verbose]: osu 2020.515.0.0
2020-05-27 13:05:04 [verbose]: Running on Unix 4.19.0.9, 4 cores
2020-05-27 13:05:04 [verbose]: ----------------------------------------------------------
2020-05-27 13:05:04 [verbose]: BASS Initialized
2020-05-27 13:05:04 [verbose]: BASS Version:               2.4.14.1
2020-05-27 13:05:04 [verbose]: BASS FX Version:            2.4.12.1
2020-05-27 13:05:04 [verbose]: Device:                     Default
2020-05-27 13:05:04 [verbose]: Drive:                      default
2020-05-27 13:05:16 [verbose]: Connected MIDI device: Midi Through Port-0
2020-05-27 13:05:16 [verbose]: Screen changed → Loader
2020-05-27 13:05:16 [verbose]: Screen changed → Disclaimer
2020-05-27 13:05:23 [verbose]: Screen changed → IntroCircles
2020-05-27 13:05:23 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2020-05-27 13:05:25 [verbose]: Screen changed → MainMenu
2020-05-27 13:05:26 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2020-05-27 13:05:34 [verbose]: Focus contention triggered by ChangelogOverlay.
2020-05-27 13:05:35 [verbose]: Focus contention triggered by ChangelogOverlay.
2020-05-27 13:05:49 [verbose]: ButtonSystem's state changed from TopLevel to Initial
2020-05-27 13:11:02 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2020-05-27 13:11:05 [verbose]: ButtonSystem's state changed from TopLevel to Play
2020-05-27 13:11:07 [verbose]: ButtonSystem's state changed from Play to TopLevel
2020-05-27 13:11:13 [verbose]: ButtonSystem's state changed from TopLevel to Play
2020-05-27 13:11:14 [verbose]: ButtonSystem's state changed from Play to EnteringMode
2020-05-27 13:11:14 [verbose]: Screen changed → Multiplayer
2020-05-27 13:11:15 [verbose]: Polling adjusted (listing: 15000, selection: 15000)
2020-05-27 13:11:17 [verbose]: Focus contention triggered by NotificationOverlay.
2020-05-27 13:11:27 [verbose]: Focus contention triggered by NotificationOverlay.
2020-05-27 13:11:38 [verbose]: Screen changed ← MainMenu
2020-05-27 13:11:38 [verbose]: ButtonSystem's state changed from EnteringMode to TopLevel
2020-05-27 13:11:39 [verbose]: ButtonSystem's state changed from TopLevel to Play
2020-05-27 13:11:39 [verbose]: ButtonSystem's state changed from Play to EnteringMode
2020-05-27 13:11:39 [verbose]: Screen changed → PlaySongSelect
2020-05-27 13:11:39 [verbose]: updating selection with beatmap:364 ruleset:0
2020-05-27 13:11:41 [verbose]: updating selection with beatmap:16 ruleset:0
2020-05-27 13:11:41 [verbose]: beatmap changed from "Helblinde - Putin's Boner (Sotarks) [Akitoshi's Normal]" to "Agnete Kjolsrud - Get Jinxed (Tarrasky) [Setorrasky's Bronze]"
2020-05-27 13:11:41 [verbose]: working beatmap updated to Agnete Kjolsrud - Get Jinxed (Tarrasky) [Setorrasky's Bronze]
2020-05-27 13:11:42 [verbose]: Screen changed → PlayerLoader
2020-05-27 13:11:43 [verbose]: VideoDecoder faulted: System.DllNotFoundException: Unable to load shared library 'avformat' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat: cannot open shared object file: No such file or directory
2020-05-27 13:11:43 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
2020-05-27 13:11:43 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
2020-05-27 13:11:43 [verbose]: at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
2020-05-27 13:11:43 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.<>c.<CreateFuncs>b__58_0(String name)
2020-05-27 13:11:43 [verbose]: at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_318()
2020-05-27 13:11:43 [verbose]: at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
2020-05-27 13:11:43 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding()
2020-05-27 13:11:43 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding()
2020-05-27 13:11:44 [error]: Beatmap download failed!
2020-05-27 13:11:44 [error]: System.Net.WebException: Request to https://osu.ppy.sh/api/v2/beatmapsets/124806/download timed out after 20 seconds idle (read 0 bytes, retried 0 times).
2020-05-27 13:11:44 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2020-05-27 13:11:44 [error]: at osu.Framework.IO.Network.FileWebRequest.Complete(Exception e)
2020-05-27 13:11:44 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform()
2020-05-27 13:11:44 [error]: at osu.Framework.IO.Network.WebRequest.PerformAsync()
2020-05-27 13:11:44 [error]: at osu.Framework.Extensions.ExceptionExtensions.ExceptionExtensions.Rethrow(Exception exception)
2020-05-27 13:11:44 [error]: at osu.Framework.Extensions.ExceptionExtensions.ExceptionExtensions.RethrowAsSingular(AggregateException aggregateException)
2020-05-27 13:11:44 [error]: at osu.Framework.IO.Network.WebRequest.Perform()
2020-05-27 13:11:44 [error]: at osu.Game.Online.API.APIRequest.Perform(IAPIProvider api) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/API/APIRequest.cs:line 112
2020-05-27 13:11:44 [error]: at osu.Game.Online.API.APIAccess.Perform(APIRequest request) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/API/APIAccess.cs:line 212
2020-05-27 13:11:46 [error]: Beatmap download failed!
2020-05-27 13:11:46 [error]: System.Net.WebException: Request to https://osu.ppy.sh/api/v2/beatmapsets/232051/download timed out after 20 seconds idle (read 0 bytes, retried 0 times).
2020-05-27 13:11:46 [error]: at osu.Framework.IO.Network.WebRequest.Complete(Exception e)
2020-05-27 13:11:46 [error]: at osu.Framework.IO.Network.FileWebRequest.Complete(Exception e)
2020-05-27 13:11:46 [error]: at osu.Framework.IO.Network.WebRequest.internalPerform()
2020-05-27 13:11:46 [error]: at osu.Framework.IO.Network.WebRequest.PerformAsync()
2020-05-27 13:11:46 [error]: at osu.Framework.Extensions.ExceptionExtensions.ExceptionExtensions.Rethrow(Exception exception)
2020-05-27 13:11:46 [error]: at osu.Framework.Extensions.ExceptionExtensions.ExceptionExtensions.RethrowAsSingular(AggregateException aggregateException)
2020-05-27 13:11:46 [error]: at osu.Framework.IO.Network.WebRequest.Perform()
2020-05-27 13:11:46 [error]: at osu.Game.Online.API.APIRequest.Perform(IAPIProvider api) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/API/APIRequest.cs:line 112
2020-05-27 13:11:46 [error]: at osu.Game.Online.API.APIAccess.Perform(APIRequest request) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/API/APIAccess.cs:line 212
2020-05-27 13:11:48 [verbose]: Screen changed → Player
2020-05-27 13:11:59 [verbose]: Screen changed ← PlayerLoader
2020-05-27 13:11:59 [verbose]: VideoDecoder faulted: System.DllNotFoundException: Unable to load shared library 'avformat' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat: cannot open shared object file: No such file or directory
2020-05-27 13:11:59 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
2020-05-27 13:11:59 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
2020-05-27 13:11:59 [verbose]: at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
2020-05-27 13:11:59 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.<>c.<CreateFuncs>b__58_0(String name)
2020-05-27 13:11:59 [verbose]: at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_318()
2020-05-27 13:11:59 [verbose]: at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
2020-05-27 13:11:59 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding()
2020-05-27 13:11:59 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding()
2020-05-27 13:12:01 [verbose]: Screen changed → Player
2020-05-27 13:12:19 [verbose]: Screen changed ← PlayerLoader
2020-05-27 13:12:19 [verbose]: Screen changed ← PlaySongSelect
2020-05-27 13:17:03 [verbose]: Screen changed ← MainMenu
2020-05-27 13:17:03 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2020-05-27 13:17:03 [verbose]: ButtonSystem's state changed from EnteringMode to TopLevel
2020-05-27 13:17:11 [verbose]: ButtonSystem's state changed from TopLevel to Initial
```
Including output of `ffmpeg` since I think it may be relevant:
```
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

**Comment by bdach** [comment]
ffmpeg version looks correct but might be symlinked wrong. You can use `LD_DEBUG=libs` to diagnose.

Closing as duplicate unless evidence surfaces that would indicate it isn't one.
