### ISSUE TITLE
Double click on clear of bound key provide an exception

### ISSUE THREAD

**Issue by TheStaticTurtle** [ppy/osu#9171]
**Describe the bug:** 
When two bindings are bound for an action a fast double click of the clear button will provide an exception

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
Compiled in release mode at commit  00024f56fa6c5ac75d162e3de2d8aa555cb49b85

**Logs:**
```
2020-06-01 20:57:59 [error]: An unhandled error has occurred.
2020-06-01 20:57:59 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2020-06-01 20:57:59 [error]: at osu.Game.Overlays.KeyBinding.KeyBindingRow.clear() in C:\Users\tugle\Desktop\osu\osu.Game\Overlays\KeyBinding\KeyBindingRow.cs:line 277
2020-06-01 20:57:59 [error]: at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e)
2020-06-01 20:57:59 [error]: at osu.Game.Graphics.UserInterface.OsuButton.OnClick(ClickEvent e) in C:\Users\tugle\Desktop\osu\osu.Game\Graphics\UserInterface\OsuButton.cs:line 108
2020-06-01 20:57:59 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2020-06-01 20:57:59 [error]: at osu.Framework.Input.InputManager.Update()
2020-06-01 20:57:59 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2020-06-01 20:57:59 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2020-06-01 20:57:59 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2020-06-01 20:57:59 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2020-06-01 20:57:59 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
```

**Comment by bdach** [comment]
This is not exclusive to just double-clicking the clear button - a similar thing can be reproduced when entering a new key binding (e.g. via keyboard) and clicking the clear button in quick succession.

Pretty sure `clear()` just needs to guard against `null`, which it doesn't right now:

https://github.com/ppy/osu/blob/d5ae8f5ef4d52804b26fa6af5e4aba5004be63e3/osu.Game/Overlays/KeyBinding/KeyBindingRow.cs#L275-L279

The fix itself looks easy, but it would be good to have regression tests for this.
