### ISSUE TITLE
[x64] coreclr-3.1.5 corerun segfault

### ISSUE THREAD

**Issue by xiangzhai** [ppy/osu#9312]
Hi,

**Describe the crash:** 

[coreclr-3.1.5](https://github.com/dotnet/coreclr/tree/v3.1.5) self-build:

```
./build.sh release ignorewarnings skipcrossgen -skiptests
```

corerun segfault:

```
export CORE_LIBRARIES=/home/zhaixiang/coreclr-3.1.5/.dotnet/shared/Microsoft.NETCore.App/3.1.0

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native

gdb -ex=r --args /home/zhaixiang/coreclr-3.1.5/bin/Product/Linux.x64.Release/corerun ./osu.Desktop/bin/Release/netcoreapp3.1/osu!.dll

...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff117fa700 (LWP 27577)]
0x00007ffecc5835d9 in ?? () from /home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libbass_fx.so

(gdb) bt
#0  0x00007ffecc5835d9 in ?? () from /home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libbass_fx.so
#1  0x00007ffff7df0159 in _dl_close_worker () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7deeb1d in _dl_open () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7bd7eeb in dlopen_doit () from /lib64/libdl.so.2
#4  0x00007ffff7dea704 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7bd84ed in _dlerror_run () from /lib64/libdl.so.2
#6  0x00007ffff7bd7f81 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#7  0x00007ffff6ac0c9b in LOADLoadLibraryDirect (libraryNameOrPath=0x7ffecc57b8e3 "AUATA\211\364A\201", <incomplete sequence \354>) at /home/zhaixiang/coreclr-3.1.5/src/pal/src/loader/module.cpp:1431
#8  PAL_LoadLibraryDirect (lpLibFileName=<optimized out>) at /home/zhaixiang/coreclr-3.1.5/src/pal/src/loader/module.cpp:630
#9  0x00007ffff68f3973 in LocalLoadLibraryHelper (name=0x7ffecc57b8e3 u"啁呁襁䇴", flags=<optimized out>, pErrorTracker=0x7fff117f9100) at /home/zhaixiang/coreclr-3.1.5/src/vm/dllimport.cpp:5909
#10 NDirect::LoadLibraryModuleBySearch (callingAssembly=0x7ffef40075d0, searchAssemblyDirectory=<optimized out>, dllImportSearchPathFlags=<optimized out>, pErrorTracker=0x7fff117f9100, wszLibName=0x7fff117f8ea8 u"bass_fx") at /home/zhaixiang/coreclr-3.1.5/src/vm/dllimport.cpp:6547
#11 0x00007ffff68f4dfe in NDirect::LoadLibraryModule (pMD=0x7fff7e7e53d0, pErrorTracker=0x7fff117f9100) at /home/zhaixiang/coreclr-3.1.5/src/vm/dllimport.cpp:6626
#12 0x00007ffff68f2e08 in NDirect::NDirectLink (pMD=0x7fff7e7e53d0) at /home/zhaixiang/coreclr-3.1.5/src/vm/dllimport.cpp:6693
#13 0x00007ffff68f4f54 in NDirectImportWorker (pMD=0x7fff7e7e53d0) at /home/zhaixiang/coreclr-3.1.5/src/vm/dllimport.cpp:6799
#14 0x00007ffff68a8a26 in NDirectImportThunk () at /home/zhaixiang/coreclr-3.1.5/src/vm/amd64/unixasmhelpers.S:116
#15 0x00007fff7e6d4e06 in ?? ()
#16 0x00007fff7c022ae5 in ?? ()
#17 0x0000000002da9ed0 in ?? ()
#18 0x00007ffff6d5f4e8 in vtable for InlinedCallFrame () from /home/zhaixiang/coreclr-3.1.5/bin/Product/Linux.x64.Release/libcoreclr.so
#19 0x00007fff117f9c70 in ?? ()
#20 0x00007fff7e7e53d0 in ?? ()
#21 0x0000000000000005 in ?? ()
#22 0x00007fff117f9500 in ?? ()
#23 0x00007fff7e6d4e06 in ?? ()
#24 0x00007fff117f9590 in ?? ()
#25 0x00007fff58600d60 in ?? ()
#26 0x00007fff7ca9c5e0 in ?? ()
#27 0x00000000015854d0 in ?? ()
#28 0x0000000000000000 in ?? ()
(gdb) x/22i 0x00007ffecc5835d9-88
   0x7ffecc583581:	callq  0x7ffecc5751d0 <pthread_mutexattr_destroy@plt>
   0x7ffecc583586:	pop    %rax
   0x7ffecc583587:	pop    %rdx
   0x7ffecc583588:	pop    %rbx
   0x7ffecc583589:	retq   
   0x7ffecc58358a:	sub    $0x8,%rsp
   0x7ffecc58358e:	callq  0x7ffecc57debc
   0x7ffecc583593:	callq  0x7ffecc582648
   0x7ffecc583598:	mov    $0x87be4bff,%edi
   0x7ffecc58359d:	callq  0x7ffecc575390 <BASS_FX_BPM_Free@plt>
   0x7ffecc5835a2:	mov    $0x87be4bff,%edi
   0x7ffecc5835a7:	callq  0x7ffecc5752d0 <BASS_FX_BPM_BeatFree@plt>
   0x7ffecc5835ac:	pop    %rcx
   0x7ffecc5835ad:	lea    0x20524c(%rip),%rdi        # 0x7ffecc788800
   0x7ffecc5835b4:	jmpq   0x7ffecc5753a0 <pthread_mutex_destroy@plt>
   0x7ffecc5835b9:	sub    $0x8,%rsp
   0x7ffecc5835bd:	cmpl   $0x0,0x205234(%rip)        # 0x7ffecc7887f8
   0x7ffecc5835c4:	jne    0x7ffecc5835dc
   0x7ffecc5835c6:	mov    0x205223(%rip),%rax        # 0x7ffecc7887f0
   0x7ffecc5835cd:	mov    $0x3,%esi
   0x7ffecc5835d2:	mov    0x2049d7(%rip),%rdi        # 0x7ffecc787fb0
=> 0x7ffecc5835d9:	callq  *0x8(%rax)
```

But `/home/zhaixiang/coreclr-3.1.5/.dotnet/dotnet run --project osu.Desktop -c Release` is able to work!

**osu!lazer version:** 

git commit [26ea75519cc385d1094344907fc49937399bc4cb](https://github.com/ppy/osu/commit/26ea75519cc385d1094344907fc49937399bc4cb)

**Computer Specifications:** 

* CentOS 7 3.10.0-957.21.3.el7.x86_64

```
ldd /home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/*.so
/home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libbass_fx.so:
	linux-vdso.so.1 =>  (0x00007fffd6330000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb7e8a98000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb7e8796000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb7e83c9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7e8fb6000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb7e81b3000)
/home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libbass.so:
	linux-vdso.so.1 =>  (0x00007ffdc0fe7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fac314d7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fac312bb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fac310b3000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fac30db1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fac309e4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fac3193a000)
/home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libe_sqlite3.so:
	linux-vdso.so.1 =>  (0x00007ffe0cfeb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6e1c14c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6e1c80e000)
/home/zhaixiang/osu/osu.Desktop/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libstbi.so:
	linux-vdso.so.1 =>  (0x00007ffc8685d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa652fe6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa652c19000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa65350c000)
```

Thanks,
Leslie Zhai

**Comment by smoogipoo** [comment]
Not sure what you're expecting us to do here. We don't and will never support compiling the .NET runtime yourself for the purpose of running osu! - we'll only support using the official sdks and runtimes provided by MS.

There's any number of things that could've gone wrong. You'll have to debug this yourself if you're interested in fixing it and make a PR, but this is un-actionable by us.

**Comment by xiangzhai** [comment]
It is might be BASS library issue...

```
(gdb) x/22i 0x00007ffecc5835d9-88
   0x7ffecc583581:	callq  0x7ffecc5751d0 <pthread_mutexattr_destroy@plt>
   0x7ffecc583586:	pop    %rax
   0x7ffecc583587:	pop    %rdx
   0x7ffecc583588:	pop    %rbx
   0x7ffecc583589:	retq   
   0x7ffecc58358a:	sub    $0x8,%rsp
   0x7ffecc58358e:	callq  0x7ffecc57debc
   0x7ffecc583593:	callq  0x7ffecc582648
   0x7ffecc583598:	mov    $0x87be4bff,%edi
=> 0x7ffecc58359d:	callq  0x7ffecc575390 <BASS_FX_BPM_Free@plt>
   0x7ffecc5835a2:	mov    $0x87be4bff,%edi
=> 0x7ffecc5835a7:	callq  0x7ffecc5752d0 <BASS_FX_BPM_BeatFree@plt>
   0x7ffecc5835ac:	pop    %rcx
   0x7ffecc5835ad:	lea    0x20524c(%rip),%rdi        # 0x7ffecc788800
   0x7ffecc5835b4:	jmpq   0x7ffecc5753a0 <pthread_mutex_destroy@plt>
   0x7ffecc5835b9:	sub    $0x8,%rsp
   0x7ffecc5835bd:	cmpl   $0x0,0x205234(%rip)        # 0x7ffecc7887f8
   0x7ffecc5835c4:	jne    0x7ffecc5835dc
   0x7ffecc5835c6:	mov    0x205223(%rip),%rax        # 0x7ffecc7887f0
   0x7ffecc5835cd:	mov    $0x3,%esi
   0x7ffecc5835d2:	mov    0x2049d7(%rip),%rdi        # 0x7ffecc787fb0
=> 0x7ffecc5835d9:	callq  *0x8(%rax)
```

**Comment by peppy** [comment]
As above, this isn't really something we can support, but the most likely problem is wrong arch / platform libraries are being loaded. Good luck solving it!
