### ISSUE TITLE
Crash during song select 'Could not load a part of the path'

### ISSUE THREAD

**Issue by kkartaltepe** [ppy/osu#9746]
**Describe the bug:** 
Osu crashed during song select and produced this stacktrace below

Some background, I had migrated a near empty osu lazer install into a new location (lets call it external1). Then loaded a few thousand songs. Some time later I started osu lazer again and it seemed to have no songs so i loaded a 1000 of the same set of songs again. After playing for an hour I remembered that I had migrated the directory before so I migrated osu again to external1. Then when I was selecting a song after the migration finished it crashed. I dont know if this is related to the crash but thats the history.

**Screenshots or videos showing encountered issue:** 
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/kk/external-data/geimu/osu_lazer/osu-lazer/cache/fonts'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at osu.Framework.Platform.NativeStorage.GetFiles(String path, String pattern)
   at osu.Game.IO.WrappedStorage.GetFiles(String path, String pattern) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/IO/WrappedStorage.cs:line 62
   at osu.Game.IO.WrappedStorage.GetFiles(String path, String pattern) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/IO/WrappedStorage.cs:line 62
   at osu.Framework.IO.Stores.RawCachingGlyphStore.createCachedPageInfo(Int32 page)
   at osu.Framework.IO.Stores.RawCachingGlyphStore.LoadCharacter(Character character)
   at osu.Framework.IO.Stores.GlyphStore.Get(String name)
   at osu.Framework.IO.Stores.ResourceStore`1.Get(String name)
   at osu.Framework.Graphics.Textures.TextureStore.Get(String name, WrapMode wrapModeS, WrapMode wrapModeT)
   at osu.Framework.IO.Stores.FontStore.Get(String name)
   at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character)
   at osu.Framework.Graphics.Sprites.SpriteText.load(ShaderManager shaders)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
   at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
   at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](IEnumerable`1& components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass96_0.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
```

**osu!lazer version:** 
2020.725.0 linux appimage

**Logs:**

**Comment by kkartaltepe** [comment]
Im honestly not sure if I chose the same folder as I did last time, or if lazer tried to avoid blasting its old folder. It appears I actually have two lazer folders one in in `/home/kk/external-data/geimu/osu_lazer` and one in `/home/kk/external-data/geimu/osu_lazer/osu-lazer`

But restarting osu, it sees the migrated songs (based on ~/.local/share/osu/storage.ini, from the inner osu-lazer folder) and hasnt crashed again, even when playing the same song that prompted the crash after migration.

**Comment by bdach** [comment]
The two disparate folders are intentional. The first time you chose to migrate to an empty folder, so lazer chose it as its new root, and the second time around the folder was no longer empty, so lazer created a new one to avoid accidentally nuking potentially unrelated data.

The crash will be related to running the migration itself. Unsure why the font cache hasn't been copied (on unix I'd expect copy and unlink to work flawlessly).

**Comment by kkartaltepe** [comment]
If it helps, the cache folder was never unlinked and remained in the `~/.local/share/osu/cache` folder. And the old location and the new were different filesystems.

**Comment by smoogipoo** [comment]
The cache directory is specified to be excluded from the migration. I'm not sure why that is because it probably could/should be, especially if it gets larger. @peppy ?

**Comment by smoogipoo** [comment]
In any case the glyph store should be able to handle a missing cache safely.

**Comment by peppy** [comment]
I did this because it was a common cause of failure, due to writes happening in the background. Also it shouldn't get large enough to matter, and should be preferred to be on the likely-faster OS disk.

**Comment by kkartaltepe** [comment]
This may be off topic for this issue but it would be preferable, to me at least, to store caches in $XDG_CACHE_DIR (Default $HOME/.cache) instead of in the config dir.

**Comment by bdach** [comment]
@kkartaltepe that directory path is [not something that .NET Core provides portably via any known `SpecialFolder` as far as I'm aware](https://developers.redhat.com/blog/2018/11/07/dotnet-special-folder-api-linux/), so it's extremely unlikely we'll be changing that for linux alone.

**Comment by zachmanthethird** [comment]
I'm attempting to migrate my osu!lazer directory away from my C drive because of performance issues with said hard drive (I really need to get it replaced...). Unfortunately, it appears as though it cannot transfer client.db while being used by itself. My osu!lazer install is completely clean (no songs; no settings), and nothing else is open during the migration.
~~Not sure if this belongs here, but it matches the issue title and labels.~~
![image](https://user-images.githubusercontent.com/74262407/98711452-d8a91600-2339-11eb-9385-55f9a56f93aa.png)

**Comment by bdach** [comment]
The migration process is somewhat best-effort. EF/sqlite will sometimes play up when trying to migrate. We're not likely to do much work in this regard as the current database setup is somewhat temporary/will possibly be replaced at some point.

**Comment by peppy** [comment]
If it fails, try again until it works. Make sure to perform the folder change from the main menu without opening other screens.

**Comment by Jordan-Jay** [comment]
On a brief look into this issue this seems to be working perfectly fine on the latest version of Lazer with importing files from my personal wine osu-stable to Lazer. I think i can guess what is causing this error. This seems like an issue where Linux can't access the media as it's being used by Windows (Since Windows is in Hibernation). This will be a common issue i suspect since a lot of Linux users keep their windows drives around for transferring data to Linux. I'll look into this myself at a later date.
