### ISSUE TITLE
Frame limiter not working

### ISSUE THREAD

**Issue by SS-035** [ppy/osu#9910]
**Describe the bug:** 
Frame limiter is not working no matter which option is selected. In multithread setting, it shots above 1000 and in single thread over 140. Gameplay and audio stutters every now and then (probably because of the issue).

**osu!lazer version:** 
2020.814.0.0 (Appimage using on Ubuntu 20.04 LTS)

**Logs:**
[database.log](https://github.com/ppy/osu/files/5092008/database.log)
[runtime.log](https://github.com/ppy/osu/files/5092009/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5092010/performance.log)

**Comment by bdach** [comment]
The frame limiter limits the draw thread and not the other threads in multithreaded mode, as it's generally by far the most resource-intensive one. This is by design. If you want to limit all threads to one update rate, please switch to single-threaded.

**Comment by SS-035** [comment]
The problem is in single-thread mode also. No matter what I choose (VSync/ 2*X/ 4*x/ 8*x/ Unlimited), fps is not capped at all. VSync and 2*X settings should not result in more than 140 fps, right?

**Comment by bdach** [comment]
That sounds wrong. Please attach a video or screenshot of this.

Does the fps not go down to 60 if the game is windowed and unfocused?

**Comment by SS-035** [comment]
Yes, FPS goes down to 60 if game is windowed or unfocused. I shall send a video as soon as I can.

**Comment by SS-035** [comment]
I shall correct myself first. The VSync settings keeps the FPS under 60, the stuttering I felt because the FPS frequently goes down to 40s/50s for some reason. But 2*X settings does not limit anything. In that setting (with single thread) my FPS stays in the range 100-190. I have attached a short clip taken by external camera as the recording software affects my potato PC's performance. 
[clip.zip](https://github.com/ppy/osu/files/5092322/clip.zip)

**Comment by SS-035** [comment]
I just observed that FPS drops depending on how fast my cursor moves. If I do not give any input then FPS stays 57-61 with VSync and 140-160 with 2*X. When I move my cursor then depending on my movement, fps frequently drops to around 40 and around 100 respectively. This also happens without my input in autoplay mode.

**Comment by peppy** [comment]
This is not related to frame limiter. You have a performance issue, likely due to system specs. Please provide system specs.

Closing issue for now as invalid.

**Comment by SS-035** [comment]
> .. But 2*X settings does not limit anything. In that setting (with single thread) my FPS stays in the range 100-190..
>
Come on, at least read the whole thread. I just mentioned the FPS drop as a side note. The main issue was, I was getting 190 FPS when it was supposed to be locked at 120 FPS when using 2*X frame limiter. How is getting more frames performance problem? Anyway my system spec is Core i3 5005U (Intel HD 5500, no dedicated GPU) with 4 GB RAM.

**Comment by peppy** [comment]
Please provide a video showing what you're seeing.

**Comment by SS-035** [comment]
> I shall correct myself first. The VSync settings keeps the FPS under 60, the stuttering I felt because the FPS frequently goes down to 40s/50s for some reason. But 2*X settings does not limit anything. In that setting (with single thread) my FPS stays in the range 100-190. I have attached a short clip taken by external camera as the recording software affects my potato PC's performance.
> [clip.zip](https://github.com/ppy/osu/files/5092322/clip.zip)

It was attached in this.

**Comment by peppy** [comment]
This means your OS may be reporting your refresh rate incorrectly. Please check your OS config first, and also test with `--sdl` flag.

**Comment by SS-035** [comment]
> Please check your OS config first, and also test with `--sdl` flag.


What is the command for that? I am using Ubuntu 20.04 LTS.

**Comment by peppy** [comment]
The fact the refresh rate is not a whole number may be related.

The command is adding `--sdl` to the end of the osu! executable.

**Comment by SS-035** [comment]
```
$ Games/osu.AppImage --sdl
touch: cannot touch '/home/user/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at osu.Framework.Platform.Sdl.Sdl2WindowBackend..ctor()
   at osu.Framework.Platform.DesktopWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
Aborted (core dumped)
```
Game crashed.

Without `--sdl` it shows the following output but runs.
```
touch: cannot touch '/home/user/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
```

**Comment by peppy** [comment]
Apologies, turns out this is actually "by design". The fact you are setting single-threaded means your frame limiter is meeting our "update rate" specifications, which are automatically (and forcefully) set above your frame rate limiter.

This is actually a weird UX issue since it's not what you are expecting, so we probably want to look at having the game run at the user-displayed "draw rate" instead.

**Comment by peppy** [comment]
Need to asses whether this is a framework-side fix or not. Probably with investigation into how the default case handles (where the user has not changed / set a frame limiter).
