### ISSUE TITLE
Changing skins can sometimes crash the game

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#9942]
```
System.ObjectDisposedException: Can not play disposed samples.
Object name: 'osu.Framework.Audio.Sample.SampleChannelBass'.
   at osu.Framework.Audio.Sample.SampleChannel.Play(Boolean restart)
   at osu.Framework.Audio.Sample.SampleChannelBass.Play(Boolean restart)
   at osu.Game.Skinning.SkinnableSound.<play>b__22_0(DrawableSample c) in /home/smgi/Repos/osu/osu.Game/Skinning/SkinnableSound.cs:line 100
   at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
   at osu.Game.Skinning.SkinnableSound.play() in /home/smgi/Repos/osu/osu.Game/Skinning/SkinnableSound.cs:line 97
   at osu.Game.Skinning.SkinnableSound.Play() in /home/smgi/Repos/osu/osu.Game/Skinning/SkinnableSound.cs:line 92
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.PlaySamples() in /home/smgi/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 387
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.updateState(ArmedState newState, Boolean force) in /home/smgi/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 273
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.SkinChanged(ISkinSource skin, Boolean allowFallback) in /home/smgi/Repos/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 321
   at osu.Game.Skinning.SkinReloadableDrawable.skinChanged() in /home/smgi/Repos/osu/osu.Game/Skinning/SkinReloadableDrawable.cs:line 61
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
```
Seems to be trying to play previous samples somehow.

**Comment by frenzibyte** [comment]
Sounds very similar to https://github.com/ppy/osu/issues/5798#issuecomment-548630321
